/**
 * The optional database layer, using Prisma with the MariaDB driver adapter,
 * the same way the tilawah bot does (so this fits the fleet: a shared MariaDB
 * and a `<bot>-migrate` deploy step that runs `prisma migrate deploy`).
 *
 * The database is OPTIONAL. If DATABASE_URL is unset, `prisma` is null and the
 * personal-tutor commands report that they are off; the channel broadcaster runs
 * exactly as before, with no database. This keeps the "no database by default"
 * design while letting one env var switch the tutor on.
 *
 * The Prisma client is generated by `prisma generate` into ./generated/prisma
 * (gitignored). Tables are created by `prisma migrate deploy` (the migrate
 * service), not at runtime.
 */
import { PrismaMariaDb } from '@prisma/adapter-mariadb';
import { logger } from 'telegram-broadcast-kit';
import { config } from '../config';
import { PrismaClient } from './generated/prisma/client';

/** Split DATABASE_URL into the parts the MariaDB adapter wants. */
function parseDbUrl(raw: string): {
  host: string;
  port: number;
  user: string;
  password: string;
  database: string;
} {
  let u: URL;
  try {
    // Swapping mysql:// for mariadb:// only helps Node's URL parser read the
    // userinfo when the password has special characters; the server is MariaDB.
    u = new URL(raw.replace(/^mysql:\/\//, 'mariadb://'));
  } catch {
    throw new Error('DATABASE_URL is malformed. Expected mysql://user:password@host:3306/database');
  }
  const database = u.pathname.replace(/^\//, '');
  if (!database) {
    throw new Error(
      'DATABASE_URL has no database name. Expected mysql://user:password@host:3306/database',
    );
  }
  return {
    host: u.hostname,
    port: u.port ? parseInt(u.port, 10) : 3306,
    user: decodeURIComponent(u.username),
    password: decodeURIComponent(u.password),
    database,
  };
}

function createClient(): PrismaClient | null {
  if (!config.databaseUrl) return null;
  const { host, port, user, password, database } = parseDbUrl(config.databaseUrl);
  const adapter = new PrismaMariaDb(
    { host, port, user, password, database, connectionLimit: 5 },
    { database },
  );
  const logLevels = config.isDev ? (['warn', 'error'] as const) : (['error'] as const);
  return new PrismaClient({ adapter, log: [...logLevels] });
}

/** The shared Prisma client, or null when no DATABASE_URL is configured. */
export const prisma: PrismaClient | null = createClient();

/** Whether the personal-tutor (database) features are enabled. */
export const dbEnabled = prisma !== null;

if (dbEnabled) logger.info('Personal tutor enabled (database configured)');

/** Disconnect on shutdown. Safe to call when there is no client. */
export async function closeDb(): Promise<void> {
  if (prisma) await prisma.$disconnect();
}
