import { existsSync, readdirSync } from 'node:fs';
import { join } from 'node:path';

/**
 * Where the voice clips live, and how to find one clip's file.
 *
 * The OGG/Opus clips are generated by scripts/generate-audio.ts and live under
 * src/content/audio. They are ElevenLabs output under a commercial license (not
 * redistributable, see NOTICE), so they are git-ignored and NOT in the repo. The
 * running bot only ever READS them, so there is no text-to-speech key, cost, or
 * network call at runtime.
 *
 * The path is resolved from the current working directory, which is the project
 * root in every documented way of running the bot (pnpm dev, pnpm start, the
 * Docker CMD, and the dev scripts all start from the repo root). We deliberately
 * do NOT resolve relative to this compiled module, because `tsc` emits the code
 * to dist/ but never copies the .ogg files there.
 *
 * IMPORTANT for Docker: the .ogg clips are NOT baked into the image. In
 * production this dir is a read-only bind mount of the host's clip folder (see
 * docs/DEPLOY.md). Locally it is just the folder filled by `pnpm generate-audio`.
 * If the dir is empty (mount missing, or clips never generated), every voice post
 * fails; index.ts logs a loud error at boot (via countAudioClips) so that is
 * obvious in the logs instead of looking like "the bot just went quiet".
 */
export const AUDIO_DIR = join(process.cwd(), 'src', 'content', 'audio');

/** Absolute path to one voice clip's committed audio file. */
export function audioPathFor(fileName: string): string {
  return join(AUDIO_DIR, fileName);
}

/**
 * How many .ogg clips are actually present on disk. Used by the startup check to
 * fail loudly when the audio did not make it into the running image. Returns 0
 * if the directory does not exist (rather than throwing), so the caller can warn.
 */
export function countAudioClips(): number {
  if (!existsSync(AUDIO_DIR)) return 0;
  return readdirSync(AUDIO_DIR).filter((f) => f.endsWith('.ogg')).length;
}
