/**
 * C1 (advanced) role-play dialogues.
 *
 * Polished, professional exchanges: running a meeting, diplomatic disagreement,
 * feedback, hedging, and decisions. Shadow both sides to absorb the calm,
 * confident delivery of a fluent professional.
 */
import type { Dialogue } from '../types';

export const c1Dialogues: Dialogue[] = [
  {
    id: 'c1-dl-001',
    situation: 'Opening a meeting',
    turns: [
      { speaker: 'A', text: 'Shall we get the ball rolling?' },
      { speaker: 'B', text: "Yes, let's dive in." },
      { speaker: 'A', text: 'Great. First item on the agenda.' },
    ],
    note: `Open with "Shall we get the ball rolling?" then "let's dive in".`,
    audio: 'c1-dl-001.ogg',
  },
  {
    id: 'c1-dl-002',
    situation: 'Diplomatic disagreement',
    turns: [
      { speaker: 'A', text: 'I think we should outsource it.' },
      { speaker: 'B', text: "I take your point, but I'd argue we lose control that way." },
      { speaker: 'A', text: "That's worth considering." },
    ],
    note: `Disagree with finesse: "I take your point, but I'd argue..."`,
    audio: 'c1-dl-002.ogg',
  },
  {
    id: 'c1-dl-003',
    situation: 'Receiving praise',
    turns: [
      { speaker: 'A', text: 'How did I do?' },
      { speaker: 'B', text: "Credit where it's due, you handled the tough questions well." },
      { speaker: 'A', text: 'Thanks, that means a lot.' },
    ],
    note: `Praise sincerely: "Credit where it's due, you handled it well."`,
    audio: 'c1-dl-003.ogg',
  },
  {
    id: 'c1-dl-004',
    situation: 'Giving a rough estimate',
    turns: [
      { speaker: 'A', text: 'Can you give me a rough figure?' },
      { speaker: 'B', text: 'Off the top of my head, somewhere around fifty.' },
      { speaker: 'A', text: "That's helpful, thanks." },
    ],
    note: `Estimate loosely: "Off the top of my head, around fifty."`,
    audio: 'c1-dl-004.ogg',
  },
  {
    id: 'c1-dl-005',
    situation: 'Deferring a decision',
    turns: [
      { speaker: 'A', text: 'Should we commit today?' },
      { speaker: 'B', text: "I'd rather not rush it. Let's sleep on it." },
      { speaker: 'A', text: "Sensible. We'll decide tomorrow." },
    ],
    note: `Defer a decision: "I'd rather not rush it. Let's sleep on it."`,
    audio: 'c1-dl-005.ogg',
  },
  {
    id: 'c1-dl-006',
    situation: 'Refocusing a discussion',
    turns: [
      { speaker: 'A', text: "We're getting into the weeds here." },
      { speaker: 'B', text: "Good point. Let's not lose sight of the goal." },
      { speaker: 'A', text: 'Exactly. Back to the big picture.' },
    ],
    note: `Refocus: "Let's not lose sight of the goal."`,
    audio: 'c1-dl-006.ogg',
  },
  {
    id: 'c1-dl-007',
    situation: 'Conceding a point',
    turns: [
      { speaker: 'A', text: 'The data clearly supports option B.' },
      { speaker: 'B', text: 'Fair enough, I stand corrected.' },
      { speaker: 'A', text: "No worries, it wasn't obvious." },
    ],
    note: `Concede gracefully: "Fair enough, I stand corrected."`,
    audio: 'c1-dl-007.ogg',
  },
  {
    id: 'c1-dl-008',
    situation: 'Softening bad news',
    turns: [
      { speaker: 'A', text: 'Did we win the contract?' },
      { speaker: 'B', text: "I'm afraid it's not the news we were hoping for." },
      { speaker: 'A', text: 'Ah. Well, thanks for letting me know.' },
    ],
    note: `Soften bad news: "It's not the news we were hoping for."`,
    audio: 'c1-dl-008.ogg',
  },
  {
    id: 'c1-dl-009',
    situation: 'Pressing for action',
    turns: [
      { speaker: 'A', text: "Let's wait until next quarter." },
      { speaker: 'B', text: "We can't afford to lose momentum now." },
      { speaker: 'A', text: 'You make a compelling case.' },
    ],
    note: `Press the point: "We can't afford to lose momentum now."`,
    audio: 'c1-dl-009.ogg',
  },
  {
    id: 'c1-dl-010',
    situation: 'Managing a tough deadline',
    turns: [
      { speaker: 'A', text: 'I need this by tomorrow.' },
      { speaker: 'B', text: 'I can do that, but something else will have to slip.' },
      { speaker: 'A', text: 'Understood. Prioritize this one.' },
    ],
    note: `Manage up: "I can do that, but something else will have to slip."`,
    audio: 'c1-dl-010.ogg',
  },
  {
    id: 'c1-dl-011',
    situation: 'Building rapport',
    turns: [
      { speaker: 'A', text: "How's the new role treating you?" },
      { speaker: 'B', text: "Steep learning curve, but I'm enjoying it." },
      { speaker: 'A', text: "That's the spirit." },
    ],
    note: `Build rapport: "How's the new role treating you?"`,
    audio: 'c1-dl-011.ogg',
  },
  {
    id: 'c1-dl-012',
    situation: 'A tactful no',
    turns: [
      { speaker: 'A', text: 'Could you lead the project?' },
      { speaker: 'B', text: "I'm flattered, but my plate is full right now." },
      { speaker: 'A', text: 'Of course. Maybe next time.' },
    ],
    note: `Say no with grace: "I'm flattered, but my plate is full."`,
    audio: 'c1-dl-012.ogg',
  },
  {
    id: 'c1-dl-013',
    situation: 'Clarifying scope',
    turns: [
      { speaker: 'A', text: "So we're handling the whole rollout?" },
      { speaker: 'B', text: 'Not quite. Just the first phase.' },
      { speaker: 'A', text: "Understood, that's more manageable." },
    ],
    note: `Narrow the scope: "Not quite. Just the first phase."`,
    audio: 'c1-dl-013.ogg',
  },
  {
    id: 'c1-dl-014',
    situation: 'Handling feedback well',
    turns: [
      { speaker: 'A', text: 'The report was a bit rushed.' },
      { speaker: 'B', text: "I hear you. I'll give it another pass." },
      { speaker: 'A', text: "It's solid overall, just polish it." },
    ],
    note: `Take feedback well: "I hear you. I'll give it another pass."`,
    audio: 'c1-dl-014.ogg',
  },
  {
    id: 'c1-dl-015',
    situation: 'Steering back on track',
    turns: [
      { speaker: 'A', text: 'We could also redesign the logo.' },
      { speaker: 'B', text: "Let's table that for now and stay focused." },
      { speaker: 'A', text: 'Agreed, one thing at a time.' },
    ],
    note: `Steer back: "Let's table that for now and stay focused."`,
    audio: 'c1-dl-015.ogg',
  },
  {
    id: 'c1-dl-016',
    situation: 'Showing support',
    turns: [
      { speaker: 'A', text: 'What do you think of the proposal?' },
      { speaker: 'B', text: "Honestly, I'm really on board with it." },
      { speaker: 'A', text: "Brilliant, let's move forward." },
    ],
    note: `Show support: "Honestly, I'm really on board with it."`,
    audio: 'c1-dl-016.ogg',
  },
  {
    id: 'c1-dl-017',
    situation: 'Weighing a risk',
    turns: [
      { speaker: 'A', text: "There's a chance it backfires." },
      { speaker: 'B', text: 'True, but the upside outweighs the risk.' },
      { speaker: 'A', text: "I'll take that bet." },
    ],
    note: `Weigh a risk: "The upside outweighs the risk."`,
    audio: 'c1-dl-017.ogg',
  },
  {
    id: 'c1-dl-018',
    situation: 'Reframing a problem',
    turns: [
      { speaker: 'A', text: 'This is a disaster.' },
      { speaker: 'B', text: "Let's call it a setback, not a disaster." },
      { speaker: 'A', text: "Fair, that's a healthier way to see it." },
    ],
    note: `Reframe a problem: "Let's call it a setback, not a disaster."`,
    audio: 'c1-dl-018.ogg',
  },
  {
    id: 'c1-dl-019',
    situation: 'Closing a meeting',
    turns: [
      { speaker: 'A', text: "I think that's everything." },
      { speaker: 'B', text: "Let's reconvene once we have the figures." },
      { speaker: 'A', text: "Perfect, I'll set it up." },
    ],
    note: `Close cleanly: "Let's reconvene once we have the figures."`,
    audio: 'c1-dl-019.ogg',
  },
  {
    id: 'c1-dl-020',
    situation: 'Reflecting on a decision',
    turns: [
      { speaker: 'A', text: 'In hindsight, we moved too fast.' },
      { speaker: 'B', text: 'Maybe, but we learned a lot.' },
      { speaker: 'A', text: 'True, lesson noted.' },
    ],
    note: `Reflect: "In hindsight, we moved too fast."`,
    audio: 'c1-dl-020.ogg',
  },
  {
    id: 'c1-dl-021',
    situation: 'Debating an idea',
    turns: [
      { speaker: 'A', text: "I'm not convinced this is the right call." },
      { speaker: 'B', text: "What's giving you doubts?" },
      { speaker: 'A', text: 'Mainly the cost, to be frank.' },
    ],
    note: `"What's giving you doubts?" draws out the real concern.`,
    audio: 'c1-dl-021.ogg',
  },
  {
    id: 'c1-dl-022',
    situation: 'Diplomatic disagreement',
    turns: [
      { speaker: 'A', text: "I'd argue the opposite, actually." },
      { speaker: 'B', text: "Go on, I'm curious to hear why." },
      { speaker: 'A', text: 'Well, the data points the other way.' },
    ],
    note: `"I'd argue the opposite" disagrees while inviting discussion.`,
    audio: 'c1-dl-022.ogg',
  },
  {
    id: 'c1-dl-023',
    situation: 'Networking',
    turns: [
      { speaker: 'A', text: "I've heard great things about your work." },
      { speaker: 'B', text: "That's kind of you to say." },
      { speaker: 'A', text: 'We should compare notes sometime.' },
    ],
    note: `"compare notes" means share experiences and ideas.`,
    audio: 'c1-dl-023.ogg',
  },
  {
    id: 'c1-dl-024',
    situation: 'Managing expectations',
    turns: [
      { speaker: 'A', text: 'Will it be ready by Friday?' },
      { speaker: 'B', text: "I'll be honest, it's looking tight." },
      { speaker: 'A', text: 'Understood, keep me posted.' },
    ],
    note: `"it's looking tight" warns of a deadline you may miss.`,
    audio: 'c1-dl-024.ogg',
  },
  {
    id: 'c1-dl-025',
    situation: 'Clearing the air',
    turns: [
      { speaker: 'A', text: 'I think we got off on the wrong foot.' },
      { speaker: 'B', text: "Maybe we did. Let's start over." },
      { speaker: 'A', text: "I'd like that." },
    ],
    note: `"got off on the wrong foot" means started a relationship badly.`,
    audio: 'c1-dl-025.ogg',
  },
  {
    id: 'c1-dl-026',
    situation: 'Pitching an idea',
    turns: [
      { speaker: 'A', text: 'Hear me out before you say no.' },
      { speaker: 'B', text: 'Alright, you have my attention.' },
      { speaker: 'A', text: 'What if we tried it for a month?' },
    ],
    note: `"Hear me out" asks for a chance to explain fully first.`,
    audio: 'c1-dl-026.ogg',
  },
  {
    id: 'c1-dl-027',
    situation: 'Negotiating scope',
    turns: [
      { speaker: 'A', text: 'Can we add two more features?' },
      { speaker: 'B', text: 'We can, but something else has to give.' },
      { speaker: 'A', text: "Fair, let's prioritise together." },
    ],
    note: `"something has to give" means a trade-off is needed.`,
    audio: 'c1-dl-027.ogg',
  },
  {
    id: 'c1-dl-028',
    situation: 'Mentoring',
    turns: [
      { speaker: 'A', text: 'I keep second-guessing my decisions.' },
      { speaker: 'B', text: "That usually means you care, not that you're wrong." },
      { speaker: 'A', text: "I hadn't thought of it that way." },
    ],
    note: `Reframe a worry: "That means you care, not that you're wrong."`,
    audio: 'c1-dl-028.ogg',
  },
  {
    id: 'c1-dl-029',
    situation: 'Challenging a claim',
    turns: [
      { speaker: 'A', text: "I'm not sure the data supports that." },
      { speaker: 'B', text: 'What would change your mind?' },
      { speaker: 'A', text: 'A larger sample, for a start.' },
    ],
    note: `"What would change your mind?" invites real evidence.`,
    audio: 'c1-dl-029.ogg',
  },
  {
    id: 'c1-dl-030',
    situation: 'Managing up',
    turns: [
      { speaker: 'A', text: "I think we're taking on too much." },
      { speaker: 'B', text: 'What would you cut?' },
      { speaker: 'A', text: 'The lowest-impact project, to protect the rest.' },
    ],
    note: `Propose a fix, not just a complaint: "to protect the rest."`,
    audio: 'c1-dl-030.ogg',
  },
  {
    id: 'c1-dl-031',
    situation: 'Receiving criticism well',
    turns: [
      { speaker: 'A', text: 'Your draft buried the main point.' },
      { speaker: 'B', text: "You're right, I'll lead with it." },
      { speaker: 'A', text: "Exactly, that'll make it land." },
    ],
    note: `"You're right, I'll ..." accepts feedback without defensiveness.`,
    audio: 'c1-dl-031.ogg',
  },
  {
    id: 'c1-dl-032',
    situation: 'Building consensus',
    turns: [
      { speaker: 'A', text: 'Are we all comfortable with this?' },
      { speaker: 'B', text: "Mostly, though I'd like one more day." },
      { speaker: 'A', text: "Reasonable, let's reconvene tomorrow." },
    ],
    note: `"Are we all comfortable with this?" tests for agreement.`,
    audio: 'c1-dl-032.ogg',
  },
  {
    id: 'c1-dl-033',
    situation: 'Strategic disagreement',
    turns: [
      { speaker: 'A', text: "I think we're solving the wrong problem." },
      { speaker: 'B', text: "Go on, what's the real one?" },
      { speaker: 'A', text: 'Retention, not new sign-ups.' },
    ],
    note: `"X, not Y" sharpens what the real issue is.`,
    audio: 'c1-dl-033.ogg',
  },
  {
    id: 'c1-dl-034',
    situation: 'Coaching a decision',
    turns: [
      { speaker: 'A', text: "I can't decide between the two offers." },
      { speaker: 'B', text: 'Which one scares you in a good way?' },
      { speaker: 'A', text: 'The second, honestly.' },
    ],
    note: `A good coaching question reframes the whole choice.`,
    audio: 'c1-dl-034.ogg',
  },
  {
    id: 'c1-dl-035',
    situation: 'Managing expectations',
    turns: [
      { speaker: 'A', text: 'Can you guarantee it by Friday?' },
      { speaker: 'B', text: 'I can guarantee my best effort, not the date.' },
      { speaker: 'A', text: "That's fair enough." },
    ],
    note: `Promise effort, not an outcome you cannot control.`,
    audio: 'c1-dl-035.ogg',
  },
  {
    id: 'c1-dl-036',
    situation: 'Declining extra work',
    turns: [
      { speaker: 'A', text: 'Could you take this on as well?' },
      { speaker: 'B', text: "I'd rather do one thing well than two poorly." },
      { speaker: 'A', text: "Understood, I'll find someone." },
    ],
    note: `"one thing well than two poorly" declines with a reason.`,
    audio: 'c1-dl-036.ogg',
  },
  {
    id: 'c1-dl-037',
    situation: 'Clearing up a misunderstanding',
    turns: [
      { speaker: 'A', text: 'I felt you dismissed my idea.' },
      { speaker: 'B', text: "That wasn't my intention at all." },
      { speaker: 'A', text: "Thanks, I'm glad we cleared that up." },
    ],
    note: `Name the feeling, hear the intention, then move on.`,
    audio: 'c1-dl-037.ogg',
  },
  {
    id: 'c1-dl-038',
    situation: 'Weighing a risk',
    turns: [
      { speaker: 'A', text: "It's a bold move, isn't it?" },
      { speaker: 'B', text: 'Bold, but the downside is small.' },
      { speaker: 'A', text: 'Then the math is on our side.' },
    ],
    note: `Weigh upside against "the downside is small".`,
    audio: 'c1-dl-038.ogg',
  },
  {
    id: 'c1-dl-039',
    situation: 'Encouraging ownership',
    turns: [
      { speaker: 'A', text: 'Should I check with you first?' },
      { speaker: 'B', text: 'No, make the call; I trust your judgment.' },
      { speaker: 'A', text: "Okay, I'll own it." },
    ],
    note: `"make the call" hands someone real responsibility.`,
    audio: 'c1-dl-039.ogg',
  },
  {
    id: 'c1-dl-040',
    situation: 'Closing a discussion',
    turns: [
      { speaker: 'A', text: "I think we've talked it to death." },
      { speaker: 'B', text: "Agreed, let's decide and move." },
      { speaker: 'A', text: 'Done. We go with option B.' },
    ],
    note: `"talked it to death" signals it is time to decide.`,
    audio: 'c1-dl-040.ogg',
  },
  {
    id: 'c1-dl-041',
    situation: 'Framing a problem',
    turns: [
      { speaker: 'A', text: 'Sales are down again.' },
      { speaker: 'B', text: 'Is it the price or the product?' },
      { speaker: 'A', text: "That's exactly what we need to find out." },
    ],
    note: `A sharp question narrows a vague problem.`,
    audio: 'c1-dl-041.ogg',
  },
  {
    id: 'c1-dl-042',
    situation: 'Setting boundaries',
    turns: [
      { speaker: 'A', text: 'Can you join the call at nine tonight?' },
      { speaker: 'B', text: "I switch off after seven, I'm afraid." },
      { speaker: 'A', text: "Understood, let's find another slot." },
    ],
    note: `"I switch off after seven" states a boundary kindly.`,
    audio: 'c1-dl-042.ogg',
  },
  {
    id: 'c1-dl-043',
    situation: 'Encouraging a risk',
    turns: [
      { speaker: 'A', text: 'I am afraid it might fail.' },
      { speaker: 'B', text: 'And if it works?' },
      { speaker: 'A', text: "Then it changes everything. Let's try." },
    ],
    note: `"And if it works?" flips fear into possibility.`,
    audio: 'c1-dl-043.ogg',
  },
  {
    id: 'c1-dl-044',
    situation: 'Checking your tone',
    turns: [
      { speaker: 'A', text: 'Was I too blunt in there?' },
      { speaker: 'B', text: 'Direct, yes; rude, no.' },
      { speaker: 'A', text: "Good, that's the line I want." },
    ],
    note: `"Direct, yes; rude, no." draws a useful distinction.`,
    audio: 'c1-dl-044.ogg',
  },
  {
    id: 'c1-dl-045',
    situation: 'Aligning on a plan',
    turns: [
      { speaker: 'A', text: 'Are we building for now or for scale?' },
      { speaker: 'B', text: 'For scale, but without over-engineering.' },
      { speaker: 'A', text: "Then let's keep it simple and extendable." },
    ],
    note: `"X, but without Y" sets a balanced direction.`,
    audio: 'c1-dl-045.ogg',
  },
  {
    id: 'c1-dl-046',
    situation: 'Deciding under uncertainty',
    turns: [
      { speaker: 'A', text: "We don't have all the data yet." },
      { speaker: 'B', text: "We rarely will; let's decide with what we have." },
      { speaker: 'A', text: 'Agreed, waiting has a cost too.' },
    ],
    note: `"waiting has a cost too" counters endless delay.`,
    audio: 'c1-dl-046.ogg',
  },
  {
    id: 'c1-dl-047',
    situation: 'Delegating with trust',
    turns: [
      { speaker: 'A', text: 'Do you want to review it first?' },
      { speaker: 'B', text: 'No, ship it; you know this better than I do.' },
      { speaker: 'A', text: "Appreciated, I'll take it from here." },
    ],
    note: `"ship it" means release it; trust shown by stepping back.`,
    audio: 'c1-dl-047.ogg',
  },
  {
    id: 'c1-dl-048',
    situation: 'Agreeing to disagree',
    turns: [
      { speaker: 'A', text: "I don't think we'll agree on this." },
      { speaker: 'B', text: "That's okay; let's note it and move on." },
      { speaker: 'A', text: 'Fair enough, onward.' },
    ],
    note: `"let's note it and move on" keeps a meeting unstuck.`,
    audio: 'c1-dl-048.ogg',
  },
];
