/**
 * A2 (elementary) grammar points: the past, the near future, and everyday
 * function words. Plain rules with spoken examples.
 */
import type { GrammarRule } from '../types';

export const a2Grammar: GrammarRule[] = [
  {
    id: 'a2-gr-001',
    rule: 'Past simple: regular verbs (-ed)',
    explanation: `Add -ed to a regular verb to talk about a finished past action.`,
    examples: ['I worked yesterday.', 'We watched a movie.', 'She called me last night.'],
    note: `The time is finished and known (yesterday, last night).`,
    audio: 'a2-gr-001.ogg',
  },
  {
    id: 'a2-gr-002',
    rule: 'Past simple: irregular verbs',
    explanation: `Many common verbs change form in the past instead of adding -ed.`,
    examples: ['I went home early.', 'She saw a bird.', 'We had a great time.'],
    note: `These must be learned one by one: go-went, see-saw, have-had.`,
    audio: 'a2-gr-002.ogg',
  },
  {
    id: 'a2-gr-003',
    rule: 'Present continuous (am/is/are + -ing)',
    explanation: `Use it for an action happening right now.`,
    examples: ['I am eating lunch.', 'They are playing outside.', 'She is working now.'],
    note: `For things happening now, not for habits (use present simple for habits).`,
    audio: 'a2-gr-003.ogg',
  },
  {
    id: 'a2-gr-004',
    rule: 'going to for plans',
    explanation: `Use "going to" plus the base verb for future plans and intentions.`,
    examples: ['I am going to call her.', 'We are going to travel.', 'It is going to rain.'],
    note: `Use it when you have already decided something.`,
    audio: 'a2-gr-004.ogg',
  },
  {
    id: 'a2-gr-005',
    rule: 'Comparatives with -er',
    explanation: `Add -er to short adjectives, then "than" to compare two things.`,
    examples: [
      'She is taller than me.',
      'This phone is cheaper.',
      'Today is colder than yesterday.',
    ],
    note: `Double the last letter sometimes: big becomes bigger.`,
    audio: 'a2-gr-005.ogg',
  },
  {
    id: 'a2-gr-006',
    rule: 'some and any',
    explanation: `Use "some" in positive sentences and "any" in questions and negatives.`,
    examples: ['I have some money.', 'Do you have any questions?', 'There is not any milk.'],
    note: `Offers are an exception: "Would you like some tea?"`,
    audio: 'a2-gr-006.ogg',
  },
  {
    id: 'a2-gr-007',
    rule: 'have to for obligation',
    explanation: `Use "have to" (or "has to") plus the base verb for things you must do.`,
    examples: ['I have to go now.', 'She has to work tomorrow.', 'Do we have to pay?'],
    note: `Use "has to" with he, she, and it.`,
    audio: 'a2-gr-007.ogg',
  },
  {
    id: 'a2-gr-008',
    rule: 'would like for polite wants',
    explanation: `"Would like" is a polite way to say "want".`,
    examples: ['I would like a coffee.', 'Would you like some help?', 'She would like to join us.'],
    note: `Use "to" before a verb: "would like to join".`,
    audio: 'a2-gr-008.ogg',
  },
  {
    id: 'a2-gr-009',
    rule: `Adverbs of frequency`,
    explanation: `Words like always, usually, often, sometimes, and never go before the main verb.`,
    examples: ['I usually walk to work.', 'She never eats meat.', 'We sometimes go out.'],
    note: `But they go AFTER "to be": "He is always late."`,
    audio: 'a2-gr-009.ogg',
  },
  {
    id: 'a2-gr-010',
    rule: `Prepositions of time: in, on, at`,
    explanation: `Use "at" for clock times, "on" for days and dates, and "in" for months and years.`,
    examples: ['The meeting is at 7.', 'I work on Mondays.', 'She was born in July.'],
    note: `at a time, on a day, in a longer period.`,
    audio: 'a2-gr-010.ogg',
  },
  {
    id: 'a2-gr-011',
    rule: `much and many`,
    explanation: `Use "many" with countable nouns and "much" with uncountable nouns.`,
    examples: [
      'How many apples do we need?',
      'How much water is left?',
      'There are too many cars.',
    ],
    note: `Countable: apples, cars. Uncountable: water, money, time.`,
    audio: 'a2-gr-011.ogg',
  },
  {
    id: 'a2-gr-012',
    rule: `Superlatives with -est`,
    explanation: `Add -est to short adjectives and "the" before them to mean "the most".`,
    examples: [
      'She is the tallest in the class.',
      'It is the biggest city here.',
      'Today is the hottest day.',
    ],
    note: `Use "the most" with longer adjectives: "the most expensive".`,
    audio: 'a2-gr-012.ogg',
  },
  {
    id: 'a2-gr-013',
    rule: `will for predictions`,
    explanation: `Use "will" plus the base verb for what you think will happen.`,
    examples: ['It will rain tomorrow.', 'You will love this film.', 'They will be tired.'],
    note: `Often after "I think": "I think it will rain."`,
    audio: 'a2-gr-013.ogg',
  },
  {
    id: 'a2-gr-014',
    rule: `can and could for requests`,
    explanation: `Use "Can you...?" or the more polite "Could you...?" to ask for something.`,
    examples: ['Can you help me?', 'Could you open the window?', 'Could I have the menu?'],
    note: `"Could" is a little more polite than "can".`,
    audio: 'a2-gr-014.ogg',
  },
  {
    id: 'a2-gr-015',
    rule: `Possessive pronouns: mine, yours, hers`,
    explanation: `Use these to replace "my/your/her + noun" and avoid repeating the noun.`,
    examples: ['This book is mine.', 'Is this pen yours?', 'The blue car is hers.'],
    note: `No noun after them: "It is mine", not "It is mine book".`,
    audio: 'a2-gr-015.ogg',
  },
  {
    id: 'a2-gr-016',
    rule: `because and so`,
    explanation: `"Because" gives the reason; "so" gives the result.`,
    examples: [
      'I stayed home because I was tired.',
      'It rained, so we left.',
      'She studied hard, so she passed.',
    ],
    note: `reason + because; result + so.`,
    audio: 'a2-gr-016.ogg',
  },
  {
    id: 'a2-gr-017',
    rule: `Past simple questions and negatives with did`,
    explanation: `For past questions and negatives, use "did" or "did not" plus the base verb.`,
    examples: ['Did you see it?', 'I did not go.', 'Where did they meet?'],
    note: `After "did", use the base verb: "did you go", not "did you went".`,
    audio: 'a2-gr-017.ogg',
  },
  {
    id: 'a2-gr-018',
    rule: `there was and there were`,
    explanation: `Use "there was" for one thing in the past and "there were" for more than one.`,
    examples: ['There was a party.', 'There were many people.', 'There was not enough food.'],
    note: `was + singular; were + plural.`,
    audio: 'a2-gr-018.ogg',
  },
  {
    id: 'a2-gr-019',
    rule: `Comparisons with as ... as`,
    explanation: `Use "as + adjective + as" to say two things are equal, or "not as ... as" for less.`,
    examples: [
      'She is as tall as me.',
      'It is not as cold as yesterday.',
      'Run as fast as you can.',
    ],
    note: `"not as ... as" means less than the other thing.`,
    audio: 'a2-gr-019.ogg',
  },
  {
    id: 'a2-gr-020',
    rule: `Countable and uncountable nouns`,
    explanation: `Countable nouns have a plural; uncountable nouns like water, money, and time do not.`,
    examples: ['I have two apples.', 'I need some water.', 'He has a lot of money.'],
    note: `Do not say "informations" or "advices"; they are uncountable.`,
    audio: 'a2-gr-020.ogg',
  },
  {
    id: 'a2-gr-021',
    rule: `let's and shall we for suggestions`,
    explanation: `Use "Let's" plus a base verb to suggest doing something together; "Shall we?" checks they agree.`,
    examples: ["Let's go home.", 'Shall we start?', "Let's not be late."],
    note: `"Let's" means "let us". "Shall we?" is a polite check.`,
    audio: 'a2-gr-021.ogg',
  },
  {
    id: 'a2-gr-022',
    rule: `one and ones`,
    explanation: `Use "one" or "ones" so you do not repeat a noun you have already said.`,
    examples: ['I like the red one.', 'These ones are cheaper.', 'Which one do you want?'],
    note: `one = singular; ones = plural.`,
    audio: 'a2-gr-022.ogg',
  },
];
