/**
 * A1 (beginner) grammar points.
 *
 * One small, high-frequency rule each, in plain words, with example sentences
 * the audio reads aloud. The learner reads the rule and HEARS it used correctly.
 */
import type { GrammarRule } from '../types';

export const a1Grammar: GrammarRule[] = [
  {
    id: 'a1-gr-001',
    rule: 'The verb "to be": am, is, are',
    explanation: `Use "am" with I, "is" with he, she, or it, and "are" with you, we, and they.`,
    examples: ['I am a student.', 'She is happy.', 'They are at home.'],
    note: `Do not drop it: say "She is happy", not "She happy".`,
    audio: 'a1-gr-001.ogg',
  },
  {
    id: 'a1-gr-002',
    rule: 'a and an',
    explanation: `Use "a" before a consonant sound and "an" before a vowel sound.`,
    examples: ['I have a cat.', 'She ate an apple.', 'He is an hour late.'],
    note: `It is about the sound, not the letter: "an hour", "a university".`,
    audio: 'a1-gr-002.ogg',
  },
  {
    id: 'a1-gr-003',
    rule: 'Plural nouns with -s',
    explanation: `Add -s to most nouns to talk about more than one.`,
    examples: ['One book, two books.', 'I have three cats.', 'We need some chairs.'],
    note: `A few are irregular: one child, two children; one man, two men.`,
    audio: 'a1-gr-003.ogg',
  },
  {
    id: 'a1-gr-004',
    rule: 'this and that',
    explanation: `Use "this" for something near you and "that" for something far.`,
    examples: ['This is my bag.', 'That is your car.', 'I like this one.'],
    note: `For more than one, use "these" (near) and "those" (far).`,
    audio: 'a1-gr-004.ogg',
  },
  {
    id: 'a1-gr-005',
    rule: 'Present simple with I, you, we, they',
    explanation: `Use the base verb (no ending) with I, you, we, and they.`,
    examples: ['I work in a shop.', 'We live here.', 'They play football.'],
    note: `Do not add -s with these subjects: "I work", not "I works".`,
    audio: 'a1-gr-005.ogg',
  },
  {
    id: 'a1-gr-006',
    rule: 'Present simple with he, she, it',
    explanation: `Add -s to the verb with he, she, and it.`,
    examples: ['He works at a bank.', 'She likes tea.', 'It rains a lot here.'],
    note: `This -s is easy to forget. Say "She likes", not "She like".`,
    audio: 'a1-gr-006.ogg',
  },
  {
    id: 'a1-gr-007',
    rule: 'can for ability',
    explanation: `Use "can" plus the base verb to say what you are able to do.`,
    examples: ['I can swim.', 'She can drive.', 'Can you help me?'],
    note: `No "to" and no -s: "She can drive", not "She can to drives".`,
    audio: 'a1-gr-007.ogg',
  },
  {
    id: 'a1-gr-008',
    rule: 'there is and there are',
    explanation: `Use "there is" for one thing and "there are" for more than one.`,
    examples: [
      'There is a book on the desk.',
      'There are two pens here.',
      'Is there a bank nearby?',
    ],
    note: `Match the noun: one means "is", many means "are".`,
    audio: 'a1-gr-008.ogg',
  },
  {
    id: 'a1-gr-009',
    rule: `Possessive 's`,
    explanation: `Add 's to a person or thing to show it owns something.`,
    examples: ["Sam's car is new.", "This is my sister's bag.", "The dog's tail is short."],
    note: `For one owner, add 's. Do not confuse it with "is" ("Sam's happy" can mean both).`,
    audio: 'a1-gr-009.ogg',
  },
  {
    id: 'a1-gr-010',
    rule: `Object pronouns: me, him, her, us, them`,
    explanation: `Use these after a verb or preposition, instead of repeating the name.`,
    examples: ['She called me.', 'I saw them at the park.', 'Give it to him.'],
    note: `Subject: I, he, she, we, they. Object: me, him, her, us, them.`,
    audio: 'a1-gr-010.ogg',
  },
  {
    id: 'a1-gr-011',
    rule: `Prepositions of place: in, on, under`,
    explanation: `They show where something is.`,
    examples: [
      'The book is on the table.',
      'The cat is under the chair.',
      'The keys are in my bag.',
    ],
    note: `on a surface, in a container or space, under something above it.`,
    audio: 'a1-gr-011.ogg',
  },
  {
    id: 'a1-gr-012',
    rule: `The article "the"`,
    explanation: `Use "the" for something specific that both people know.`,
    examples: ['Close the door, please.', 'The sun is bright today.', 'I like the red one.'],
    note: `Use "a/an" for something new, "the" for something already known.`,
    audio: 'a1-gr-012.ogg',
  },
  {
    id: 'a1-gr-013',
    rule: `like + noun or -ing`,
    explanation: `Use "like" plus a noun, or plus a verb ending in -ing, to say what you enjoy.`,
    examples: ['I like coffee.', 'She likes dogs.', 'We like swimming.'],
    note: `Remember the -s with he, she, it: "She likes".`,
    audio: 'a1-gr-013.ogg',
  },
  {
    id: 'a1-gr-014',
    rule: `want + noun or to + verb`,
    explanation: `Use "want" plus a noun, or "want to" plus a base verb.`,
    examples: ['I want some water.', 'She wants a new phone.', 'I want to go home.'],
    note: `Use "to" before a verb: "want to go", not "want go".`,
    audio: 'a1-gr-014.ogg',
  },
  {
    id: 'a1-gr-015',
    rule: `Imperatives (giving instructions)`,
    explanation: `Use the base verb to tell someone to do something; add "do not" to tell them not to.`,
    examples: ['Open the window, please.', 'Turn left at the corner.', 'Do not touch that.'],
    note: `No subject is needed: just the verb.`,
    audio: 'a1-gr-015.ogg',
  },
  {
    id: 'a1-gr-016',
    rule: `Question words: what, where, when, who`,
    explanation: `Start a question with a question word to ask for information.`,
    examples: ['What is this?', 'Where do you live?', 'When does it start?'],
    note: `The verb usually comes after the question word: "Where IS it?"`,
    audio: 'a1-gr-016.ogg',
  },
  {
    id: 'a1-gr-017',
    rule: `Negatives: do not and does not`,
    explanation: `To make a present simple negative, put "do not" or "does not" before the base verb.`,
    examples: ['I do not like coffee.', 'She does not work here.', 'They do not know.'],
    note: `Use "does not" with he, she, it. Short forms: don't, doesn't.`,
    audio: 'a1-gr-017.ogg',
  },
  {
    id: 'a1-gr-018',
    rule: `Questions with do and does`,
    explanation: `Start a yes/no question with "Do" or "Does", then the subject and the base verb.`,
    examples: ['Do you like tea?', 'Does she live here?', 'Do they speak English?'],
    note: `Use "Does" with he, she, it; "Do" with I, you, we, they.`,
    audio: 'a1-gr-018.ogg',
  },
  {
    id: 'a1-gr-019',
    rule: `have got for what you have`,
    explanation: `Use "have got" or "has got" to say what you own. It is very common in speaking.`,
    examples: ["I've got a car.", 'She has got two cats.', 'We have got a problem.'],
    note: `"have got" means "have". Short forms: I've got, she's got.`,
    audio: 'a1-gr-019.ogg',
  },
  {
    id: 'a1-gr-020',
    rule: `Telling the time`,
    explanation: `Use "It is" plus the hour, or "past" and "to" for the minutes.`,
    examples: ["It's three o'clock.", "It's half past four.", "It's quarter to six."],
    note: `"past" is after the hour; "to" is before the next hour.`,
    audio: 'a1-gr-020.ogg',
  },
  {
    id: 'a1-gr-021',
    rule: `and, but, or`,
    explanation: `Join ideas with "and" to add, "but" to show a difference, and "or" to give a choice.`,
    examples: ['Tea and coffee.', 'Small but strong.', 'Now or later?'],
    note: `"but" shows a contrast; "or" offers a choice.`,
    audio: 'a1-gr-021.ogg',
  },
  {
    id: 'a1-gr-022',
    rule: `Subject pronouns: I, you, he, she, it, we, they`,
    explanation: `A subject pronoun replaces the person or thing doing the action, before the verb.`,
    examples: ['I am happy.', 'She is my friend.', 'They are at home.'],
    note: `These come before the verb: "She is", not "Her is".`,
    audio: 'a1-gr-022.ogg',
  },
];
