/**
 * B1 (intermediate) grammar points: the present perfect, real conditionals,
 * past habits, and the structures that trip learners up most.
 */
import type { GrammarRule } from '../types';

export const b1Grammar: GrammarRule[] = [
  {
    id: 'b1-gr-001',
    rule: 'Present perfect for experience',
    explanation: `Use "have/has" plus the past participle for life experience, with no exact time.`,
    examples: [
      'I have visited Paris.',
      'Have you ever tried sushi?',
      'She has never flown before.',
    ],
    note: `No finished time word here. Do not say "I have visited Paris last year".`,
    audio: 'b1-gr-001.ogg',
  },
  {
    id: 'b1-gr-002',
    rule: 'Present perfect vs past simple',
    explanation: `Use the past simple when you say WHEN; use the present perfect when you do not.`,
    examples: [
      'I have lost my keys.',
      'I lost them yesterday.',
      'She has finished. She finished at six.',
    ],
    note: `A finished time word (yesterday, at six) forces the past simple.`,
    audio: 'b1-gr-002.ogg',
  },
  {
    id: 'b1-gr-003',
    rule: 'First conditional (real future)',
    explanation: `If + present simple, then will + base verb. For likely future situations.`,
    examples: [
      'If it rains, I will stay home.',
      'She will pass if she studies.',
      'If you ask, he will help.',
    ],
    note: `Do not use "will" in the if-part: "If it rains", not "If it will rain".`,
    audio: 'b1-gr-003.ogg',
  },
  {
    id: 'b1-gr-004',
    rule: 'used to for past habits',
    explanation: `Use "used to" plus the base verb for things that were true before but are not now.`,
    examples: ['I used to smoke.', 'She used to live here.', 'We used to play together.'],
    note: `In questions and negatives, drop the -d: "Did you use to...?"`,
    audio: 'b1-gr-004.ogg',
  },
  {
    id: 'b1-gr-005',
    rule: 'Comparatives with more',
    explanation: `Use "more" before longer adjectives instead of adding -er.`,
    examples: [
      'This is more expensive.',
      'It is more interesting than the book.',
      'She is more careful now.',
    ],
    note: `Say "more careful", never "more carefuller" or "carefuller".`,
    audio: 'b1-gr-005.ogg',
  },
  {
    id: 'b1-gr-006',
    rule: 'too and enough',
    explanation: `"Too" goes before an adjective (a problem); "enough" goes after it (the right amount).`,
    examples: [
      'It is too expensive.',
      'It is not big enough.',
      'I am not tall enough to reach it.',
    ],
    note: `"too" means more than you want; "enough" means as much as you need.`,
    audio: 'b1-gr-006.ogg',
  },
  {
    id: 'b1-gr-007',
    rule: 'Past continuous',
    explanation: `Was/were + -ing for an action in progress at a past moment.`,
    examples: [
      'I was sleeping when you called.',
      'They were eating at noon.',
      'What were you doing?',
    ],
    note: `Often paired with the past simple: a longer action interrupted by a shorter one.`,
    audio: 'b1-gr-007.ogg',
  },
  {
    id: 'b1-gr-008',
    rule: 'should for advice',
    explanation: `Use "should" plus the base verb to give advice or an opinion.`,
    examples: ['You should rest.', 'You should not worry.', 'Should I call her?'],
    note: `No "to" after should: "You should rest", not "You should to rest".`,
    audio: 'b1-gr-008.ogg',
  },
  {
    id: 'b1-gr-009',
    rule: `Quantifiers: a few and a little`,
    explanation: `Use "a few" with countable nouns and "a little" with uncountable nouns to mean "some".`,
    examples: [
      'I have a few friends here.',
      'Give me a little time.',
      'We need a few more chairs.',
    ],
    note: `a few + countable (friends); a little + uncountable (time, water).`,
    audio: 'b1-gr-009.ogg',
  },
  {
    id: 'b1-gr-010',
    rule: `Verb + -ing or verb + to`,
    explanation: `Some verbs take -ing (enjoy, finish, avoid); others take "to" (want, need, decide).`,
    examples: ['I enjoy reading.', 'She wants to leave.', 'We finished cleaning the house.'],
    note: `Learn them in pairs: "enjoy doing", "want to do".`,
    audio: 'b1-gr-010.ogg',
  },
  {
    id: 'b1-gr-011',
    rule: `Present perfect with for and since`,
    explanation: `Use "for" with a length of time and "since" with a starting point.`,
    examples: [
      'I have lived here for ten years.',
      'She has worked here since 2015.',
      'We have known them for ages.',
    ],
    note: `for + period (ten years); since + start point (2015, Monday).`,
    audio: 'b1-gr-011.ogg',
  },
  {
    id: 'b1-gr-012',
    rule: `will vs going to`,
    explanation: `Use "will" for a decision made now, and "going to" for a plan you already had.`,
    examples: [
      "The phone is ringing; I'll get it.",
      "I'm going to study tonight.",
      "We're going to move house.",
    ],
    note: `Spontaneous decision: will. Existing plan: going to.`,
    audio: 'b1-gr-012.ogg',
  },
  {
    id: 'b1-gr-013',
    rule: `must and have to`,
    explanation: `Both show obligation. "Have to" is the everyday form; "must" can feel stronger or more personal.`,
    examples: [
      'You must wear a seatbelt.',
      'I have to finish this today.',
      'Do we have to pay now?',
    ],
    note: `"must not" = it is forbidden; "do not have to" = it is not necessary.`,
    audio: 'b1-gr-013.ogg',
  },
  {
    id: 'b1-gr-014',
    rule: `Adverbs of manner (-ly)`,
    explanation: `Add -ly to many adjectives to say HOW someone does something.`,
    examples: ['She speaks quietly.', 'He drives carefully.', 'They worked quickly.'],
    note: `Some are irregular: good becomes well ("She sings well").`,
    audio: 'b1-gr-014.ogg',
  },
  {
    id: 'b1-gr-015',
    rule: `Relative clauses with who and that`,
    explanation: `Use "who" or "that" to add information about a person, joining two ideas.`,
    examples: [
      'The man who called is my boss.',
      'The person that helped me was kind.',
      'I know someone who speaks five languages.',
    ],
    note: `who for people; that works for people or things.`,
    audio: 'b1-gr-015.ogg',
  },
  {
    id: 'b1-gr-016',
    rule: `Comparative adverbs`,
    explanation: `Use "more" with -ly adverbs, and "than" to compare how actions are done.`,
    examples: [
      'She speaks more clearly than me.',
      'He works more carefully now.',
      'Drive more slowly, please.',
    ],
    note: `Short ones change form: "faster", "harder", "better".`,
    audio: 'b1-gr-016.ogg',
  },
];
