/**
 * C1 (advanced) idioms: richer figurative expressions that make speech sound
 * fluent and native, taught with a meaning, examples, and a usage tip.
 */
import type { IdiomEntry } from '../types';

export const c1Idioms: IdiomEntry[] = [
  {
    id: 'c1-idm-001',
    idiom: 'a blessing in disguise',
    meaning: 'something that seems bad at first but turns out to be good.',
    examples: [
      'Losing that job was a blessing in disguise.',
      'It felt awful, but it was a blessing in disguise.',
    ],
    note: `Used when looking back on a setback that helped you.`,
    audio: 'c1-idm-001.ogg',
  },
  {
    id: 'c1-idm-002',
    idiom: 'the last straw',
    meaning: 'the final small problem that makes a situation unbearable.',
    examples: ['The rude reply was the last straw.', 'That was the last straw for me.'],
    note: `From "the straw that broke the camel's back".`,
    audio: 'c1-idm-002.ogg',
  },
  {
    id: 'c1-idm-003',
    idiom: 'jump on the bandwagon',
    meaning: 'to join something only because it has become popular.',
    examples: ['Everyone jumped on the bandwagon.', 'Do not just jump on the bandwagon.'],
    note: `Slightly critical: suggests following the crowd.`,
    audio: 'c1-idm-003.ogg',
  },
  {
    id: 'c1-idm-004',
    idiom: 'take it with a grain of salt',
    meaning: 'to not fully believe something; to be a little doubtful.',
    examples: ['Take that review with a grain of salt.', 'I take his advice with a grain of salt.'],
    note: `Polite way to say a source may not be fully reliable.`,
    audio: 'c1-idm-004.ogg',
  },
  {
    id: 'c1-idm-005',
    idiom: 'cut corners',
    meaning: 'to do something cheaply or quickly, lowering the quality.',
    examples: ['They cut corners to save money.', 'Do not cut corners on safety.'],
    note: `Negative. Suggests skipping proper steps.`,
    audio: 'c1-idm-005.ogg',
  },
  {
    id: 'c1-idm-006',
    idiom: 'on the back burner',
    meaning: 'set aside for now, to deal with later.',
    examples: ['We put the project on the back burner.', 'That idea is on the back burner.'],
    note: `Not cancelled, just delayed in favor of other things.`,
    audio: 'c1-idm-006.ogg',
  },
  {
    id: 'c1-idm-007',
    idiom: 'a ballpark figure',
    meaning: 'a rough estimate, not an exact number.',
    examples: ['Can you give me a ballpark figure?', 'As a ballpark figure, around fifty.'],
    note: `Common in business when you want an approximate amount.`,
    audio: 'c1-idm-007.ogg',
  },
  {
    id: 'c1-idm-008',
    idiom: 'get the ball rolling',
    meaning: 'to start something.',
    examples: ['Let us get the ball rolling.', 'A small step gets the ball rolling.'],
    note: `Encouraging. Means make a beginning so progress follows.`,
    audio: 'c1-idm-008.ogg',
  },
  {
    id: 'c1-idm-009',
    idiom: 'read between the lines',
    meaning: 'to understand a hidden or unstated meaning.',
    examples: [
      'Read between the lines of her email.',
      'If you read between the lines, he is unhappy.',
    ],
    note: `About noticing what is implied, not literally said.`,
    audio: 'c1-idm-009.ogg',
  },
  {
    id: 'c1-idm-010',
    idiom: 'a grey area',
    meaning: 'a situation where the rules are unclear.',
    examples: ['The law here is a grey area.', 'It falls into a grey area.'],
    note: `Means it is not clearly right or wrong, allowed or not.`,
    audio: 'c1-idm-010.ogg',
  },
  {
    id: 'c1-idm-011',
    idiom: "the lion's share",
    meaning: 'the largest part of something.',
    examples: [
      "She did the lion's share of the work.",
      "They took the lion's share of the profit.",
    ],
    note: `Means much more than an equal part.`,
    audio: 'c1-idm-011.ogg',
  },
  {
    id: 'c1-idm-012',
    idiom: 'a silver lining',
    meaning: 'a hopeful or good side of a bad situation.',
    examples: ['Every cloud has a silver lining.', 'The silver lining was the lesson we learned.'],
    note: `From the saying "every cloud has a silver lining".`,
    audio: 'c1-idm-012.ogg',
  },
  {
    id: 'c1-idm-013',
    idiom: 'a turning point',
    meaning: 'a moment of important change.',
    examples: ['It was a turning point in her life.', 'That meeting was the turning point.'],
    note: `Marks the moment where things clearly changed.`,
    audio: 'c1-idm-013.ogg',
  },
  {
    id: 'c1-idm-014',
    idiom: 'the benefit of the doubt',
    meaning: 'trust given to someone when you are not sure.',
    examples: ['I gave him the benefit of the doubt.', 'Give them the benefit of the doubt.'],
    note: `Choosing to believe someone despite some doubt.`,
    audio: 'c1-idm-014.ogg',
  },
  {
    id: 'c1-idm-015',
    idiom: 'a level playing field',
    meaning: 'fair conditions where everyone has an equal chance.',
    examples: ['We want a level playing field.', 'The rules create a level playing field.'],
    note: `Everyone competes under the same fair rules.`,
    audio: 'c1-idm-015.ogg',
  },
  {
    id: 'c1-idm-016',
    idiom: 'food for thought',
    meaning: 'something worth thinking about carefully.',
    examples: ['That is real food for thought.', 'Her talk gave me food for thought.'],
    note: `Said of an idea that makes you stop and reflect.`,
    audio: 'c1-idm-016.ogg',
  },
  {
    id: 'c1-idm-017',
    idiom: 'the best of both worlds',
    meaning: 'the advantages of two different things at once.',
    examples: [
      'Working from home gives the best of both worlds.',
      'It is the best of both worlds.',
    ],
    note: `Means you enjoy two benefits without the usual trade-off.`,
    audio: 'c1-idm-017.ogg',
  },
  {
    id: 'c1-idm-018',
    idiom: 'a fish out of water',
    meaning: 'someone uncomfortable in an unfamiliar situation.',
    examples: [
      'I felt like a fish out of water there.',
      'He was a fish out of water at the party.',
    ],
    note: `Describes feeling out of place or awkward.`,
    audio: 'c1-idm-018.ogg',
  },
  {
    id: 'c1-idm-019',
    idiom: 'the calm before the storm',
    meaning: 'a quiet period right before a busy or difficult one.',
    examples: ['Enjoy the calm before the storm.', 'This quiet is the calm before the storm.'],
    note: `Suggests trouble or busyness is coming soon.`,
    audio: 'c1-idm-019.ogg',
  },
  {
    id: 'c1-idm-020',
    idiom: 'a blessing and a curse',
    meaning: 'something that is both good and bad.',
    examples: [
      'Living downtown is a blessing and a curse.',
      'His ambition is a blessing and a curse.',
    ],
    note: `Highlights two opposite effects of the same thing.`,
    audio: 'c1-idm-020.ogg',
  },
  {
    id: 'c1-idm-021',
    idiom: 'a sticking point',
    meaning: 'a problem that stops people from reaching agreement.',
    examples: ['Price was the main sticking point.', 'We solved every sticking point but one.'],
    note: `Common in negotiations: the issue that blocks a deal.`,
    audio: 'c1-idm-021.ogg',
  },
  {
    id: 'c1-idm-022',
    idiom: 'common ground',
    meaning: 'shared opinions or interests that people agree on.',
    examples: ['We finally found common ground.', 'Let us look for some common ground.'],
    note: `The basis for agreement between two sides.`,
    audio: 'c1-idm-022.ogg',
  },
  {
    id: 'c1-idm-023',
    idiom: 'a wake-up call',
    meaning: 'an event that makes you realise you must change.',
    examples: ['The diagnosis was a wake-up call.', 'It was a wake-up call for the whole team.'],
    note: `A shock or warning that forces action.`,
    audio: 'c1-idm-023.ogg',
  },
  {
    id: 'c1-idm-024',
    idiom: 'a recipe for disaster',
    meaning: 'a situation very likely to go badly.',
    examples: ['Rushing this is a recipe for disaster.', 'That plan is a recipe for disaster.'],
    note: `Warns that something will probably fail.`,
    audio: 'c1-idm-024.ogg',
  },
  {
    id: 'c1-idm-025',
    idiom: 'a safe bet',
    meaning: 'something very likely to succeed or be true.',
    examples: ['It is a safe bet they will win.', 'The classic choice is a safe bet.'],
    note: `A low-risk, reliable option.`,
    audio: 'c1-idm-025.ogg',
  },
  {
    id: 'c1-idm-026',
    idiom: 'a vicious circle',
    meaning: 'a bad situation that keeps making itself worse.',
    examples: ['Debt can become a vicious circle.', 'Stress and poor sleep form a vicious circle.'],
    note: `Also called a "vicious cycle".`,
    audio: 'c1-idm-026.ogg',
  },
  {
    id: 'c1-idm-027',
    idiom: 'the upper hand',
    meaning: 'an advantage or position of control.',
    examples: ['She gained the upper hand in the talks.', 'They have the upper hand now.'],
    note: `Means more power or control than the other side.`,
    audio: 'c1-idm-027.ogg',
  },
  {
    id: 'c1-idm-028',
    idiom: 'a fresh start',
    meaning: 'a new beginning, leaving the past behind.',
    examples: ['The move gave them a fresh start.', 'Everyone deserves a fresh start.'],
    note: `A chance to begin again with a clean slate.`,
    audio: 'c1-idm-028.ogg',
  },
];
