/**
 * B1 (intermediate) idioms: common figurative expressions that make everyday
 * speech sound natural, taught with a plain meaning and examples.
 */
import type { IdiomEntry } from '../types';

export const b1Idioms: IdiomEntry[] = [
  {
    id: 'b1-idm-001',
    idiom: 'break the ice',
    meaning: 'to make people feel relaxed at the start of a meeting or chat.',
    examples: ['A joke can break the ice.', 'He told a story to break the ice.'],
    note: `Often about a first meeting or a new group.`,
    audio: 'b1-idm-001.ogg',
  },
  {
    id: 'b1-idm-002',
    idiom: 'hit the road',
    meaning: 'to leave; to start a journey.',
    examples: ['It is late, let us hit the road.', 'We hit the road early.'],
    note: `Casual. A lively way to say "let us go".`,
    audio: 'b1-idm-002.ogg',
  },
  {
    id: 'b1-idm-003',
    idiom: 'under the weather',
    meaning: 'feeling slightly ill.',
    examples: ['I am a bit under the weather today.', 'She felt under the weather.'],
    note: `A gentle, polite way to say you are not well.`,
    audio: 'b1-idm-003.ogg',
  },
  {
    id: 'b1-idm-004',
    idiom: 'a rip-off',
    meaning: 'something far too expensive for what it is.',
    examples: ['Ten dollars for a coffee is a rip-off.', 'That hotel was a rip-off.'],
    note: `Casual and negative. The verb "rip off" means to cheat someone.`,
    audio: 'b1-idm-004.ogg',
  },
  {
    id: 'b1-idm-005',
    idiom: 'keep an eye on',
    meaning: 'to watch carefully.',
    examples: ['Can you keep an eye on my bag?', 'Keep an eye on the time.'],
    note: `"keep an eye on" a person, thing, or situation.`,
    audio: 'b1-idm-005.ogg',
  },
  {
    id: 'b1-idm-006',
    idiom: 'change your mind',
    meaning: 'to form a new, different opinion or decision.',
    examples: ['I changed my mind about the trip.', 'You can change your mind later.'],
    note: `Very common. Note the difference from "make up your mind" (decide).`,
    audio: 'b1-idm-006.ogg',
  },
  {
    id: 'b1-idm-007',
    idiom: 'get the hang of it',
    meaning: 'to learn how to do something with practice.',
    examples: ['It is hard at first, but you get the hang of it.', 'I am getting the hang of it.'],
    note: `Encouraging. Means a skill becomes easy with practice.`,
    audio: 'b1-idm-007.ogg',
  },
  {
    id: 'b1-idm-008',
    idiom: 'on the same page',
    meaning: 'in agreement; understanding things the same way.',
    examples: ['Let us make sure we are on the same page.', 'Good, we are on the same page.'],
    note: `Common at work when checking that everyone agrees.`,
    audio: 'b1-idm-008.ogg',
  },
  {
    id: 'b1-idm-009',
    idiom: 'call it a day',
    meaning: 'to stop working for the day.',
    examples: ['We are tired, let us call it a day.', 'I will call it a day at five.'],
    note: `Casual. Means you have done enough for now.`,
    audio: 'b1-idm-009.ogg',
  },
  {
    id: 'b1-idm-010',
    idiom: 'cost an arm and a leg',
    meaning: 'to be very expensive.',
    examples: ['The repair cost an arm and a leg.', 'It does not cost an arm and a leg.'],
    note: `A vivid, casual way to say something was very pricey.`,
    audio: 'b1-idm-010.ogg',
  },
  {
    id: 'b1-idm-011',
    idiom: 'out of the blue',
    meaning: 'suddenly and unexpectedly.',
    examples: ['She called me out of the blue.', 'It happened out of the blue.'],
    note: `Used for surprising, completely unplanned events.`,
    audio: 'b1-idm-011.ogg',
  },
  {
    id: 'b1-idm-012',
    idiom: 'at the last minute',
    meaning: 'at the latest possible time.',
    examples: ['He cancelled at the last minute.', 'We booked at the last minute.'],
    note: `Often suggests leaving something too late.`,
    audio: 'b1-idm-012.ogg',
  },
  {
    id: 'b1-idm-013',
    idiom: 'once in a while',
    meaning: 'occasionally; not very often.',
    examples: ['We meet once in a while.', 'I treat myself once in a while.'],
    note: `Close to "sometimes" or "now and then".`,
    audio: 'b1-idm-013.ogg',
  },
  {
    id: 'b1-idm-014',
    idiom: 'in the same boat',
    meaning: 'in the same difficult situation as others.',
    examples: ['We are all in the same boat.', 'Do not worry, I am in the same boat.'],
    note: `Builds a sense that you share the problem together.`,
    audio: 'b1-idm-014.ogg',
  },
  {
    id: 'b1-idm-015',
    idiom: 'keep in touch',
    meaning: 'to stay in contact with someone.',
    examples: ['Let us keep in touch.', 'We kept in touch for years.'],
    note: `A warm thing to say when you part with someone.`,
    audio: 'b1-idm-015.ogg',
  },
  {
    id: 'b1-idm-016',
    idiom: 'a long way to go',
    meaning: 'much more still to do before finishing.',
    examples: ['We have a long way to go.', 'The project has a long way to go.'],
    note: `Acknowledges progress, but also unfinished work.`,
    audio: 'b1-idm-016.ogg',
  },
];
