/**
 * A2 (elementary) idioms: everyday expressions that make casual speech sound
 * natural, taught with a plain meaning and simple examples.
 */
import type { IdiomEntry } from '../types';

export const a2Idioms: IdiomEntry[] = [
  {
    id: 'a2-idm-001',
    idiom: 'grab a bite',
    meaning: 'to get something quick to eat.',
    examples: ['Let us grab a bite after work.', 'I need to grab a bite.'],
    note: `Casual. "grab" here just means "get" quickly.`,
    audio: 'a2-idm-001.ogg',
  },
  {
    id: 'a2-idm-002',
    idiom: 'hang out',
    meaning: 'to spend relaxed time with people.',
    examples: ['We hung out at the park.', 'Want to hang out this weekend?'],
    note: `Very common and casual. "hang out with" friends.`,
    audio: 'a2-idm-002.ogg',
  },
  {
    id: 'a2-idm-003',
    idiom: 'no big deal',
    meaning: 'not important; nothing to worry about.',
    examples: ['Do not worry, it is no big deal.', 'It was no big deal, really.'],
    note: `Reassures someone. The opposite, "a big deal", means important.`,
    audio: 'a2-idm-003.ogg',
  },
  {
    id: 'a2-idm-004',
    idiom: 'make up your mind',
    meaning: 'to decide.',
    examples: ['Please make up your mind.', 'I cannot make up my mind.'],
    note: `Often used when someone is taking too long to choose.`,
    audio: 'a2-idm-004.ogg',
  },
  {
    id: 'a2-idm-005',
    idiom: 'get along',
    meaning: 'to have a friendly relationship.',
    examples: ['They get along well.', 'I get along with my coworkers.'],
    note: `"get along with" someone. Opposite: not get along.`,
    audio: 'a2-idm-005.ogg',
  },
  {
    id: 'a2-idm-006',
    idiom: 'in a hurry',
    meaning: 'needing to be quick; rushed.',
    examples: ['Sorry, I am in a hurry.', 'Do not eat in a hurry.'],
    note: `"in a rush" means the same thing.`,
    audio: 'a2-idm-006.ogg',
  },
  {
    id: 'a2-idm-007',
    idiom: 'feel like',
    meaning: 'to want to do or have something.',
    examples: ['I feel like a coffee.', 'Do you feel like going out?'],
    note: `Use "feel like" plus a noun or an -ing verb.`,
    audio: 'a2-idm-007.ogg',
  },
  {
    id: 'a2-idm-008',
    idiom: 'a piece of cake',
    meaning: 'very easy.',
    examples: ['The test was a piece of cake.', 'Do not worry, it is a piece of cake.'],
    note: `Casual and positive. Means something is no trouble at all.`,
    audio: 'a2-idm-008.ogg',
  },
  {
    id: 'a2-idm-009',
    idiom: 'give it a try',
    meaning: 'to attempt something.',
    examples: ['Just give it a try.', 'I will give it a try.'],
    note: `Encouraging. "give it a go" means the same.`,
    audio: 'a2-idm-009.ogg',
  },
  {
    id: 'a2-idm-010',
    idiom: 'on time',
    meaning: 'at the right time; not late.',
    examples: ['The bus came on time.', 'Please be on time.'],
    note: `"on time" is punctual; "in time" means before a deadline.`,
    audio: 'a2-idm-010.ogg',
  },
  {
    id: 'a2-idm-011',
    idiom: 'make sense',
    meaning: 'to be clear or logical.',
    examples: ['That makes sense now.', 'It does not make sense to me.'],
    note: `"make sense of" something means to understand it.`,
    audio: 'a2-idm-011.ogg',
  },
  {
    id: 'a2-idm-012',
    idiom: 'out of order',
    meaning: 'not working (about a machine).',
    examples: ['The lift is out of order.', 'The machine is out of order.'],
    note: `Usually for machines; for a person it can mean rude.`,
    audio: 'a2-idm-012.ogg',
  },
  {
    id: 'a2-idm-013',
    idiom: 'run out of',
    meaning: 'to use all of something, so none is left.',
    examples: ['We ran out of milk.', 'I am running out of time.'],
    note: `Use "run out of" plus the thing that is finished.`,
    audio: 'a2-idm-013.ogg',
  },
  {
    id: 'a2-idm-014',
    idiom: 'look forward to',
    meaning: 'to feel happy about something that is coming.',
    examples: ['I look forward to the weekend.', 'She looks forward to seeing you.'],
    note: `Followed by a noun or an -ing verb, not the base verb.`,
    audio: 'a2-idm-014.ogg',
  },
  {
    id: 'a2-idm-015',
    idiom: 'give someone a hand',
    meaning: 'to help someone.',
    examples: ['Can you give me a hand?', 'He gave me a hand with the bags.'],
    note: `"give a hand" can also mean to clap for someone.`,
    audio: 'a2-idm-015.ogg',
  },
  {
    id: 'a2-idm-016',
    idiom: 'take it easy',
    meaning: 'to relax and not worry.',
    examples: ['Take it easy this weekend.', 'Take it easy, it is all fine.'],
    note: `Also a friendly, casual way to say goodbye.`,
    audio: 'a2-idm-016.ogg',
  },
  {
    id: 'a2-idm-017',
    idiom: 'no rush',
    meaning: 'there is no need to hurry.',
    examples: ['No rush, finish your coffee.', 'Send it whenever; no rush.'],
    note: `A relaxed, kind way to remove pressure.`,
    audio: 'a2-idm-017.ogg',
  },
  {
    id: 'a2-idm-018',
    idiom: 'fed up',
    meaning: 'annoyed and tired of something.',
    examples: ['I am fed up with the noise.', 'She got fed up and left.'],
    note: `Use "fed up with" something. Casual but a bit negative.`,
    audio: 'a2-idm-018.ogg',
  },
  {
    id: 'a2-idm-019',
    idiom: 'a big deal',
    meaning: 'something important.',
    examples: ['This game is a big deal for him.', 'It is not a big deal to me.'],
    note: `"a big deal" is important; "no big deal" is not important.`,
    audio: 'a2-idm-019.ogg',
  },
  {
    id: 'a2-idm-020',
    idiom: 'sort of',
    meaning: 'partly; not exactly.',
    examples: ['Do you like it? Sort of.', 'It is sort of difficult.'],
    note: `Softens an answer. "Kind of" means the same.`,
    audio: 'a2-idm-020.ogg',
  },
  {
    id: 'a2-idm-021',
    idiom: 'kind of',
    meaning: 'a little; in a way.',
    examples: ['I am kind of tired.', 'It is kind of expensive.'],
    note: `Very common in speech, often said quickly as "kinda".`,
    audio: 'a2-idm-021.ogg',
  },
  {
    id: 'a2-idm-022',
    idiom: 'for good',
    meaning: 'permanently; forever.',
    examples: ['He left the city for good.', 'The shop closed for good.'],
    note: `Means the change is final, not temporary.`,
    audio: 'a2-idm-022.ogg',
  },
  {
    id: 'a2-idm-023',
    idiom: 'make a difference',
    meaning: 'to have an important effect.',
    examples: ['Small changes make a difference.', 'You really made a difference.'],
    note: `Usually about a positive effect on something.`,
    audio: 'a2-idm-023.ogg',
  },
  {
    id: 'a2-idm-024',
    idiom: 'keep going',
    meaning: 'continue and do not stop.',
    examples: ['You are doing well, keep going!', 'Keep going, you are almost there.'],
    note: `Encouraging, like "do not give up".`,
    audio: 'a2-idm-024.ogg',
  },
  {
    id: 'a2-idm-025',
    idiom: 'take turns',
    meaning: 'to do something one after another.',
    examples: ['Let us take turns.', 'The children took turns on the swing.'],
    note: `Each person does it in order, not all at once.`,
    audio: 'a2-idm-025.ogg',
  },
  {
    id: 'a2-idm-026',
    idiom: 'calm down',
    meaning: 'to become less angry or worried.',
    examples: ['Please calm down, it is okay.', 'Take a breath and calm down.'],
    note: `Say it gently; it can sound rude if said sharply.`,
    audio: 'a2-idm-026.ogg',
  },
  {
    id: 'a2-idm-027',
    idiom: 'speak up',
    meaning: 'to talk louder, or to share your opinion.',
    examples: ['Could you speak up, please?', 'Speak up if you disagree.'],
    note: `Two meanings: talk louder, or say what you think.`,
    audio: 'a2-idm-027.ogg',
  },
  {
    id: 'a2-idm-028',
    idiom: 'slow down',
    meaning: 'to go or do something more slowly.',
    examples: ['Slow down, we have plenty of time.', 'You are talking too fast; slow down.'],
    note: `For speed, or for being too busy in life.`,
    audio: 'a2-idm-028.ogg',
  },
  {
    id: 'a2-idm-029',
    idiom: 'first of all',
    meaning: 'before anything else; to begin.',
    examples: ['First of all, thank you for coming.', 'First of all, let us check the facts.'],
    note: `Used to introduce the first point.`,
    audio: 'a2-idm-029.ogg',
  },
  {
    id: 'a2-idm-030',
    idiom: 'by accident',
    meaning: 'not on purpose; by chance.',
    examples: ['I deleted it by accident.', 'We met by accident.'],
    note: `The opposite is "on purpose".`,
    audio: 'a2-idm-030.ogg',
  },
  {
    id: 'a2-idm-031',
    idiom: 'on purpose',
    meaning: 'deliberately; intentionally.',
    examples: ['He did it on purpose.', 'I left early on purpose.'],
    note: `The opposite is "by accident".`,
    audio: 'a2-idm-031.ogg',
  },
  {
    id: 'a2-idm-032',
    idiom: 'at least',
    meaning: 'not less than; or, used to find a positive.',
    examples: ['It costs at least fifty dollars.', 'We lost, but at least we tried.'],
    note: `Two uses: a minimum amount, or a small comfort.`,
    audio: 'a2-idm-032.ogg',
  },
  {
    id: 'a2-idm-033',
    idiom: 'in fact',
    meaning: 'used to add a true or surprising detail.',
    examples: ['It is cheap. In fact, it is free.', 'In fact, I have never been there.'],
    note: `Often corrects or strengthens what was just said.`,
    audio: 'a2-idm-033.ogg',
  },
  {
    id: 'a2-idm-034',
    idiom: 'no matter',
    meaning: 'it is not important; whatever happens.',
    examples: ['No matter what, I will help.', 'No matter how hard, keep going.'],
    note: `Often "no matter what" or "no matter how".`,
    audio: 'a2-idm-034.ogg',
  },
];
