/**
 * B2 (upper-intermediate) idioms: expressions common in work and discussion that
 * make speech sound natural and confident, taught with a meaning and examples.
 */
import type { IdiomEntry } from '../types';

export const b2Idioms: IdiomEntry[] = [
  {
    id: 'b2-idm-001',
    idiom: 'on the fence',
    meaning: 'unable to decide between two options.',
    examples: ['I am still on the fence about it.', 'She is on the fence about the job.'],
    note: `Neutral. Means you have not chosen a side yet.`,
    audio: 'b2-idm-001.ogg',
  },
  {
    id: 'b2-idm-002',
    idiom: 'cut to the chase',
    meaning: 'to get to the main point quickly.',
    examples: ['Let me cut to the chase.', 'Cut to the chase, what do you need?'],
    note: `Direct and businesslike. Skips the small details.`,
    audio: 'b2-idm-002.ogg',
  },
  {
    id: 'b2-idm-003',
    idiom: 'touch base',
    meaning: 'to make brief contact to share an update.',
    examples: ['Let us touch base next week.', 'I just wanted to touch base with you.'],
    note: `Common at work. A quick check-in, not a long meeting.`,
    audio: 'b2-idm-003.ogg',
  },
  {
    id: 'b2-idm-004',
    idiom: 'a long shot',
    meaning: 'something with little chance of success.',
    examples: ['It is a long shot, but worth a try.', 'Winning was a long shot.'],
    note: `Often softened with "but worth a try".`,
    audio: 'b2-idm-004.ogg',
  },
  {
    id: 'b2-idm-005',
    idiom: 'get cold feet',
    meaning: 'to become nervous and unsure right before doing something.',
    examples: ['He got cold feet before the speech.', 'Do not get cold feet now.'],
    note: `Usually just before a big decision or event.`,
    audio: 'b2-idm-005.ogg',
  },
  {
    id: 'b2-idm-006',
    idiom: 'the bottom line',
    meaning: 'the most important fact or final result.',
    examples: ['The bottom line is we need more time.', 'What is the bottom line here?'],
    note: `Signals the key point after some discussion.`,
    audio: 'b2-idm-006.ogg',
  },
  {
    id: 'b2-idm-007',
    idiom: 'bite off more than you can chew',
    meaning: 'to take on more than you can handle.',
    examples: ['I bit off more than I could chew.', 'Do not bite off more than you can chew.'],
    note: `A warning about taking on too much work.`,
    audio: 'b2-idm-007.ogg',
  },
  {
    id: 'b2-idm-008',
    idiom: 'play it by ear',
    meaning: 'to decide as you go, without a fixed plan.',
    examples: ['Let us play it by ear.', 'We did not plan; we played it by ear.'],
    note: `Casual. Means stay flexible rather than plan everything.`,
    audio: 'b2-idm-008.ogg',
  },
  {
    id: 'b2-idm-009',
    idiom: 'on the same wavelength',
    meaning: 'thinking in a similar way; understanding each other easily.',
    examples: ['We are on the same wavelength.', 'They were on the same wavelength.'],
    note: `Warmer than "on the same page"; suggests natural understanding.`,
    audio: 'b2-idm-009.ogg',
  },
  {
    id: 'b2-idm-010',
    idiom: 'in the long run',
    meaning: 'over a long period of time; eventually.',
    examples: ['It will save money in the long run.', 'In the long run, it is worth it.'],
    note: `Contrasts with "in the short term".`,
    audio: 'b2-idm-010.ogg',
  },
  {
    id: 'b2-idm-011',
    idiom: 'go the extra mile',
    meaning: 'to make more effort than is expected.',
    examples: ['She always goes the extra mile.', 'We go the extra mile for clients.'],
    note: `Praises effort above the minimum required.`,
    audio: 'b2-idm-011.ogg',
  },
  {
    id: 'b2-idm-012',
    idiom: 'on second thought',
    meaning: 'after thinking about it again.',
    examples: ['On second thought, let us wait.', 'On second thought, you are right.'],
    note: `Signals that you have just changed your mind.`,
    audio: 'b2-idm-012.ogg',
  },
  {
    id: 'b2-idm-013',
    idiom: 'a win-win',
    meaning: 'a result that is good for everyone involved.',
    examples: ['It is a win-win for both sides.', 'That sounds like a win-win.'],
    note: `Means no one loses in the arrangement.`,
    audio: 'b2-idm-013.ogg',
  },
  {
    id: 'b2-idm-014',
    idiom: 'back to square one',
    meaning: 'back to the very start, with no progress made.',
    examples: ['The plan failed, so it is back to square one.', 'We are back to square one.'],
    note: `Used after an attempt that did not work out.`,
    audio: 'b2-idm-014.ogg',
  },
  {
    id: 'b2-idm-015',
    idiom: 'the big picture',
    meaning: 'the whole situation, rather than the small details.',
    examples: ['Try to see the big picture.', 'Do not lose sight of the big picture.'],
    note: `Opposite of getting stuck in tiny details.`,
    audio: 'b2-idm-015.ogg',
  },
  {
    id: 'b2-idm-016',
    idiom: 'a gut feeling',
    meaning: 'a strong instinct that is not based on facts.',
    examples: ['I have a gut feeling about this.', 'Trust your gut feeling.'],
    note: `An intuition you sense but cannot fully explain.`,
    audio: 'b2-idm-016.ogg',
  },
  {
    id: 'b2-idm-017',
    idiom: 'in hindsight',
    meaning: 'looking back, now that you know the result.',
    examples: ['In hindsight, we left too early.', 'It was a mistake, in hindsight.'],
    note: `Used to judge a past decision with what you now know.`,
    audio: 'b2-idm-017.ogg',
  },
  {
    id: 'b2-idm-018',
    idiom: 'a mixed bag',
    meaning: 'a mixture of good and bad parts.',
    examples: ['The reviews were a mixed bag.', 'The trip was a mixed bag.'],
    note: `Neutral: some good, some not so good.`,
    audio: 'b2-idm-018.ogg',
  },
  {
    id: 'b2-idm-019',
    idiom: 'the lesser of two evils',
    meaning: 'the less bad of two poor choices.',
    examples: ['I chose the lesser of two evils.', 'It was the lesser of two evils.'],
    note: `Used when neither option is good, but one is less bad.`,
    audio: 'b2-idm-019.ogg',
  },
  {
    id: 'b2-idm-020',
    idiom: 'a leap of faith',
    meaning: 'a risk taken while trusting it will work out.',
    examples: ['Starting the business was a leap of faith.', 'Take a leap of faith.'],
    note: `Acting with hope before you have any proof.`,
    audio: 'b2-idm-020.ogg',
  },
  {
    id: 'b2-idm-021',
    idiom: 'by and large',
    meaning: 'mostly; generally speaking.',
    examples: ['By and large, it went well.', 'The team is, by and large, happy.'],
    note: `Introduces a general, overall judgment.`,
    audio: 'b2-idm-021.ogg',
  },
  {
    id: 'b2-idm-022',
    idiom: 'the jury is still out',
    meaning: 'a decision or opinion has not been reached yet.',
    examples: [
      'The jury is still out on the new plan.',
      'On that question, the jury is still out.',
    ],
    note: `Means it is too early to judge the result.`,
    audio: 'b2-idm-022.ogg',
  },
  {
    id: 'b2-idm-023',
    idiom: 'cut someone some slack',
    meaning: 'to be less strict or critical with someone.',
    examples: ['Cut him some slack, he is new.', 'Could you cut me some slack today?'],
    note: `Asks for a little patience or understanding.`,
    audio: 'b2-idm-023.ogg',
  },
  {
    id: 'b2-idm-024',
    idiom: 'on the ball',
    meaning: 'alert, quick, and well prepared.',
    examples: ['She is really on the ball.', 'Thanks for being on the ball.'],
    note: `Praises someone who is sharp and on top of things.`,
    audio: 'b2-idm-024.ogg',
  },
  {
    id: 'b2-idm-025',
    idiom: "a stone's throw away",
    meaning: 'very close; a short distance.',
    examples: ["The beach is a stone's throw away.", "It is a stone's throw from the office."],
    note: `A vivid way to say something is very near.`,
    audio: 'b2-idm-025.ogg',
  },
  {
    id: 'b2-idm-026',
    idiom: 'have second thoughts',
    meaning: 'to start to doubt a decision.',
    examples: ['I am having second thoughts about it.', 'She had second thoughts and stayed.'],
    note: `Means you are beginning to reconsider a choice.`,
    audio: 'b2-idm-026.ogg',
  },
  {
    id: 'b2-idm-027',
    idiom: 'set in stone',
    meaning: 'fixed and impossible to change.',
    examples: ['The plan is not set in stone.', 'Nothing here is set in stone yet.'],
    note: `Often used in the negative: not yet final.`,
    audio: 'b2-idm-027.ogg',
  },
  {
    id: 'b2-idm-028',
    idiom: 'draw the line',
    meaning: 'to set a limit on what you will accept.',
    examples: ['I draw the line at rudeness.', 'You have to draw the line somewhere.'],
    note: `Marks the boundary of acceptable behaviour.`,
    audio: 'b2-idm-028.ogg',
  },
];
