/**
 * B1 (intermediate) idioms: common figurative expressions that make everyday
 * speech sound natural, taught with a plain meaning and examples.
 */
import type { IdiomEntry } from '../types';

export const b1Idioms: IdiomEntry[] = [
  {
    id: 'b1-idm-001',
    idiom: 'break the ice',
    meaning: 'to make people feel relaxed at the start of a meeting or chat.',
    examples: ['A joke can break the ice.', 'He told a story to break the ice.'],
    note: `Often about a first meeting or a new group.`,
    audio: 'b1-idm-001.ogg',
  },
  {
    id: 'b1-idm-002',
    idiom: 'hit the road',
    meaning: 'to leave; to start a journey.',
    examples: ['It is late, let us hit the road.', 'We hit the road early.'],
    note: `Casual. A lively way to say "let us go".`,
    audio: 'b1-idm-002.ogg',
  },
  {
    id: 'b1-idm-003',
    idiom: 'under the weather',
    meaning: 'feeling slightly ill.',
    examples: ['I am a bit under the weather today.', 'She felt under the weather.'],
    note: `A gentle, polite way to say you are not well.`,
    audio: 'b1-idm-003.ogg',
  },
  {
    id: 'b1-idm-004',
    idiom: 'a rip-off',
    meaning: 'something far too expensive for what it is.',
    examples: ['Ten dollars for a coffee is a rip-off.', 'That hotel was a rip-off.'],
    note: `Casual and negative. The verb "rip off" means to cheat someone.`,
    audio: 'b1-idm-004.ogg',
  },
  {
    id: 'b1-idm-005',
    idiom: 'keep an eye on',
    meaning: 'to watch carefully.',
    examples: ['Can you keep an eye on my bag?', 'Keep an eye on the time.'],
    note: `"keep an eye on" a person, thing, or situation.`,
    audio: 'b1-idm-005.ogg',
  },
  {
    id: 'b1-idm-006',
    idiom: 'change your mind',
    meaning: 'to form a new, different opinion or decision.',
    examples: ['I changed my mind about the trip.', 'You can change your mind later.'],
    note: `Very common. Note the difference from "make up your mind" (decide).`,
    audio: 'b1-idm-006.ogg',
  },
  {
    id: 'b1-idm-007',
    idiom: 'get the hang of it',
    meaning: 'to learn how to do something with practice.',
    examples: ['It is hard at first, but you get the hang of it.', 'I am getting the hang of it.'],
    note: `Encouraging. Means a skill becomes easy with practice.`,
    audio: 'b1-idm-007.ogg',
  },
  {
    id: 'b1-idm-008',
    idiom: 'on the same page',
    meaning: 'in agreement; understanding things the same way.',
    examples: ['Let us make sure we are on the same page.', 'Good, we are on the same page.'],
    note: `Common at work when checking that everyone agrees.`,
    audio: 'b1-idm-008.ogg',
  },
  {
    id: 'b1-idm-009',
    idiom: 'call it a day',
    meaning: 'to stop working for the day.',
    examples: ['We are tired, let us call it a day.', 'I will call it a day at five.'],
    note: `Casual. Means you have done enough for now.`,
    audio: 'b1-idm-009.ogg',
  },
  {
    id: 'b1-idm-010',
    idiom: 'cost an arm and a leg',
    meaning: 'to be very expensive.',
    examples: ['The repair cost an arm and a leg.', 'It does not cost an arm and a leg.'],
    note: `A vivid, casual way to say something was very pricey.`,
    audio: 'b1-idm-010.ogg',
  },
  {
    id: 'b1-idm-011',
    idiom: 'out of the blue',
    meaning: 'suddenly and unexpectedly.',
    examples: ['She called me out of the blue.', 'It happened out of the blue.'],
    note: `Used for surprising, completely unplanned events.`,
    audio: 'b1-idm-011.ogg',
  },
  {
    id: 'b1-idm-012',
    idiom: 'at the last minute',
    meaning: 'at the latest possible time.',
    examples: ['He cancelled at the last minute.', 'We booked at the last minute.'],
    note: `Often suggests leaving something too late.`,
    audio: 'b1-idm-012.ogg',
  },
  {
    id: 'b1-idm-013',
    idiom: 'once in a while',
    meaning: 'occasionally; not very often.',
    examples: ['We meet once in a while.', 'I treat myself once in a while.'],
    note: `Close to "sometimes" or "now and then".`,
    audio: 'b1-idm-013.ogg',
  },
  {
    id: 'b1-idm-014',
    idiom: 'in the same boat',
    meaning: 'in the same difficult situation as others.',
    examples: ['We are all in the same boat.', 'Do not worry, I am in the same boat.'],
    note: `Builds a sense that you share the problem together.`,
    audio: 'b1-idm-014.ogg',
  },
  {
    id: 'b1-idm-015',
    idiom: 'keep in touch',
    meaning: 'to stay in contact with someone.',
    examples: ['Let us keep in touch.', 'We kept in touch for years.'],
    note: `A warm thing to say when you part with someone.`,
    audio: 'b1-idm-015.ogg',
  },
  {
    id: 'b1-idm-016',
    idiom: 'a long way to go',
    meaning: 'much more still to do before finishing.',
    examples: ['We have a long way to go.', 'The project has a long way to go.'],
    note: `Acknowledges progress, but also unfinished work.`,
    audio: 'b1-idm-016.ogg',
  },
  {
    id: 'b1-idm-017',
    idiom: 'in a nutshell',
    meaning: 'in a few words; briefly.',
    examples: ['In a nutshell, we won.', 'That is the plan, in a nutshell.'],
    note: `Used before or after a short summary.`,
    audio: 'b1-idm-017.ogg',
  },
  {
    id: 'b1-idm-018',
    idiom: 'on the dot',
    meaning: 'at exactly that time.',
    examples: ['She arrived at nine on the dot.', 'The meeting starts at two on the dot.'],
    note: `Stresses being exactly punctual, not a minute late.`,
    audio: 'b1-idm-018.ogg',
  },
  {
    id: 'b1-idm-019',
    idiom: 'around the clock',
    meaning: 'all day and all night, without stopping.',
    examples: ['They worked around the clock.', 'The shop is open around the clock.'],
    note: `Means twenty-four hours a day.`,
    audio: 'b1-idm-019.ogg',
  },
  {
    id: 'b1-idm-020',
    idiom: 'a rule of thumb',
    meaning: 'a rough, practical guideline, not an exact rule.',
    examples: ['As a rule of thumb, save ten percent.', 'A good rule of thumb is to ask first.'],
    note: `A handy general guide that usually works.`,
    audio: 'b1-idm-020.ogg',
  },
  {
    id: 'b1-idm-021',
    idiom: 'the ins and outs',
    meaning: 'the small details of how something works.',
    examples: ['She knows the ins and outs of the job.', 'I am learning the ins and outs.'],
    note: `The detailed, practical knowledge of something.`,
    audio: 'b1-idm-021.ogg',
  },
  {
    id: 'b1-idm-022',
    idiom: 'off the top of my head',
    meaning: 'from memory, without checking, so maybe not exact.',
    examples: ['Off the top of my head, about fifty.', 'I cannot say off the top of my head.'],
    note: `Signals a quick guess that could be slightly wrong.`,
    audio: 'b1-idm-022.ogg',
  },
  {
    id: 'b1-idm-023',
    idiom: 'the other day',
    meaning: 'recently; a few days ago.',
    examples: ['I saw her the other day.', 'The other day, it rained really hard.'],
    note: `A vague, casual way to say "recently".`,
    audio: 'b1-idm-023.ogg',
  },
  {
    id: 'b1-idm-024',
    idiom: 'all of a sudden',
    meaning: 'suddenly and unexpectedly.',
    examples: ['All of a sudden, the lights went out.', 'It changed all of a sudden.'],
    note: `Same idea as "suddenly", but more dramatic.`,
    audio: 'b1-idm-024.ogg',
  },
  {
    id: 'b1-idm-025',
    idiom: 'in the meantime',
    meaning: 'in the time before something else happens.',
    examples: ['The food is coming; in the meantime, relax.', 'In the meantime, I will start.'],
    note: `Bridges two events with a gap between them.`,
    audio: 'b1-idm-025.ogg',
  },
  {
    id: 'b1-idm-026',
    idiom: 'make the most of',
    meaning: 'to use something as well as you can.',
    examples: ['Make the most of your holiday.', 'We made the most of the sunshine.'],
    note: `Often about a limited chance, time, or resource.`,
    audio: 'b1-idm-026.ogg',
  },
  {
    id: 'b1-idm-027',
    idiom: 'get used to',
    meaning: 'to become familiar and comfortable with something.',
    examples: ['I am getting used to the new job.', 'You will get used to it.'],
    note: `Followed by a noun or an -ing verb: "used to doing".`,
    audio: 'b1-idm-027.ogg',
  },
  {
    id: 'b1-idm-028',
    idiom: 'more or less',
    meaning: 'almost; approximately.',
    examples: ['It is more or less finished.', 'We agree, more or less.'],
    note: `Softens a statement; means roughly or nearly.`,
    audio: 'b1-idm-028.ogg',
  },
  {
    id: 'b1-idm-029',
    idiom: 'up to you',
    meaning: 'it is your decision.',
    examples: ['Where shall we eat? Up to you.', 'It is totally up to you.'],
    note: `A friendly way to let someone else choose.`,
    audio: 'b1-idm-029.ogg',
  },
  {
    id: 'b1-idm-030',
    idiom: 'now and then',
    meaning: 'occasionally; from time to time.',
    examples: ['We meet now and then.', 'I cook now and then.'],
    note: `Same idea as "once in a while".`,
    audio: 'b1-idm-030.ogg',
  },
  {
    id: 'b1-idm-031',
    idiom: 'for a change',
    meaning: 'as something different from usual.',
    examples: ['Let us walk for a change.', 'Try tea for a change.'],
    note: `Suggests doing something different than normal.`,
    audio: 'b1-idm-031.ogg',
  },
  {
    id: 'b1-idm-032',
    idiom: 'in the end',
    meaning: 'finally, after everything.',
    examples: ['In the end, we stayed home.', 'It worked out in the end.'],
    note: `Used to give the final result of a story.`,
    audio: 'b1-idm-032.ogg',
  },
  {
    id: 'b1-idm-033',
    idiom: 'as a matter of fact',
    meaning: 'in fact; actually.',
    examples: ['As a matter of fact, I agree.', 'I know him, as a matter of fact.'],
    note: `Adds a true detail, often a mild surprise.`,
    audio: 'b1-idm-033.ogg',
  },
  {
    id: 'b1-idm-034',
    idiom: 'to be fair',
    meaning: 'used to add a balanced or kinder point.',
    examples: [
      'He was late, but to be fair, the train broke down.',
      'To be fair, she did warn us.',
    ],
    note: `Introduces a point that softens a criticism.`,
    audio: 'b1-idm-034.ogg',
  },
];
