/**
 * A1 (beginner) idioms: a few very common, transparent expressions that even
 * beginners hear all the time, taught with a plain meaning and simple examples.
 */
import type { IdiomEntry } from '../types';

export const a1Idioms: IdiomEntry[] = [
  {
    id: 'a1-idm-001',
    idiom: 'no problem',
    meaning: 'a friendly way to say "that is fine" or "you are welcome".',
    examples: ['Thanks! No problem.', 'No problem, I can wait.'],
    note: `Very common and casual. A polite reply to thanks or a request.`,
    audio: 'a1-idm-001.ogg',
  },
  {
    id: 'a1-idm-002',
    idiom: 'never mind',
    meaning: 'it does not matter; forget it.',
    examples: ['Never mind, it is not important.', 'Oh, never mind, I found it.'],
    note: `Use it to drop a topic gently or wave away a small problem.`,
    audio: 'a1-idm-002.ogg',
  },
  {
    id: 'a1-idm-003',
    idiom: 'take care',
    meaning: 'a warm way to say goodbye.',
    examples: ['See you tomorrow. Take care!', 'Take care of yourself.'],
    note: `A friendly goodbye. "Take care of" also means look after something.`,
    audio: 'a1-idm-003.ogg',
  },
  {
    id: 'a1-idm-004',
    idiom: 'a little bit',
    meaning: 'a small amount.',
    examples: ['I am a little bit tired.', 'Can I have a little bit more?'],
    note: `Softens what you say. "A bit" alone is a shorter version.`,
    audio: 'a1-idm-004.ogg',
  },
  {
    id: 'a1-idm-005',
    idiom: 'all right',
    meaning: 'okay; fine; yes.',
    examples: ['All right, let us go.', 'Are you all right?'],
    note: `Use it to agree or to ask if someone is okay.`,
    audio: 'a1-idm-005.ogg',
  },
  {
    id: 'a1-idm-006',
    idiom: 'right now',
    meaning: 'at this moment; immediately.',
    examples: ['I am busy right now.', 'Can you come right now?'],
    note: `Stronger and more urgent than just "now".`,
    audio: 'a1-idm-006.ogg',
  },
  {
    id: 'a1-idm-007',
    idiom: 'of course',
    meaning: 'yes, certainly.',
    examples: ['Of course you can.', 'Of course I remember you!'],
    note: `A warm, sure "yes". Can sound impatient if said sharply.`,
    audio: 'a1-idm-007.ogg',
  },
  {
    id: 'a1-idm-008',
    idiom: 'by the way',
    meaning: 'used to add something new to the conversation.',
    examples: ['By the way, are you free tonight?', 'Oh, by the way, she called.'],
    note: `Often shortened to "BTW" in writing. Adds a side point.`,
    audio: 'a1-idm-008.ogg',
  },
  {
    id: 'a1-idm-009',
    idiom: 'come on',
    meaning: 'used to encourage someone, or to hurry them.',
    examples: ['Come on, you can do it!', 'Come on, we are late.'],
    note: `Tone matters: warm encouragement, or gentle impatience.`,
    audio: 'a1-idm-009.ogg',
  },
  {
    id: 'a1-idm-010',
    idiom: 'go ahead',
    meaning: 'please do it; you have my permission.',
    examples: ['Can I sit here? Sure, go ahead.', 'Go ahead and start.'],
    note: `A friendly way to give permission or invite someone to begin.`,
    audio: 'a1-idm-010.ogg',
  },
  {
    id: 'a1-idm-011',
    idiom: 'see you',
    meaning: 'a short, casual goodbye.',
    examples: ['See you tomorrow.', 'See you, take care.'],
    note: `Short for "see you later". Very casual and friendly.`,
    audio: 'a1-idm-011.ogg',
  },
  {
    id: 'a1-idm-012',
    idiom: 'not bad',
    meaning: 'quite good, often better than expected.',
    examples: ['How are you? Not bad, thanks.', 'The film was not bad.'],
    note: `Often means "actually good", said in a modest way.`,
    audio: 'a1-idm-012.ogg',
  },
  {
    id: 'a1-idm-013',
    idiom: 'no way',
    meaning: 'used to show strong surprise or a firm refusal.',
    examples: ['No way, that is amazing!', 'No way, I will not do that.'],
    note: `Tone shows the meaning: surprise (wow) or a strong "no".`,
    audio: 'a1-idm-013.ogg',
  },
  {
    id: 'a1-idm-014',
    idiom: 'for sure',
    meaning: 'definitely; certainly.',
    examples: ['I will be there, for sure.', 'For sure, no problem.'],
    note: `A casual way to agree strongly.`,
    audio: 'a1-idm-014.ogg',
  },
  {
    id: 'a1-idm-015',
    idiom: 'hold on',
    meaning: 'wait a moment.',
    examples: ['Hold on, I am coming.', 'Hold on a second.'],
    note: `Also used on the phone to mean "please wait".`,
    audio: 'a1-idm-015.ogg',
  },
  {
    id: 'a1-idm-016',
    idiom: 'watch out',
    meaning: 'be careful.',
    examples: ['Watch out, it is hot!', 'Watch out for the step.'],
    note: `A quick warning about possible danger.`,
    audio: 'a1-idm-016.ogg',
  },
  {
    id: 'a1-idm-017',
    idiom: 'good job',
    meaning: 'used to praise someone for doing something well.',
    examples: ['Good job, everyone!', 'You finished it? Good job.'],
    note: `Warm and common. "Nice job" and "well done" are similar.`,
    audio: 'a1-idm-017.ogg',
  },
  {
    id: 'a1-idm-018',
    idiom: 'well done',
    meaning: 'used to congratulate someone.',
    examples: ['Well done on your exam!', 'Well done, that was great.'],
    note: `A little more formal than "good job".`,
    audio: 'a1-idm-018.ogg',
  },
  {
    id: 'a1-idm-019',
    idiom: 'no worries',
    meaning: 'it is fine; do not worry about it.',
    examples: ['No worries, take your time.', 'Sorry I am late! No worries.'],
    note: `A relaxed reply to thanks or an apology.`,
    audio: 'a1-idm-019.ogg',
  },
  {
    id: 'a1-idm-020',
    idiom: 'you bet',
    meaning: 'yes, of course; certainly.',
    examples: ['Can you help? You bet!', 'You bet I will be there.'],
    note: `A friendly, casual "yes". Common in American English.`,
    audio: 'a1-idm-020.ogg',
  },
  {
    id: 'a1-idm-021',
    idiom: 'my bad',
    meaning: 'a casual way to admit a small mistake.',
    examples: ['My bad, I forgot.', 'Oh, my bad, wrong door.'],
    note: `Very informal. It means "that was my fault".`,
    audio: 'a1-idm-021.ogg',
  },
  {
    id: 'a1-idm-022',
    idiom: 'hang in there',
    meaning: 'keep going; do not give up.',
    examples: ['Hang in there, it gets easier.', 'Tough week? Hang in there.'],
    note: `A warm way to encourage someone having a hard time.`,
    audio: 'a1-idm-022.ogg',
  },
  {
    id: 'a1-idm-023',
    idiom: 'take a look',
    meaning: 'to look at something.',
    examples: ['Take a look at this.', 'Can you take a look?'],
    note: `A casual, friendly way to say "look at".`,
    audio: 'a1-idm-023.ogg',
  },
  {
    id: 'a1-idm-024',
    idiom: 'give me a sec',
    meaning: 'wait a moment.',
    examples: ['Give me a sec, I am almost done.', 'One sec, please.'],
    note: `"sec" is short for "second". Very casual.`,
    audio: 'a1-idm-024.ogg',
  },
  {
    id: 'a1-idm-025',
    idiom: 'in a minute',
    meaning: 'very soon.',
    examples: ['I will be there in a minute.', 'Dinner is ready in a minute.'],
    note: `It means soon, not exactly sixty seconds.`,
    audio: 'a1-idm-025.ogg',
  },
  {
    id: 'a1-idm-026',
    idiom: 'let me see',
    meaning: 'used while you stop to think or check.',
    examples: ['Let me see, yes, Friday works.', 'Let me see what I can do.'],
    note: `Buys you a moment to think or look something up.`,
    audio: 'a1-idm-026.ogg',
  },
  {
    id: 'a1-idm-027',
    idiom: 'good point',
    meaning: 'that is a fair or clever thing to say.',
    examples: ['Good point, I had not thought of that.', 'That is a good point.'],
    note: `Agrees that someone said something useful.`,
    audio: 'a1-idm-027.ogg',
  },
  {
    id: 'a1-idm-028',
    idiom: 'fair enough',
    meaning: 'okay, that is reasonable.',
    examples: ['Fair enough, let us do it your way.', 'You are busy? Fair enough.'],
    note: `Accepts a reason, even without full agreement.`,
    audio: 'a1-idm-028.ogg',
  },
];
