/**
 * C2 (mastery) idioms: vivid, sophisticated expressions that mark a truly fluent
 * speaker, taught with a meaning, examples, and a usage tip.
 */
import type { IdiomEntry } from '../types';

export const c2Idioms: IdiomEntry[] = [
  {
    id: 'c2-idm-001',
    idiom: 'the elephant in the room',
    meaning: 'an obvious problem that everyone avoids talking about.',
    examples: [
      'Let us address the elephant in the room.',
      'Nobody mentioned the elephant in the room.',
    ],
    note: `Used to name a difficult topic people are dodging.`,
    audio: 'c2-idm-001.ogg',
  },
  {
    id: 'c2-idm-002',
    idiom: 'a double-edged sword',
    meaning: 'something with both good and bad effects.',
    examples: ['Fame is a double-edged sword.', 'The new tool is a double-edged sword.'],
    note: `Used to flag that a benefit also carries a cost.`,
    audio: 'c2-idm-002.ogg',
  },
  {
    id: 'c2-idm-003',
    idiom: 'preaching to the choir',
    meaning: 'arguing for something to people who already agree.',
    examples: ['You are preaching to the choir.', 'I am preaching to the choir here, I know.'],
    note: `Gently notes that persuasion is unnecessary here.`,
    audio: 'c2-idm-003.ogg',
  },
  {
    id: 'c2-idm-004',
    idiom: 'a slippery slope',
    meaning: 'a small action that could lead to something much worse.',
    examples: ['Bending one rule is a slippery slope.', 'It is a slippery slope from there.'],
    note: `Warns that one step may lead to a bad chain of events.`,
    audio: 'c2-idm-004.ogg',
  },
  {
    id: 'c2-idm-005',
    idiom: 'devil is in the details',
    meaning: 'the small details are where problems hide.',
    examples: [
      'It sounds simple, but the devil is in the details.',
      'As always, the devil is in the details.',
    ],
    note: `Reminds people to check the fine print carefully.`,
    audio: 'c2-idm-005.ogg',
  },
  {
    id: 'c2-idm-006',
    idiom: 'paint yourself into a corner',
    meaning: 'to put yourself in a difficult position with no good options.',
    examples: [
      'He painted himself into a corner.',
      'We do not want to paint ourselves into a corner.',
    ],
    note: `Often about a hasty promise or decision that traps you.`,
    audio: 'c2-idm-006.ogg',
  },
  {
    id: 'c2-idm-007',
    idiom: 'a foregone conclusion',
    meaning: 'a result that is certain before it happens.',
    examples: ['The outcome was a foregone conclusion.', 'It is not a foregone conclusion yet.'],
    note: `Formal. Means the ending is obvious in advance.`,
    audio: 'c2-idm-007.ogg',
  },
  {
    id: 'c2-idm-008',
    idiom: 'bend over backwards',
    meaning: 'to try extremely hard to help or please someone.',
    examples: ['She bent over backwards to help us.', 'They bent over backwards for the client.'],
    note: `Emphasises great, sometimes excessive, effort.`,
    audio: 'c2-idm-008.ogg',
  },
  {
    id: 'c2-idm-009',
    idiom: 'the tip of the iceberg',
    meaning: 'a small visible part of a much larger problem.',
    examples: [
      'These complaints are just the tip of the iceberg.',
      'That is the tip of the iceberg.',
    ],
    note: `Suggests far more lies hidden beneath the surface.`,
    audio: 'c2-idm-009.ogg',
  },
  {
    id: 'c2-idm-010',
    idiom: 'across the board',
    meaning: 'affecting everyone or everything equally.',
    examples: ['Prices rose across the board.', 'The change applies across the board.'],
    note: `Means with no exceptions, applying to all.`,
    audio: 'c2-idm-010.ogg',
  },
  {
    id: 'c2-idm-011',
    idiom: 'the eleventh hour',
    meaning: 'the very last moment before a deadline.',
    examples: ['They agreed at the eleventh hour.', 'An eleventh-hour deal saved it.'],
    note: `Formal and vivid way to say at the last possible moment.`,
    audio: 'c2-idm-011.ogg',
  },
  {
    id: 'c2-idm-012',
    idiom: 'a watershed moment',
    meaning: 'a turning point that changes everything after it.',
    examples: [
      'It was a watershed moment for the company.',
      'The election was a watershed moment.',
    ],
    note: `Bigger and more historic than an ordinary turning point.`,
    audio: 'c2-idm-012.ogg',
  },
  {
    id: 'c2-idm-013',
    idiom: 'par for the course',
    meaning: 'typical and expected, often of something annoying.',
    examples: ['Delays are par for the course here.', 'Long queues are par for the course.'],
    note: `From golf; means the usual, normal thing to happen.`,
    audio: 'c2-idm-013.ogg',
  },
  {
    id: 'c2-idm-014',
    idiom: 'a Catch-22',
    meaning: 'a no-win situation caused by contradictory rules.',
    examples: [
      'No job without experience, no experience without a job: a Catch-22.',
      'We are stuck in a Catch-22.',
    ],
    note: `From the novel; a trap with no good way out.`,
    audio: 'c2-idm-014.ogg',
  },
  {
    id: 'c2-idm-015',
    idiom: 'a Pyrrhic victory',
    meaning: 'a win that costs so much it is hardly worth it.',
    examples: ['It was a Pyrrhic victory at best.', 'They won, but it was Pyrrhic.'],
    note: `A victory whose cost outweighs the gain.`,
    audio: 'c2-idm-015.ogg',
  },
  {
    id: 'c2-idm-016',
    idiom: 'a moot point',
    meaning: 'a question no longer worth debating.',
    examples: ['It is a moot point now.', 'That became a moot point after the vote.'],
    note: `Either already settled, or no longer relevant.`,
    audio: 'c2-idm-016.ogg',
  },
  {
    id: 'c2-idm-017',
    idiom: 'a fait accompli',
    meaning: 'a thing already done, so it cannot be changed.',
    examples: ['The merger was presented as a fait accompli.', 'By then it was a fait accompli.'],
    note: `Borrowed from French; formal. Decided before others could object.`,
    audio: 'c2-idm-017.ogg',
  },
  {
    id: 'c2-idm-018',
    idiom: 'a poisoned chalice',
    meaning: 'something that seems desirable but brings trouble.',
    examples: ['The top job was a poisoned chalice.', 'That contract is a poisoned chalice.'],
    note: `An attractive prize that turns out to harm whoever takes it.`,
    audio: 'c2-idm-018.ogg',
  },
  {
    id: 'c2-idm-019',
    idiom: 'move the goalposts',
    meaning: 'to unfairly change the rules or aims partway through.',
    examples: ['They keep moving the goalposts.', 'Do not move the goalposts on me.'],
    note: `Negative: it makes a target harder after work has started.`,
    audio: 'c2-idm-019.ogg',
  },
  {
    id: 'c2-idm-020',
    idiom: 'a storm in a teacup',
    meaning: 'a lot of fuss about something unimportant.',
    examples: ['It was a storm in a teacup.', 'Do not turn this into a storm in a teacup.'],
    note: `American English often says "a tempest in a teapot".`,
    audio: 'c2-idm-020.ogg',
  },
  {
    id: 'c2-idm-021',
    idiom: 'the thin end of the wedge',
    meaning: 'a small change that may lead to a much bigger, worse one.',
    examples: ['This fee is the thin end of the wedge.', 'They fear the thin end of the wedge.'],
    note: `A warning, close to "a slippery slope".`,
    audio: 'c2-idm-021.ogg',
  },
  {
    id: 'c2-idm-022',
    idiom: 'a house of cards',
    meaning: 'a plan or structure that could collapse very easily.',
    examples: ['The whole scheme was a house of cards.', 'It all fell like a house of cards.'],
    note: `Suggests something fragile, built on a weak base.`,
    audio: 'c2-idm-022.ogg',
  },
  {
    id: 'c2-idm-023',
    idiom: 'a zero-sum game',
    meaning: 'a situation where one side gains only if another loses.',
    examples: ['Trade need not be a zero-sum game.', 'He treats every talk as a zero-sum game.'],
    note: `From game theory; one side's gain equals the other's loss.`,
    audio: 'c2-idm-023.ogg',
  },
  {
    id: 'c2-idm-024',
    idiom: 'the path of least resistance',
    meaning: 'the easiest way, needing the least effort or conflict.',
    examples: [
      'He always takes the path of least resistance.',
      'Avoid the path of least resistance here.',
    ],
    note: `Often a gentle criticism of choosing the easy way.`,
    audio: 'c2-idm-024.ogg',
  },
  {
    id: 'c2-idm-025',
    idiom: 'a self-fulfilling prophecy',
    meaning: 'a belief that comes true because you act on it.',
    examples: [
      'Expecting failure can be a self-fulfilling prophecy.',
      'Her confidence became a self-fulfilling prophecy.',
    ],
    note: `The prediction itself helps cause the outcome.`,
    audio: 'c2-idm-025.ogg',
  },
  {
    id: 'c2-idm-026',
    idiom: 'a false economy',
    meaning: 'a saving now that ends up costing more later.',
    examples: [
      'Buying cheap tools is a false economy.',
      'Skipping maintenance is a false economy.',
    ],
    note: `Looks cheaper at first, but costs more in the end.`,
    audio: 'c2-idm-026.ogg',
  },
  {
    id: 'c2-idm-027',
    idiom: 'a labour of love',
    meaning: 'hard work done for joy rather than money.',
    examples: ['The garden was a labour of love.', 'Writing the book was a labour of love.'],
    note: `Effort given freely because you love doing it.`,
    audio: 'c2-idm-027.ogg',
  },
  {
    id: 'c2-idm-028',
    idiom: 'the lay of the land',
    meaning: 'the current state of a situation.',
    examples: [
      'Let us get the lay of the land first.',
      'She studied the lay of the land before acting.',
    ],
    note: `American English; British often says "the lie of the land".`,
    audio: 'c2-idm-028.ogg',
  },
];
