/**
 * B2 (upper-intermediate) monologues: clear arguments and structured advice, the
 * kind of thing you might say in a discussion. Listen, then retell in your words.
 */
import type { Monologue } from '../types';

export const b2Monologues: Monologue[] = [
  {
    id: 'b2-mn-001',
    topic: 'The value of travel',
    text: 'I believe travel teaches you things no classroom can. When you visit a new country, you see different ways of living and thinking. At first it can feel uncomfortable, but that discomfort is where you grow. You come home with a wider view of the world.',
    note: `General truths in the present simple, building a clear argument.`,
    audio: 'b2-mn-001.ogg',
  },
  {
    id: 'b2-mn-002',
    topic: 'Work-life balance',
    text: 'These days, work-life balance is harder than ever. With phones, work follows us home, and it is tempting to always be available. I have learned to set boundaries, like switching off after dinner. It is not selfish; it actually makes me more productive.',
    note: `"I have learned" introduces a lesson; a semicolon links two ideas.`,
    audio: 'b2-mn-002.ogg',
  },
  {
    id: 'b2-mn-003',
    topic: 'A skill worth learning',
    text: 'If I could recommend one skill, it would be public speaking. Most people fear it, yet it shapes how others see you. The trick is preparation and practice, not magic. The more you do it, the more natural it becomes.',
    note: `Opens with a second conditional; "the more... the more" shows cause and effect.`,
    audio: 'b2-mn-003.ogg',
  },
  {
    id: 'b2-mn-004',
    topic: 'How I handle stress',
    text: 'When things get stressful, I follow a simple routine. First, I step away and take a few deep breaths. Then I write down what I can control and what I cannot. Finally, I focus only on the next small step. It keeps me calm and moving forward.',
    note: `Sequencing words (first, then, finally) give a clear structure.`,
    audio: 'b2-mn-004.ogg',
  },
  {
    id: 'b2-mn-005',
    topic: 'A change I would make',
    text: 'If I ran my company, I would change how we hold meetings. Too many are long and vague, and could have been an email. I would keep them short, with a clear goal and a clear end. People would have more time to actually do their work.',
    note: `Second conditional throughout to describe an imagined change.`,
    audio: 'b2-mn-005.ogg',
  },
  {
    id: 'b2-mn-006',
    topic: 'A book that changed me',
    text: 'One book genuinely changed the way I think. It argued that small daily habits matter more than big, rare efforts. At first I was skeptical, but I decided to test it. Within months, those tiny changes had added up to something real.',
    note: `"had added up" (past perfect) shows a result built over time.`,
    audio: 'b2-mn-006.ogg',
  },
  {
    id: 'b2-mn-007',
    topic: 'The best advice I ever got',
    text: 'The best advice I ever received was to focus on progress, not perfection. For years, I waited until things were perfect before sharing them, and I missed many chances. Now I try to start, learn, and improve as I go. It is far less stressful, and I get more done. Perfection, I have realized, is often just an excuse to delay.',
    note: `"focus on X, not Y" is a crisp way to frame advice.`,
    audio: 'b2-mn-007.ogg',
  },
  {
    id: 'b2-mn-008',
    topic: 'How travel changed me',
    text: 'Traveling alone for the first time changed how I see the world. I had to solve problems on my own, from missed trains to lost bookings. At first it was frightening, but slowly I grew more capable and calm. I came home more confident and more open to people who are different from me. That trip taught me more than any classroom could.',
    note: `Past narrative with a clear before-and-after.`,
    audio: 'b2-mn-008.ogg',
  },
  {
    id: 'b2-mn-009',
    topic: 'My view on remote work',
    text: 'Remote work has clear advantages and real drawbacks. On the one hand, it saves commuting time and lets me focus deeply. On the other, it can feel isolating, and the line between work and home gets blurry. What works for me is a fixed schedule and a real break for lunch. With a little discipline, the benefits outweigh the costs.',
    note: `"On the one hand... on the other..." structures a balanced view.`,
    audio: 'b2-mn-009.ogg',
  },
  {
    id: 'b2-mn-010',
    topic: 'A goal I am chasing',
    text: 'Right now, I am working toward giving a talk at a conference. Public speaking used to terrify me, so this is a real stretch. I have started small, presenting to my team and asking for honest feedback. Each time, the fear shrinks a little. I may not be ready yet, but I am closer than I was.',
    note: `Present continuous for a current goal; "used to" for the past fear.`,
    audio: 'b2-mn-010.ogg',
  },
  {
    id: 'b2-mn-011',
    topic: 'The value of failure',
    text: 'For most of my life, I was afraid of failing, so I avoided anything I might not do perfectly. Looking back, that fear cost me far more than any mistake ever did. The few times I did fail, I learned more in a week than in a year of playing it safe. Now I treat failure as feedback, not as proof that I am not good enough.',
    note: `"not as ..., but as ..." reframes a hard idea in a fluent way.`,
    audio: 'b2-mn-011.ogg',
  },
  {
    id: 'b2-mn-012',
    topic: 'Living in a foreign country',
    text: 'Moving abroad was harder than I expected. The language, the customs, even the supermarkets felt strange at first. There were days I wanted to go home. But slowly, the unfamiliar became familiar, and strangers became friends. It taught me that I am far more adaptable than I ever believed.',
    note: `"at first ... but slowly ..." traces a gradual change.`,
    audio: 'b2-mn-012.ogg',
  },
  {
    id: 'b2-mn-013',
    topic: 'Technology and daily life',
    text: 'Technology has made my life easier in countless ways, but it has a cost. I can work from anywhere, yet I struggle to switch off. My phone saves time and steals my attention in the same breath. I am learning to set boundaries, like leaving it in another room. The goal is to use the tools without being used by them.',
    note: `Use "yet" and "but" to balance two sides of an argument.`,
    audio: 'b2-mn-013.ogg',
  },
  {
    id: 'b2-mn-014',
    topic: 'What good communication means',
    text: 'Good communication is less about speaking well and more about listening. For years I focused on getting my point across. I have come to see that people respond when they feel understood. Now I ask more questions and interrupt less. Strangely, I am more persuasive when I talk the least.',
    note: `"less about ..., more about ..." is a polished comparison.`,
    audio: 'b2-mn-014.ogg',
  },
  {
    id: 'b2-mn-015',
    topic: 'A risk that paid off',
    text: 'A few years ago, I left a stable job to join a tiny company. Everyone thought I was crazy, and honestly, so did I some nights. The work was uncertain and the pay was lower at first. But I learned faster than ever and found work I actually cared about. Sometimes the safe choice is the real risk.',
    note: `End with a twist: "the safe choice is the real risk".`,
    audio: 'b2-mn-015.ogg',
  },
  {
    id: 'b2-mn-016',
    topic: 'The habit that changed my life',
    text: 'The single habit that changed my life was writing things down. Each morning, I spend ten minutes planning my day on paper. It sounds small, but it clears the noise in my head. I waste less time wondering what to do next. A clear plan, I have found, is the cheapest form of calm.',
    note: `"It sounds small, but ..." sets up a surprising payoff.`,
    audio: 'b2-mn-016.ogg',
  },
  {
    id: 'b2-mn-017',
    topic: 'The power of small habits',
    text: 'I used to believe that big results required big, dramatic changes. In reality, almost every improvement in my life came from small, boring habits repeated daily. Ten minutes of reading, a short walk, a tidy desk; none of them felt important alone. But over months, they quietly reshaped how I work and feel. Consistency, I have learned, beats intensity almost every time.',
    note: `A list of three, then a clear takeaway sentence.`,
    audio: 'b2-mn-017.ogg',
  },
  {
    id: 'b2-mn-018',
    topic: 'Working with difficult people',
    text: 'Early in my career, I avoided people I found difficult. I assumed the problem was always them. Over time, I realised I could not control their behaviour, only my response to it. Once I stopped taking things personally, the tension dropped. Now I see those relationships as the best training I ever had.',
    note: `"I could not control ..., only ..." is a fluent contrast.`,
    audio: 'b2-mn-018.ogg',
  },
  {
    id: 'b2-mn-019',
    topic: 'Why I stopped multitasking',
    text: 'For a long time, I wore multitasking like a badge of honour. I answered emails in meetings and checked my phone while writing. The truth is, I did everything a little worse and finished nothing properly. When I started doing one thing at a time, my work improved overnight. Focus, it turns out, is a skill, not a personality trait.',
    note: `"..., it turns out, is X, not Y" lands a neat conclusion.`,
    audio: 'b2-mn-019.ogg',
  },
  {
    id: 'b2-mn-020',
    topic: 'Learning from a failure',
    text: 'A project I led two years ago failed completely. We missed every deadline and the client walked away. For weeks I felt like a fraud. But when I looked closely, I found a dozen clear lessons about planning and honesty. That failure taught me more than any of my successes ever did.',
    note: `End with a strong reversal: failure as the best teacher.`,
    audio: 'b2-mn-020.ogg',
  },
  {
    id: 'b2-mn-021',
    topic: 'The value of boredom',
    text: 'We treat boredom like a problem to be solved with a screen. Yet some of my best ideas have arrived in dull, empty moments. When I let my mind wander on a walk, it makes connections it never could under pressure. Now I protect a little boredom on purpose. An idle mind, I have found, is often a creative one.',
    note: `"Yet ..." pivots from the common view to your own.`,
    audio: 'b2-mn-021.ogg',
  },
  {
    id: 'b2-mn-022',
    topic: 'Choosing where to live',
    text: 'When I chose where to live, I focused only on the rent and the commute. What I underestimated was how much the surroundings would shape my mood. A quiet street, good light, and a park nearby changed my daily life more than I expected. We adapt to our environment without noticing. So it is worth choosing it carefully.',
    note: `"What I underestimated was ..." is a polished cleft sentence.`,
    audio: 'b2-mn-022.ogg',
  },
];
