/**
 * B1 (intermediate) monologues: real opinions and small personal stories, with a
 * reflective last line. Listen, then retell in your own words.
 */
import type { Monologue } from '../types';

export const b1Monologues: Monologue[] = [
  {
    id: 'b1-mn-001',
    topic: 'A challenge I faced',
    text: 'A few years ago, I lost my job. At first, I felt lost and worried. But I decided to learn new skills and stay positive. After six months, I found a better position. Looking back, that hard time made me stronger.',
    note: `Past simple for the story, then a reflective line at the end.`,
    audio: 'b1-mn-001.ogg',
  },
  {
    id: 'b1-mn-002',
    topic: 'Why I like my city',
    text: 'I have lived in this city for ten years, and I still love it. There is always something to do, from concerts to markets. The people are open and the food is amazing. Yes, it can be expensive, but it is worth it.',
    note: `"have lived" shows duration; the last line gives a balanced view.`,
    audio: 'b1-mn-002.ogg',
  },
  {
    id: 'b1-mn-003',
    topic: 'A typical work day',
    text: 'My work day usually starts with checking emails and planning my tasks. Around noon, I have a quick lunch with my colleagues. The afternoon is for meetings, which can be long. By the time I get home, I am tired but satisfied.',
    note: `"usually" for routine; "which" adds extra detail.`,
    audio: 'b1-mn-003.ogg',
  },
  {
    id: 'b1-mn-004',
    topic: 'My view on social media',
    text: 'Honestly, I think social media has good and bad sides. It helps us stay in touch with people far away. On the other hand, it can waste a lot of time. I try to use it less and enjoy real life more.',
    note: `"On the other hand" balances the two sides of an opinion.`,
    audio: 'b1-mn-004.ogg',
  },
  {
    id: 'b1-mn-005',
    topic: 'A goal I am working on',
    text: 'Right now, I am working on getting fit. I have started running three times a week and eating better. It is not always easy, especially on cold mornings. But I feel more energetic already, so I will keep going.',
    note: `"have started" links past to present; give a reason and a result.`,
    audio: 'b1-mn-005.ogg',
  },
  {
    id: 'b1-mn-006',
    topic: 'A memorable meal',
    text: "I will never forget a meal at my grandmother's house. The whole family was there, laughing and talking. The table was full of homemade dishes. It was not really about the food. It was about being together.",
    note: `Past tenses for the scene, then a thoughtful final line.`,
    audio: 'b1-mn-006.ogg',
  },
  {
    id: 'b1-mn-007',
    topic: 'A person who influenced me',
    text: 'My first manager taught me a lot. She was patient and always explained things clearly. When I made mistakes, she helped me learn instead of getting angry. Because of her, I became more confident. I still use her advice today.',
    note: `"Because of her" links cause and effect.`,
    audio: 'b1-mn-007.ogg',
  },
  {
    id: 'b1-mn-008',
    topic: 'My morning routine',
    text: 'I have a simple morning routine that keeps me focused. First, I drink some water and stretch for a few minutes. Then I plan the three most important things for the day. I avoid my phone until after breakfast. By the time I start work, I feel ready.',
    note: `Sequencing words plus a relative clause ("that keeps me focused").`,
    audio: 'b1-mn-008.ogg',
  },
  {
    id: 'b1-mn-009',
    topic: 'Something I would change',
    text: 'One thing I would change about my city is the traffic. In the morning, the roads are completely full, and a short trip can take an hour. I think better public transport would help. It would save time and reduce pollution. I hope it improves soon.',
    note: `"I would change" plus reasons with "would help / would save".`,
    audio: 'b1-mn-009.ogg',
  },
  {
    id: 'b1-mn-010',
    topic: 'Something I am proud of',
    text: 'I am proud that I finished my degree while working full time. It was exhausting, and many nights I wanted to give up. But I kept going, one assignment at a time. When I graduated, my family was so happy. It taught me that I can do hard things.',
    note: `"I am proud that..." plus a story and a lesson.`,
    audio: 'b1-mn-010.ogg',
  },
  {
    id: 'b1-mn-011',
    topic: 'How I deal with stress',
    text: 'When I feel stressed, I try not to panic. First, I take a few deep breaths and step away from the problem. Then I make a short list of what I can actually control. Talking to a friend helps too. Most problems feel smaller once I slow down.',
    note: `Sequence your method with "First", "Then", and "once".`,
    audio: 'b1-mn-011.ogg',
  },
  {
    id: 'b1-mn-012',
    topic: 'A book that changed me',
    text: 'A few years ago, I read a book about habits. It explained how small daily actions add up over time. After reading it, I started waking up earlier and reading more. The change was slow but real. It taught me that progress comes from consistency, not luck.',
    note: `"It taught me that ..." links the book to a lesson.`,
    audio: 'b1-mn-012.ogg',
  },
  {
    id: 'b1-mn-013',
    topic: 'Why I love my hometown',
    text: 'My hometown is not famous, but I love it. The streets are quiet and everyone knows each other. There is a market every Sunday where you can find fresh food. As a child, I played in the same park my parents did. It will always feel like home.',
    note: `Mix present and past tenses to describe a place over time.`,
    audio: 'b1-mn-013.ogg',
  },
  {
    id: 'b1-mn-014',
    topic: 'A challenge at work',
    text: 'Last year, my team lost an important member, and we had to manage with fewer people. At first, the workload felt impossible. We sat down together and shared the tasks more fairly. Slowly, we found a better way to work. In the end, we became stronger as a team.',
    note: `"At first ... In the end ..." shows how a situation changed.`,
    audio: 'b1-mn-014.ogg',
  },
  {
    id: 'b1-mn-015',
    topic: 'My plans for the future',
    text: 'In the next few years, I want to grow in my career and learn new skills. I am also saving money to travel more. One day, I would like to live abroad for a while. I know plans can change, but having a direction helps. It keeps me motivated.',
    note: `Use "I want to", "I would like to", and "One day" for plans.`,
    audio: 'b1-mn-015.ogg',
  },
  {
    id: 'b1-mn-016',
    topic: 'Something I changed my mind about',
    text: 'I used to think that being busy meant being successful. I filled every hour and felt proud of it. Over time, I realised I was exhausted and not really happier. Now I try to do less, but do it well. Rest, I have learned, is part of the work.',
    note: `"I used to think ... Now ..." marks a change of view.`,
    audio: 'b1-mn-016.ogg',
  },
  {
    id: 'b1-mn-017',
    topic: 'A lesson from a job',
    text: 'My first job was in a busy restaurant. The work was hard and the hours were long. But I learned how to stay calm when everything went wrong at once. I also learned to work as part of a team. Those skills still help me today.',
    note: `Link a past job to the present with "still help me today".`,
    audio: 'b1-mn-017.ogg',
  },
  {
    id: 'b1-mn-018',
    topic: 'Why I value sleep',
    text: 'For years, I thought sleep was a waste of time. I stayed up late and woke up tired. Eventually, I realised it was hurting my focus and my mood. Now I treat sleep as part of my work, not the opposite. Everything feels easier when I am well rested.',
    note: `"For years, I thought ... Now ..." shows a change of view.`,
    audio: 'b1-mn-018.ogg',
  },
  {
    id: 'b1-mn-019',
    topic: 'A friendship that lasted',
    text: 'I have known my best friend since we were children. We grew up on the same street and went to the same school. Life took us to different cities, but we still talk every week. A good friendship does not need constant contact. It just needs trust and a little effort.',
    note: `"I have known ... since ..." uses the present perfect.`,
    audio: 'b1-mn-019.ogg',
  },
  {
    id: 'b1-mn-020',
    topic: 'Dealing with change',
    text: 'Last year, my company moved to a new office across the city. At first, I was annoyed by the longer journey. But the change pushed me to find a better routine. I started walking part of the way and reading more. Sometimes a small disruption leads to a better habit.',
    note: `"At first ... But ..." sets up a change for the better.`,
    audio: 'b1-mn-020.ogg',
  },
  {
    id: 'b1-mn-021',
    topic: 'Something I am learning',
    text: 'Right now, I am learning to cook proper meals instead of ordering food. I follow simple recipes and try one new dish each week. Some of them fail, and that is fine. Slowly, my confidence in the kitchen is growing. It is cheaper, healthier, and surprisingly fun.',
    note: `"Right now, I am ...-ing" describes a current project.`,
    audio: 'b1-mn-021.ogg',
  },
  {
    id: 'b1-mn-022',
    topic: 'A piece of advice I follow',
    text: 'Someone once told me to do the hardest task first thing in the morning. At first, it sounded unpleasant, but I gave it a try. Now I finish the difficult work before my energy drops. The rest of the day feels lighter. It is the simplest advice that has helped me the most.',
    note: `Report advice with "told me to ..." then give the result.`,
    audio: 'b1-mn-022.ogg',
  },
];
