/**
 * C1 (advanced) monologues: confident, well-structured reflections on ideas. The
 * goal is fluent flow and a strong finish. Listen, then retell in your own words.
 */
import type { Monologue } from '../types';

export const c1Monologues: Monologue[] = [
  {
    id: 'c1-mn-001',
    topic: 'On lifelong learning',
    text: "I am convinced that learning should not stop when school does. The world shifts so quickly that yesterday's expertise can fade fast. What matters is staying curious and willing to be a beginner again. Those who keep learning tend to stay relevant, and frankly, more interesting.",
    note: `Confident tone; "What matters is..." puts the focus on your main point.`,
    audio: 'c1-mn-001.ogg',
  },
  {
    id: 'c1-mn-002',
    topic: 'The art of listening',
    text: 'We often think good communication is about speaking well, but listening is half the skill, if not more. When you truly listen, people feel understood, and they open up. It is harder than it sounds, because our minds race ahead to reply. Slowing down to listen is a rare and powerful habit.',
    note: `"if not more" concedes a point; notice the smooth, even flow.`,
    audio: 'c1-mn-002.ogg',
  },
  {
    id: 'c1-mn-003',
    topic: 'Why failure matters',
    text: 'Having failed more than once, I have come to see failure differently. It is not the opposite of success; it is part of the path to it. Each setback, painful as it is, teaches something a win never could. The key is to fail, reflect, and try again, a little wiser.',
    note: `"Having failed..." is a participle opener; the ending lands the point.`,
    audio: 'c1-mn-003.ogg',
  },
  {
    id: 'c1-mn-004',
    topic: 'On giving feedback',
    text: 'Giving feedback well is an underrated skill. The goal is not to prove you are right, but to help the other person improve. I try to be specific, kind, and focused on the work, not the person. Done well, honest feedback is one of the best gifts you can give.',
    note: `"not to... but to..." sets up a clean contrast.`,
    audio: 'c1-mn-004.ogg',
  },
  {
    id: 'c1-mn-005',
    topic: 'The pace of technology',
    text: 'Technology promises to save us time, yet many of us feel busier than ever. The tools are not the problem; how we use them is. If we let every notification pull at us, we lose the deep focus that real work requires. Used wisely, though, the same tools can set us free.',
    note: `"yet" signals contrast; "Used wisely" is a neat participle clause.`,
    audio: 'c1-mn-005.ogg',
  },
  {
    id: 'c1-mn-006',
    topic: 'A piece of advice',
    text: 'If I could give my younger self one piece of advice, it would be this: do not wait until you feel ready. You rarely will. Confidence does not come before action; it comes from it. Start small, start scared, but start.',
    note: `A second conditional opener and a short, punchy three-part ending.`,
    audio: 'c1-mn-006.ogg',
  },
  {
    id: 'c1-mn-007',
    topic: 'On the value of curiosity',
    text: 'Curiosity, I have come to believe, is the engine of a meaningful life. The people I most admire are not the cleverest, but the most interested, always asking questions and following them wherever they lead. Curiosity keeps the mind young and the work fresh. When I feel stuck, it is usually because I have stopped being curious.',
    note: `An inserted "I have come to believe" adds a thoughtful, fluent tone.`,
    audio: 'c1-mn-007.ogg',
  },
  {
    id: 'c1-mn-008',
    topic: 'Why I value simplicity',
    text: 'Over the years, I have learned to prize simplicity in almost everything. A simple plan is easier to follow; a simple message is easier to remember; a simple life is easier to enjoy. Complexity often hides a lack of clarity. Stripping things back takes effort and courage, but what remains is usually what mattered all along.',
    note: `Parallel structure (a simple X is easier to...) gives rhythm.`,
    audio: 'c1-mn-008.ogg',
  },
  {
    id: 'c1-mn-009',
    topic: 'On handling criticism',
    text: 'Learning to handle criticism well has been one of the most useful skills I have developed. My instinct used to be to defend myself immediately, but that taught me nothing. Now I try to listen fully, separate the useful from the unkind, and thank the person regardless. Not all feedback is right, but almost all of it holds a grain of truth.',
    note: `Contrast your old instinct with your current approach.`,
    audio: 'c1-mn-009.ogg',
  },
  {
    id: 'c1-mn-010',
    topic: 'What I have learned about time',
    text: 'If there is one thing experience has taught me, it is that time is our most honest currency. We can always earn more money, but never more hours. For a long time I spent my time carelessly. These days I try to ask what truly deserves my attention and protect it fiercely. How we spend our days, after all, is how we spend our lives.',
    note: `"If there is one thing..." is a strong, fluent opener.`,
    audio: 'c1-mn-010.ogg',
  },
  {
    id: 'c1-mn-011',
    topic: 'On the art of listening',
    text: 'We tend to think of conversation as taking turns to speak, but the real skill lies in listening. When I truly listen, I notice what is left unsaid as much as the words themselves. People relax when they sense they are being heard rather than waited out. Over the years, I have learned that silence is not empty; it is where understanding grows. The best conversations leave me changed, not merely informed.',
    note: `"not X; it is Y" and "not merely ..." add fluent contrast.`,
    audio: 'c1-mn-011.ogg',
  },
  {
    id: 'c1-mn-012',
    topic: 'Why curiosity matters',
    text: 'Of all the qualities worth cultivating, I would put curiosity near the top. It costs nothing, yet it quietly transforms how you move through the world. A curious person treats every stranger as a story and every setback as a puzzle. I have noticed that the people who stay curious rarely grow bitter or bored. Curiosity, in the end, is what keeps the mind young long after the body is not.',
    note: `"Of all the ..., I would put ..." is a confident opener.`,
    audio: 'c1-mn-012.ogg',
  },
  {
    id: 'c1-mn-013',
    topic: 'The discipline of saying no',
    text: 'Learning to say no was one of the hardest lessons of my adult life. For years I said yes to everything, afraid of disappointing people. The result was a calendar full of priorities that were not my own. Saying no, I slowly realised, is how you say yes to what matters. A clear no, offered kindly, is a form of respect.',
    note: `"Saying no is how you say yes to ..." is a memorable reframe.`,
    audio: 'c1-mn-013.ogg',
  },
  {
    id: 'c1-mn-014',
    topic: 'On changing your mind',
    text: 'There is a strange pride people take in never changing their minds, as if consistency were the highest virtue. I see it differently now. Changing my mind in the face of better evidence is not weakness; it is how I grow. The hard part is doing it gracefully, without pretending I never held the old view. The strongest people I know hold their opinions firmly and their egos loosely.',
    note: `"hold their opinions firmly and their egos loosely" is a neat line.`,
    audio: 'c1-mn-014.ogg',
  },
  {
    id: 'c1-mn-015',
    topic: 'What travel taught me',
    text: 'Travel did not make me wiser overnight, but it slowly rearranged how I see things. Standing in an unfamiliar place, I realised how much of what I called normal was simply local. The discomfort of not knowing the rules forced me to pay attention again. I came home with fewer certainties and far more questions. That, I think, is the quiet gift of going far from what you know.',
    note: `"fewer certainties and far more questions" balances a sentence well.`,
    audio: 'c1-mn-015.ogg',
  },
  {
    id: 'c1-mn-016',
    topic: 'The cost of comparison',
    text: 'Few habits drain a life as quietly as comparison. For years I measured my progress against people whose full story I never knew. The result was a constant, low hum of dissatisfaction, no matter what I achieved. When I finally turned my attention to my own path, the noise faded. I am happiest, it turns out, when I compete only with the person I was yesterday.',
    note: `"as quietly as ..." and "it turns out" sound natural and fluent.`,
    audio: 'c1-mn-016.ogg',
  },
  {
    id: 'c1-mn-017',
    topic: 'On the discipline of attention',
    text: "We like to think we choose what we pay attention to, but mostly the world chooses for us. Notifications, headlines, and other people's urgencies pull our focus in a hundred directions. Reclaiming attention has become, for me, a daily act of resistance. I guard my mornings, silence my phone, and protect long stretches of quiet. What I attend to, in the end, is what my life becomes.",
    note: `Ends on a memorable line: attention shapes the life.`,
    audio: 'c1-mn-017.ogg',
  },
  {
    id: 'c1-mn-018',
    topic: 'The trouble with advice',
    text: "Advice is one of the cheapest things to give and the hardest to use well. Most of it is really autobiography in disguise, shaped by someone else's circumstances. I have learned to listen for the principle beneath the suggestion, not the suggestion itself. The same action that saved one person can sink another. In the end, advice is a starting point for thinking, not a substitute for it.",
    note: `"a starting point ..., not a substitute" is a clean contrast.`,
    audio: 'c1-mn-018.ogg',
  },
  {
    id: 'c1-mn-019',
    topic: 'Why I read old books',
    text: 'There is a quiet comfort in reading books that have survived a century or more. They have already passed the only test that matters, which is time. While the latest opinions shift week to week, these ideas have proven durable. I do not agree with all of them, but they slow me down and stretch my thinking. The past, read carefully, is a remarkably good teacher.',
    note: `"While X ..., Y ..." sets the new against the lasting.`,
    audio: 'c1-mn-019.ogg',
  },
  {
    id: 'c1-mn-020',
    topic: 'The cost of always being available',
    text: 'When messages first followed me everywhere, it felt like freedom. I could work from anywhere and answer anyone at any time. Slowly, that freedom became a quiet obligation to never switch off. I was present everywhere and fully present nowhere. Learning to be unreachable, for an hour or an evening, has become a small but vital discipline.',
    note: `"present everywhere and fully present nowhere" is a sharp line.`,
    audio: 'c1-mn-020.ogg',
  },
  {
    id: 'c1-mn-021',
    topic: 'On choosing your battles',
    text: 'I used to argue every point I believed was right, as if being correct were the same as being effective. It rarely was. People dig in when they feel attacked, and the relationship suffers along with the argument. Now I ask whether a particular hill is worth dying on. Saving my energy for what truly matters has made me far more persuasive.',
    note: `"as if X were the same as Y" is an elegant comparison.`,
    audio: 'c1-mn-021.ogg',
  },
  {
    id: 'c1-mn-022',
    topic: 'The quiet skill of finishing',
    text: "Starting things is easy and even exciting; finishing them is where most ambition quietly dies. I have a graveyard of half-built projects to prove it. What changed for me was lowering the bar for 'done' and shipping anyway. A finished, imperfect thing teaches you far more than a perfect, imagined one. The world rewards completion, not intention.",
    note: `"rewards completion, not intention" makes the point stick.`,
    audio: 'c1-mn-022.ogg',
  },
  {
    id: 'c1-mn-023',
    topic: 'On the value of constraints',
    text: 'We tend to think freedom means having no limits, but I have found the opposite. A blank page paralyses me; a tight brief sets me free. Constraints force creativity by removing the burden of infinite choice. The best work I have done came from rules I did not choose. Limits, used well, are not a cage but a frame.',
    note: `"not a cage but a frame" reframes the whole idea.`,
    audio: 'c1-mn-023.ogg',
  },
  {
    id: 'c1-mn-024',
    topic: 'Finishing what I read',
    text: 'I once prided myself on the number of books I started. The shelves filled up, but little of it stayed with me. Now I read fewer books and finish them slowly, taking notes. One book truly absorbed teaches more than ten skimmed. Depth, I have learned, is its own kind of speed.',
    note: `"Depth is its own kind of speed" is a memorable paradox.`,
    audio: 'c1-mn-024.ogg',
  },
  {
    id: 'c1-mn-025',
    topic: 'Why I distrust easy answers',
    text: "Whenever a complex problem has a simple, satisfying answer, I get suspicious. Real life rarely offers villains and heroes, only trade-offs. The honest response to most big questions begins with 'it depends'. That is not indecision; it is respect for how tangled things are. Certainty is comforting, but accuracy is more useful.",
    note: `"not indecision; it is respect" defends a careful stance.`,
    audio: 'c1-mn-025.ogg',
  },
  {
    id: 'c1-mn-026',
    topic: 'On being a beginner again',
    text: 'There is a particular discomfort in being bad at something as an adult. We are used to competence, and clumsiness feels like a threat. Yet starting from zero is where the steepest learning happens. I now seek out that discomfort on purpose, a little each year. Staying a beginner, somewhere, keeps the rest of life from going stale.',
    note: `"Yet ..." pivots from the discomfort to its hidden value.`,
    audio: 'c1-mn-026.ogg',
  },
  {
    id: 'c1-mn-027',
    topic: 'The quiet cost of comparison',
    text: "Social feeds taught me to measure my ordinary days against everyone's highlights. The math is rigged, and the result is always the same: I lose. When I stepped back, I rediscovered a simpler pleasure in my own small progress. I now compare myself only to who I was last year. That single change quietly returned a great deal of peace.",
    note: `"The math is rigged" makes an abstract point concrete.`,
    audio: 'c1-mn-027.ogg',
  },
  {
    id: 'c1-mn-028',
    topic: 'What a long illness taught me',
    text: 'A few years ago, illness forced me to stop completely for months. Stripped of my routines, I had to ask what actually mattered. The answer was smaller and gentler than I expected: people, rest, and meaning. I returned slower, but far clearer about how to spend my days. Sometimes a forced pause is the only way we finally listen.',
    note: `A colon introduces the short, surprising answer.`,
    audio: 'c1-mn-028.ogg',
  },
];
