/**
 * C2 (mastery) monologues: polished, almost essay-like reflections. The aim is
 * native rhythm, precise word choice, and a memorable close. Listen, then retell.
 */
import type { Monologue } from '../types';

export const c2Monologues: Monologue[] = [
  {
    id: 'c2-mn-001',
    topic: 'On clear writing',
    text: 'Clear writing is clear thinking made visible. When an idea is muddled on the page, it is usually muddled in the mind. The discipline of cutting every needless word forces you to know exactly what you mean. That, more than any clever phrase, is what readers quietly respect.',
    note: `Notice the parallel rhythm and the emphatic "That... is what" ending.`,
    audio: 'c2-mn-001.ogg',
  },
  {
    id: 'c2-mn-002',
    topic: 'The illusion of multitasking',
    text: 'We pride ourselves on multitasking, yet the evidence is unkind to that belief. What we call multitasking is really rapid switching, and each switch quietly taxes our attention. The result is work that takes longer and feels more draining. Paradoxically, doing one thing at a time is the faster path.',
    note: `Hedged, careful claims; "Paradoxically" flags a surprising truth.`,
    audio: 'c2-mn-002.ogg',
  },
  {
    id: 'c2-mn-003',
    topic: 'On disagreement',
    text: 'The healthiest teams I have seen are not those that never disagree, but those that disagree well. They argue about ideas without attacking people, and they change their minds when the evidence demands it. Comfortable agreement can be a warning sign, not a virtue. Real progress is often born of respectful friction.',
    note: `Balanced structure and parallelism carry a nuanced point.`,
    audio: 'c2-mn-003.ogg',
  },
  {
    id: 'c2-mn-004',
    topic: 'The weight of attention',
    text: 'Where we place our attention is, in the end, how we spend our lives. It is our scarcest resource, and the one we guard least. Countless forces compete for it, most of them indifferent to our goals. To reclaim our attention is, quietly, to reclaim ourselves.',
    note: `Reflective and literary; the final sentence mirrors the first.`,
    audio: 'c2-mn-004.ogg',
  },
  {
    id: 'c2-mn-005',
    topic: 'On reputation',
    text: 'A reputation is built slowly and lost quickly, which is precisely why it is worth guarding. It is not what you say about yourself, but what others can rely on you to do. Small, consistent acts of integrity compound over years. When the moment of pressure comes, that quiet record speaks for you.',
    note: `"It is not... but..." is a cleft for emphasis; smooth, even pace.`,
    audio: 'c2-mn-005.ogg',
  },
  {
    id: 'c2-mn-006',
    topic: 'Embracing uncertainty',
    text: 'Much of our anxiety comes from a craving for certainty that life will not grant. The mature response is not to pretend we know, but to act wisely despite not knowing. We gather what evidence we can, decide, and stay ready to adjust. Comfort with uncertainty may be the most useful skill of all.',
    note: `Formal hedging and a confident, summarizing final line.`,
    audio: 'c2-mn-006.ogg',
  },
  {
    id: 'c2-mn-007',
    topic: 'The courage to change your mind',
    text: 'There is a quiet courage in changing your mind, and it is badly underrated. We treat consistency as a virtue and reversal as weakness, yet clinging to a belief against the evidence is not strength but stubbornness. The thinkers I admire hold their views firmly but loosely, ready to update the moment the facts demand it. The goal, after all, was never to be right yesterday, but to be right today.',
    note: `"firmly but loosely" is a memorable paradox; "yet" pivots the argument.`,
    audio: 'c2-mn-007.ogg',
  },
  {
    id: 'c2-mn-008',
    topic: 'The myth of overnight success',
    text: 'We love the story of the overnight success, but it is almost always a comfortable fiction. Behind the sudden breakthrough lie years of unglamorous, invisible work, the failures no one filmed and the doubts no one shared. What looks like luck is usually preparation meeting opportunity. I find this oddly reassuring: the path is open to anyone patient enough to walk it quietly, long before anyone is watching.',
    note: `Inversion ("Behind the breakthrough lie years...") adds polish.`,
    audio: 'c2-mn-008.ogg',
  },
  {
    id: 'c2-mn-009',
    topic: 'Listening to disagree well',
    text: "Disagreement is not the enemy of good thinking; it is the engine of it. The danger is not that we argue, but that we argue badly, hearing only enough to prepare our rebuttal. Real listening means trying to build the other person's case better than they did, and only then responding. It is slow, humbling work, and it is where genuine understanding begins.",
    note: `"not X; it is Y" and "not that... but that..." carry a nuanced point.`,
    audio: 'c2-mn-009.ogg',
  },
  {
    id: 'c2-mn-010',
    topic: 'What attention reveals about us',
    text: 'Tell me what you pay attention to, and I will tell you who you are. Attention is not a passive lens but an active choice, repeated thousands of times a day, and those choices quietly shape the self. We become, over time, what we repeatedly notice and ignore. In an age engineered to capture our focus, deciding for ourselves where it goes may be the most important freedom we have left.',
    note: `Opens with a bold conditional; "not X but Y" sharpens the idea.`,
    audio: 'c2-mn-010.ogg',
  },
  {
    id: 'c2-mn-011',
    topic: 'On the illusion of certainty',
    text: 'We crave certainty the way we crave sugar, and it is about as nourishing. The confident voice in the room is rewarded long before anyone checks whether it was right. Yet the older I get, the more I distrust my own certainty, especially when it feels effortless. Real understanding tends to arrive quietly, hedged with conditions and aware of its own limits. To say I am not sure has become, for me, a sign of honesty rather than weakness.',
    note: `Opens with a vivid simile; "Yet the older I get ..." adds nuance.`,
    audio: 'c2-mn-011.ogg',
  },
  {
    id: 'c2-mn-012',
    topic: 'The quiet power of restraint',
    text: 'There is a kind of strength that makes no noise at all. It is the reply not sent in anger, the boast left unspoken, the impulse noticed and gently set aside. We celebrate bold action and overlook the harder discipline of holding back. Yet most of the regrets I have collected came from things I did in haste, not from patience. Restraint, I have come to believe, is not the absence of passion but its mastery.',
    note: `A list of three examples, then "not the absence of ... but ...".`,
    audio: 'c2-mn-012.ogg',
  },
  {
    id: 'c2-mn-013',
    topic: 'Why we misremember the past',
    text: 'Memory feels like a recording, but it behaves more like a rumour, revised quietly with every retelling. We edit our own histories to fit who we have since become, smoothing the contradictions until the story is clean. This is not dishonesty so much as the mind protecting its sense of self. Knowing this, I hold my certainties about the past a little more loosely. The version I trust most is usually the one that makes me slightly uncomfortable.',
    note: `"not X so much as Y" is an elegant way to qualify a claim.`,
    audio: 'c2-mn-013.ogg',
  },
  {
    id: 'c2-mn-014',
    topic: 'On the seduction of busyness',
    text: 'Busyness has become a badge we wear with weary pride, proof that we matter. But motion is not the same as progress, and a full calendar can be a very convenient place to hide. For years I mistook exhaustion for achievement and noise for purpose. The work that truly mattered was almost always quiet, slow, and easy to postpone. These days I am suspicious of any busyness that conveniently spares me from thinking.',
    note: `"mistook X for Y" appears twice; "motion is not progress" lands well.`,
    audio: 'c2-mn-014.ogg',
  },
  {
    id: 'c2-mn-015',
    topic: 'What kindness really costs',
    text: 'We speak of kindness as if it were free, but the kind that counts usually costs something. It is easy to be generous with what we have to spare; harder to give patience when we are tired or credit when we crave it ourselves. The most decent people I know practise a kindness that is deliberate, not merely pleasant. They are kind on the days it is inconvenient. That, I think, is the only kind that truly tells you who someone is.',
    note: `Semicolons balance the easy case against the hard one.`,
    audio: 'c2-mn-015.ogg',
  },
  {
    id: 'c2-mn-016',
    topic: 'The freedom in lowering the stakes',
    text: 'So much of my anxiety once came from treating every choice as final, every misstep as ruin. Age, and a few genuine disasters, taught me how rarely that is true. Most decisions are reversible, most failures survivable, most audiences far less interested in my stumbles than I imagined. Lowering the stakes did not make me careless; it made me brave. It is hard to take a real risk while guarding against an imaginary catastrophe.',
    note: `The rule of three ("most ..., most ..., most ...") builds rhythm.`,
    audio: 'c2-mn-016.ogg',
  },
  {
    id: 'c2-mn-017',
    topic: 'On the comfort of strong opinions',
    text: 'Strong opinions are seductive because they relieve us of the burden of thinking. Once we have picked a side, every new fact arrives pre-sorted into friend or enemy. I notice this most in myself when I feel certain and calm at the same time; that combination is usually a warning. Real understanding tends to be uncomfortable, provisional, and slow. I have come to trust the views that cost me something to hold.',
    note: `Ends on a paradox worth chewing on.`,
    audio: 'c2-mn-017.ogg',
  },
  {
    id: 'c2-mn-018',
    topic: 'Why simplicity is hard',
    text: 'Anyone can make a thing complicated; making it simple is the real labour. Simplicity is not the absence of effort but the residue of a great deal of it. Every clear sentence I write hides a dozen muddled ones I had to cut. The same is true of good design, good teaching, and good thinking. We mistake complexity for depth, when often it is just unfinished work.',
    note: `"not the absence of ... but the residue of ..." is a strong line.`,
    audio: 'c2-mn-018.ogg',
  },
  {
    id: 'c2-mn-019',
    topic: 'The myth of the self-made',
    text: 'We love the story of the self-made success, perhaps because it flatters us. But scratch any such story and you find teachers, lucky breaks, and quiet support along the way. None of this diminishes the effort involved; it simply places it in context. Acknowledging the help we received is not weakness but accuracy. Gratitude, properly understood, is just a clear-eyed view of how anything gets done.',
    note: `"not weakness but accuracy" reframes gratitude sharply.`,
    audio: 'c2-mn-019.ogg',
  },
  {
    id: 'c2-mn-020',
    topic: 'On holding power lightly',
    text: 'The people I have most admired wore their authority lightly, almost apologetically. They asked questions where others issued orders, and they shared credit by instinct. It struck me that real confidence rarely needs to announce itself. The loudest person in the room is seldom the most secure one. Power, like salt, is best used sparingly and noticed only when it is absent.',
    note: `The closing simile ("like salt") makes the idea memorable.`,
    audio: 'c2-mn-020.ogg',
  },
  {
    id: 'c2-mn-021',
    topic: 'The luxury of changing your mind',
    text: 'There was a time when changing my mind felt like losing an argument with myself. I clung to old positions long after the evidence had moved on. Now I see a changed mind as a sign that learning is still happening. The cost is a little pride; the reward is a more accurate map of the world. I would rather be usefully wrong today than uselessly consistent forever.',
    note: `"usefully wrong ... than uselessly consistent" balances neatly.`,
    audio: 'c2-mn-021.ogg',
  },
  {
    id: 'c2-mn-022',
    topic: 'On what we owe to strangers',
    text: 'It is easy to be kind to the people we love and tempting to ignore everyone else. Yet a society is really just a long chain of small courtesies between strangers. The patience in a queue, the held door, the honest answer; these are the threads that hold it together. None of them are heroic, and that is precisely the point. Civilisation is mostly made of ordinary decency, repeated by people who will never meet.',
    note: `A list of three small acts builds to a quiet, big claim.`,
    audio: 'c2-mn-022.ogg',
  },
];
