/**
 * A1 (beginner) monologues: short, clear model passages on everyday topics. The
 * learner listens, then says it again in their own words (a retell). Short on
 * purpose, so a beginner can actually repeat the whole thing.
 */
import type { Monologue } from '../types';

export const a1Monologues: Monologue[] = [
  {
    id: 'a1-mn-001',
    topic: 'Introducing yourself',
    text: 'Hi, my name is Sam. I am from Spain, but I live in London now. I work in a small coffee shop. In my free time, I like reading and walking. It is nice to meet you.',
    note: `A simple self-intro. Notice the order: name, where from, job, hobbies.`,
    audio: 'a1-mn-001.ogg',
  },
  {
    id: 'a1-mn-002',
    topic: 'My family',
    text: 'I have a small family. My mother is a teacher and my father is a doctor. I have one sister, and she is younger than me. We live together in a big house. We are very close.',
    note: `Use "have" for family and the present simple for facts.`,
    audio: 'a1-mn-002.ogg',
  },
  {
    id: 'a1-mn-003',
    topic: 'My daily routine',
    text: 'I get up at seven every day. I have breakfast and go to work. I come home at six. In the evening, I cook dinner and watch TV. I go to bed at eleven.',
    note: `Present simple for routine. Notice the time words: at seven, in the evening.`,
    audio: 'a1-mn-003.ogg',
  },
  {
    id: 'a1-mn-004',
    topic: 'My town',
    text: 'I live in a small town near the sea. It is quiet and clean. There is a market, a park, and two schools. The people here are friendly. I really love it.',
    note: `Use "there is" and "there are" to describe a place.`,
    audio: 'a1-mn-004.ogg',
  },
  {
    id: 'a1-mn-005',
    topic: 'My favorite food',
    text: 'My favorite food is pizza. I like it with cheese and tomatoes. I eat it every weekend with my friends. It is cheap and very tasty. I never get bored of it.',
    note: `Simple opinions with "like" and "is".`,
    audio: 'a1-mn-005.ogg',
  },
  {
    id: 'a1-mn-006',
    topic: 'My weekend',
    text: 'On weekends, I do not work. I sleep late and meet my friends. We go to the park or watch a movie. Sometimes I call my family. I feel happy and relaxed.',
    note: `Present simple for habits. Notice "sometimes" before the verb.`,
    audio: 'a1-mn-006.ogg',
  },
  {
    id: 'a1-mn-007',
    topic: 'My best friend',
    text: 'My best friend is Ali. We met at school ten years ago. He is funny and kind. We play football every weekend. I am lucky to have him.',
    note: `Describe a person with simple adjectives: funny, kind.`,
    audio: 'a1-mn-007.ogg',
  },
  {
    id: 'a1-mn-008',
    topic: 'My home',
    text: 'I live in a small apartment. It has two rooms and a little kitchen. My favorite place is the balcony. I drink my coffee there every morning. It is quiet and nice.',
    note: `Use "there is/has" and "my favorite place is" to describe a home.`,
    audio: 'a1-mn-008.ogg',
  },
  {
    id: 'a1-mn-009',
    topic: 'A normal morning',
    text: 'I wake up early. I make tea and read the news. Then I take a shower and get dressed. I leave for work at eight. I like calm mornings.',
    note: `Sequence with "then". Present simple for a routine.`,
    audio: 'a1-mn-009.ogg',
  },
  {
    id: 'a1-mn-010',
    topic: 'My pet',
    text: 'I have a small dog. Her name is Luna. She is brown and very friendly. We walk in the park every day. She makes me happy.',
    note: `"makes me happy" is a useful little phrase.`,
    audio: 'a1-mn-010.ogg',
  },
  {
    id: 'a1-mn-011',
    topic: 'My best friend',
    text: 'My best friend is Ana. We met at school ten years ago. She is funny and very kind. We talk every day. I am lucky to have her.',
    note: `Use the past simple "met" for when you met, present simple for now.`,
    audio: 'a1-mn-011.ogg',
  },
  {
    id: 'a1-mn-012',
    topic: 'My morning',
    text: 'I wake up early every day. First, I drink a glass of water. Then I make breakfast and read the news. I leave the house at eight. I like quiet mornings.',
    note: `Use "First" and "Then" to put your routine in order.`,
    audio: 'a1-mn-012.ogg',
  },
  {
    id: 'a1-mn-013',
    topic: 'My favorite season',
    text: 'My favorite season is spring. The weather is warm and the flowers grow. I go outside and walk a lot. Everything looks fresh and green. It makes me happy.',
    note: `"My favorite season is ..." then say why with simple sentences.`,
    audio: 'a1-mn-013.ogg',
  },
  {
    id: 'a1-mn-014',
    topic: 'My job',
    text: 'I work in a small shop near my house. I start at nine and finish at five. I help customers and count the money. My boss is kind. I like my job.',
    note: `Use the present simple for facts about your job.`,
    audio: 'a1-mn-014.ogg',
  },
  {
    id: 'a1-mn-015',
    topic: 'Cooking',
    text: 'In my free time, I like to cook. I make simple food like soup and rice. Sometimes my friends come to eat. We talk and laugh together. It is my favorite part of the week.',
    note: `"like to" plus a verb: "I like to cook".`,
    audio: 'a1-mn-015.ogg',
  },
  {
    id: 'a1-mn-016',
    topic: 'My city',
    text: 'I live in a big city. There are many shops and parks. The buses are fast and cheap. Sometimes it is noisy, but I like it. There is always something to do.',
    note: `Use "There is" and "There are" to describe a place.`,
    audio: 'a1-mn-016.ogg',
  },
  {
    id: 'a1-mn-017',
    topic: 'My favorite day',
    text: 'Saturday is my favorite day. I do not work, so I sleep a little longer. I meet my friends in the afternoon. In the evening, we eat together. It is a happy day for me.',
    note: `Use "so" to link a reason and a result.`,
    audio: 'a1-mn-017.ogg',
  },
  {
    id: 'a1-mn-018',
    topic: 'My phone',
    text: 'I use my phone every day. I call my family and send messages. I also take photos and listen to music. Sometimes I play games. It helps me stay close to people.',
    note: `Use the present simple for daily habits.`,
    audio: 'a1-mn-018.ogg',
  },
  {
    id: 'a1-mn-019',
    topic: 'My favorite drink',
    text: 'My favorite drink is tea. I make it every morning with a little sugar. It is warm and sweet. I drink it slowly and read the news. It is a nice start to my day.',
    note: `Time words like "every morning" show a routine.`,
    audio: 'a1-mn-019.ogg',
  },
  {
    id: 'a1-mn-020',
    topic: 'Going shopping',
    text: 'On Sundays, I go to the market. I buy fresh fruit and vegetables. The market is busy and noisy. I like the colors and the smells. I always come home with a full bag.',
    note: `"On Sundays" shows something you do every week.`,
    audio: 'a1-mn-020.ogg',
  },
  {
    id: 'a1-mn-021',
    topic: 'My neighbor',
    text: 'My neighbor is a kind old man. He lives alone with his cat. Sometimes I help him carry his bags. He always says thank you. We are good friends.',
    note: `Use the present simple to describe a person.`,
    audio: 'a1-mn-021.ogg',
  },
  {
    id: 'a1-mn-022',
    topic: 'The weather here',
    text: 'The weather here is usually warm. In summer, it is very hot and sunny. In winter, it is cool but not cold. It rarely rains. I like the warm days the best.',
    note: `Words like "usually" and "rarely" say how often.`,
    audio: 'a1-mn-022.ogg',
  },
  {
    id: 'a1-mn-023',
    topic: 'My weekend',
    text: 'On the weekend, I do not work. I sleep late and have a big breakfast. In the afternoon, I visit my friends. We talk and play games. It is a happy time.',
    note: `Time phrases like "In the afternoon" organise your day.`,
    audio: 'a1-mn-023.ogg',
  },
  {
    id: 'a1-mn-024',
    topic: 'My room',
    text: 'My room is small but nice. There is a bed, a desk, and a big window. I keep my books on the desk. In the evening, I read here. It is my favorite place.',
    note: `Use "There is" and "There are" to describe a room.`,
    audio: 'a1-mn-024.ogg',
  },
  {
    id: 'a1-mn-025',
    topic: 'Family dinners',
    text: 'My family eats dinner together every night. My mother cooks and we all help. We talk about our day. The food is simple and good. I love this time with them.',
    note: `Use the present simple for things you do every day.`,
    audio: 'a1-mn-025.ogg',
  },
  {
    id: 'a1-mn-026',
    topic: 'Learning to swim',
    text: 'I am learning to swim. At first, I was afraid of the water. Now I can swim a little. My teacher is very kind. I practice every week.',
    note: `"At first ... Now ..." shows a change over time.`,
    audio: 'a1-mn-026.ogg',
  },
  {
    id: 'a1-mn-027',
    topic: 'My favorite animal',
    text: 'My favorite animal is the elephant. It is big and gray. Elephants are clever and kind. I saw one at the zoo last year. It was amazing.',
    note: `Use the past simple "saw" and "was" for last year.`,
    audio: 'a1-mn-027.ogg',
  },
  {
    id: 'a1-mn-028',
    topic: 'A gift I like',
    text: 'Last week, my friend gave me a book. It is about space and stars. I read a little every night. It is very interesting. I want to say thank you again.',
    note: `"gave" is the past simple of "give".`,
    audio: 'a1-mn-028.ogg',
  },
];
