/**
 * A2 (elementary) monologues: slightly longer model passages with a little story
 * and feeling. Listen, then retell in your own words.
 */
import type { Monologue } from '../types';

export const a2Monologues: Monologue[] = [
  {
    id: 'a2-mn-001',
    topic: 'A trip I took',
    text: 'Last summer, I went to Italy with my friends. We stayed in a small hotel near the beach. Every morning, we swam in the sea and ate fresh fruit. In the evening, we walked around the town. It was a wonderful trip.',
    note: `Past simple for a finished story. Notice "went", "stayed", "was".`,
    audio: 'a2-mn-001.ogg',
  },
  {
    id: 'a2-mn-002',
    topic: 'My job',
    text: 'I work as a nurse in a hospital. My day is busy, but I like helping people. I start early and finish late. Sometimes the work is hard, but it feels important. I am proud of my job.',
    note: `Mix present-simple facts with how you feel about them.`,
    audio: 'a2-mn-002.ogg',
  },
  {
    id: 'a2-mn-003',
    topic: 'Learning English',
    text: 'I am learning English because I want a better job. I study a little every day. I watch videos and practice speaking. It is not easy, but I am getting better. I will keep trying.',
    note: `"because" gives a reason; "will" states a plan.`,
    audio: 'a2-mn-003.ogg',
  },
  {
    id: 'a2-mn-004',
    topic: 'A person I admire',
    text: 'I really admire my grandmother. She is kind, patient, and very strong. She raised five children alone. She always smiles, even on hard days. I want to be like her.',
    note: `Use clear adjectives to describe a person.`,
    audio: 'a2-mn-004.ogg',
  },
  {
    id: 'a2-mn-005',
    topic: 'My hobby',
    text: 'In my free time, I love cooking. I learned it from my mother when I was young. I try new recipes every week. Cooking helps me relax after work. My friends say my food is delicious.',
    note: `Talk about a hobby and give a reason you enjoy it.`,
    audio: 'a2-mn-005.ogg',
  },
  {
    id: 'a2-mn-006',
    topic: 'Plans for next year',
    text: 'Next year, I am going to move to a new city. I want to find a better job and meet new people. I am a little nervous, but also excited. I think it will be a good change.',
    note: `"going to" for plans, "will" for predictions.`,
    audio: 'a2-mn-006.ogg',
  },
  {
    id: 'a2-mn-007',
    topic: 'A skill I want to learn',
    text: 'I really want to learn how to swim. I never learned as a child, and now I feel a little scared of deep water. This summer, I am going to take lessons. I think it will be good for my health. I am excited to try.',
    note: `"going to" for the plan, "I think it will" for the prediction.`,
    audio: 'a2-mn-007.ogg',
  },
  {
    id: 'a2-mn-008',
    topic: 'My favorite place',
    text: 'My favorite place is a small library near my house. It is always quiet and warm. I go there on Saturdays to read and study. The people are friendly, and the coffee is cheap. I feel calm there.',
    note: `Describe a place with adjectives and what you do there.`,
    audio: 'a2-mn-008.ogg',
  },
  {
    id: 'a2-mn-009',
    topic: 'A holiday I remember',
    text: 'Two years ago, I visited the mountains with my family. We stayed in a small cabin. Every day, we walked and took photos. At night, we cooked together and laughed. It was simple, but I will never forget it.',
    note: `Past simple story, ending with a feeling.`,
    audio: 'a2-mn-009.ogg',
  },
  {
    id: 'a2-mn-010',
    topic: 'Why I am learning English',
    text: 'I am learning English for my future. I want to travel and meet people from other countries. I also need it for my job. It is hard sometimes, but I practice every day. Step by step, I am getting better.',
    note: `Give reasons with "for" and "to". "Step by step" sounds natural.`,
    audio: 'a2-mn-010.ogg',
  },
  {
    id: 'a2-mn-011',
    topic: 'A trip I enjoyed',
    text: 'Last summer, I went to the mountains with my family. We stayed in a small house near a lake. Every morning, we walked and took photos. The air was clean and the views were beautiful. I want to go back one day.',
    note: `Use the past simple to tell a story: went, stayed, walked.`,
    audio: 'a2-mn-011.ogg',
  },
  {
    id: 'a2-mn-012',
    topic: 'My favorite hobby',
    text: 'My favorite hobby is photography. I started two years ago with my phone. Now I have a small camera. I love taking pictures of streets and people. It helps me see the world more carefully.',
    note: `"I love" plus an -ing verb: "I love taking pictures".`,
    audio: 'a2-mn-012.ogg',
  },
  {
    id: 'a2-mn-013',
    topic: 'A person I admire',
    text: 'I really admire my grandmother. She grew up with very little, but she never gave up. She taught me to be patient and kind. She always has a story to tell. I hope I can be like her.',
    note: `Use "She taught me to ..." to share a lesson from someone.`,
    audio: 'a2-mn-013.ogg',
  },
  {
    id: 'a2-mn-014',
    topic: 'My weekend routine',
    text: 'On weekends, I like to relax. I get up late and have a big breakfast. In the afternoon, I meet friends or go shopping. In the evening, I watch a film at home. It is the perfect way to rest.',
    note: `Use time phrases: "In the afternoon", "In the evening".`,
    audio: 'a2-mn-014.ogg',
  },
  {
    id: 'a2-mn-015',
    topic: 'A skill I want to learn',
    text: 'I want to learn how to drive. Right now, I take the bus everywhere. With a car, I could travel more easily. I am a little nervous, but also excited. I plan to start lessons next month.',
    note: `"I want to learn how to ..." plus a verb.`,
    audio: 'a2-mn-015.ogg',
  },
  {
    id: 'a2-mn-016',
    topic: 'My favorite place',
    text: 'My favorite place is a small café near my office. It is quiet and warm. I go there to read or just think. The coffee is great and the staff are friendly. I feel calm every time I visit.',
    note: `"I go there to ..." explains why you go somewhere.`,
    audio: 'a2-mn-016.ogg',
  },
  {
    id: 'a2-mn-017',
    topic: 'A small win',
    text: 'Last week, I finally fixed my bike by myself. I watched a short video and followed the steps. At first, I made a mistake, but I tried again. In the end, it worked perfectly. I felt really proud of myself.',
    note: `Tell a short story with the past simple and "In the end".`,
    audio: 'a2-mn-017.ogg',
  },
  {
    id: 'a2-mn-018',
    topic: 'My commute',
    text: 'Every morning, I take the train to work. It takes about thirty minutes. I usually read or listen to a podcast. Sometimes the train is crowded, but I do not mind. It is a quiet time to think.',
    note: `Use "It takes ..." to talk about how long something lasts.`,
    audio: 'a2-mn-018.ogg',
  },
  {
    id: 'a2-mn-019',
    topic: 'A hobby I started',
    text: 'A few months ago, I started painting. I am not very good yet, but I enjoy it. I paint on the weekend when I have free time. It helps me relax after a busy week. I want to keep improving.',
    note: `"keep improving" uses "keep" plus an -ing verb.`,
    audio: 'a2-mn-019.ogg',
  },
  {
    id: 'a2-mn-020',
    topic: 'My best meal',
    text: "The best meal I ever had was at my grandmother's house. She cooked a big pot of soup with fresh bread. The whole family sat together and talked for hours. The food was simple but full of love. I will never forget that day.",
    note: `Use the past simple and "The best ... I ever had".`,
    audio: 'a2-mn-020.ogg',
  },
  {
    id: 'a2-mn-021',
    topic: 'A place I want to visit',
    text: 'One day, I would like to visit Japan. I am interested in the food and the culture. I have seen many photos of the cities and temples. I think it would be an amazing trip. I am saving money for it now.',
    note: `"I would like to ..." is a polite way to say what you want.`,
    audio: 'a2-mn-021.ogg',
  },
  {
    id: 'a2-mn-022',
    topic: 'How I learn English',
    text: 'I practice English a little every day. I watch videos with subtitles and repeat the sentences. I also write new words in a small notebook. It is slow, but I can see progress. Every small step counts.',
    note: `Use the present simple for things you do regularly.`,
    audio: 'a2-mn-022.ogg',
  },
  {
    id: 'a2-mn-023',
    topic: 'A busy day',
    text: 'Yesterday was a very busy day. I woke up early and went to work. After work, I did the shopping and cooked dinner. In the evening, I was very tired. But I felt happy because I finished everything.',
    note: `Tell a day in order with the past simple and time words.`,
    audio: 'a2-mn-023.ogg',
  },
  {
    id: 'a2-mn-024',
    topic: 'My favorite app',
    text: 'My favorite app helps me learn new words. Every day, it gives me a short lesson. I practice for ten minutes on the bus. Slowly, my English is getting better. Small steps really help.',
    note: `"is getting better" shows a slow change in progress.`,
    audio: 'a2-mn-024.ogg',
  },
  {
    id: 'a2-mn-025',
    topic: 'A problem I solved',
    text: 'Last month, my laptop stopped working. At first, I did not know what to do. I watched a video and tried a few things. In the end, I fixed it myself. I felt really proud.',
    note: `"At first ... In the end ..." frames a short story.`,
    audio: 'a2-mn-025.ogg',
  },
  {
    id: 'a2-mn-026',
    topic: 'Sundays in the park',
    text: 'On Sundays, my family goes to the park. We bring food and sit on the grass. The children play and we relax. Sometimes we ride bikes. It is the best day of the week.',
    note: `Use the present simple for a weekly routine.`,
    audio: 'a2-mn-026.ogg',
  },
  {
    id: 'a2-mn-027',
    topic: 'A goal for this year',
    text: 'This year, I want to read more books. I used to watch TV every night. Now I read for thirty minutes before bed. I already feel calmer. I hope to read twenty books.',
    note: `"I used to ... Now ..." contrasts an old and a new habit.`,
    audio: 'a2-mn-027.ogg',
  },
  {
    id: 'a2-mn-028',
    topic: 'Someone who helped me',
    text: 'When I started my job, a kind woman helped me. She showed me everything and answered my questions. I was nervous, but she made me feel welcome. Now we are good friends. I am very grateful to her.',
    note: `"made me feel welcome" uses "make + someone + adjective".`,
    audio: 'a2-mn-028.ogg',
  },
  {
    id: 'a2-mn-029',
    topic: 'A new restaurant',
    text: 'Last weekend, I tried a new restaurant. The food was delicious and not expensive. The staff were friendly and quick. I had pasta and a fresh salad. I will definitely go again.',
    note: `Use the past simple to review an experience.`,
    audio: 'a2-mn-029.ogg',
  },
  {
    id: 'a2-mn-030',
    topic: 'A person I look up to',
    text: 'I really look up to my older brother. He works hard and never complains. He helped me when I was young. He always gives good advice. I want to be like him.',
    note: `"look up to" means admire and respect.`,
    audio: 'a2-mn-030.ogg',
  },
  {
    id: 'a2-mn-031',
    topic: 'A weekend by the sea',
    text: 'Last month, I took a short trip to the coast. I stayed in a small hotel near the beach. Every morning, I walked by the sea. The fresh air helped me relax. I came home feeling new.',
    note: `Tell a trip with the past simple and time words.`,
    audio: 'a2-mn-031.ogg',
  },
  {
    id: 'a2-mn-032',
    topic: 'Trying something new',
    text: 'Last week, I tried rock climbing for the first time. I was scared at the start. My friend showed me what to do. By the end, I really enjoyed it. I want to try it again.',
    note: `"at the start ... By the end ..." frames a change.`,
    audio: 'a2-mn-032.ogg',
  },
  {
    id: 'a2-mn-033',
    topic: 'How I save money',
    text: 'I am trying to save money this year. I make coffee at home instead of buying it. I also cook more and eat out less. Small changes add up quickly. I already saved enough for a trip.',
    note: `"instead of" plus -ing shows a swap of habits.`,
    audio: 'a2-mn-033.ogg',
  },
  {
    id: 'a2-mn-034',
    topic: 'A memorable birthday',
    text: 'My last birthday was very special. My friends made a surprise party. They cooked my favorite food. We laughed and talked all night. I felt very lucky to have them.',
    note: `Past simple verbs tell the story: made, cooked, laughed.`,
    audio: 'a2-mn-034.ogg',
  },
];
