/**
 * C2 (mastery) question-prompt drills. Demanding, abstract questions with
 * polished, nuanced answers. Hear, pause, give a real answer, then compare.
 */
import type { Prompt } from '../types';

export const c2Prompts: Prompt[] = [
  {
    id: 'c2-pr-001',
    topic: 'Philosophy',
    question: 'Does technology make us freer or more dependent?',
    answer:
      'Both, really. It hands us extraordinary tools, yet quietly reshapes our habits in ways we rarely notice.',
    note: `"Both, really" refuses a false choice; "yet" adds the twist.`,
    audio: 'c2-pr-001.ogg',
  },
  {
    id: 'c2-pr-002',
    topic: 'Debate',
    question: 'Is it better to be respected or liked?',
    answer:
      'If I had to choose, respected. Being liked is pleasant, but respect tends to outlast it.',
    note: `"If I had to choose..." commits gracefully to one side.`,
    audio: 'c2-pr-002.ogg',
  },
  {
    id: 'c2-pr-003',
    topic: 'Values',
    question: 'Can money buy happiness?',
    answer:
      'Up to a point. It removes certain miseries, but beyond comfort, meaning matters far more.',
    note: `"Up to a point" is a classic hedged opening.`,
    audio: 'c2-pr-003.ogg',
  },
  {
    id: 'c2-pr-004',
    topic: 'Expertise',
    question: "What's the mark of true expertise?",
    answer: 'Knowing the limits of what you know, and being able to explain it simply.',
    note: `Answer an abstract question with two -ing phrases.`,
    audio: 'c2-pr-004.ogg',
  },
  {
    id: 'c2-pr-005',
    topic: 'Reflection',
    question: 'What would you want said about you?',
    answer: 'That I was kind when it was hard, and honest when it cost me something.',
    note: `Report a wish with "That I was..."; parallel structure adds weight.`,
    audio: 'c2-pr-005.ogg',
  },
  {
    id: 'c2-pr-006',
    topic: 'Society',
    question: 'Is privacy dead in the digital age?',
    answer: "Not dead, but endangered. We've traded it cheaply, and we may regret the price.",
    note: `Reject the extreme ("Not dead, but..."), then warn.`,
    audio: 'c2-pr-006.ogg',
  },
  {
    id: 'c2-pr-007',
    topic: 'Creativity',
    question: 'Where do your best ideas come from?',
    answer:
      'Usually when I step away from the problem, on a walk or in the shower, not at the desk.',
    note: `Answer "when..." and end with a vivid contrast.`,
    audio: 'c2-pr-007.ogg',
  },
  {
    id: 'c2-pr-008',
    topic: 'Ethics',
    question: 'Do the ends justify the means?',
    answer: 'Rarely. How you get somewhere often shapes what you find when you arrive.',
    note: `A one-word stance ("Rarely.") then a memorable reason.`,
    audio: 'c2-pr-008.ogg',
  },
  {
    id: 'c2-pr-009',
    topic: 'Growth',
    question: "What's the most useful thing you've unlearned?",
    answer: 'The belief that being busy is the same as being productive. It is not.',
    note: `Name the old belief, then knock it down: "It is not."`,
    audio: 'c2-pr-009.ogg',
  },
  {
    id: 'c2-pr-010',
    topic: 'Persuasion',
    question: "How do you change someone's mind?",
    answer: 'Not by winning the argument, but by making them feel understood first.',
    note: `"Not by... but by..." reframes how to persuade.`,
    audio: 'c2-pr-010.ogg',
  },
  {
    id: 'c2-pr-011',
    topic: 'Priorities',
    question: "How do you decide what's worth your time?",
    answer: "I ask whether I'll be glad I did it a year from now. That usually clears things up.",
    note: `Share a decision rule, then its effect.`,
    audio: 'c2-pr-011.ogg',
  },
  {
    id: 'c2-pr-012',
    topic: 'Legacy',
    question: 'What does it mean to leave a mark?',
    answer:
      'Less a monument, more the small, compounding effect you have on the people around you.',
    note: `"Less... more..." redefines a grand idea in human terms.`,
    audio: 'c2-pr-012.ogg',
  },
  {
    id: 'c2-pr-013',
    topic: 'Philosophy',
    question: 'Can a person ever be truly objective?',
    answer: 'Probably not, though noticing our own biases is half the battle.',
    note: `"Probably not, though ..." hedges, then adds an insight.`,
    audio: 'c2-pr-013.ogg',
  },
  {
    id: 'c2-pr-014',
    topic: 'Ethics',
    question: 'Do the ends ever justify the means?',
    answer: 'Rarely, and we tend to tell ourselves they do far too easily.',
    note: `"Rarely, and ..." hedges, then adds a sharp observation.`,
    audio: 'c2-pr-014.ogg',
  },
  {
    id: 'c2-pr-015',
    topic: 'Society',
    question: 'Has technology made us more or less connected?',
    answer: 'More reachable, perhaps, but not necessarily more connected.',
    note: `"perhaps, but not necessarily ..." draws a fine distinction.`,
    audio: 'c2-pr-015.ogg',
  },
  {
    id: 'c2-pr-016',
    topic: 'Self',
    question: "What's a belief you've outgrown?",
    answer: 'The notion that certainty is a sign of intelligence.',
    note: `"The notion that ..." is an elegant way to name a belief.`,
    audio: 'c2-pr-016.ogg',
  },
  {
    id: 'c2-pr-017',
    topic: 'Character',
    question: "What's an underrated quality in people?",
    answer: 'Quiet consistency; it outlasts brilliance almost every time.',
    note: `Make a bold claim, then back it with a short reason.`,
    audio: 'c2-pr-017.ogg',
  },
  {
    id: 'c2-pr-018',
    topic: 'Hypotheticals',
    question: 'If you could master any one skill instantly, what would it be?',
    answer: 'Listening, properly; most problems soften once people feel heard.',
    note: `"..., properly;" adds emphasis, then a reason follows.`,
    audio: 'c2-pr-018.ogg',
  },
  {
    id: 'c2-pr-019',
    topic: 'Philosophy',
    question: 'Is certainty a virtue or a trap?',
    answer: 'Usually a trap dressed as a virtue, in my experience.',
    note: `"..., in my experience." softens a bold claim.`,
    audio: 'c2-pr-019.ogg',
  },
  {
    id: 'c2-pr-020',
    topic: 'Society',
    question: 'Can institutions be moral, or only people?',
    answer: 'Only people, ultimately; institutions merely amplify them.',
    note: `"Only people, ultimately;" then a sharp follow-up.`,
    audio: 'c2-pr-020.ogg',
  },
  {
    id: 'c2-pr-021',
    topic: 'Self',
    question: 'What have you made peace with?',
    answer: "That I'll never read every book I want to.",
    note: `Begin with "That ..." to name what you accept.`,
    audio: 'c2-pr-021.ogg',
  },
  {
    id: 'c2-pr-022',
    topic: 'Ethics',
    question: 'Is forgiveness for them or for you?',
    answer: 'Largely for you; resentment is a poison you brew yourself.',
    note: `"Largely for you;" then a striking image.`,
    audio: 'c2-pr-022.ogg',
  },
  {
    id: 'c2-pr-023',
    topic: 'Knowledge',
    question: 'How do you tell wisdom from cleverness?',
    answer: 'Cleverness solves the problem; wisdom questions whether to.',
    note: `Contrast two ideas with a semicolon for balance.`,
    audio: 'c2-pr-023.ogg',
  },
  {
    id: 'c2-pr-024',
    topic: 'Society',
    question: 'What does a society reveal by what it rewards?',
    answer: 'Almost everything; incentives are values made visible.',
    note: `"...; incentives are values made visible." is a neat line.`,
    audio: 'c2-pr-024.ogg',
  },
  {
    id: 'c2-pr-025',
    topic: 'Growth',
    question: "What's the most freeing thing you've accepted?",
    answer: "That most people aren't thinking about me at all.",
    note: `"That most people ..." names a liberating realisation.`,
    audio: 'c2-pr-025.ogg',
  },
  {
    id: 'c2-pr-026',
    topic: 'The future',
    question: 'If you could ask the future one question, what would it be?',
    answer: 'Not what happens, but whether we handled it well.',
    note: `"Not ..., but ..." reframes the whole question.`,
    audio: 'c2-pr-026.ogg',
  },
  {
    id: 'c2-pr-027',
    topic: 'Knowledge',
    question: 'Is ignorance ever preferable to knowledge?',
    answer: 'Rarely, though some truths arrive before we can bear them.',
    note: `"Rarely, though ..." concedes a subtle exception.`,
    audio: 'c2-pr-027.ogg',
  },
  {
    id: 'c2-pr-028',
    topic: 'Character',
    question: 'Can a flaw also be a strength?',
    answer: 'Frequently; the same intensity that burns can also illuminate.',
    note: `"Frequently; ..." answers, then adds a vivid image.`,
    audio: 'c2-pr-028.ogg',
  },
  {
    id: 'c2-pr-029',
    topic: 'Ethics',
    question: 'What do we owe to the future?',
    answer: 'At minimum, not to mortgage it for our own comfort.',
    note: `"At minimum, ..." sets a clear ethical floor.`,
    audio: 'c2-pr-029.ogg',
  },
  {
    id: 'c2-pr-030',
    topic: 'Truth',
    question: 'Is objectivity a myth or a goal?',
    answer: 'A goal we approach but never quite reach, like the horizon.',
    note: `A simile ("like the horizon") makes the idea memorable.`,
    audio: 'c2-pr-030.ogg',
  },
  {
    id: 'c2-pr-031',
    topic: 'Self',
    question: 'What is the cost of being right too often?',
    answer: 'People stop telling you when you are wrong.',
    note: `A short, blunt sentence can land harder than a long one.`,
    audio: 'c2-pr-031.ogg',
  },
  {
    id: 'c2-pr-032',
    topic: 'Conversation',
    question: 'How do you measure a good conversation?',
    answer: 'By whether I left it thinking differently than I arrived.',
    note: `"By whether ..." names your standard in one line.`,
    audio: 'c2-pr-032.ogg',
  },
  {
    id: 'c2-pr-033',
    topic: 'Philosophy',
    question: 'What is more dangerous: doubt or certainty?',
    answer: 'Certainty, usually; doubt at least keeps the door open.',
    note: `"Certainty, usually; ..." chooses a side, then justifies it.`,
    audio: 'c2-pr-033.ogg',
  },
  {
    id: 'c2-pr-034',
    topic: 'Meaning',
    question: 'Can suffering have meaning?',
    answer: 'Not inherently; meaning is what we choose to make of it.',
    note: `"Not inherently; ..." resists an easy yes or no.`,
    audio: 'c2-pr-034.ogg',
  },
  {
    id: 'c2-pr-035',
    topic: 'Habits',
    question: 'Is consistency overrated or underrated?',
    answer: 'Underrated in habits, overrated in opinions.',
    note: `A neat parallel: same word, two opposite verdicts.`,
    audio: 'c2-pr-035.ogg',
  },
  {
    id: 'c2-pr-036',
    topic: 'Perspective',
    question: 'What is the danger of a single story?',
    answer: 'It mistakes one true detail for the whole truth.',
    note: `"mistakes X for Y" names the error precisely.`,
    audio: 'c2-pr-036.ogg',
  },
  {
    id: 'c2-pr-037',
    topic: 'Learning',
    question: 'How do you know when you have learned something?',
    answer: 'When I can teach it simply and apply it under pressure.',
    note: `"When I can ... and ..." sets two clear tests.`,
    audio: 'c2-pr-037.ogg',
  },
  {
    id: 'c2-pr-038',
    topic: 'Growth',
    question: 'Is comfort the enemy of growth?',
    answer: 'Often, though some comfort is what makes risk survivable.',
    note: `"Often, though ..." concedes a subtle counterpoint.`,
    audio: 'c2-pr-038.ogg',
  },
  {
    id: 'c2-pr-039',
    topic: 'Mindset',
    question: 'What do strong opinions cost us?',
    answer: 'The information that only reaches an open mind.',
    note: `A single sentence can carry a sharp idea.`,
    audio: 'c2-pr-039.ogg',
  },
  {
    id: 'c2-pr-040',
    topic: 'Courage',
    question: 'What is the most underrated form of courage?',
    answer: 'Changing your mind in front of people who expected you not to.',
    note: `An -ing phrase can answer a "what is ...?" question well.`,
    audio: 'c2-pr-040.ogg',
  },
];
