/**
 * C1 (advanced) question-prompt drills. Abstract and reflective questions with
 * thoughtful, well-shaped answers. Hear, pause, answer at length, then compare.
 */
import type { Prompt } from '../types';

export const c1Prompts: Prompt[] = [
  {
    id: 'c1-pr-001',
    topic: 'Values',
    question: 'What does success mean to you?',
    answer:
      "Less about money, and more about doing work I'm proud of and having time for the people I love.",
    note: `Define a big word with "less about... more about...".`,
    audio: 'c1-pr-001.ogg',
  },
  {
    id: 'c1-pr-002',
    topic: 'Debate',
    question: 'Is ambition always a good thing?',
    answer: 'Not necessarily. Unchecked, it can cost you your health and your relationships.',
    note: `"Not necessarily" opens a nuanced answer.`,
    audio: 'c1-pr-002.ogg',
  },
  {
    id: 'c1-pr-003',
    topic: 'Reflection',
    question: 'How do you define a life well lived?',
    answer:
      'By the relationships you build and the difference you make, not by what you accumulate.',
    note: `"By... not by..." contrasts what counts with what does not.`,
    audio: 'c1-pr-003.ogg',
  },
  {
    id: 'c1-pr-004',
    topic: 'Motivation',
    question: 'How do you stay motivated on a long project?',
    answer: 'I break it into small wins and keep reminding myself why it matters.',
    note: `Two strategies, joined with "and".`,
    audio: 'c1-pr-004.ogg',
  },
  {
    id: 'c1-pr-005',
    topic: 'Opinions',
    question: 'Should everyone learn to code?',
    answer: 'Not everyone, but understanding the basics helps in almost any field now.',
    note: `Qualify a yes/no with "Not everyone, but...".`,
    audio: 'c1-pr-005.ogg',
  },
  {
    id: 'c1-pr-006',
    topic: 'Hypotheticals',
    question: 'If money were no object, what would you do?',
    answer: "I'd probably teach. There's real satisfaction in helping people grow.",
    note: `Second conditional: "If... were..., I'd...". Then give a reason.`,
    audio: 'c1-pr-006.ogg',
  },
  {
    id: 'c1-pr-007',
    topic: 'Communication',
    question: 'How does your culture shape the way you communicate?',
    answer:
      "We tend to be indirect, so I've had to learn to be clearer with international colleagues.",
    note: `"We tend to..." describes a general tendency, then a personal effect.`,
    audio: 'c1-pr-007.ogg',
  },
  {
    id: 'c1-pr-008',
    topic: 'Leadership',
    question: 'What separates a leader from a manager?',
    answer: 'A manager runs the process; a leader gives people a reason to care about it.',
    note: `Contrast two roles with a semicolon for a crisp answer.`,
    audio: 'c1-pr-008.ogg',
  },
  {
    id: 'c1-pr-009',
    topic: 'Resilience',
    question: 'How do you bounce back from failure?',
    answer: 'I let myself feel it briefly, then I look for the lesson and move on.',
    note: `"bounce back" = recover. Describe it as steps.`,
    audio: 'c1-pr-009.ogg',
  },
  {
    id: 'c1-pr-010',
    topic: 'Ethics',
    question: 'Is it ever okay to lie?',
    answer: "A small kindness, perhaps. But trust is hard to rebuild, so I'm careful.",
    note: `Concede a little ("perhaps"), then state your real position.`,
    audio: 'c1-pr-010.ogg',
  },
  {
    id: 'c1-pr-011',
    topic: 'Change',
    question: 'How do you feel about change?',
    answer: "Uncomfortable at first, but I've learned that's usually where growth hides.",
    note: `Admit a feeling, then reframe it positively.`,
    audio: 'c1-pr-011.ogg',
  },
  {
    id: 'c1-pr-012',
    topic: 'Wisdom',
    question: "What's the best advice you've ever received?",
    answer: "That you can't control outcomes, only your effort and your attitude.",
    note: `Report advice with "That you...".`,
    audio: 'c1-pr-012.ogg',
  },
  {
    id: 'c1-pr-013',
    topic: 'Friendship',
    question: 'What matters most to you in a friendship?',
    answer: 'Trust, above all; everything else can be worked on.',
    note: `"..., above all;" puts one value first, then qualifies it.`,
    audio: 'c1-pr-013.ogg',
  },
  {
    id: 'c1-pr-014',
    topic: 'Debate',
    question: 'Should education be free for everyone?',
    answer: 'In principle yes, though someone has to fund it.',
    note: `"In principle yes, though ..." agrees while noting a catch.`,
    audio: 'c1-pr-014.ogg',
  },
  {
    id: 'c1-pr-015',
    topic: 'Reflection',
    question: 'How have your priorities shifted over time?',
    answer: "I've come to value time far more than money.",
    note: `"I've come to value ..." marks a gradual change of view.`,
    audio: 'c1-pr-015.ogg',
  },
  {
    id: 'c1-pr-016',
    topic: 'Opinions',
    question: "What's an opinion you hold that others might disagree with?",
    answer: "That being busy isn't the same as being productive.",
    note: `Start with "That ..." to state the opinion you hold.`,
    audio: 'c1-pr-016.ogg',
  },
  {
    id: 'c1-pr-017',
    topic: 'Leadership',
    question: 'What separates a good leader from a great one?',
    answer: 'A great one listens before they decide.',
    note: `Use "A great one ..." to draw a sharp contrast.`,
    audio: 'c1-pr-017.ogg',
  },
  {
    id: 'c1-pr-018',
    topic: 'Hypotheticals',
    question: 'If you had a year off, how would you spend it?',
    answer: "I'd travel slowly and finally learn an instrument.",
    note: `Second conditional: "If I had ..., I'd ..."`,
    audio: 'c1-pr-018.ogg',
  },
  {
    id: 'c1-pr-019',
    topic: 'Philosophy',
    question: 'Is happiness a goal or a by-product?',
    answer: 'A by-product, mostly; chase it directly and it slips away.',
    note: `"A by-product, mostly;" then a vivid reason.`,
    audio: 'c1-pr-019.ogg',
  },
  {
    id: 'c1-pr-020',
    topic: 'Work',
    question: "What's overrated in your field?",
    answer: 'Working long hours; output rarely scales with them.',
    note: `Name it, then "; output rarely scales with them."`,
    audio: 'c1-pr-020.ogg',
  },
  {
    id: 'c1-pr-021',
    topic: 'Society',
    question: 'Does competition bring out the best in us?',
    answer: 'Sometimes, though it can quietly corrode cooperation.',
    note: `"Sometimes, though ..." hedges, then adds a caveat.`,
    audio: 'c1-pr-021.ogg',
  },
  {
    id: 'c1-pr-022',
    topic: 'Self',
    question: 'What belief do you hold loosely?',
    answer: 'Most of them, honestly; certainty makes me nervous now.',
    note: `"Most of them, honestly;" sounds candid and reflective.`,
    audio: 'c1-pr-022.ogg',
  },
  {
    id: 'c1-pr-023',
    topic: 'Change',
    question: 'When did you last change your mind on something big?',
    answer: 'Recently, on how much control we really have.',
    note: `"Recently, on ..." names a topic concisely.`,
    audio: 'c1-pr-023.ogg',
  },
  {
    id: 'c1-pr-024',
    topic: 'Trust',
    question: 'How do you earn trust quickly?',
    answer: 'By doing what you said you would, repeatedly.',
    note: `"By ...-ing ..." explains the method.`,
    audio: 'c1-pr-024.ogg',
  },
  {
    id: 'c1-pr-025',
    topic: 'Culture',
    question: "What's a tradition worth keeping?",
    answer: 'Eating together, unhurried and without phones.',
    note: `Add texture with "..., unhurried and ..."`,
    audio: 'c1-pr-025.ogg',
  },
  {
    id: 'c1-pr-026',
    topic: 'Education',
    question: 'If you could fix one part of education, what would it be?',
    answer: "I'd teach people how to learn, not just what to learn.",
    note: `"..., not just ..." draws a sharp contrast.`,
    audio: 'c1-pr-026.ogg',
  },
  {
    id: 'c1-pr-027',
    topic: 'Character',
    question: 'What does maturity look like to you?',
    answer: 'Doing the right thing even when no one is watching.',
    note: `An -ing phrase plus "even when ..." defines an idea well.`,
    audio: 'c1-pr-027.ogg',
  },
  {
    id: 'c1-pr-028',
    topic: 'Choices',
    question: 'Is it better to follow passion or stability?',
    answer: 'A blend, ideally; passion on a stable base lasts longer.',
    note: `"A blend, ideally; ..." resists a false either/or.`,
    audio: 'c1-pr-028.ogg',
  },
  {
    id: 'c1-pr-029',
    topic: 'Self',
    question: 'How do you handle praise?',
    answer: 'Gratefully, but I try not to let it define me.',
    note: `"Gratefully, but ..." accepts praise without leaning on it.`,
    audio: 'c1-pr-029.ogg',
  },
  {
    id: 'c1-pr-030',
    topic: 'Wisdom',
    question: 'What separates knowledge from wisdom?',
    answer: 'Knowledge is knowing; wisdom is knowing when and whether.',
    note: `"X is ...; Y is ..." draws a clean distinction.`,
    audio: 'c1-pr-030.ogg',
  },
  {
    id: 'c1-pr-031',
    topic: 'Values',
    question: 'When is compromise a mistake?',
    answer: 'When it costs a value you cannot quietly get back.',
    note: `"When it costs ..." names the condition precisely.`,
    audio: 'c1-pr-031.ogg',
  },
  {
    id: 'c1-pr-032',
    topic: 'Habits',
    question: 'What habit has shaped you most?',
    answer: 'Writing daily; it forces me to actually think.',
    note: `Name the habit, then "; it forces me to ..."`,
    audio: 'c1-pr-032.ogg',
  },
  {
    id: 'c1-pr-033',
    topic: 'Trust',
    question: 'How do you know whom to trust?',
    answer: 'I watch what people do when it is inconvenient.',
    note: `"I watch what people do when ..." reveals your test.`,
    audio: 'c1-pr-033.ogg',
  },
  {
    id: 'c1-pr-034',
    topic: 'Craft',
    question: 'What is worth doing slowly?',
    answer: 'Anything you want to do well: learning, healing, building.',
    note: `A colon plus a short list adds weight to the point.`,
    audio: 'c1-pr-034.ogg',
  },
  {
    id: 'c1-pr-035',
    topic: 'Character',
    question: 'What is the difference between confidence and arrogance?',
    answer: 'Confidence listens; arrogance only waits to speak.',
    note: `"X listens; Y only ..." draws a clean contrast.`,
    audio: 'c1-pr-035.ogg',
  },
  {
    id: 'c1-pr-036',
    topic: 'Self',
    question: 'How do you handle being wrong in public?',
    answer: 'I admit it quickly; the cover-up always costs more.',
    note: `"...; the cover-up always costs more." justifies the choice.`,
    audio: 'c1-pr-036.ogg',
  },
  {
    id: 'c1-pr-037',
    topic: 'Ideas',
    question: 'What is an idea you keep returning to?',
    answer: 'That attention, not time, is our scarcest resource.',
    note: `"That ..., not ..., is ..." states a belief with contrast.`,
    audio: 'c1-pr-037.ogg',
  },
  {
    id: 'c1-pr-038',
    topic: 'Wellbeing',
    question: 'How do you avoid burning out?',
    answer: 'I treat rest as part of the plan, not a reward.',
    note: `"as part of the plan, not a reward" reframes rest.`,
    audio: 'c1-pr-038.ogg',
  },
  {
    id: 'c1-pr-039',
    topic: 'Craft',
    question: 'What separates good work from great work?',
    answer: 'The willingness to revisit it once more when it is good enough.',
    note: `"The willingness to ..." names the deciding habit.`,
    audio: 'c1-pr-039.ogg',
  },
  {
    id: 'c1-pr-040',
    topic: 'Values',
    question: 'What is worth being stubborn about?',
    answer: 'Values; almost everything else is negotiable.',
    note: `"Values; ..." answers in one word, then qualifies it.`,
    audio: 'c1-pr-040.ogg',
  },
];
