/**
 * C2 (mastery) question-prompt drills. Demanding, abstract questions with
 * polished, nuanced answers. Hear, pause, give a real answer, then compare.
 */
import type { Prompt } from '../types';

export const c2Prompts: Prompt[] = [
  {
    id: 'c2-pr-001',
    topic: 'Philosophy',
    question: 'Does technology make us freer or more dependent?',
    answer:
      'Both, really. It hands us extraordinary tools, yet quietly reshapes our habits in ways we rarely notice.',
    note: `"Both, really" refuses a false choice; "yet" adds the twist.`,
    audio: 'c2-pr-001.ogg',
  },
  {
    id: 'c2-pr-002',
    topic: 'Debate',
    question: 'Is it better to be respected or liked?',
    answer:
      'If I had to choose, respected. Being liked is pleasant, but respect tends to outlast it.',
    note: `"If I had to choose..." commits gracefully to one side.`,
    audio: 'c2-pr-002.ogg',
  },
  {
    id: 'c2-pr-003',
    topic: 'Values',
    question: 'Can money buy happiness?',
    answer:
      'Up to a point. It removes certain miseries, but beyond comfort, meaning matters far more.',
    note: `"Up to a point" is a classic hedged opening.`,
    audio: 'c2-pr-003.ogg',
  },
  {
    id: 'c2-pr-004',
    topic: 'Expertise',
    question: "What's the mark of true expertise?",
    answer: 'Knowing the limits of what you know, and being able to explain it simply.',
    note: `Answer an abstract question with two -ing phrases.`,
    audio: 'c2-pr-004.ogg',
  },
  {
    id: 'c2-pr-005',
    topic: 'Reflection',
    question: 'What would you want said about you?',
    answer: 'That I was kind when it was hard, and honest when it cost me something.',
    note: `Report a wish with "That I was..."; parallel structure adds weight.`,
    audio: 'c2-pr-005.ogg',
  },
  {
    id: 'c2-pr-006',
    topic: 'Society',
    question: 'Is privacy dead in the digital age?',
    answer: "Not dead, but endangered. We've traded it cheaply, and we may regret the price.",
    note: `Reject the extreme ("Not dead, but..."), then warn.`,
    audio: 'c2-pr-006.ogg',
  },
  {
    id: 'c2-pr-007',
    topic: 'Creativity',
    question: 'Where do your best ideas come from?',
    answer:
      'Usually when I step away from the problem, on a walk or in the shower, not at the desk.',
    note: `Answer "when..." and end with a vivid contrast.`,
    audio: 'c2-pr-007.ogg',
  },
  {
    id: 'c2-pr-008',
    topic: 'Ethics',
    question: 'Do the ends justify the means?',
    answer: 'Rarely. How you get somewhere often shapes what you find when you arrive.',
    note: `A one-word stance ("Rarely.") then a memorable reason.`,
    audio: 'c2-pr-008.ogg',
  },
  {
    id: 'c2-pr-009',
    topic: 'Growth',
    question: "What's the most useful thing you've unlearned?",
    answer: 'The belief that being busy is the same as being productive. It is not.',
    note: `Name the old belief, then knock it down: "It is not."`,
    audio: 'c2-pr-009.ogg',
  },
  {
    id: 'c2-pr-010',
    topic: 'Persuasion',
    question: "How do you change someone's mind?",
    answer: 'Not by winning the argument, but by making them feel understood first.',
    note: `"Not by... but by..." reframes how to persuade.`,
    audio: 'c2-pr-010.ogg',
  },
  {
    id: 'c2-pr-011',
    topic: 'Priorities',
    question: "How do you decide what's worth your time?",
    answer: "I ask whether I'll be glad I did it a year from now. That usually clears things up.",
    note: `Share a decision rule, then its effect.`,
    audio: 'c2-pr-011.ogg',
  },
  {
    id: 'c2-pr-012',
    topic: 'Legacy',
    question: 'What does it mean to leave a mark?',
    answer:
      'Less a monument, more the small, compounding effect you have on the people around you.',
    note: `"Less... more..." redefines a grand idea in human terms.`,
    audio: 'c2-pr-012.ogg',
  },
  {
    id: 'c2-pr-013',
    topic: 'Philosophy',
    question: 'Can a person ever be truly objective?',
    answer: 'Probably not, though noticing our own biases is half the battle.',
    note: `"Probably not, though ..." hedges, then adds an insight.`,
    audio: 'c2-pr-013.ogg',
  },
  {
    id: 'c2-pr-014',
    topic: 'Ethics',
    question: 'Do the ends ever justify the means?',
    answer: 'Rarely, and we tend to tell ourselves they do far too easily.',
    note: `"Rarely, and ..." hedges, then adds a sharp observation.`,
    audio: 'c2-pr-014.ogg',
  },
  {
    id: 'c2-pr-015',
    topic: 'Society',
    question: 'Has technology made us more or less connected?',
    answer: 'More reachable, perhaps, but not necessarily more connected.',
    note: `"perhaps, but not necessarily ..." draws a fine distinction.`,
    audio: 'c2-pr-015.ogg',
  },
  {
    id: 'c2-pr-016',
    topic: 'Self',
    question: "What's a belief you've outgrown?",
    answer: 'The notion that certainty is a sign of intelligence.',
    note: `"The notion that ..." is an elegant way to name a belief.`,
    audio: 'c2-pr-016.ogg',
  },
  {
    id: 'c2-pr-017',
    topic: 'Character',
    question: "What's an underrated quality in people?",
    answer: 'Quiet consistency; it outlasts brilliance almost every time.',
    note: `Make a bold claim, then back it with a short reason.`,
    audio: 'c2-pr-017.ogg',
  },
  {
    id: 'c2-pr-018',
    topic: 'Hypotheticals',
    question: 'If you could master any one skill instantly, what would it be?',
    answer: 'Listening, properly; most problems soften once people feel heard.',
    note: `"..., properly;" adds emphasis, then a reason follows.`,
    audio: 'c2-pr-018.ogg',
  },
  {
    id: 'c2-pr-019',
    topic: 'Philosophy',
    question: 'Is certainty a virtue or a trap?',
    answer: 'Usually a trap dressed as a virtue, in my experience.',
    note: `"..., in my experience." softens a bold claim.`,
    audio: 'c2-pr-019.ogg',
  },
  {
    id: 'c2-pr-020',
    topic: 'Society',
    question: 'Can institutions be moral, or only people?',
    answer: 'Only people, ultimately; institutions merely amplify them.',
    note: `"Only people, ultimately;" then a sharp follow-up.`,
    audio: 'c2-pr-020.ogg',
  },
  {
    id: 'c2-pr-021',
    topic: 'Self',
    question: 'What have you made peace with?',
    answer: "That I'll never read every book I want to.",
    note: `Begin with "That ..." to name what you accept.`,
    audio: 'c2-pr-021.ogg',
  },
  {
    id: 'c2-pr-022',
    topic: 'Ethics',
    question: 'Is forgiveness for them or for you?',
    answer: 'Largely for you; resentment is a poison you brew yourself.',
    note: `"Largely for you;" then a striking image.`,
    audio: 'c2-pr-022.ogg',
  },
  {
    id: 'c2-pr-023',
    topic: 'Knowledge',
    question: 'How do you tell wisdom from cleverness?',
    answer: 'Cleverness solves the problem; wisdom questions whether to.',
    note: `Contrast two ideas with a semicolon for balance.`,
    audio: 'c2-pr-023.ogg',
  },
  {
    id: 'c2-pr-024',
    topic: 'Society',
    question: 'What does a society reveal by what it rewards?',
    answer: 'Almost everything; incentives are values made visible.',
    note: `"...; incentives are values made visible." is a neat line.`,
    audio: 'c2-pr-024.ogg',
  },
  {
    id: 'c2-pr-025',
    topic: 'Growth',
    question: "What's the most freeing thing you've accepted?",
    answer: "That most people aren't thinking about me at all.",
    note: `"That most people ..." names a liberating realisation.`,
    audio: 'c2-pr-025.ogg',
  },
  {
    id: 'c2-pr-026',
    topic: 'The future',
    question: 'If you could ask the future one question, what would it be?',
    answer: 'Not what happens, but whether we handled it well.',
    note: `"Not ..., but ..." reframes the whole question.`,
    audio: 'c2-pr-026.ogg',
  },
];
