/**
 * B1 (intermediate) question-prompt drills. Fuller answers with opinions and
 * reasons. Hear the question, pause, answer out loud, then compare.
 */
import type { Prompt } from '../types';

export const b1Prompts: Prompt[] = [
  {
    id: 'b1-pr-001',
    topic: 'Work',
    question: 'Tell me about your job.',
    answer: "I work in marketing. It's busy, but I enjoy the variety.",
    note: `Say what you do, then one honest detail with "but".`,
    audio: 'b1-pr-001.ogg',
  },
  {
    id: 'b1-pr-002',
    topic: 'Opinions',
    question: 'What do you think about working from home?',
    answer: 'Honestly, I like it, but I miss seeing my colleagues.',
    note: `"Honestly," signals a real opinion is coming.`,
    audio: 'b1-pr-002.ogg',
  },
  {
    id: 'b1-pr-003',
    topic: 'Experiences',
    question: "What's the best trip you've ever taken?",
    answer: 'Probably Japan. The food and the people were amazing.',
    note: `"Probably..." is a natural way to start before you commit.`,
    audio: 'b1-pr-003.ogg',
  },
  {
    id: 'b1-pr-004',
    topic: 'Advice',
    question: 'How can I improve my English?',
    answer: 'Practice a little every day, and try not to fear mistakes.',
    note: `Give advice with the base verb: "Practice...", "try not to..."`,
    audio: 'b1-pr-004.ogg',
  },
  {
    id: 'b1-pr-005',
    topic: 'Goals',
    question: 'What are you trying to achieve this year?',
    answer: 'I want to get fitter and read more books.',
    note: `"I want to..." plus two clear goals.`,
    audio: 'b1-pr-005.ogg',
  },
  {
    id: 'b1-pr-006',
    topic: 'Decisions',
    question: 'How do you usually make big decisions?',
    answer: 'I write down the pros and cons, then sleep on it.',
    note: `Describe a process with "first... then...". "sleep on it" = decide later.`,
    audio: 'b1-pr-006.ogg',
  },
  {
    id: 'b1-pr-007',
    topic: 'Hobbies',
    question: 'How did you get into your hobby?',
    answer: 'A friend introduced me to it, and I was hooked.',
    note: `"get into" = start enjoying. "hooked" = loving it quickly.`,
    audio: 'b1-pr-007.ogg',
  },
  {
    id: 'b1-pr-008',
    topic: 'Challenges',
    question: "What's the hardest thing about learning English?",
    answer: 'For me, it is speaking quickly without translating in my head.',
    note: `"For me," makes a general question personal.`,
    audio: 'b1-pr-008.ogg',
  },
  {
    id: 'b1-pr-009',
    topic: 'Lifestyle',
    question: "What's your ideal weekend?",
    answer: 'A long walk, good coffee, and time with friends.',
    note: `You can answer with a list, no full sentence needed.`,
    audio: 'b1-pr-009.ogg',
  },
  {
    id: 'b1-pr-010',
    topic: 'Culture',
    question: "What's a tradition you enjoy?",
    answer: 'I love family dinners on Sundays. We all cook together.',
    note: `Name the tradition, then add what happens.`,
    audio: 'b1-pr-010.ogg',
  },
  {
    id: 'b1-pr-011',
    topic: 'Technology',
    question: 'How has your phone changed your life?',
    answer: "It's useful, but I try not to let it waste my time.",
    note: `Balance a good point with "but" and a concern.`,
    audio: 'b1-pr-011.ogg',
  },
  {
    id: 'b1-pr-012',
    topic: 'Reflection',
    question: "What's something you've changed your mind about?",
    answer: 'I used to dislike public speaking, but now I enjoy it.',
    note: `"I used to... but now..." shows a change over time.`,
    audio: 'b1-pr-012.ogg',
  },
  {
    id: 'b1-pr-013',
    topic: 'Opinions',
    question: "What's your opinion on social media?",
    answer: "I think it's useful, but it can waste a lot of time.",
    note: `Balance an opinion with "I think ..., but ..."`,
    audio: 'b1-pr-013.ogg',
  },
  {
    id: 'b1-pr-014',
    topic: 'Travel',
    question: "What's the most interesting place you've visited?",
    answer: 'Probably Rome, because of the history.',
    note: `Hedge with "Probably ...", then give a reason with "because".`,
    audio: 'b1-pr-014.ogg',
  },
  {
    id: 'b1-pr-015',
    topic: 'Goals',
    question: "What's a skill you'd like to learn?",
    answer: "I'd like to learn how to cook properly.",
    note: `Use "I'd like to learn how to ..." plus a verb.`,
    audio: 'b1-pr-015.ogg',
  },
  {
    id: 'b1-pr-016',
    topic: 'Days off',
    question: 'How do you like to spend a day off?',
    answer: 'I usually go for a long walk and then read.',
    note: `Describe a typical day with "I usually ..." plus "and then".`,
    audio: 'b1-pr-016.ogg',
  },
  {
    id: 'b1-pr-017',
    topic: 'Habits',
    question: "What's a habit you'd like to break?",
    answer: "I'd like to stop checking my phone so much.",
    note: `Use "I'd like to stop" plus an -ing verb.`,
    audio: 'b1-pr-017.ogg',
  },
  {
    id: 'b1-pr-018',
    topic: 'Change',
    question: 'Is your life different from five years ago?',
    answer: "Yes, I'm much more confident now.",
    note: `Use "much more ..." to compare then and now.`,
    audio: 'b1-pr-018.ogg',
  },
  {
    id: 'b1-pr-019',
    topic: 'Work',
    question: 'What does a typical day look like for you?',
    answer: 'It starts early, mostly meetings and emails, then focused work.',
    note: `Use "It starts ..., then ..." to sequence a day.`,
    audio: 'b1-pr-019.ogg',
  },
  {
    id: 'b1-pr-020',
    topic: 'Travel',
    question: 'Would you rather explore a city or relax on a beach?',
    answer: 'A city, definitely; I get restless lying still.',
    note: `"A city, definitely;" gives a strong choice, then a reason.`,
    audio: 'b1-pr-020.ogg',
  },
  {
    id: 'b1-pr-021',
    topic: 'Learning',
    question: 'What helps you remember new words?',
    answer: 'Using them in real sentences, not just lists.',
    note: `Start with an -ing phrase: "Using them in ..."`,
    audio: 'b1-pr-021.ogg',
  },
  {
    id: 'b1-pr-022',
    topic: 'Opinions',
    question: 'Is it better to specialise or to be a generalist?',
    answer: 'It depends, but I lean toward being a generalist.',
    note: `"It depends, but I lean toward ..." sounds balanced.`,
    audio: 'b1-pr-022.ogg',
  },
  {
    id: 'b1-pr-023',
    topic: 'Growth',
    question: 'What are you better at than you used to be?',
    answer: 'Staying calm under pressure, for sure.',
    note: `End with "..., for sure." to sound confident.`,
    audio: 'b1-pr-023.ogg',
  },
  {
    id: 'b1-pr-024',
    topic: 'Food',
    question: "What's a food everyone should try once?",
    answer: 'Honestly, a proper home-cooked curry.',
    note: `"Honestly, ..." makes a recommendation feel personal.`,
    audio: 'b1-pr-024.ogg',
  },
  {
    id: 'b1-pr-025',
    topic: 'Mornings',
    question: 'How do you start your morning?',
    answer: 'With a glass of water and a short walk.',
    note: `Answer with "With ..." plus your routine.`,
    audio: 'b1-pr-025.ogg',
  },
  {
    id: 'b1-pr-026',
    topic: 'Decisions',
    question: 'How do you know when to give up on something?',
    answer: 'When the cost clearly outweighs the reward.',
    note: `Use "When ... outweighs ..." to state a condition.`,
    audio: 'b1-pr-026.ogg',
  },
];
