/**
 * B2 (upper-intermediate) question-prompt drills. Opinion and hypothetical
 * questions with balanced, structured answers. Hear, pause, answer, compare.
 */
import type { Prompt } from '../types';

export const b2Prompts: Prompt[] = [
  {
    id: 'b2-pr-001',
    topic: 'Opinions',
    question: 'Do you think social media does more harm than good?',
    answer: 'It depends. It connects people, but it can also be a real time sink.',
    note: `"It depends" then give both sides with "but".`,
    audio: 'b2-pr-001.ogg',
  },
  {
    id: 'b2-pr-002',
    topic: 'Work',
    question: 'What makes a good manager?',
    answer: 'Someone who listens, gives clear direction, and trusts their team.',
    note: `Answer "Someone who..." plus a short list.`,
    audio: 'b2-pr-002.ogg',
  },
  {
    id: 'b2-pr-003',
    topic: 'Hypotheticals',
    question: 'If you could live anywhere, where would it be?',
    answer: 'Somewhere by the sea, with good weather and a slower pace of life.',
    note: `Answer a "would" question without a full sentence: a vivid phrase works.`,
    audio: 'b2-pr-003.ogg',
  },
  {
    id: 'b2-pr-004',
    topic: 'Problem solving',
    question: 'How do you handle a disagreement at work?',
    answer: 'I try to understand their side first, then look for common ground.',
    note: `Describe steps: "first... then...". "common ground" = shared agreement.`,
    audio: 'b2-pr-004.ogg',
  },
  {
    id: 'b2-pr-005',
    topic: 'Growth',
    question: "What's a skill you wish you'd learned earlier?",
    answer: 'Honestly, public speaking. It opens so many doors.',
    note: `"I wish I'd..." talks about a past regret. Add why it matters.`,
    audio: 'b2-pr-005.ogg',
  },
  {
    id: 'b2-pr-006',
    topic: 'Values',
    question: 'What matters most to you in a job?',
    answer: 'Meaningful work and good people, more than just the salary.',
    note: `Rank what matters with "more than".`,
    audio: 'b2-pr-006.ogg',
  },
  {
    id: 'b2-pr-007',
    topic: 'Habits',
    question: "What's a habit that's improved your life?",
    answer: "Going to bed earlier. Everything feels easier when I'm rested.",
    note: `Name the habit, then the benefit you noticed.`,
    audio: 'b2-pr-007.ogg',
  },
  {
    id: 'b2-pr-008',
    topic: 'Staying informed',
    question: 'How do you avoid feeling overwhelmed by the news?',
    answer: 'I read one good source in the morning and avoid the rest.',
    note: `Describe a simple personal rule.`,
    audio: 'b2-pr-008.ogg',
  },
  {
    id: 'b2-pr-009',
    topic: 'Advice',
    question: 'What advice would you give your younger self?',
    answer: 'Worry less about what others think, and start before you feel ready.',
    note: `Give advice in the imperative: "Worry less...", "start...".`,
    audio: 'b2-pr-009.ogg',
  },
  {
    id: 'b2-pr-010',
    topic: 'Reflection',
    question: "What's a mistake that taught you something?",
    answer: 'Rushing a project once. I learned that planning actually saves time.',
    note: `Name the mistake, then "I learned that..."`,
    audio: 'b2-pr-010.ogg',
  },
  {
    id: 'b2-pr-011',
    topic: 'Preferences',
    question: 'Would you rather travel or save money?',
    answer: 'At this stage, travel. The memories are worth more than the savings.',
    note: `"At this stage" shows your answer might change later.`,
    audio: 'b2-pr-011.ogg',
  },
  {
    id: 'b2-pr-012',
    topic: 'The future',
    question: 'Where do you see yourself in five years?',
    answer: 'Hopefully leading a small team and still learning every day.',
    note: `"Hopefully" plus -ing verbs keeps it natural, not robotic.`,
    audio: 'b2-pr-012.ogg',
  },
  {
    id: 'b2-pr-013',
    topic: 'Society',
    question: "What's a problem you'd like to see solved?",
    answer: "Honestly, I'd start with how we treat the environment.",
    note: `Open with "Honestly," then "I'd start with ..." to prioritise.`,
    audio: 'b2-pr-013.ogg',
  },
  {
    id: 'b2-pr-014',
    topic: 'Work',
    question: 'How do you handle stress at work?',
    answer: 'I break big tasks into smaller steps and take breaks.',
    note: `"I break ... into ..." describes a coping strategy clearly.`,
    audio: 'b2-pr-014.ogg',
  },
  {
    id: 'b2-pr-015',
    topic: 'Culture',
    question: "What's something people misunderstand about your culture?",
    answer: "That we're all the same; in fact, regions differ a lot.",
    note: `Use "in fact" to correct a common assumption.`,
    audio: 'b2-pr-015.ogg',
  },
  {
    id: 'b2-pr-016',
    topic: 'Growth',
    question: "What's a challenge that taught you something?",
    answer: 'Moving abroad alone taught me to rely on myself.',
    note: `Use "... taught me to ..." to link an event to a lesson.`,
    audio: 'b2-pr-016.ogg',
  },
  {
    id: 'b2-pr-017',
    topic: 'Media',
    question: 'Do you think the news today is reliable?',
    answer: 'To an extent, but I always check more than one source.',
    note: `"To an extent, but ..." gives a balanced, careful answer.`,
    audio: 'b2-pr-017.ogg',
  },
  {
    id: 'b2-pr-018',
    topic: 'Routine',
    question: 'If you could change one thing about your routine, what would it be?',
    answer: "I'd wake up earlier to have a calmer start.",
    note: `Use "I'd ... to ..." to give the change and its purpose.`,
    audio: 'b2-pr-018.ogg',
  },
  {
    id: 'b2-pr-019',
    topic: 'Work',
    question: 'How do you give difficult feedback?',
    answer: 'Privately, kindly, and with specific examples.',
    note: `A rule of three: three short, parallel points.`,
    audio: 'b2-pr-019.ogg',
  },
  {
    id: 'b2-pr-020',
    topic: 'Values',
    question: "What's worth paying more for?",
    answer: 'Things you use daily, like a good bed or shoes.',
    note: `"Things you ..., like ..." gives a category and an example.`,
    audio: 'b2-pr-020.ogg',
  },
  {
    id: 'b2-pr-021',
    topic: 'Society',
    question: 'Has remote work changed how we live?',
    answer: 'Massively; it blurred the line between home and office.',
    note: `One strong word, then a semicolon and the detail.`,
    audio: 'b2-pr-021.ogg',
  },
  {
    id: 'b2-pr-022',
    topic: 'Wellbeing',
    question: 'What recharges you after a hard week?',
    answer: 'Time outdoors, away from any screen.',
    note: `A short noun phrase answer can sound natural and strong.`,
    audio: 'b2-pr-022.ogg',
  },
  {
    id: 'b2-pr-023',
    topic: 'Growth',
    question: "What's a fear you've overcome?",
    answer: 'Speaking up in big meetings; practice slowly killed it.',
    note: `Name the fear, then "; practice slowly killed it."`,
    audio: 'b2-pr-023.ogg',
  },
  {
    id: 'b2-pr-024',
    topic: 'Work',
    question: 'Should companies track productivity?',
    answer: 'Within reason, but trust usually works better.',
    note: `"Within reason, but ..." gives a careful, balanced view.`,
    audio: 'b2-pr-024.ogg',
  },
  {
    id: 'b2-pr-025',
    topic: 'Hypotheticals',
    question: 'If you could automate one chore, which would it be?',
    answer: "Ironing, without a moment's hesitation.",
    note: `End with "..., without a moment's hesitation." for emphasis.`,
    audio: 'b2-pr-025.ogg',
  },
  {
    id: 'b2-pr-026',
    topic: 'People',
    question: "What's something you've gotten wrong about people?",
    answer: "That confidence and competence go together; they often don't.",
    note: `Start with "That ...", then overturn it with "they often don't".`,
    audio: 'b2-pr-026.ogg',
  },
  {
    id: 'b2-pr-027',
    topic: 'Work',
    question: 'What makes a workplace healthy?',
    answer: 'Trust, clear goals, and the freedom to disagree.',
    note: `A rule of three: three short, parallel ideas.`,
    audio: 'b2-pr-027.ogg',
  },
  {
    id: 'b2-pr-028',
    topic: 'Priorities',
    question: 'How do you decide what to prioritise?',
    answer: 'I ask what will matter most a month from now.',
    note: `"I ask what ..." explains your method.`,
    audio: 'b2-pr-028.ogg',
  },
  {
    id: 'b2-pr-029',
    topic: 'Growth',
    question: 'Is failure necessary for success?',
    answer: 'Often, yes; it teaches what success never can.',
    note: `"Often, yes; ..." hedges, then makes a sharp point.`,
    audio: 'b2-pr-029.ogg',
  },
  {
    id: 'b2-pr-030',
    topic: 'Values',
    question: 'How has your definition of success changed?',
    answer: 'It used to be money; now it is freedom and time.',
    note: `"It used to be ...; now it is ..." shows the shift.`,
    audio: 'b2-pr-030.ogg',
  },
  {
    id: 'b2-pr-031',
    topic: 'Advice',
    question: 'What is an underrated piece of advice?',
    answer: 'Start before you feel ready; readiness rarely arrives.',
    note: `Give the advice, then "; readiness rarely arrives."`,
    audio: 'b2-pr-031.ogg',
  },
  {
    id: 'b2-pr-032',
    topic: 'Mindset',
    question: 'How do you stay open to other opinions?',
    answer: 'I assume I am missing something, and usually I am.',
    note: `"I assume ..., and usually I am." sounds humble and real.`,
    audio: 'b2-pr-032.ogg',
  },
  {
    id: 'b2-pr-033',
    topic: 'Patience',
    question: 'What is worth being patient for?',
    answer: 'Anything built to last, like trust or real skill.',
    note: `"Anything ..., like ..." gives a category and examples.`,
    audio: 'b2-pr-033.ogg',
  },
  {
    id: 'b2-pr-034',
    topic: 'Reflection',
    question: 'If you could redo one decision, would you?',
    answer: 'Probably not; even the bad ones taught me something.',
    note: `"Probably not; ..." gives a thoughtful, balanced answer.`,
    audio: 'b2-pr-034.ogg',
  },
];
