/**
 * A1 (beginner) question-prompt drills.
 *
 * Hear a simple question, pause the clip, answer out loud, then hear a model
 * answer and compare. This trains speaking on demand: the question removes "what
 * do I say?" so you can focus on HOW you say it.
 */
import type { Prompt } from '../types';

export const a1Prompts: Prompt[] = [
  {
    id: 'a1-pr-001',
    topic: 'Introductions',
    question: "What's your name?",
    answer: 'My name is Sam. Nice to meet you.',
    note: `Answer with "My name is..." then add "Nice to meet you."`,
    audio: 'a1-pr-001.ogg',
  },
  {
    id: 'a1-pr-002',
    topic: 'Where you live',
    question: 'Where do you live?',
    answer: 'I live in London.',
    note: `Use "I live in" plus your city.`,
    audio: 'a1-pr-002.ogg',
  },
  {
    id: 'a1-pr-003',
    topic: 'Jobs',
    question: 'What do you do?',
    answer: "I'm a teacher.",
    note: `"What do you do?" asks about your job. Answer "I'm a..." plus the job.`,
    audio: 'a1-pr-003.ogg',
  },
  {
    id: 'a1-pr-004',
    topic: 'Daily life',
    question: 'What time do you get up?',
    answer: 'I get up at seven.',
    note: `Answer with "I get up at" plus the time.`,
    audio: 'a1-pr-004.ogg',
  },
  {
    id: 'a1-pr-005',
    topic: 'Food',
    question: "What's your favorite food?",
    answer: 'My favorite food is pizza.',
    note: `Echo the question: "My favorite food is..."`,
    audio: 'a1-pr-005.ogg',
  },
  {
    id: 'a1-pr-006',
    topic: 'Family',
    question: 'Do you have any brothers or sisters?',
    answer: 'Yes, I have one sister.',
    note: `Start "Yes, I have..." or "No, I don't."`,
    audio: 'a1-pr-006.ogg',
  },
  {
    id: 'a1-pr-007',
    topic: 'Free time',
    question: 'What do you do in your free time?',
    answer: 'I like reading and walking.',
    note: `Use "I like" plus -ing verbs: reading, walking.`,
    audio: 'a1-pr-007.ogg',
  },
  {
    id: 'a1-pr-008',
    topic: 'Weather',
    question: "What's the weather like today?",
    answer: "It's sunny and warm.",
    note: `Answer with "It's" plus the weather words.`,
    audio: 'a1-pr-008.ogg',
  },
  {
    id: 'a1-pr-009',
    topic: 'The weekend',
    question: 'What do you do on weekends?',
    answer: 'I meet my friends and relax.',
    note: `Present simple for habits: "I meet", "I relax".`,
    audio: 'a1-pr-009.ogg',
  },
  {
    id: 'a1-pr-010',
    topic: 'Countries',
    question: 'Where are you from?',
    answer: "I'm from Spain.",
    note: `Answer "I'm from" plus your country.`,
    audio: 'a1-pr-010.ogg',
  },
  {
    id: 'a1-pr-011',
    topic: 'Languages',
    question: 'Do you speak English?',
    answer: "Yes, a little. I'm learning.",
    note: `It is fine to say "a little". Then add "I'm learning."`,
    audio: 'a1-pr-011.ogg',
  },
  {
    id: 'a1-pr-012',
    topic: 'Feelings',
    question: 'How are you today?',
    answer: "I'm good, thank you. And you?",
    note: `Answer, then bounce it back: "And you?"`,
    audio: 'a1-pr-012.ogg',
  },
  {
    id: 'a1-pr-013',
    topic: 'Languages',
    question: 'What languages do you speak?',
    answer: 'I speak Arabic and a little English.',
    note: `Use "I speak ..." plus the languages you know.`,
    audio: 'a1-pr-013.ogg',
  },
  {
    id: 'a1-pr-014',
    topic: 'Drinks',
    question: 'Do you like coffee or tea?',
    answer: 'I like tea more than coffee.',
    note: `Use "I like ... more than ..." to compare two things.`,
    audio: 'a1-pr-014.ogg',
  },
  {
    id: 'a1-pr-015',
    topic: 'Colors',
    question: "What's your favorite color?",
    answer: 'My favorite color is blue.',
    note: `Answer with "My favorite color is ..." plus the color.`,
    audio: 'a1-pr-015.ogg',
  },
  {
    id: 'a1-pr-016',
    topic: 'Family',
    question: 'How many people are in your family?',
    answer: 'There are four people in my family.',
    note: `Use "There are ... in my family." plus a number.`,
    audio: 'a1-pr-016.ogg',
  },
  {
    id: 'a1-pr-017',
    topic: 'Breakfast',
    question: 'What do you have for breakfast?',
    answer: 'I usually have eggs and bread.',
    note: `Use "I usually have ..." for a regular meal.`,
    audio: 'a1-pr-017.ogg',
  },
  {
    id: 'a1-pr-018',
    topic: 'Pets',
    question: 'Do you have any pets?',
    answer: 'Yes, I have a small dog.',
    note: `Answer "Yes, I have a ..." or "No, I don't".`,
    audio: 'a1-pr-018.ogg',
  },
  {
    id: 'a1-pr-019',
    topic: 'Days',
    question: 'What day is it today?',
    answer: 'Today is Monday.',
    note: `Answer with "Today is ..." plus the day.`,
    audio: 'a1-pr-019.ogg',
  },
  {
    id: 'a1-pr-020',
    topic: 'Likes',
    question: 'Do you like music?',
    answer: 'Yes, I love music.',
    note: `Answer "Yes, I love ..." or "No, not really".`,
    audio: 'a1-pr-020.ogg',
  },
  {
    id: 'a1-pr-021',
    topic: 'Home',
    question: 'Do you live in a house or a flat?',
    answer: 'I live in a small flat.',
    note: `Use "I live in a ..." plus the type of home.`,
    audio: 'a1-pr-021.ogg',
  },
  {
    id: 'a1-pr-022',
    topic: 'Age',
    question: 'How old are you?',
    answer: 'I am twenty-five years old.',
    note: `Use "I am ... years old." for your age.`,
    audio: 'a1-pr-022.ogg',
  },
  {
    id: 'a1-pr-023',
    topic: 'Routine',
    question: 'What time do you go to bed?',
    answer: 'I go to bed at eleven.',
    note: `Use "I go to bed at ..." plus the time.`,
    audio: 'a1-pr-023.ogg',
  },
  {
    id: 'a1-pr-024',
    topic: 'Transport',
    question: 'Do you have a car?',
    answer: 'No, I take the bus.',
    note: `Answer "No, I ..." with what you do instead.`,
    audio: 'a1-pr-024.ogg',
  },
  {
    id: 'a1-pr-025',
    topic: 'Skills',
    question: 'Can you cook?',
    answer: 'Yes, I can cook simple meals.',
    note: `Use "Yes, I can ..." plus what you can do.`,
    audio: 'a1-pr-025.ogg',
  },
  {
    id: 'a1-pr-026',
    topic: 'Weather',
    question: 'Do you like the rain?',
    answer: 'No, I prefer sunny days.',
    note: `Use "I prefer ..." to say what you like more.`,
    audio: 'a1-pr-026.ogg',
  },
];
