/**
 * A2 (elementary) question-prompt drills. Slightly fuller answers, with reasons.
 * Hear the question, pause, answer out loud, then compare with the model.
 */
import type { Prompt } from '../types';

export const a2Prompts: Prompt[] = [
  {
    id: 'a2-pr-001',
    topic: 'Plans',
    question: 'What are you doing this weekend?',
    answer: "I'm going to visit my family.",
    note: `Use "going to" for plans: "I'm going to..."`,
    audio: 'a2-pr-001.ogg',
  },
  {
    id: 'a2-pr-002',
    topic: 'The past',
    question: 'What did you do yesterday?',
    answer: 'I worked, and then I watched a movie.',
    note: `Past simple: "worked", "watched". Link two actions with "and then".`,
    audio: 'a2-pr-002.ogg',
  },
  {
    id: 'a2-pr-003',
    topic: 'Preferences',
    question: 'Do you prefer tea or coffee?',
    answer: 'I prefer coffee, especially in the morning.',
    note: `Use "I prefer..." then add a detail with "especially".`,
    audio: 'a2-pr-003.ogg',
  },
  {
    id: 'a2-pr-004',
    topic: 'Travel',
    question: 'Have you ever been abroad?',
    answer: 'Yes, I went to Italy last year.',
    note: `Answer "Yes" then give the past simple detail: "I went to..."`,
    audio: 'a2-pr-004.ogg',
  },
  {
    id: 'a2-pr-005',
    topic: 'Routine',
    question: 'How do you get to work?',
    answer: 'I usually take the bus.',
    note: `"usually" softens a habit. "take the bus / train / car".`,
    audio: 'a2-pr-005.ogg',
  },
  {
    id: 'a2-pr-006',
    topic: 'Music',
    question: 'What kind of music do you like?',
    answer: 'I like pop, and a bit of jazz too.',
    note: `Name a type, then add another with "and a bit of".`,
    audio: 'a2-pr-006.ogg',
  },
  {
    id: 'a2-pr-007',
    topic: 'Shopping',
    question: 'How often do you go shopping?',
    answer: 'About once a week, usually on Saturday.',
    note: `Frequency: "once a week", "twice a month".`,
    audio: 'a2-pr-007.ogg',
  },
  {
    id: 'a2-pr-008',
    topic: 'Health',
    question: 'How do you stay healthy?',
    answer: 'I try to walk every day and eat well.',
    note: `"I try to..." is a natural, humble way to answer.`,
    audio: 'a2-pr-008.ogg',
  },
  {
    id: 'a2-pr-009',
    topic: 'Seasons',
    question: "What's your favorite season?",
    answer: "I love spring, because it's not too hot.",
    note: `Give a reason with "because".`,
    audio: 'a2-pr-009.ogg',
  },
  {
    id: 'a2-pr-010',
    topic: 'Opinions',
    question: 'What do you think of this city?',
    answer: 'I really like it. It is friendly and lively.',
    note: `Give an opinion, then two adjectives to support it.`,
    audio: 'a2-pr-010.ogg',
  },
  {
    id: 'a2-pr-011',
    topic: 'The future',
    question: 'What are your plans for next year?',
    answer: "I'm hoping to find a better job.",
    note: `"I'm hoping to..." is softer than "I will".`,
    audio: 'a2-pr-011.ogg',
  },
  {
    id: 'a2-pr-012',
    topic: 'Memories',
    question: "What's your earliest memory?",
    answer: "I remember playing in my grandmother's garden.",
    note: `"I remember" plus an -ing verb: "I remember playing..."`,
    audio: 'a2-pr-012.ogg',
  },
  {
    id: 'a2-pr-013',
    topic: 'Films',
    question: 'How often do you watch films?',
    answer: 'I watch a film almost every weekend.',
    note: `"How often ...?" Answer with "almost every ..." plus a time.`,
    audio: 'a2-pr-013.ogg',
  },
  {
    id: 'a2-pr-014',
    topic: 'Plans',
    question: 'What are your plans for tonight?',
    answer: "I'm going to cook dinner and relax.",
    note: `Use "going to" for plans you have already made.`,
    audio: 'a2-pr-014.ogg',
  },
  {
    id: 'a2-pr-015',
    topic: 'Preferences',
    question: 'Do you prefer the city or the countryside?',
    answer: "I prefer the city because it's lively.",
    note: `Use "I prefer ... because ..." to give a reason.`,
    audio: 'a2-pr-015.ogg',
  },
  {
    id: 'a2-pr-016',
    topic: 'Sports',
    question: 'Do you play any sports?',
    answer: 'Yes, I play football on Sundays.',
    note: `Use "I play ..." plus the sport. For activities: "I go swimming".`,
    audio: 'a2-pr-016.ogg',
  },
  {
    id: 'a2-pr-017',
    topic: 'Work',
    question: 'What do you like about your job?',
    answer: 'I like working with friendly people.',
    note: `Use "I like" plus an -ing verb: "I like working".`,
    audio: 'a2-pr-017.ogg',
  },
  {
    id: 'a2-pr-018',
    topic: 'The past',
    question: 'What did you do last weekend?',
    answer: 'I stayed home and watched films.',
    note: `Use the past simple for last weekend: "I stayed", "I watched".`,
    audio: 'a2-pr-018.ogg',
  },
  {
    id: 'a2-pr-019',
    topic: 'Food',
    question: "What's the best meal you've ever had?",
    answer: 'Probably fresh pasta in Italy. It was amazing.',
    note: `Use "Probably ..." plus a past trip and "It was ..."`,
    audio: 'a2-pr-019.ogg',
  },
  {
    id: 'a2-pr-020',
    topic: 'Evenings',
    question: 'What do you usually do after work?',
    answer: 'I usually relax and cook dinner.',
    note: `Use "I usually ..." for a regular evening.`,
    audio: 'a2-pr-020.ogg',
  },
  {
    id: 'a2-pr-021',
    topic: 'Technology',
    question: 'How often do you use your phone?',
    answer: 'Honestly, too much, all day long.',
    note: `Start with "Honestly," to sound natural and frank.`,
    audio: 'a2-pr-021.ogg',
  },
  {
    id: 'a2-pr-022',
    topic: 'People',
    question: 'Who do you spend the most time with?',
    answer: 'Mostly my family and a few close friends.',
    note: `Use "Mostly ..." to give the main answer.`,
    audio: 'a2-pr-022.ogg',
  },
  {
    id: 'a2-pr-023',
    topic: 'Goals',
    question: 'What do you want to learn this year?',
    answer: 'I want to learn how to swim.',
    note: `Use "I want to learn how to ..." plus a verb.`,
    audio: 'a2-pr-023.ogg',
  },
  {
    id: 'a2-pr-024',
    topic: 'Holidays',
    question: 'Where did you go on your last holiday?',
    answer: 'I went to the mountains with my family.',
    note: `Use the past simple: "I went to ..."`,
    audio: 'a2-pr-024.ogg',
  },
  {
    id: 'a2-pr-025',
    topic: 'Reading',
    question: 'Do you read much?',
    answer: 'Yes, I read before bed every night.',
    note: `Add a habit: "Yes, I ... every night."`,
    audio: 'a2-pr-025.ogg',
  },
  {
    id: 'a2-pr-026',
    topic: 'Summer',
    question: 'What will you do this summer?',
    answer: "I'll probably visit my grandparents.",
    note: `Use "I'll probably ..." for an uncertain plan.`,
    audio: 'a2-pr-026.ogg',
  },
  {
    id: 'a2-pr-027',
    topic: 'Routine',
    question: 'What time do you usually wake up?',
    answer: 'I usually wake up at six.',
    note: `Use "I usually ... at ..." for a regular time.`,
    audio: 'a2-pr-027.ogg',
  },
  {
    id: 'a2-pr-028',
    topic: 'Places',
    question: 'What is your hometown like?',
    answer: 'It is small and quiet, near the sea.',
    note: `Use "It is ..., near ..." to add a location.`,
    audio: 'a2-pr-028.ogg',
  },
  {
    id: 'a2-pr-029',
    topic: 'Cooking',
    question: 'Do you like cooking?',
    answer: 'Yes, I cook dinner almost every day.',
    note: `Add detail: "Yes, I ... almost every day."`,
    audio: 'a2-pr-029.ogg',
  },
  {
    id: 'a2-pr-030',
    topic: 'The past',
    question: 'What did you have for lunch?',
    answer: 'I had a sandwich and a coffee.',
    note: `Use the past simple "had" for a finished meal.`,
    audio: 'a2-pr-030.ogg',
  },
  {
    id: 'a2-pr-031',
    topic: 'Small talk',
    question: 'How was your day?',
    answer: 'Pretty good, just a bit tired.',
    note: `"Pretty good, ..." is a natural, friendly answer.`,
    audio: 'a2-pr-031.ogg',
  },
  {
    id: 'a2-pr-032',
    topic: 'Skills',
    question: 'What are you good at?',
    answer: 'I am quite good at fixing things.',
    note: `Use "I am good at ..." plus an -ing verb.`,
    audio: 'a2-pr-032.ogg',
  },
  {
    id: 'a2-pr-033',
    topic: 'Travel',
    question: 'Where would you like to travel?',
    answer: 'I would like to travel to Japan one day.',
    note: `Use "I would like to ..." plus "one day".`,
    audio: 'a2-pr-033.ogg',
  },
  {
    id: 'a2-pr-034',
    topic: 'Relaxing',
    question: 'What do you do to relax?',
    answer: 'I listen to music and go for walks.',
    note: `Use "I ... to relax." plus your activities.`,
    audio: 'a2-pr-034.ogg',
  },
  {
    id: 'a2-pr-035',
    topic: 'The past',
    question: 'What did you watch last night?',
    answer: 'I watched a documentary about the ocean.',
    note: `Use the past simple "watched" plus what it was about.`,
    audio: 'a2-pr-035.ogg',
  },
  {
    id: 'a2-pr-036',
    topic: 'Evenings',
    question: 'How do you usually spend your evenings?',
    answer: 'I cook, then watch a series and relax.',
    note: `"I ..., then ..." puts actions in order.`,
    audio: 'a2-pr-036.ogg',
  },
  {
    id: 'a2-pr-037',
    topic: 'Skills',
    question: 'What is something you do well?',
    answer: 'I am good at organising things.',
    note: `Use "I am good at ..." plus an -ing verb.`,
    audio: 'a2-pr-037.ogg',
  },
  {
    id: 'a2-pr-038',
    topic: 'Communication',
    question: 'Do you prefer texting or calling?',
    answer: 'Texting, usually; it is quicker for me.',
    note: `"Texting, usually;" gives a clear choice and a reason.`,
    audio: 'a2-pr-038.ogg',
  },
  {
    id: 'a2-pr-039',
    topic: 'Places',
    question: 'What is your favorite place in your city?',
    answer: 'The old park; it is calm and green.',
    note: `Name the place, then "; it is ..." to describe it.`,
    audio: 'a2-pr-039.ogg',
  },
  {
    id: 'a2-pr-040',
    topic: 'The future',
    question: 'What are you looking forward to?',
    answer: 'A short holiday next month.',
    note: `A short noun phrase answer is natural here.`,
    audio: 'a2-pr-040.ogg',
  },
];
