/**
 * B2 (upper-intermediate) question-prompt drills. Opinion and hypothetical
 * questions with balanced, structured answers. Hear, pause, answer, compare.
 */
import type { Prompt } from '../types';

export const b2Prompts: Prompt[] = [
  {
    id: 'b2-pr-001',
    topic: 'Opinions',
    question: 'Do you think social media does more harm than good?',
    answer: 'It depends. It connects people, but it can also be a real time sink.',
    note: `"It depends" then give both sides with "but".`,
    audio: 'b2-pr-001.ogg',
  },
  {
    id: 'b2-pr-002',
    topic: 'Work',
    question: 'What makes a good manager?',
    answer: 'Someone who listens, gives clear direction, and trusts their team.',
    note: `Answer "Someone who..." plus a short list.`,
    audio: 'b2-pr-002.ogg',
  },
  {
    id: 'b2-pr-003',
    topic: 'Hypotheticals',
    question: 'If you could live anywhere, where would it be?',
    answer: 'Somewhere by the sea, with good weather and a slower pace of life.',
    note: `Answer a "would" question without a full sentence: a vivid phrase works.`,
    audio: 'b2-pr-003.ogg',
  },
  {
    id: 'b2-pr-004',
    topic: 'Problem solving',
    question: 'How do you handle a disagreement at work?',
    answer: 'I try to understand their side first, then look for common ground.',
    note: `Describe steps: "first... then...". "common ground" = shared agreement.`,
    audio: 'b2-pr-004.ogg',
  },
  {
    id: 'b2-pr-005',
    topic: 'Growth',
    question: "What's a skill you wish you'd learned earlier?",
    answer: 'Honestly, public speaking. It opens so many doors.',
    note: `"I wish I'd..." talks about a past regret. Add why it matters.`,
    audio: 'b2-pr-005.ogg',
  },
  {
    id: 'b2-pr-006',
    topic: 'Values',
    question: 'What matters most to you in a job?',
    answer: 'Meaningful work and good people, more than just the salary.',
    note: `Rank what matters with "more than".`,
    audio: 'b2-pr-006.ogg',
  },
  {
    id: 'b2-pr-007',
    topic: 'Habits',
    question: "What's a habit that's improved your life?",
    answer: "Going to bed earlier. Everything feels easier when I'm rested.",
    note: `Name the habit, then the benefit you noticed.`,
    audio: 'b2-pr-007.ogg',
  },
  {
    id: 'b2-pr-008',
    topic: 'Staying informed',
    question: 'How do you avoid feeling overwhelmed by the news?',
    answer: 'I read one good source in the morning and avoid the rest.',
    note: `Describe a simple personal rule.`,
    audio: 'b2-pr-008.ogg',
  },
  {
    id: 'b2-pr-009',
    topic: 'Advice',
    question: 'What advice would you give your younger self?',
    answer: 'Worry less about what others think, and start before you feel ready.',
    note: `Give advice in the imperative: "Worry less...", "start...".`,
    audio: 'b2-pr-009.ogg',
  },
  {
    id: 'b2-pr-010',
    topic: 'Reflection',
    question: "What's a mistake that taught you something?",
    answer: 'Rushing a project once. I learned that planning actually saves time.',
    note: `Name the mistake, then "I learned that..."`,
    audio: 'b2-pr-010.ogg',
  },
  {
    id: 'b2-pr-011',
    topic: 'Preferences',
    question: 'Would you rather travel or save money?',
    answer: 'At this stage, travel. The memories are worth more than the savings.',
    note: `"At this stage" shows your answer might change later.`,
    audio: 'b2-pr-011.ogg',
  },
  {
    id: 'b2-pr-012',
    topic: 'The future',
    question: 'Where do you see yourself in five years?',
    answer: 'Hopefully leading a small team and still learning every day.',
    note: `"Hopefully" plus -ing verbs keeps it natural, not robotic.`,
    audio: 'b2-pr-012.ogg',
  },
  {
    id: 'b2-pr-013',
    topic: 'Society',
    question: "What's a problem you'd like to see solved?",
    answer: "Honestly, I'd start with how we treat the environment.",
    note: `Open with "Honestly," then "I'd start with ..." to prioritise.`,
    audio: 'b2-pr-013.ogg',
  },
  {
    id: 'b2-pr-014',
    topic: 'Work',
    question: 'How do you handle stress at work?',
    answer: 'I break big tasks into smaller steps and take breaks.',
    note: `"I break ... into ..." describes a coping strategy clearly.`,
    audio: 'b2-pr-014.ogg',
  },
  {
    id: 'b2-pr-015',
    topic: 'Culture',
    question: "What's something people misunderstand about your culture?",
    answer: "That we're all the same; in fact, regions differ a lot.",
    note: `Use "in fact" to correct a common assumption.`,
    audio: 'b2-pr-015.ogg',
  },
  {
    id: 'b2-pr-016',
    topic: 'Growth',
    question: "What's a challenge that taught you something?",
    answer: 'Moving abroad alone taught me to rely on myself.',
    note: `Use "... taught me to ..." to link an event to a lesson.`,
    audio: 'b2-pr-016.ogg',
  },
  {
    id: 'b2-pr-017',
    topic: 'Media',
    question: 'Do you think the news today is reliable?',
    answer: 'To an extent, but I always check more than one source.',
    note: `"To an extent, but ..." gives a balanced, careful answer.`,
    audio: 'b2-pr-017.ogg',
  },
  {
    id: 'b2-pr-018',
    topic: 'Routine',
    question: 'If you could change one thing about your routine, what would it be?',
    answer: "I'd wake up earlier to have a calmer start.",
    note: `Use "I'd ... to ..." to give the change and its purpose.`,
    audio: 'b2-pr-018.ogg',
  },
];
