/**
 * A1 (beginner) pronunciation drills: the most common vowel and consonant
 * contrasts that change meaning, plus the first, simplest reductions. Short word
 * pairs and one example sentence, read aloud so the learner hears the difference.
 */
import type { PronunciationDrill } from '../types';

export const a1Pronunciation: PronunciationDrill[] = [
  {
    id: 'a1-pn-001',
    focus: 'minimal-pair',
    title: 'ship vs sheep',
    explanation: `The "i" in ship is short and quick; the "ee" in sheep is long. Stretch the long one.`,
    items: ['ship, sheep', 'it, eat', 'this, these', 'I see a sheep on the ship.'],
    note: `Short i is relaxed; long ee is longer and tense, with a small smile.`,
    audio: 'a1-pn-001.ogg',
  },
  {
    id: 'a1-pn-002',
    focus: 'minimal-pair',
    title: 'bad vs bed',
    explanation: `"bad" uses a wide, open "a"; "bed" uses a shorter "e". Open your mouth more for bad.`,
    items: ['bad, bed', 'sat, set', 'man, men', 'The man sat on the bed.'],
    note: `Drop your jaw lower for the "a" in bad.`,
    audio: 'a1-pn-002.ogg',
  },
  {
    id: 'a1-pn-003',
    focus: 'minimal-pair',
    title: 'cat vs cut',
    explanation: `"cat" uses a front "a"; "cut" uses a relaxed, central "uh". Keep cut short.`,
    items: ['cat, cut', 'bat, but', 'hat, hut', 'The cat ran to the hut.'],
    note: `The "u" in cut is the relaxed, central sound.`,
    audio: 'a1-pn-003.ogg',
  },
  {
    id: 'a1-pn-004',
    focus: 'minimal-pair',
    title: 'pen vs pan',
    explanation: `"pen" uses "e"; "pan" uses a wider "a". Smile a little for pen, open more for pan.`,
    items: ['pen, pan', 'men, man', 'ten, tan', 'Put the pen in the pan.'],
    note: `Open your mouth wider for pan than for pen.`,
    audio: 'a1-pn-004.ogg',
  },
  {
    id: 'a1-pn-005',
    focus: 'minimal-pair',
    title: 'full vs fool',
    explanation: `"full" is short; "fool" is long. Round your lips more for the long oo in fool.`,
    items: ['full, fool', 'pull, pool', 'look, Luke', 'Do not be a fool by the pool.'],
    note: `Long oo is longer and more rounded than short oo.`,
    audio: 'a1-pn-005.ogg',
  },
  {
    id: 'a1-pn-006',
    focus: 'connected-speech',
    title: 'going to becomes gonna',
    explanation: `In fast, casual speech, "going to" often sounds like "gonna".`,
    items: ['I am going to call you.', 'We are going to be late.', 'It is going to rain.'],
    note: `Say "gonna" only in casual speech, never in writing.`,
    audio: 'a1-pn-006.ogg',
  },
  {
    id: 'a1-pn-007',
    focus: 'connected-speech',
    title: 'want to becomes wanna',
    explanation: `"want to" often sounds like "wanna" in relaxed, everyday speech.`,
    items: ['I want to go home.', 'Do you want to eat?', 'They want to help.'],
    note: `Say "wanna" casually, but always write "want to".`,
    audio: 'a1-pn-007.ogg',
  },
  {
    id: 'a1-pn-008',
    focus: 'connected-speech',
    title: 'linking two vowels',
    explanation: `When one word ends in a vowel and the next begins with one, glide them together.`,
    items: ['I am happy.', 'She is here.', 'Go away.'],
    note: `Move smoothly from one word to the next, with no hard stop.`,
    audio: 'a1-pn-008.ogg',
  },
  {
    id: 'a1-pn-009',
    focus: 'spelling-sound',
    title: 'silent e makes the vowel long',
    explanation: `A silent "e" at the end makes the vowel say its name: "hat" becomes "hate".`,
    items: ['hat, hate', 'pin, pine', 'cap, cape', 'not, note'],
    note: `The "e" is silent, but it lengthens the vowel before it.`,
    audio: 'a1-pn-009.ogg',
  },
  {
    id: 'a1-pn-010',
    focus: 'spelling-sound',
    title: 'the plural -s ending',
    explanation: `The plural "-s" sounds like "s" after some words and "z" after others.`,
    items: ['cats (s)', 'dogs (z)', 'books (s)', 'pens (z)'],
    note: `After most voiced sounds, the "-s" buzzes like a "z".`,
    audio: 'a1-pn-010.ogg',
  },
  {
    id: 'a1-pn-011',
    focus: 'minimal-pair',
    title: 'see vs say',
    explanation: `"see" is one steady long "ee"; "say" glides through the vowel (ay).`,
    items: ['see, say', 'me, may', 'tea, they', 'I see what you say.'],
    note: `Say glides and moves; see stays still.`,
    audio: 'a1-pn-011.ogg',
  },
  {
    id: 'a1-pn-012',
    focus: 'minimal-pair',
    title: 'hot vs hat',
    explanation: `"hot" is open and a little round; "hat" is a flat, front "a".`,
    items: ['hot, hat', 'cop, cap', 'lock, lack', 'The cat is hot.'],
    note: `Round the lips slightly for "hot".`,
    audio: 'a1-pn-012.ogg',
  },
  {
    id: 'a1-pn-013',
    focus: 'connected-speech',
    title: "I am becomes I'm",
    explanation: `In speech, "I am" almost always shrinks to "I'm".`,
    items: ['I am ready.', 'I am here.', 'I am tired.'],
    note: `Use the contraction "I'm" in normal, everyday speech.`,
    audio: 'a1-pn-013.ogg',
  },
  {
    id: 'a1-pn-014',
    focus: 'word-stress',
    title: 'two-syllable words',
    explanation: `Most common two-syllable nouns stress the first part.`,
    items: ['TAble', 'WAter', 'HAPpy', 'MUSic'],
    note: `Say the first syllable a little louder and longer.`,
    audio: 'a1-pn-014.ogg',
  },
  {
    id: 'a1-pn-015',
    focus: 'weak-forms',
    title: 'a and the are weak',
    explanation: `"a" and "the" are quiet and quick; never stress them.`,
    items: ['a cup of tea', 'the dog', 'a big house'],
    note: `These tiny words almost disappear in speech.`,
    audio: 'a1-pn-015.ogg',
  },
  {
    id: 'a1-pn-016',
    focus: 'spelling-sound',
    title: 'ch says ch',
    explanation: `The letters "ch" usually make the "ch" sound.`,
    items: ['chair', 'cheese', 'lunch', 'teacher'],
    note: `Push the lips forward for a short burst: "ch".`,
    audio: 'a1-pn-016.ogg',
  },
  {
    id: 'a1-pn-017',
    focus: 'minimal-pair',
    title: 'very vs berry',
    explanation: `"v" uses the teeth on the lip; "b" presses both lips together.`,
    items: ['very, berry', 'vote, boat', 'vest, best', 'A very big berry.'],
    note: `For "v", the top teeth touch the bottom lip and buzz.`,
    audio: 'a1-pn-017.ogg',
  },
  {
    id: 'a1-pn-018',
    focus: 'connected-speech',
    title: "do not becomes don't",
    explanation: `"do not" becomes "don't" in everyday speech.`,
    items: ['I do not know.', 'They do not care.', 'We do not have it.'],
    note: `Use "don't"; the full "do not" sounds very formal.`,
    audio: 'a1-pn-018.ogg',
  },
  {
    id: 'a1-pn-019',
    focus: 'word-stress',
    title: 'thirteen vs thirty',
    explanation: `"thirTEEN" stresses the end; "THIRty" stresses the start.`,
    items: ['thirteen, thirty', 'fourteen, forty', 'fifteen, fifty'],
    note: `Listen for the stress to tell the two numbers apart.`,
    audio: 'a1-pn-019.ogg',
  },
  {
    id: 'a1-pn-020',
    focus: 'spelling-sound',
    title: 'sh says sh',
    explanation: `The letters "sh" make a soft, quiet "sh" sound.`,
    items: ['ship', 'fish', 'shop', 'wash'],
    note: `Smooth and quiet, with no voice, just air.`,
    audio: 'a1-pn-020.ogg',
  },
];
