/**
 * A2 (elementary) pronunciation drills: more vowel and consonant contrasts, the
 * tricky r/l and -ng sounds, and the everyday reductions that make speech flow.
 */
import type { PronunciationDrill } from '../types';

export const a2Pronunciation: PronunciationDrill[] = [
  {
    id: 'a2-pn-001',
    focus: 'minimal-pair',
    title: 'live vs leave',
    explanation: `"live" has a short i; "leave" has a long ee. Stretch the long vowel in leave.`,
    items: ['live, leave', 'sit, seat', 'fill, feel', 'I live here, so I will not leave.'],
    note: `Hold the ee in leave a little longer than feels natural.`,
    audio: 'a2-pn-001.ogg',
  },
  {
    id: 'a2-pn-002',
    focus: 'minimal-pair',
    title: 'thin vs thing',
    explanation: `"thin" ends with the tongue tip (-n); "thing" ends with the back of the tongue (-ng).`,
    items: ['thin, thing', 'win, wing', 'sin, sing', 'It is a thin thing.'],
    note: `For -ng, let the back of the tongue rise, not the tip.`,
    audio: 'a2-pn-002.ogg',
  },
  {
    id: 'a2-pn-003',
    focus: 'minimal-pair',
    title: 'right vs light',
    explanation: `English r curls the tongue back without touching; l touches the tip behind the teeth.`,
    items: ['right, light', 'road, load', 'rock, lock', 'Turn right at the light.'],
    note: `For r, do not let the tongue touch the roof; for l, it does.`,
    audio: 'a2-pn-003.ogg',
  },
  {
    id: 'a2-pn-004',
    focus: 'minimal-pair',
    title: 'boat vs bought',
    explanation: `"boat" glides (oh-w); "bought" is a single, open "aw" sound. Keep bought steady.`,
    items: ['boat, bought', 'coat, caught', 'so, saw', 'I bought a boat.'],
    note: `Boat moves and glides; bought stays open and still.`,
    audio: 'a2-pn-004.ogg',
  },
  {
    id: 'a2-pn-005',
    focus: 'minimal-pair',
    title: 'cap vs cup',
    explanation: `"cap" uses a front "a"; "cup" uses a relaxed, central "uh".`,
    items: ['cap, cup', 'ran, run', 'bag, bug', 'Put the cap on the cup.'],
    note: `Cup uses the same relaxed vowel as "but" and "up".`,
    audio: 'a2-pn-005.ogg',
  },
  {
    id: 'a2-pn-006',
    focus: 'connected-speech',
    title: 'got to and going to',
    explanation: `"got to" becomes "gotta" and "going to" becomes "gonna" in casual speech.`,
    items: ['I have got to go.', 'We have got to try.', 'I am going to wait.'],
    note: `These are for casual speaking only; keep writing standard.`,
    audio: 'a2-pn-006.ogg',
  },
  {
    id: 'a2-pn-007',
    focus: 'weak-forms',
    title: 'and shrinks to n',
    explanation: `In fast speech, "and" often shrinks to a quick "n" between two words.`,
    items: ['fish and chips', 'salt and pepper', 'rock and roll'],
    note: `Do not stress "and"; let it almost disappear.`,
    audio: 'a2-pn-007.ogg',
  },
  {
    id: 'a2-pn-008',
    focus: 'connected-speech',
    title: 'the disappearing h',
    explanation: `In "him, her, his", the h often drops when the word follows another in speech.`,
    items: ['Give him a hand.', 'Tell her the news.', 'I saw his car.'],
    note: `It sounds like "give-im" and "tell-er" in fast, natural speech.`,
    audio: 'a2-pn-008.ogg',
  },
  {
    id: 'a2-pn-009',
    focus: 'spelling-sound',
    title: 'the -ed ending: t, d, or id',
    explanation: `The past "-ed" sounds like "t", "d", or "id" depending on the verb.`,
    items: ['worked (t)', 'played (d)', 'wanted (id)', 'stopped (t)'],
    note: `After a "t" or "d" sound, "-ed" adds a syllable: "wan-tid".`,
    audio: 'a2-pn-009.ogg',
  },
  {
    id: 'a2-pn-010',
    focus: 'spelling-sound',
    title: 'silent letters',
    explanation: `Some letters are written but not said at all.`,
    items: ['know (silent k)', 'write (silent w)', 'hour (silent h)', 'lamb (silent b)'],
    note: `Do not pronounce the silent letter; learn the whole word.`,
    audio: 'a2-pn-010.ogg',
  },
  {
    id: 'a2-pn-011',
    focus: 'minimal-pair',
    title: 'cheap vs jeep',
    explanation: `"ch" is voiceless air; "j" is the same shape but voiced and buzzing.`,
    items: ['cheap, jeep', 'choke, joke', 'rich, ridge', 'A cheap jeep.'],
    note: `"j" buzzes in the throat; "ch" is just a puff of air.`,
    audio: 'a2-pn-011.ogg',
  },
  {
    id: 'a2-pn-012',
    focus: 'word-stress',
    title: 'endings keep the stress',
    explanation: `Adding "-ing" or "-ed" does not move where the stress falls.`,
    items: ['LISTen, LISTening', 'OPen, OPened', 'VISit, VISiting'],
    note: `The stressed syllable stays the same when you add an ending.`,
    audio: 'a2-pn-012.ogg',
  },
  {
    id: 'a2-pn-013',
    focus: 'connected-speech',
    title: 'have to becomes hafta',
    explanation: `"have to" often sounds like "hafta" in casual speech.`,
    items: ['I have to go.', 'You have to try.', 'We have to wait.'],
    note: `Casual speaking only; always write "have to".`,
    audio: 'a2-pn-013.ogg',
  },
  {
    id: 'a2-pn-014',
    focus: 'minimal-pair',
    title: 'law vs low',
    explanation: `"law" is an open "aw"; "low" glides and rounds (oh).`,
    items: ['law, low', 'saw, so', 'fall, foal', 'The law is low.'],
    note: `Low glides and rounds; law stays open and steady.`,
    audio: 'a2-pn-014.ogg',
  },
  {
    id: 'a2-pn-015',
    focus: 'weak-forms',
    title: "can vs can't",
    explanation: `"can" is weak and quick; "can't" is stressed and clear.`,
    items: ['I can swim.', "I can't swim.", 'She can come.'],
    note: `If the word is stressed and clear, it is probably "can't".`,
    audio: 'a2-pn-015.ogg',
  },
  {
    id: 'a2-pn-016',
    focus: 'spelling-sound',
    title: 'ph says f',
    explanation: `The letters "ph" together make an "f" sound.`,
    items: ['phone', 'photo', 'graph', 'elephant'],
    note: `Just say "f"; the "p" and "h" join into one sound.`,
    audio: 'a2-pn-016.ogg',
  },
  {
    id: 'a2-pn-017',
    focus: 'spelling-sound',
    title: 'double letters, one sound',
    explanation: `A double letter usually makes a single sound, not two.`,
    items: ['letter', 'happy', 'dinner', 'rabbit'],
    note: `Do not say the letter twice; it is one sound.`,
    audio: 'a2-pn-017.ogg',
  },
  {
    id: 'a2-pn-018',
    focus: 'connected-speech',
    title: 'what do you becomes whaddaya',
    explanation: `"what do you" blurs into "whaddaya" in fast, casual speech.`,
    items: ['What do you want?', 'What do you think?', 'What do you mean?'],
    note: `Very common and casual; do not over-pronounce each word.`,
    audio: 'a2-pn-018.ogg',
  },
  {
    id: 'a2-pn-019',
    focus: 'word-stress',
    title: '-tion words: stress before it',
    explanation: `Words ending in "-tion" stress the syllable just before it.`,
    items: ['inforMAtion', 'eduCAtion', 'celeBRAtion'],
    note: `The strong beat lands right before "-tion".`,
    audio: 'a2-pn-019.ogg',
  },
  {
    id: 'a2-pn-020',
    focus: 'minimal-pair',
    title: 'thank vs tank',
    explanation: `"th" puts the tongue between the teeth; "t" taps behind them.`,
    items: ['thank, tank', 'thin, tin', 'thought, taught', 'Thank you for the tank.'],
    note: `Let the tongue tip show for "th".`,
    audio: 'a2-pn-020.ogg',
  },
];
