/**
 * C1 (advanced) pronunciation drills: stress that shifts with word forms, the
 * schwa and weak forms that drive English rhythm, elision, and the smooth
 * catenation of natural speech.
 */
import type { PronunciationDrill } from '../types';

export const c1Pronunciation: PronunciationDrill[] = [
  {
    id: 'c1-pn-001',
    focus: 'word-stress',
    title: 'REcord vs reCORD',
    explanation: `Many words shift stress by job: REcord (noun) vs reCORD (verb). Stress changes meaning.`,
    items: ['record, record', 'present, present', 'Please record this record.'],
    note: `Stress the first part for the noun, the second for the verb.`,
    audio: 'c1-pn-001.ogg',
  },
  {
    id: 'c1-pn-002',
    focus: 'word-stress',
    title: 'stress moves with endings',
    explanation: `Adding a suffix can move the stress to a different syllable.`,
    items: ['PHOto, phoTOgrapher, photoGRAPHic', 'ECONomy, ecoNOMic', 'POLitics, poLItical'],
    note: `Let the stress shift; do not keep it fixed on the root.`,
    audio: 'c1-pn-002.ogg',
  },
  {
    id: 'c1-pn-003',
    focus: 'weak-forms',
    title: 'the schwa, English rhythm',
    explanation: `Unstressed vowels collapse to a quick "uh", the schwa. It is the most common sound.`,
    items: ['banana', 'about', 'the support of a teacher'],
    note: `Squeeze the weak syllables; only the stressed one is clear.`,
    audio: 'c1-pn-003.ogg',
  },
  {
    id: 'c1-pn-004',
    focus: 'connected-speech',
    title: 'elision: dropping sounds',
    explanation: `In clusters, sounds drop, like the "t" in "next day" or "most people".`,
    items: ['next day', 'most people', 'kept quiet'],
    note: `The middle consonant often vanishes in fast speech.`,
    audio: 'c1-pn-004.ogg',
  },
  {
    id: 'c1-pn-005',
    focus: 'weak-forms',
    title: 'two ways to say the',
    explanation: `"the" is "thuh" before a consonant sound and "thee" before a vowel sound.`,
    items: ['the book', 'the apple', 'the end of the hour'],
    note: `It follows the sound, not the spelling: "thee hour".`,
    audio: 'c1-pn-005.ogg',
  },
  {
    id: 'c1-pn-006',
    focus: 'connected-speech',
    title: 'catenation across words',
    explanation: `Final consonants flow onto the next word's vowel, making one smooth stream.`,
    items: ['an apple a day', 'first of all', 'an hour and a half'],
    note: `Aim for a single connected sound, not separate words.`,
    audio: 'c1-pn-006.ogg',
  },
  {
    id: 'c1-pn-007',
    focus: 'word-stress',
    title: 'compound noun stress',
    explanation: `Compound nouns usually stress the first word, which marks one specific thing.`,
    items: ['GREENhouse', 'BLACKboard', 'a HOTdog, not a hot DOG'],
    note: `Stress the first part to mean the compound, not two separate words.`,
    audio: 'c1-pn-007.ogg',
  },
  {
    id: 'c1-pn-008',
    focus: 'minimal-pair',
    title: 'saw vs sore vs so',
    explanation: `Subtle differences in vowel and r-coloring (American English) set these apart.`,
    items: ['saw, sore, so', 'law, lore, low', 'I saw a sore on my toe.'],
    note: `In American English, "sore" carries an r-color; "saw" and "so" do not.`,
    audio: 'c1-pn-008.ogg',
  },
  {
    id: 'c1-pn-009',
    focus: 'spelling-sound',
    title: 'stress changes the vowel',
    explanation: `When stress moves off a vowel, that vowel collapses to a schwa.`,
    items: ['PHOtograph, phoTOgrapher', 'The "o" reduces when it loses the stress.'],
    note: `Same letters, different sound, depending on the stress.`,
    audio: 'c1-pn-009.ogg',
  },
  {
    id: 'c1-pn-010',
    focus: 'word-stress',
    title: 'stress moves across a word family',
    explanation: `Within a word family, the stressed syllable can move with each form.`,
    items: ['POLitics', 'poLItical', 'politICian'],
    note: `Three forms, three different stressed syllables.`,
    audio: 'c1-pn-010.ogg',
  },
  {
    id: 'c1-pn-011',
    focus: 'spelling-sound',
    title: 'the many sounds of a',
    explanation: `The letter "a" has several sounds depending on the word.`,
    items: ['cat (short)', 'car (broad)', 'cake (long)', 'about (schwa)'],
    note: `Spelling alone will not tell you; learn these by ear.`,
    audio: 'c1-pn-011.ogg',
  },
  {
    id: 'c1-pn-012',
    focus: 'connected-speech',
    title: 'intrusive linking sounds',
    explanation: `Speakers slip in a small "w", "y", or "r" to link two vowels.`,
    items: ['go away (w)', 'I agree (y)', 'the idea of it (r)'],
    note: `These links happen naturally; do not force them.`,
    audio: 'c1-pn-012.ogg',
  },
  {
    id: 'c1-pn-013',
    focus: 'weak-forms',
    title: 'the weak linking that',
    explanation: `"that" reduces when it links clauses, but stays clear when it points.`,
    items: ['I think that he left.', 'The book that I read.', 'Look at that!'],
    note: `The linking "that" is quick; the pointing "that" is clear.`,
    audio: 'c1-pn-013.ogg',
  },
  {
    id: 'c1-pn-014',
    focus: 'minimal-pair',
    title: 'accept vs except',
    explanation: `Near-homophones: "accept" means take, "except" means not including.`,
    items: ['accept, except', 'I accept all of them except one.'],
    note: `The first sound and the stress break them apart slightly.`,
    audio: 'c1-pn-014.ogg',
  },
  {
    id: 'c1-pn-015',
    focus: 'word-stress',
    title: 'compound vs phrase stress',
    explanation: `Where you stress two words changes the meaning.`,
    items: ['a GREENhouse vs a green HOUSE', 'an ENGlish teacher vs an English TEACHer'],
    note: `Front stress makes a compound; even stress makes a phrase.`,
    audio: 'c1-pn-015.ogg',
  },
  {
    id: 'c1-pn-016',
    focus: 'spelling-sound',
    title: 'the ea pair',
    explanation: `"ea" can be long "ee", short "e", or even "ay".`,
    items: ['eat (ee)', 'bread (e)', 'great (ay)', 'I eat bread.'],
    note: `There is no single rule; learn these word by word.`,
    audio: 'c1-pn-016.ogg',
  },
  {
    id: 'c1-pn-017',
    focus: 'connected-speech',
    title: 'elision in common phrases',
    explanation: `Whole sounds vanish in very frequent phrases.`,
    items: ['I dunno', 'gimme a sec', 'lemme see'],
    note: `Very informal; recognise them even if you avoid using them.`,
    audio: 'c1-pn-017.ogg',
  },
  {
    id: 'c1-pn-018',
    focus: 'weak-forms',
    title: 'stacked auxiliary contractions',
    explanation: `Helper verbs stack and reduce: "she would have" becomes "she'd've".`,
    items: ["She'd have helped.", "They'd have known.", "I'd have said so."],
    note: `Common in speech, but keep them out of formal writing.`,
    audio: 'c1-pn-018.ogg',
  },
  {
    id: 'c1-pn-019',
    focus: 'spelling-sound',
    title: 'historical silent letters',
    explanation: `Old spellings keep letters we no longer pronounce.`,
    items: ['knight (silent k and gh)', 'gnome (silent g)', 'wrist (silent w)'],
    note: `These are historical; memorise the whole word.`,
    audio: 'c1-pn-019.ogg',
  },
  {
    id: 'c1-pn-020',
    focus: 'word-stress',
    title: 'rhythm: content vs function words',
    explanation: `Stress the content words and rush the function words between them.`,
    items: ['I went to the SHOP to buy some BREAD.', 'She CALLED to say HI.'],
    note: `English rhythm rides on the stressed beats.`,
    audio: 'c1-pn-020.ogg',
  },
];
