/**
 * C2 (mastery) pronunciation drills: assimilation across word boundaries, the
 * American tapped t, heavy reductions of function words, and the way sentence
 * stress alone can change a whole meaning.
 */
import type { PronunciationDrill } from '../types';

export const c2Pronunciation: PronunciationDrill[] = [
  {
    id: 'c2-pn-001',
    focus: 'connected-speech',
    title: 'assimilation of place',
    explanation: `Sounds shift to match their neighbor: "ten boys" can sound like "tem boys".`,
    items: ['ten boys', 'good girl', 'that boy'],
    note: `The "n" or "d" moves toward the next sound; do not force it, just relax.`,
    audio: 'c2-pn-001.ogg',
  },
  {
    id: 'c2-pn-002',
    focus: 'weak-forms',
    title: 'shoulda, coulda, musta',
    explanation: `Strings of small words blur: "should have" becomes "shoulda" in fast speech.`,
    items: ["I shouldn't have asked.", 'You could have told me.', 'It must have been late.'],
    note: `"have" becomes a quick "uh-v" or even just "uh"; never "of" in writing.`,
    audio: 'c2-pn-002.ogg',
  },
  {
    id: 'c2-pn-003',
    focus: 'word-stress',
    title: 'stress for contrast',
    explanation: `Move the stress onto the word you want to contrast, and the meaning sharpens.`,
    items: ['I said the BLUE one, not the red one.', 'She LIKES him, she does not love him.'],
    note: `Stress tells the listener exactly what you mean.`,
    audio: 'c2-pn-003.ogg',
  },
  {
    id: 'c2-pn-004',
    focus: 'connected-speech',
    title: 'the American tapped t',
    explanation: `Between vowels, American "t" becomes a quick "d"-like tap.`,
    items: ['water', 'better', 'a lot of it'],
    note: `It sounds like "wadder" and "bedder" in American English.`,
    audio: 'c2-pn-004.ogg',
  },
  {
    id: 'c2-pn-005',
    focus: 'minimal-pair',
    title: 'cot vs caught vs court',
    explanation: `These vary by accent; in many American accents only "court" adds an r-color.`,
    items: ['cot, caught, court', 'tot, taught, taut', 'He sat on the cot.'],
    note: `Court carries the r-color; the other two do not.`,
    audio: 'c2-pn-005.ogg',
  },
  {
    id: 'c2-pn-006',
    focus: 'weak-forms',
    title: 'you and your become ya, yer',
    explanation: `In fast, casual speech, "you" and "your" shrink to "ya" and "yer".`,
    items: ['See you later.', "What's your name?", 'Thank you very much.'],
    note: `Casual only; over-reducing can sound sloppy in formal talk.`,
    audio: 'c2-pn-006.ogg',
  },
  {
    id: 'c2-pn-007',
    focus: 'connected-speech',
    title: 'rhythm in a long phrase',
    explanation: `English is stress-timed: it squeezes weak syllables between the strong beats.`,
    items: ['a cup of coffee and a piece of cake', 'out of sight, out of mind'],
    note: `Hit the strong content words; rush lightly through the rest.`,
    audio: 'c2-pn-007.ogg',
  },
  {
    id: 'c2-pn-008',
    focus: 'word-stress',
    title: 'sentence stress changes meaning',
    explanation: `The stressed word carries the main message, so moving it rewrites the sentence.`,
    items: [
      'I never said she stole it.',
      'I never said SHE stole it.',
      'I never said she STOLE it.',
    ],
    note: `Say each version stressing the capital word and feel the meaning change.`,
    audio: 'c2-pn-008.ogg',
  },
  {
    id: 'c2-pn-009',
    focus: 'connected-speech',
    title: 'full reduction in fast speech',
    explanation: `Strings of weak words collapse almost completely in rapid speech.`,
    items: ['Whaddaya wanna do?', 'I coulda told ya.', 'Lemme know whenya can.'],
    note: `Recognise these; use them only when truly casual.`,
    audio: 'c2-pn-009.ogg',
  },
  {
    id: 'c2-pn-010',
    focus: 'word-stress',
    title: 'contrastive stress and implication',
    explanation: `Stress carries meaning the words alone do not say.`,
    items: ["I didn't say he STOLE it.", "I didn't SAY he stole it."],
    note: `Each stressed word hints at a different unspoken meaning.`,
    audio: 'c2-pn-010.ogg',
  },
  {
    id: 'c2-pn-011',
    focus: 'spelling-sound',
    title: 'loanword pronunciations',
    explanation: `Borrowed words keep traces of their original language.`,
    items: ['genre (zh)', 'bouquet (boo-kay)', 'rendezvous (silent z and s)'],
    note: `These follow the source language, not English spelling rules.`,
    audio: 'c2-pn-011.ogg',
  },
  {
    id: 'c2-pn-012',
    focus: 'weak-forms',
    title: 'function words nearly vanish',
    explanation: `In rapid speech, articles and prepositions almost disappear.`,
    items: ['a piece of cake', 'out of the question', 'at the end of the day'],
    note: `The strong words carry it; the rest is a quick blur.`,
    audio: 'c2-pn-012.ogg',
  },
  {
    id: 'c2-pn-013',
    focus: 'spelling-sound',
    title: 'heteronyms: one spelling, two sounds',
    explanation: `Some words are spelled alike but said differently by meaning.`,
    items: ['lead (to lead / a lead pipe)', 'tear (a tear / to tear)', 'wind (the wind / to wind)'],
    note: `Only the context tells you which sound to use.`,
    audio: 'c2-pn-013.ogg',
  },
  {
    id: 'c2-pn-014',
    focus: 'connected-speech',
    title: 'assimilation across words',
    explanation: `Sounds reshape their neighbors across word boundaries.`,
    items: ['that boy (tha-boy)', 'good cook (goo-cook)', 'ten men (tem-men)'],
    note: `The change is natural and barely noticeable.`,
    audio: 'c2-pn-014.ogg',
  },
  {
    id: 'c2-pn-015',
    focus: 'word-stress',
    title: 'stress-timing keeps the beat',
    explanation: `English keeps a steady beat by squeezing the weak syllables.`,
    items: ['CATS eat FISH.', 'The CATS will have eaten the FISH.'],
    note: `Both lines take about the same time to say.`,
    audio: 'c2-pn-015.ogg',
  },
  {
    id: 'c2-pn-016',
    focus: 'spelling-sound',
    title: 'ti, ci, si can all say sh',
    explanation: `Inside words, "ti", "ci", and "si" often make a "sh" sound.`,
    items: ['nation (ti)', 'special (ci)', 'mission (si)'],
    note: `This is why "-tion" sounds like "shun".`,
    audio: 'c2-pn-016.ogg',
  },
  {
    id: 'c2-pn-017',
    focus: 'weak-forms',
    title: 'tag questions reduce and link',
    explanation: `Tags weaken and link onto the sentence, with the pitch carrying meaning.`,
    items: ["It's fine, isn't it?", "You know, don't you?", "She'll come, won't she?"],
    note: `A falling tag checks; a rising tag genuinely asks.`,
    audio: 'c2-pn-017.ogg',
  },
  {
    id: 'c2-pn-018',
    focus: 'connected-speech',
    title: 'the fixed rhythm of idioms',
    explanation: `Set phrases carry a fixed, memorable beat.`,
    items: ['easy come, easy go', 'now or never', 'sooner or later'],
    note: `Feel the rhythm; it is part of why the phrase sticks.`,
    audio: 'c2-pn-018.ogg',
  },
  {
    id: 'c2-pn-019',
    focus: 'spelling-sound',
    title: 'stress reshapes a whole word',
    explanation: `In long words, moving the stress reshapes every other vowel.`,
    items: ['ANalyse', 'aNAlysis', 'anaLYtical'],
    note: `The same root sounds quite different across its forms.`,
    audio: 'c2-pn-019.ogg',
  },
  {
    id: 'c2-pn-020',
    focus: 'word-stress',
    title: 'lengthening for emotion',
    explanation: `Stretching and stressing a word adds strong feeling.`,
    items: ['That was AMAZing.', 'I am SO tired.', 'It was HUGE.'],
    note: `Stretch the stressed syllable to show real emotion.`,
    audio: 'c2-pn-020.ogg',
  },
];
