/**
 * B2 (upper-intermediate) pronunciation drills: finer vowel contrasts, the
 * voiced/voiceless endings that change a word's job, stress that changes
 * meaning, and the natural blends of everyday speech.
 */
import type { PronunciationDrill } from '../types';

export const b2Pronunciation: PronunciationDrill[] = [
  {
    id: 'b2-pn-001',
    focus: 'minimal-pair',
    title: 'beat vs bit vs bet',
    explanation: `Long ee (beat), short i (bit), and "e" (bet) are three different vowels.`,
    items: ['beat, bit, bet', 'seat, sit, set', 'He bet he could beat it.'],
    note: `Three clearly different mouth positions, from tense to relaxed.`,
    audio: 'b2-pn-001.ogg',
  },
  {
    id: 'b2-pn-002',
    focus: 'minimal-pair',
    title: 'advice vs advise',
    explanation: `The noun "advice" ends in an "s" sound; the verb "advise" ends in a buzzing "z".`,
    items: ['advice, advise', 'a device, to devise', 'My advice is to advise them.'],
    note: `The verb buzzes at the end; the noun hisses.`,
    audio: 'b2-pn-002.ogg',
  },
  {
    id: 'b2-pn-003',
    focus: 'minimal-pair',
    title: 'pleasure vs pressure',
    explanation: `The middle differs: a soft, buzzing "zh" in pleasure vs a sharp "sh" in pressure.`,
    items: ['pleasure, pressure', 'measure, mesher', 'It is a pleasure under pressure.'],
    note: `"zh" is voiced and buzzing; "sh" is quiet and voiceless.`,
    audio: 'b2-pn-003.ogg',
  },
  {
    id: 'b2-pn-004',
    focus: 'word-stress',
    title: 'DEsert vs desSERT',
    explanation: `Stress changes the word: DEsert (dry sand) vs dessSERT (the sweet course).`,
    items: ['desert, dessert', 'We crossed the desert.', 'I want some dessert.'],
    note: `Stress the first part for sand, the second part for sweet.`,
    audio: 'b2-pn-004.ogg',
  },
  {
    id: 'b2-pn-005',
    focus: 'minimal-pair',
    title: 'fan vs fun vs phone',
    explanation: `The vowel does the work: front "a" (fan), central "uh" (fun), gliding "oh" (phone).`,
    items: ['fan, fun, phone', 'ran, run, roan', 'The fan is fun.'],
    note: `Move from a front, open vowel to a relaxed one to a rounded glide.`,
    audio: 'b2-pn-005.ogg',
  },
  {
    id: 'b2-pn-006',
    focus: 'connected-speech',
    title: 'wanna, gonna, hafta',
    explanation: `"want to", "going to", and "have to" reduce to wanna, gonna, and hafta.`,
    items: ['I want to leave.', 'I am going to try.', 'I have to work.'],
    note: `Common and natural in speech; keep the writing standard.`,
    audio: 'b2-pn-006.ogg',
  },
  {
    id: 'b2-pn-007',
    focus: 'connected-speech',
    title: 'assimilation: doncha, woncha',
    explanation: `A "t" before "y" blends into "ch"; a "d" before "y" blends into "j".`,
    items: ["Don't you know?", "Won't you come?", 'Would you mind?'],
    note: `It sounds like "doncha", "woncha", and "wouldja".`,
    audio: 'b2-pn-007.ogg',
  },
  {
    id: 'b2-pn-008',
    focus: 'weak-forms',
    title: 'weak was, were, and can',
    explanation: `When unstressed, "was", "were", and "can" reduce to "wuz", "wer", and "kn".`,
    items: ['I was late.', 'They were ready.', 'I can help.'],
    note: `Stressed "can" and weak "can" sound different; usually it is weak.`,
    audio: 'b2-pn-008.ogg',
  },
  {
    id: 'b2-pn-009',
    focus: 'spelling-sound',
    title: 'tion vs sion',
    explanation: `"-tion" says "shun"; "-sion" can say "shun" or a buzzing "zhun".`,
    items: ['action (shun)', 'vision (zhun)', 'decision (zhun)', 'station (shun)'],
    note: `After a vowel, "-sion" often buzzes: "vi-zhun".`,
    audio: 'b2-pn-009.ogg',
  },
  {
    id: 'b2-pn-010',
    focus: 'spelling-sound',
    title: 'silent letters in clusters',
    explanation: `Some letter clusters hide a silent letter in the middle or end.`,
    items: ['castle (silent t)', 'comb (silent b)', 'sign (silent g)', 'doubt (silent b)'],
    note: `Learn these as whole words; the rule is irregular.`,
    audio: 'b2-pn-010.ogg',
  },
  {
    id: 'b2-pn-011',
    focus: 'word-stress',
    title: 'stress in longer words',
    explanation: `Long words often stress the third syllable from the end.`,
    items: ['phoTOgraphy', 'deMOcracy', 'aNAlysis'],
    note: `Count back three syllables to find the strong beat.`,
    audio: 'b2-pn-011.ogg',
  },
  {
    id: 'b2-pn-012',
    focus: 'minimal-pair',
    title: 'affect vs effect',
    explanation: `The unstressed "a" in affect reduces; the "e" in effect is a bit clearer.`,
    items: ['affect, effect', 'It will affect us.', 'It had an effect.'],
    note: `In speech they are close; context usually tells them apart.`,
    audio: 'b2-pn-012.ogg',
  },
  {
    id: 'b2-pn-013',
    focus: 'connected-speech',
    title: 'the tapped and dropped t',
    explanation: `American "t" taps like "d" between vowels, and can drop after "n".`,
    items: ['water (tap)', 'better (tap)', 'twenty (dropped t)'],
    note: `"twenty" often sounds like "twenny".`,
    audio: 'b2-pn-013.ogg',
  },
  {
    id: 'b2-pn-014',
    focus: 'weak-forms',
    title: 'for, from, and at',
    explanation: `Prepositions reduce: "for" to "fer", "from" to "frm", "at" to "et".`,
    items: ['This is for you.', 'I came from work.', 'Look at this.'],
    note: `Never stress these little linking words.`,
    audio: 'b2-pn-014.ogg',
  },
  {
    id: 'b2-pn-015',
    focus: 'spelling-sound',
    title: 'the gh puzzle',
    explanation: `"gh" is silent or says "f", and almost never a hard "g".`,
    items: ['light (silent)', 'enough (f)', 'cough (f)', 'eight (silent)'],
    note: `If unsure, try silent first, then "f".`,
    audio: 'b2-pn-015.ogg',
  },
  {
    id: 'b2-pn-016',
    focus: 'word-stress',
    title: '-ic and -ical shift the stress',
    explanation: `The suffixes "-ic" and "-ical" pull the stress to just before them.`,
    items: ['ecoNOMic', 'hisTORical', 'speCIFic'],
    note: `The stress lands right before "-ic" or "-ical".`,
    audio: 'b2-pn-016.ogg',
  },
  {
    id: 'b2-pn-017',
    focus: 'spelling-sound',
    title: 'homophones',
    explanation: `Homophones sound identical but are spelled differently and mean different things.`,
    items: ['horse, hoarse', 'flower, flour', 'They sound exactly the same.'],
    note: `Only the spelling and meaning differ; the sound is one.`,
    audio: 'b2-pn-017.ogg',
  },
  {
    id: 'b2-pn-018',
    focus: 'connected-speech',
    title: 'got you becomes gotcha',
    explanation: `Fast speech blurs "got you", "want to", and similar pairs.`,
    items: ['Got you covered.', 'I need you to help.', 'I want you to know.'],
    note: `"Got you" often sounds like "gotcha".`,
    audio: 'b2-pn-018.ogg',
  },
  {
    id: 'b2-pn-019',
    focus: 'spelling-sound',
    title: 'qu says kw',
    explanation: `The letters "qu" together make a "kw" sound.`,
    items: ['quick', 'queen', 'question', 'quiet'],
    note: `Always "kw", never just "k".`,
    audio: 'b2-pn-019.ogg',
  },
  {
    id: 'b2-pn-020',
    focus: 'weak-forms',
    title: 'would, could, should',
    explanation: `These often shrink to "wud", "cud", "shud", and link onto "have".`,
    items: ['I would have gone.', 'You could have asked.', 'We should have known.'],
    note: `"would have" sounds like "would-uv", never "would of".`,
    audio: 'b2-pn-020.ogg',
  },
];
