/**
 * B1 (intermediate) pronunciation drills: the th sounds, v/w, the r-colored
 * vowels, and the weak forms and blends that separate textbook English from the
 * real thing.
 */
import type { PronunciationDrill } from '../types';

export const b1Pronunciation: PronunciationDrill[] = [
  {
    id: 'b1-pn-001',
    focus: 'minimal-pair',
    title: 'think vs sink',
    explanation: `"th" puts the tongue tip between the teeth; "s" keeps it behind them.`,
    items: ['think, sink', 'thick, sick', 'thing, sing', 'I think the sink is full.'],
    note: `Let the tongue tip lightly touch the teeth for "th".`,
    audio: 'b1-pn-001.ogg',
  },
  {
    id: 'b1-pn-002',
    focus: 'minimal-pair',
    title: 'three vs tree',
    explanation: `"th" is soft with the tongue out; "t" is a hard tap behind the teeth.`,
    items: ['three, tree', 'thread, tread', 'thrill, trill', 'There are three trees.'],
    note: `Do not turn "th" into a hard "t".`,
    audio: 'b1-pn-002.ogg',
  },
  {
    id: 'b1-pn-003',
    focus: 'minimal-pair',
    title: 'vest vs west',
    explanation: `"v" rests the top teeth on the bottom lip; "w" rounds the lips with no teeth.`,
    items: ['vest, west', 'vent, went', 'veil, wail', 'The west wind is cold.'],
    note: `For v, the top teeth touch the bottom lip and buzz.`,
    audio: 'b1-pn-003.ogg',
  },
  {
    id: 'b1-pn-004',
    focus: 'minimal-pair',
    title: 'walk vs work',
    explanation: `"walk" is an open "aw"; "work" uses the r-colored "er" sound.`,
    items: ['walk, work', 'ward, word', 'born, burn', 'I walk to work.'],
    note: `Work, word, and burn all share the "er" sound.`,
    audio: 'b1-pn-004.ogg',
  },
  {
    id: 'b1-pn-005',
    focus: 'minimal-pair',
    title: 'pull vs pool',
    explanation: `"pull" is short and relaxed; "pool" is long with rounded lips.`,
    items: ['pull, pool', 'full, fool', 'should, shooed', 'Pull the chair to the pool.'],
    note: `Round and hold the lips longer for the long oo.`,
    audio: 'b1-pn-005.ogg',
  },
  {
    id: 'b1-pn-006',
    focus: 'connected-speech',
    title: 'did you becomes didja',
    explanation: `"did you" often blends into "didja" because the d and y merge.`,
    items: ['Did you see it?', 'Did you eat?', 'What did you do?'],
    note: `The "d" and "y" join into a soft "j" sound.`,
    audio: 'b1-pn-006.ogg',
  },
  {
    id: 'b1-pn-007',
    focus: 'weak-forms',
    title: 'weak to and of',
    explanation: `Small words like "to" and "of" reduce to "tuh" and "uv" when unstressed.`,
    items: ['I need to go.', 'A cup of tea.', 'Nice to meet you.'],
    note: `Never stress these words; keep them short and quiet.`,
    audio: 'b1-pn-007.ogg',
  },
  {
    id: 'b1-pn-008',
    focus: 'connected-speech',
    title: 'linking consonant to vowel',
    explanation: `A word that ends in a consonant links onto the next word's vowel.`,
    items: ['Pick it up.', 'Turn it off.', 'Hold on a second.'],
    note: `It sounds like "pi-ki-tup" and "tur-ni-toff".`,
    audio: 'b1-pn-008.ogg',
  },
  {
    id: 'b1-pn-009',
    focus: 'spelling-sound',
    title: 'the ough family',
    explanation: `"ough" is spelled the same but said many different ways.`,
    items: ['through (oo)', 'though (oh)', 'tough (uff)', 'thought (aw)'],
    note: `There is no single rule here; learn each word by ear.`,
    audio: 'b1-pn-009.ogg',
  },
  {
    id: 'b1-pn-010',
    focus: 'spelling-sound',
    title: 'soft and hard c',
    explanation: `"c" is soft (s) before e, i, or y; hard (k) everywhere else.`,
    items: ['city (s)', 'cat (k)', 'cycle (s)', 'cup (k)'],
    note: `Before e, i, or y, the "c" sounds like "s".`,
    audio: 'b1-pn-010.ogg',
  },
  {
    id: 'b1-pn-011',
    focus: 'spelling-sound',
    title: 'soft and hard g',
    explanation: `"g" is often soft (j) before e, i, or y; hard (g) elsewhere.`,
    items: ['giant (j)', 'go (g)', 'gym (j)', 'gas (g)'],
    note: `Watch for exceptions like "get" and "give", which stay hard.`,
    audio: 'b1-pn-011.ogg',
  },
  {
    id: 'b1-pn-012',
    focus: 'word-stress',
    title: 'noun vs verb stress pairs',
    explanation: `Stress shifts from noun to verb: PREsent vs preSENT.`,
    items: ['present, present', 'object, object', 'increase, increase'],
    note: `Noun stresses the first part; the verb stresses the second.`,
    audio: 'b1-pn-012.ogg',
  },
  {
    id: 'b1-pn-013',
    focus: 'minimal-pair',
    title: 'wary vs weary',
    explanation: `"wary" has the "air" sound; "weary" has the long "ee".`,
    items: ['wary, weary', 'fairy, ferry', 'I am wary and weary.'],
    note: `Wary rhymes with "hairy"; weary with "really".`,
    audio: 'b1-pn-013.ogg',
  },
  {
    id: 'b1-pn-014',
    focus: 'connected-speech',
    title: 'got to becomes gotta',
    explanation: `"got to" reduces to "gotta" in casual speech.`,
    items: ['I have got to run.', 'We got to see it.', 'You got to try this.'],
    note: `Casual only; keep writing "got to" or "have to".`,
    audio: 'b1-pn-014.ogg',
  },
  {
    id: 'b1-pn-015',
    focus: 'weak-forms',
    title: 'have and has as helpers',
    explanation: `As helper verbs, "have" and "has" weaken to "uv" and "uz".`,
    items: ['I have seen it.', 'She has gone.', 'They have left.'],
    note: `As a main verb ("I have a car"), it stays clearer.`,
    audio: 'b1-pn-015.ogg',
  },
  {
    id: 'b1-pn-016',
    focus: 'spelling-sound',
    title: 'the schwa in endings',
    explanation: `Endings like "-er, -or, -ar" all reduce to a quick, lazy "er".`,
    items: ['teacher', 'doctor', 'dollar', 'similar'],
    note: `Different spellings, but the same relaxed "er" sound.`,
    audio: 'b1-pn-016.ogg',
  },
  {
    id: 'b1-pn-017',
    focus: 'word-stress',
    title: 'phrasal verb stress',
    explanation: `In a phrasal verb, the small particle at the end often takes the stress.`,
    items: ['turn it OFF', 'pick it UP', 'give it BACK'],
    note: `Stress the particle, not the main verb.`,
    audio: 'b1-pn-017.ogg',
  },
  {
    id: 'b1-pn-018',
    focus: 'minimal-pair',
    title: 'pour vs power',
    explanation: `"pour" is one smooth sound; "power" splits into two syllables.`,
    items: ['pour, power', 'tower, tore', 'Pour the power drink.'],
    note: `Power is "pow-er"; pour is a single beat.`,
    audio: 'b1-pn-018.ogg',
  },
  {
    id: 'b1-pn-019',
    focus: 'spelling-sound',
    title: 'wh words',
    explanation: `"wh" is usually just a "w" sound; the "who" family is the exception (h).`,
    items: ['what (w)', 'when (w)', 'who (h)', 'where (w)'],
    note: `Only "who, whose, whole" say the "h".`,
    audio: 'b1-pn-019.ogg',
  },
  {
    id: 'b1-pn-020',
    focus: 'connected-speech',
    title: 'linking short phrases',
    explanation: `Glide the final consonant into the next word, with no gap.`,
    items: ['Come on in.', 'Hang on a sec.', 'Hold it right there.'],
    note: `Aim for one smooth, connected stream of sound.`,
    audio: 'b1-pn-020.ogg',
  },
];
