/**
 * C1 (advanced) English quiz questions.
 *
 * At C1 the goal is range and nuance: less common idioms, precise vocabulary,
 * advanced collocations, multi-meaning phrasal verbs, advanced grammar
 * (inversion, mixed conditionals), and confusing pairs that trip up even
 * fluent speakers (discrete/discreet, refrain/restrain, prohibit/inhibit).
 *
 * Answer indices are 0-based. Keep explanations under 200 characters so they
 * fit Telegram's quiz explanation limit.
 */
import type { QuizQuestion } from '../types';

export const c1Questions: QuizQuestion[] = [
  {
    id: 'c1-001',
    prompt: 'The merger is still up in the ____; nothing has been decided.',
    options: ['sky', 'air', 'cloud', 'wind'],
    correctIndex: 1,
    explanation: "'Up in the air' is an idiom meaning uncertain or undecided.",
    topic: 'idioms',
  },
  {
    id: 'c1-002',
    prompt: 'The new evidence ____ serious doubt on his version of events.',
    options: ['made', 'cast', 'put', 'gave'],
    correctIndex: 1,
    explanation: "The collocation is 'cast doubt on' something, to make people question it.",
    topic: 'collocations',
  },
  {
    id: 'c1-003',
    prompt: 'After the scandal, the minister had to face the ____.',
    options: ['noise', 'crowd', 'music', 'sound'],
    correctIndex: 2,
    explanation: "'Face the music' means to accept the unpleasant consequences of your actions.",
    topic: 'idioms',
  },
  {
    id: 'c1-004',
    prompt: 'The two issues are quite ____ and should be discussed separately.',
    options: ['discreet', 'discrete', 'discreetly', 'discretion'],
    correctIndex: 1,
    explanation:
      "'Discrete' means separate and distinct. 'Discreet' means careful not to attract attention.",
    topic: 'confusing-pairs',
  },
  {
    id: 'c1-005',
    prompt: 'Her argument was so ____ that no one in the room could counter it.',
    options: ['repelling', 'expelling', 'compelling', 'dispelling'],
    correctIndex: 2,
    explanation:
      "'Compelling' means powerfully convincing. The other words share the root but differ.",
    topic: 'vocabulary',
  },
  {
    id: 'c1-006',
    prompt: "We'll have to ____ on spending until the end of the month.",
    options: ['cut off', 'cut back', 'cut up', 'cut in'],
    correctIndex: 1,
    explanation: "'Cut back (on)' means to reduce. 'Cut off' means to disconnect or isolate.",
    topic: 'phrasal-verbs',
  },
  {
    id: 'c1-007',
    prompt: "Let's not jump the ____, we don't have the final results yet.",
    options: ['fence', 'queue', 'rope', 'gun'],
    correctIndex: 3,
    explanation: "'Jump the gun' means to act too soon, before the right moment.",
    topic: 'idioms',
  },
  {
    id: 'c1-008',
    prompt: 'His controversial remarks ____ a heated debate among the members.',
    options: ['lit', 'sparked', 'burned', 'fired'],
    correctIndex: 1,
    explanation:
      "'Spark a debate' means to suddenly cause one to start, a vivid, natural collocation.",
    topic: 'collocations',
  },
  {
    id: 'c1-009',
    prompt: 'The report was ____; it quietly left out the most important facts.',
    options: ['thorough', 'comprehensive', 'misleading', 'exhaustive'],
    correctIndex: 2,
    explanation:
      "'Misleading' means giving a false impression. The other options all mean complete.",
    topic: 'vocabulary',
  },
  {
    id: 'c1-010',
    prompt: 'Passengers are kindly asked to ____ from smoking inside the station.',
    options: ['restrain', 'refrain', 'retain', 'refresh'],
    correctIndex: 1,
    explanation:
      "'Refrain from' means to hold yourself back. 'Restrain' means to hold back by force.",
    topic: 'confusing-pairs',
  },
  {
    id: 'c1-011',
    prompt: 'The project succeeded in the end, but it was touch and ____ for a while.',
    options: ['run', 'go', 'move', 'near'],
    correctIndex: 1,
    explanation: "'Touch and go' describes a situation where the outcome is uncertain and risky.",
    topic: 'idioms',
  },
  {
    id: 'c1-012',
    prompt: 'She gave a ____ account of the trip, leaving out not a single detail.',
    options: ['brief', 'vague', 'meticulous', 'cursory'],
    correctIndex: 2,
    explanation:
      "'Meticulous' means showing great attention to detail. 'Cursory' and 'brief' mean the opposite.",
    topic: 'vocabulary',
  },
  {
    id: 'c1-013',
    prompt: 'He passed the final exam by the skin of his ____.',
    options: ['teeth', 'nose', 'hair', 'neck'],
    correctIndex: 0,
    explanation: "'By the skin of your teeth' means only just, by the narrowest margin.",
    topic: 'idioms',
  },
  {
    id: 'c1-014',
    prompt: 'The storm ____ severe damage on the coastal towns.',
    options: ['made', 'did', 'inflicted', 'gave'],
    correctIndex: 2,
    explanation: "'Inflict damage on' something is the natural collocation for causing harm.",
    topic: 'collocations',
  },
  {
    id: 'c1-015',
    prompt: 'His ____ remarks offended half the people in the room.',
    options: ['tactful', 'tactless', 'polite', 'gentle'],
    correctIndex: 1,
    explanation:
      "'Tactless' means saying things without care for others' feelings. 'Tactful' is the opposite.",
    topic: 'vocabulary',
  },
  {
    id: 'c1-016',
    prompt: 'She showed great ____ in handling the delicate situation.',
    options: ['discreet', 'discrete', 'discretion', 'discreetly'],
    correctIndex: 2,
    explanation:
      "'Discretion' (noun) is the quality of being careful and tactful. 'Discreet' is the adjective.",
    topic: 'confusing-pairs',
  },
  {
    id: 'c1-017',
    prompt: 'The negotiations ____ because neither side would compromise.',
    options: ['broke down', 'broke up', 'broke into', 'broke out'],
    correctIndex: 0,
    explanation: "'Break down' here means to fail or collapse (talks, machines, systems).",
    topic: 'phrasal-verbs',
  },
  {
    id: 'c1-018',
    prompt: 'After the scandal he kept a ____ profile for months.',
    options: ['small', 'low', 'short', 'light'],
    correctIndex: 1,
    explanation: "'Keep a low profile' means to avoid attention.",
    topic: 'idioms',
  },
  {
    id: 'c1-019',
    prompt: 'The new study ____ light on a long-forgotten history.',
    options: ['threw', 'put', 'shed', 'gave'],
    correctIndex: 2,
    explanation: "'Shed light on' something means to make it clearer or easier to understand.",
    topic: 'collocations',
  },
  {
    id: 'c1-020',
    prompt: 'Rarely ____ such dedication in a young student.',
    options: ['I have seen', 'have I seen', 'I saw', 'did I saw'],
    correctIndex: 1,
    explanation: "After a negative adverb like 'rarely' at the start, we invert: have I seen.",
    topic: 'grammar',
  },
  {
    id: 'c1-021',
    prompt: 'The instructions were admirably ____ and easy to follow.',
    options: ['ambiguous', 'concise', 'vague', 'obscure'],
    correctIndex: 1,
    explanation: "'Concise' means clear and brief. The other three all mean unclear.",
    topic: 'vocabulary',
  },
  {
    id: 'c1-022',
    prompt: 'The company runs its two brands as completely ____ businesses.',
    options: ['discreet', 'discrete', 'discreetly', 'discretion'],
    correctIndex: 1,
    explanation: "'Discrete' means separate and distinct. Its look-alike 'discreet' means tactful.",
    topic: 'confusing-pairs',
  },
  {
    id: 'c1-023',
    prompt: "I can't quite ____ my finger on what is bothering me.",
    options: ['lay', 'set', 'put', 'press'],
    correctIndex: 2,
    explanation: "'Put your finger on' something means to identify exactly what it is.",
    topic: 'idioms',
  },
  {
    id: 'c1-024',
    prompt: 'Winning the award was a ____ blessing; now everyone expects more.',
    options: ['double', 'half', 'mixed', 'full'],
    correctIndex: 2,
    explanation: "A 'mixed blessing' is something with both good and bad sides.",
    topic: 'idioms',
  },
  {
    id: 'c1-025',
    prompt: 'Her sudden change of plan ____ suspicion among her colleagues.',
    options: ['rose', 'raised', 'lifted', 'arose'],
    correctIndex: 1,
    explanation: "'Raise suspicion' is the collocation. 'Raise' takes an object; 'rise' does not.",
    topic: 'collocations',
  },
  {
    id: 'c1-026',
    prompt: 'He offered only a ____ apology that satisfied no one.',
    options: ['sincere', 'half-hearted', 'genuine', 'heartfelt'],
    correctIndex: 1,
    explanation:
      "'Half-hearted' means done without real effort or conviction. The others mean sincere.",
    topic: 'vocabulary',
  },
  {
    id: 'c1-027',
    prompt: 'Had I known about the traffic, I ____ a different route.',
    options: ['will take', 'would take', 'would have taken', 'had taken'],
    correctIndex: 2,
    explanation:
      "Inverted third conditional: 'Had I known' replaces 'if', then 'would have' + participle.",
    topic: 'grammar',
  },
  {
    id: 'c1-028',
    prompt: 'Smoking is strictly ____ inside the building.',
    options: ['inhibited', 'prohibited', 'exhibited', 'inhabited'],
    correctIndex: 1,
    explanation: "'Prohibited' means forbidden. 'Inhibit' means to slow or restrain a process.",
    topic: 'confusing-pairs',
  },
  {
    id: 'c1-029',
    prompt: "Let's not ____ over the problem and just hope it goes away.",
    options: ['glance', 'glide', 'gloss', 'glow'],
    correctIndex: 2,
    explanation: "'Gloss over' means to deal with something quickly to hide its difficulties.",
    topic: 'phrasal-verbs',
  },
  {
    id: 'c1-030',
    prompt: 'The tricky question caught the candidate completely off ____.',
    options: ['side', 'hand', 'guard', 'beat'],
    correctIndex: 2,
    explanation: "'Catch someone off guard' means to surprise them when they are not prepared.",
    topic: 'idioms',
  },
  {
    id: 'c1-031',
    prompt: 'The report ____ light on the causes of the failure.',
    options: ['showed', 'shone', 'spread', 'shed'],
    correctIndex: 3,
    explanation: "The collocation is 'shed light on' something, meaning to clarify it.",
    topic: 'collocations',
  },
  {
    id: 'c1-032',
    prompt: 'Her argument was compelling, ____ a few minor flaws.',
    options: ['even', 'although', 'despite of', 'albeit with'],
    correctIndex: 3,
    explanation: "'Albeit' means 'although it is' and introduces a concession: albeit with flaws.",
    topic: 'vocabulary',
  },
  {
    id: 'c1-033',
    prompt: 'The negotiations reached a ____, with neither side willing to move.',
    options: ['stand', 'standstill of', 'deadlock of', 'stalemate'],
    correctIndex: 3,
    explanation: "A 'stalemate' is a deadlock where no progress is possible.",
    topic: 'vocabulary',
  },
  {
    id: 'c1-034',
    prompt: 'Only after the deadline ____ that the data was wrong.',
    options: ['we realised', 'did we realise', 'we did realise', 'realised we'],
    correctIndex: 1,
    explanation: "After a fronted 'Only after ...' we invert: did we realise.",
    topic: 'grammar',
  },
  {
    id: 'c1-035',
    prompt: 'He tends to ____ the importance of his own role.',
    options: ['overstate', 'overstand', 'understate of', 'overspeak'],
    correctIndex: 0,
    explanation: "'Overstate' means to exaggerate. Its opposite is 'understate'.",
    topic: 'vocabulary',
  },
  {
    id: 'c1-036',
    prompt: 'The committee decided to ____ ahead with the controversial plan.',
    options: ['press', 'push of', 'press of', 'pull'],
    correctIndex: 0,
    explanation: "'Press ahead' (also 'press on') means to continue despite difficulties.",
    topic: 'phrasal-verbs',
  },
  {
    id: 'c1-037',
    prompt: 'Were it not for her quick thinking, the deal ____ collapsed.',
    options: ['would have', 'would', 'will have', 'had'],
    correctIndex: 0,
    explanation: "This inverted third conditional needs 'would have' + participle in the result.",
    topic: 'grammar',
  },
  {
    id: 'c1-038',
    prompt: "The scandal ____ a serious blow to the minister's reputation.",
    options: ['dealt', 'made', 'gave', 'took'],
    correctIndex: 0,
    explanation: "The collocation is 'deal a blow to' something, meaning to damage it.",
    topic: 'collocations',
  },
  {
    id: 'c1-039',
    prompt: 'His explanation only served to ____ the confusion.',
    options: ['compound', 'compose', 'comprise', 'compromise'],
    correctIndex: 0,
    explanation: "'Compound' a problem means to make it worse by adding to it.",
    topic: 'vocabulary',
  },
  {
    id: 'c1-040',
    prompt: 'She has a tendency to ____ on tangents during meetings.',
    options: ['go off', 'go over', 'go on of', 'go in'],
    correctIndex: 0,
    explanation: "'Go off on a tangent' means to drift away from the main subject.",
    topic: 'idioms',
  },
  {
    id: 'c1-041',
    prompt: 'The new policy is, ____ all intents and purposes, a tax rise.',
    options: ['to', 'for', 'by', 'in'],
    correctIndex: 0,
    explanation: "'To all intents and purposes' is a fixed phrase meaning in effect, practically.",
    topic: 'idioms',
  },
  {
    id: 'c1-042',
    prompt: 'The findings are ____ with our earlier results.',
    options: ['consistent', 'persistent', 'insistent', 'resistant'],
    correctIndex: 0,
    explanation: "'Consistent with' means in agreement with. The others do not fit here.",
    topic: 'confusing-pairs',
  },
  {
    id: 'c1-043',
    prompt: 'No sooner had the sun risen ____ the birds began to sing.',
    options: ['than', 'then', 'when', 'that'],
    correctIndex: 0,
    explanation: "'No sooner ... than' is the fixed correlative for one event right after another.",
    topic: 'grammar',
  },
  {
    id: 'c1-044',
    prompt: 'The author ____ a vivid picture of life in the city.',
    options: ['paints', 'draws', 'makes', 'does'],
    correctIndex: 0,
    explanation: "The collocation is 'paint a picture' of something, used figuratively here.",
    topic: 'collocations',
  },
  {
    id: 'c1-045',
    prompt: 'The minister was forced to ____ down amid the scandal.',
    options: ['step', 'put', 'turn', 'set'],
    correctIndex: 0,
    explanation: "'Step down' means to resign from a position of responsibility.",
    topic: 'phrasal-verbs',
  },
  {
    id: 'c1-046',
    prompt: 'The proposal was met with a ____ of criticism.',
    options: ['barrage', 'baggage', 'barricade', 'bandage'],
    correctIndex: 0,
    explanation: "A 'barrage' is an overwhelming, rapid burst, here of criticism.",
    topic: 'vocabulary',
  },
  {
    id: 'c1-047',
    prompt: 'Little ____ that the decision would change everything.',
    options: ['they knew', 'did they know', 'they did know', 'knew they'],
    correctIndex: 1,
    explanation: "After the fronted negative 'Little' we invert: Little did they know.",
    topic: 'grammar',
  },
  {
    id: 'c1-048',
    prompt: 'We should not ____ to conclusions before seeing the data.',
    options: ['jump', 'leap', 'rush of', 'hop'],
    correctIndex: 0,
    explanation: "'Jump to conclusions' means to decide too quickly without the facts.",
    topic: 'idioms',
  },
  {
    id: 'c1-049',
    prompt: 'The two theories are fundamentally ____ to each other.',
    options: ['opposed', 'opposite of', 'against', 'contrary of'],
    correctIndex: 0,
    explanation:
      "Things are 'opposed to' one another. 'Contrary to' also works, but not 'contrary of'.",
    topic: 'prepositions',
  },
  {
    id: 'c1-050',
    prompt: 'His remarks were widely seen as an attempt to ____ the issue.',
    options: ['downplay', 'downfall', 'downturn', 'download'],
    correctIndex: 0,
    explanation: "'Downplay' means to make something seem less important than it is.",
    topic: 'vocabulary',
  },
  {
    id: 'c1-051',
    prompt: 'The plan fell ____ at the last minute due to a lack of funds.',
    options: ['through', 'down', 'apart of', 'off'],
    correctIndex: 0,
    explanation: "'Fall through' means to fail to happen after being planned.",
    topic: 'phrasal-verbs',
  },
  {
    id: 'c1-052',
    prompt: 'She is widely ____ as the leading expert in the field.',
    options: ['regarded', 'regard', 'regards', 'regarding'],
    correctIndex: 0,
    explanation:
      "The collocation is 'be regarded as' something. Here it is passive: is regarded as.",
    topic: 'collocations',
  },
  {
    id: 'c1-053',
    prompt: 'The data, ____ which the theory rests, is now in doubt.',
    options: ['on', 'in', 'at', 'of'],
    correctIndex: 0,
    explanation: "A theory 'rests on' evidence, so the relative clause keeps the preposition 'on'.",
    topic: 'prepositions',
  },
  {
    id: 'c1-054',
    prompt: 'He gave a ____ account of the events, leaving nothing out.',
    options: ['comprehensive', 'comprehensible', 'compulsive', 'compelling'],
    correctIndex: 0,
    explanation: "'Comprehensive' means complete. 'Comprehensible' means able to be understood.",
    topic: 'confusing-pairs',
  },
  {
    id: 'c1-055',
    prompt: 'The team worked hard to ____ the gap between the two designs.',
    options: ['bridge', 'build', 'break', 'bury'],
    correctIndex: 0,
    explanation: "The collocation is 'bridge the gap', meaning to reduce a difference.",
    topic: 'collocations',
  },
  {
    id: 'c1-056',
    prompt: 'Such ____ his confidence that he never doubted the outcome.',
    options: ['was', 'is', 'had', 'did'],
    correctIndex: 0,
    explanation: "Fronting 'Such' inverts the verb: Such was his confidence that ...",
    topic: 'grammar',
  },
  {
    id: 'c1-057',
    prompt: 'The reforms are intended to ____ economic growth.',
    options: ['spur', 'spurn', 'sprout', 'spare'],
    correctIndex: 0,
    explanation: "'Spur' means to encourage or stimulate. 'Spurn' means to reject.",
    topic: 'vocabulary',
  },
  {
    id: 'c1-058',
    prompt: "We will have to ____ for the shortfall in next year's budget.",
    options: ['make up', 'make out', 'make off', 'make over'],
    correctIndex: 0,
    explanation: "'Make up for' something means to compensate for it.",
    topic: 'phrasal-verbs',
  },
  {
    id: 'c1-059',
    prompt: 'The witness was reluctant to ____ blame on anyone.',
    options: ['apportion', 'appoint', 'appraise', 'apprise'],
    correctIndex: 0,
    explanation: "'Apportion blame' means to assign responsibility for something.",
    topic: 'collocations',
  },
  {
    id: 'c1-060',
    prompt: 'The decision is contingent ____ approval from the board.',
    options: ['on', 'of', 'to', 'with'],
    correctIndex: 0,
    explanation: "Something is 'contingent on' something else, meaning it depends on it.",
    topic: 'prepositions',
  },
];
