/**
 * A1 (beginner) English quiz questions.
 *
 * These target absolute beginners: everyday vocabulary, the verb "to be",
 * simple present, basic articles, plurals, and the most common prepositions.
 * Each question is a short, self-contained sentence with one blank.
 *
 * Answer indices are 0-based. Keep explanations under 200 characters so they
 * fit Telegram's quiz explanation limit.
 */
import type { QuizQuestion } from '../types';

export const a1Questions: QuizQuestion[] = [
  {
    id: 'a1-001',
    prompt: "I'm thirsty. Can I have a glass of ____, please?",
    options: ['bread', 'water', 'paper', 'wood'],
    correctIndex: 1,
    explanation:
      "You drink water when you're thirsty. Bread is food; paper and wood are not drinks.",
    topic: 'vocabulary',
  },
  {
    id: 'a1-002',
    prompt: 'She ____ a teacher.',
    options: ['am', 'is', 'are', 'be'],
    correctIndex: 1,
    explanation: "With he/she/it we use 'is'. Use 'am' with I, and 'are' with you/we/they.",
    topic: 'grammar',
  },
  {
    id: 'a1-003',
    prompt: 'The book is ____ the table.',
    options: ['in', 'at', 'on', 'of'],
    correctIndex: 2,
    explanation: "We use 'on' for a surface: on the table, on the wall, on the floor.",
    topic: 'prepositions',
  },
  {
    id: 'a1-004',
    prompt: 'We sleep in a ____.',
    options: ['bed', 'plate', 'door', 'spoon'],
    correctIndex: 0,
    explanation: 'You sleep in a bed. A plate holds food and a spoon is for eating.',
    topic: 'vocabulary',
  },
  {
    id: 'a1-005',
    prompt: 'There are three ____ on the table.',
    options: ['a book', 'book', 'books', 'bookes'],
    correctIndex: 2,
    explanation: 'After a number greater than one we use the plural: three books.',
    topic: 'grammar',
  },
  {
    id: 'a1-006',
    prompt: "I get up ____ 7 o'clock.",
    options: ['in', 'on', 'at', 'to'],
    correctIndex: 2,
    explanation: "We use 'at' with clock times: at 7 o'clock, at noon, at midnight.",
    topic: 'prepositions',
  },
  {
    id: 'a1-007',
    prompt: "It's cold today, so put on your ____.",
    options: ['coat', 'cup', 'lamp', 'fork'],
    correctIndex: 0,
    explanation: "A coat is warm clothing you wear when it's cold.",
    topic: 'vocabulary',
  },
  {
    id: 'a1-008',
    prompt: 'We have ____ apple and two oranges.',
    options: ['a', 'an', 'the', 'some'],
    correctIndex: 1,
    explanation:
      "Use 'an' before a vowel sound: an apple. Use 'a' before a consonant sound: a banana.",
    topic: 'grammar',
  },
  {
    id: 'a1-009',
    prompt: "Let's eat. I'm very ____.",
    options: ['tall', 'blue', 'hungry', 'open'],
    correctIndex: 2,
    explanation: 'When you want to eat, you are hungry. (When you want to drink, you are thirsty.)',
    topic: 'vocabulary',
  },
  {
    id: 'a1-010',
    prompt: 'My birthday is ____ June.',
    options: ['on', 'at', 'in', 'by'],
    correctIndex: 2,
    explanation: "We use 'in' with months and years: in June, in 2025.",
    topic: 'prepositions',
  },
  {
    id: 'a1-011',
    prompt: 'I ____ coffee every morning.',
    options: ['drinks', 'drinking', 'drink', 'drank'],
    correctIndex: 2,
    explanation: "With 'I' the present simple uses the base verb: I drink. Only he/she/it adds -s.",
    topic: 'grammar',
  },
  {
    id: 'a1-012',
    prompt: 'The ____ is yellow and gives us light during the day.',
    options: ['sun', 'moon', 'rain', 'snow'],
    correctIndex: 0,
    explanation: 'The sun shines during the day. The moon comes out at night.',
    topic: 'vocabulary',
  },
  {
    id: 'a1-013',
    prompt: 'A doctor works in a ____.',
    options: ['school', 'hospital', 'kitchen', 'garden'],
    correctIndex: 1,
    explanation: 'Doctors work in a hospital. A teacher works in a school.',
    topic: 'vocabulary',
  },
  {
    id: 'a1-014',
    prompt: 'He ____ like vegetables.',
    options: ["don't", "doesn't", "isn't", 'not'],
    correctIndex: 1,
    explanation:
      "For he/she/it the negative present simple is 'doesn't' + base verb: He doesn't like.",
    topic: 'grammar',
  },
  {
    id: 'a1-015',
    prompt: "The cat is ____ the box. You can't see it!",
    options: ['on', 'under', 'in', 'at'],
    correctIndex: 2,
    explanation: "If the cat is inside the box, we use 'in'. 'On the box' means on top of it.",
    topic: 'prepositions',
  },
  {
    id: 'a1-016',
    prompt: 'I write with a ____.',
    options: ['cup', 'sock', 'pen', 'clock'],
    correctIndex: 2,
    explanation: 'You write with a pen (or a pencil). A cup holds drinks.',
    topic: 'vocabulary',
  },
  {
    id: 'a1-017',
    prompt: '____ you from Spain?',
    options: ['Is', 'Am', 'Do', 'Are'],
    correctIndex: 3,
    explanation: "We ask about 'you' with 'Are': Are you from Spain?",
    topic: 'grammar',
  },
  {
    id: 'a1-018',
    prompt: 'My mother and father are my ____.',
    options: ['teachers', 'parents', 'friends', 'doctors'],
    correctIndex: 1,
    explanation: 'Your mother and father together are your parents.',
    topic: 'vocabulary',
  },
  {
    id: 'a1-019',
    prompt: 'I go ____ school every day.',
    options: ['to', 'at', 'in', 'on'],
    correctIndex: 0,
    explanation: "We use 'to' for movement towards a place: go to school, go to work.",
    topic: 'prepositions',
  },
  {
    id: 'a1-020',
    prompt: 'Look! The baby ____ now.',
    options: ['sleeps', 'is sleeping', 'sleep', 'sleeping'],
    correctIndex: 1,
    explanation: 'For something happening right now we use the present continuous: is + verb-ing.',
    topic: 'grammar',
  },
  {
    id: 'a1-021',
    prompt: 'We read a ____ before going to sleep.',
    options: ['book', 'fork', 'clock', 'shoe'],
    correctIndex: 0,
    explanation: 'You read a book. A fork is for eating and a clock shows the time.',
    topic: 'vocabulary',
  },
  {
    id: 'a1-022',
    prompt: 'There ____ a cat in the garden.',
    options: ['are', 'is', 'have', 'be'],
    correctIndex: 1,
    explanation: "Use 'there is' with one (singular) thing. Use 'there are' for plurals.",
    topic: 'grammar',
  },
  {
    id: 'a1-023',
    prompt: 'The picture is ____ the wall.',
    options: ['in', 'at', 'on', 'to'],
    correctIndex: 2,
    explanation: "A picture touches the surface of the wall, so we use 'on the wall'.",
    topic: 'prepositions',
  },
  {
    id: 'a1-024',
    prompt: 'A cat has four ____.',
    options: ['doors', 'legs', 'cars', 'names'],
    correctIndex: 1,
    explanation: 'Animals like cats walk on their legs. A cat has four of them.',
    topic: 'vocabulary',
  },
  {
    id: 'a1-025',
    prompt: 'I can ____ very fast.',
    options: ['running', 'runs', 'run', 'ran'],
    correctIndex: 2,
    explanation: "After 'can' we use the base verb with no -s and no -ing: can run.",
    topic: 'grammar',
  },
  {
    id: 'a1-026',
    prompt: "Close the ____, it's noisy outside.",
    options: ['window', 'water', 'apple', 'hand'],
    correctIndex: 0,
    explanation: 'You open and close a window. The other words are not things you close.',
    topic: 'vocabulary',
  },
  {
    id: 'a1-027',
    prompt: 'This is ____ book, not yours.',
    options: ['I', 'me', 'my', 'mine'],
    correctIndex: 2,
    explanation: "Before a noun we use a possessive adjective: my book. 'Mine' stands alone.",
    topic: 'grammar',
  },
  {
    id: 'a1-028',
    prompt: 'She lives ____ London.',
    options: ['at', 'in', 'on', 'to'],
    correctIndex: 1,
    explanation: "We use 'in' with cities and countries: in London, in Brazil.",
    topic: 'prepositions',
  },
  {
    id: 'a1-029',
    prompt: "I'm tired. I want to ____.",
    options: ['eat', 'sleep', 'run', 'jump'],
    correctIndex: 1,
    explanation: 'When you are tired, you want to sleep (rest). The other words need energy.',
    topic: 'vocabulary',
  },
  {
    id: 'a1-030',
    prompt: 'They ____ happy today.',
    options: ['is', 'am', 'are', 'be'],
    correctIndex: 2,
    explanation: "With 'they' (and you/we) we use 'are': They are happy.",
    topic: 'grammar',
  },
  {
    id: 'a1-031',
    prompt: 'A ____ gives us milk.',
    options: ['dog', 'cow', 'cat', 'fish'],
    correctIndex: 1,
    explanation: 'A cow gives us milk. Dogs, cats and fish do not.',
    topic: 'vocabulary',
  },
  {
    id: 'a1-032',
    prompt: 'I ____ from Egypt.',
    options: ['is', 'are', 'be', 'am'],
    correctIndex: 3,
    explanation: "With 'I' we use 'am': I am from Egypt.",
    topic: 'grammar',
  },
  {
    id: 'a1-033',
    prompt: 'We wash our hands with ____ and water.',
    options: ['soap', 'sand', 'milk', 'sugar'],
    correctIndex: 0,
    explanation: 'We use soap and water to wash. Sand, milk and sugar do not clean hands.',
    topic: 'vocabulary',
  },
  {
    id: 'a1-034',
    prompt: 'The cat is ____ the box.',
    options: ['on', 'in', 'at', 'to'],
    correctIndex: 1,
    explanation: "We use 'in' for inside something: in the box, in the room.",
    topic: 'prepositions',
  },
  {
    id: 'a1-035',
    prompt: 'She has two ____.',
    options: ['child', 'childs', 'children', 'childes'],
    correctIndex: 2,
    explanation: "The plural of 'child' is 'children', an irregular plural.",
    topic: 'grammar',
  },
  {
    id: 'a1-036',
    prompt: 'Look ____ the board, please.',
    options: ['at', 'in', 'of', 'to'],
    correctIndex: 0,
    explanation: "We 'look at' something: look at the board, look at me.",
    topic: 'prepositions',
  },
  {
    id: 'a1-037',
    prompt: 'I ____ up at seven every morning.',
    options: ['get', 'make', 'do', 'take'],
    correctIndex: 0,
    explanation: "'Get up' means to leave your bed. We get up in the morning.",
    topic: 'phrasal-verbs',
  },
  {
    id: 'a1-038',
    prompt: 'We keep food cold in the ____.',
    options: ['oven', 'fridge', 'sink', 'sofa'],
    correctIndex: 1,
    explanation: 'A fridge keeps food cold. An oven makes food hot.',
    topic: 'vocabulary',
  },
  {
    id: 'a1-039',
    prompt: 'He ____ football on Sundays.',
    options: ['play', 'plays', 'playing', 'played'],
    correctIndex: 1,
    explanation: 'With he/she/it in the present simple we add -s: he plays.',
    topic: 'grammar',
  },
  {
    id: 'a1-040',
    prompt: 'My birthday is ____ June.',
    options: ['on', 'at', 'in', 'to'],
    correctIndex: 2,
    explanation: "We use 'in' with months: in June, in winter.",
    topic: 'prepositions',
  },
  {
    id: 'a1-041',
    prompt: "Please ____ the door; it's cold.",
    options: ['open', 'close', 'jump', 'sing'],
    correctIndex: 1,
    explanation: "'Close' the door to stop the cold air. 'Open' does the opposite.",
    topic: 'vocabulary',
  },
  {
    id: 'a1-042',
    prompt: 'There are too ____ people on the bus.',
    options: ['much', 'many', 'lot', 'more'],
    correctIndex: 1,
    explanation: "Use 'many' with countable plurals (people). Use 'much' with uncountables.",
    topic: 'confusing-pairs',
  },
  {
    id: 'a1-043',
    prompt: 'She is ____ engineer.',
    options: ['a', 'an', 'the', 'some'],
    correctIndex: 1,
    explanation: "Use 'an' before a vowel sound: an engineer, an apple.",
    topic: 'grammar',
  },
  {
    id: 'a1-044',
    prompt: 'A doctor works in a ____.',
    options: ['school', 'hospital', 'farm', 'garage'],
    correctIndex: 1,
    explanation: 'Doctors work in a hospital. Teachers work in a school.',
    topic: 'vocabulary',
  },
  {
    id: 'a1-045',
    prompt: 'They ____ a big house.',
    options: ['has', 'have', 'haves', 'having'],
    correctIndex: 1,
    explanation: "With they/we/you/I we use 'have'. 'Has' is for he/she/it.",
    topic: 'grammar',
  },
  {
    id: 'a1-046',
    prompt: 'The picture is ____ the wall.',
    options: ['in', 'on', 'at', 'of'],
    correctIndex: 1,
    explanation: "We use 'on' for a surface like a wall: on the wall.",
    topic: 'prepositions',
  },
  {
    id: 'a1-047',
    prompt: "Please ____ on your coat; it's cold outside.",
    options: ['put', 'take', 'get', 'give'],
    correctIndex: 0,
    explanation: "'Put on' means to dress yourself: put on a coat. 'Take off' is the opposite.",
    topic: 'phrasal-verbs',
  },
  {
    id: 'a1-048',
    prompt: 'The day after Monday is ____.',
    options: ['Sunday', 'March', 'Friday', 'Tuesday'],
    correctIndex: 3,
    explanation: 'Tuesday comes after Monday. March is a month, not a day.',
    topic: 'vocabulary',
  },
  {
    id: 'a1-049',
    prompt: '____ shoes are new.',
    options: ['This', 'These', 'That', 'It'],
    correctIndex: 1,
    explanation: "Use 'these' for plural things near you: these shoes. 'This' is singular.",
    topic: 'grammar',
  },
  {
    id: 'a1-050',
    prompt: 'We tell the time with a ____.',
    options: ['clock', 'chair', 'plate', 'shoe'],
    correctIndex: 0,
    explanation: 'A clock shows the time.',
    topic: 'vocabulary',
  },
  {
    id: 'a1-051',
    prompt: 'I go to school ____ bus.',
    options: ['by', 'on', 'in', 'with'],
    correctIndex: 0,
    explanation: "We use 'by' for transport: by bus, by car, by train.",
    topic: 'prepositions',
  },
  {
    id: 'a1-052',
    prompt: "I'd like ____ orange, please.",
    options: ['a', 'an', 'the', 'one'],
    correctIndex: 1,
    explanation: "Use 'an' before a vowel sound: an orange.",
    topic: 'confusing-pairs',
  },
  {
    id: 'a1-053',
    prompt: '____ you swim?',
    options: ['Do', 'Are', 'Can', 'Is'],
    correctIndex: 2,
    explanation: "Use 'Can' to ask about ability: Can you swim?",
    topic: 'grammar',
  },
  {
    id: 'a1-054',
    prompt: 'Take an umbrella; it is ____.',
    options: ['sunny', 'raining', 'dry', 'warm'],
    correctIndex: 1,
    explanation: 'You need an umbrella when it is raining.',
    topic: 'vocabulary',
  },
  {
    id: 'a1-055',
    prompt: 'Please ____ off your shoes at the door.',
    options: ['take', 'put', 'get', 'look'],
    correctIndex: 0,
    explanation: "'Take off' means to remove: take off your shoes. 'Put on' is the opposite.",
    topic: 'phrasal-verbs',
  },
  {
    id: 'a1-056',
    prompt: '____ a cat in the garden.',
    options: ['There is', 'There are', 'It has', 'They are'],
    correctIndex: 0,
    explanation: "Use 'There is' for one thing: There is a cat. 'There are' is for plurals.",
    topic: 'grammar',
  },
  {
    id: 'a1-057',
    prompt: 'We read a ____ before we sleep.',
    options: ['book', 'spoon', 'door', 'sock'],
    correctIndex: 0,
    explanation: 'We read a book.',
    topic: 'vocabulary',
  },
  {
    id: 'a1-058',
    prompt: 'The shop is open ____ Monday to Friday.',
    options: ['from', 'in', 'at', 'of'],
    correctIndex: 0,
    explanation: "We use 'from ... to ...' for a range: from Monday to Friday.",
    topic: 'prepositions',
  },
  {
    id: 'a1-059',
    prompt: 'She ____ tea every morning.',
    options: ['drink', 'drinks', 'drinking', 'drank'],
    correctIndex: 1,
    explanation: "Present simple with 'she' takes -s: she drinks.",
    topic: 'grammar',
  },
  {
    id: 'a1-060',
    prompt: "The opposite of 'hot' is ____.",
    options: ['warm', 'cold', 'big', 'fast'],
    correctIndex: 1,
    explanation: "'Cold' is the opposite of 'hot'.",
    topic: 'vocabulary',
  },
];
