/**
 * C2 (mastery) English quiz questions.
 *
 * The finishing polish: sophisticated vocabulary, precise idioms, advanced
 * collocations, and the notorious confusing pairs (flout/flaunt, elicit/illicit,
 * principle/principal) that distinguish a near-native from a native speaker.
 *
 * Answer indices are 0-based. Keep explanations under 200 characters so they
 * fit Telegram's quiz explanation limit.
 */
import type { QuizQuestion } from '../types';

export const c2Questions: QuizQuestion[] = [
  {
    id: 'c2-001',
    prompt: "The CEO's sudden resignation really threw a ____ in the works.",
    options: ['wheel', 'spanner', 'stone', 'rope'],
    correctIndex: 1,
    explanation: "'Throw a spanner in the works' (US: wrench) means to disrupt a plan or process.",
    topic: 'idioms',
  },
  {
    id: 'c2-002',
    prompt: 'His ____ speech won over even the most sceptical members of the crowd.',
    options: ['garrulous', 'eloquent', 'verbose', 'taciturn'],
    correctIndex: 1,
    explanation:
      "'Eloquent' means fluent and persuasive. 'Garrulous' and 'verbose' mean wordy; 'taciturn' means silent.",
    topic: 'vocabulary',
  },
  {
    id: 'c2-003',
    prompt: "The teacher's vague question failed to ____ any response from the class.",
    options: ['illicit', 'elicit', 'solicit', 'explicit'],
    correctIndex: 1,
    explanation:
      "'Elicit' (verb) means to draw out a response. 'Illicit' is an adjective meaning illegal.",
    topic: 'confusing-pairs',
  },
  {
    id: 'c2-004',
    prompt: "Once you've signed the contract, there's no going back, the die is ____.",
    options: ['thrown', 'cast', 'set', 'rolled'],
    correctIndex: 1,
    explanation: "'The die is cast' means a decision has been made that cannot be undone.",
    topic: 'idioms',
  },
  {
    id: 'c2-005',
    prompt: 'He openly ____ the rules whenever it suited him, daring anyone to object.',
    options: ['flaunted', 'flouted', 'flounted', 'floundered'],
    correctIndex: 1,
    explanation:
      "'Flout' means to openly disregard a rule. Don't confuse it with 'flaunt' (to show off).",
    topic: 'confusing-pairs',
  },
  {
    id: 'c2-006',
    prompt: 'The findings ____ serious questions about the safety of the drug.',
    options: ['rise', 'raise', 'arise', 'lift'],
    correctIndex: 1,
    explanation: "You 'raise questions' (transitive). Questions themselves 'arise' (intransitive).",
    topic: 'collocations',
  },
  {
    id: 'c2-007',
    prompt: 'She loves to ____ her wealth, arriving at every event in a new sports car.',
    options: ['flout', 'flaunt', 'flounder', 'flank'],
    correctIndex: 1,
    explanation:
      "'Flaunt' means to show off. Its tricky twin 'flout' means to openly break a rule.",
    topic: 'confusing-pairs',
  },
  {
    id: 'c2-008',
    prompt: 'He took her glowing review with a pinch of ____, knowing she was his friend.',
    options: ['sugar', 'salt', 'pepper', 'spice'],
    correctIndex: 1,
    explanation: "'Take it with a pinch of salt' means not to accept something as completely true.",
    topic: 'idioms',
  },
  {
    id: 'c2-009',
    prompt: 'The lecture was so ____ that half the audience quietly dozed off.',
    options: ['riveting', 'soporific', 'gripping', 'engaging'],
    correctIndex: 1,
    explanation: "'Soporific' means tending to cause sleep. The other three all mean fascinating.",
    topic: 'vocabulary',
  },
  {
    id: 'c2-010',
    prompt: "The relentless drought ____ havoc on the region's harvest.",
    options: ['made', 'wreaked', 'did', 'caused'],
    correctIndex: 1,
    explanation: "The fixed collocation is 'wreak havoc', to cause great damage or chaos.",
    topic: 'collocations',
  },
  {
    id: 'c2-011',
    prompt: 'She resigned on ____, for her it was purely a matter of ethics.',
    options: ['principal', 'principle', 'principled', 'principals'],
    correctIndex: 1,
    explanation: "'Principle' (noun) is a moral rule. 'Principal' means main, or a head teacher.",
    topic: 'confusing-pairs',
  },
  {
    id: 'c2-012',
    prompt: 'His sharp eye and ____ for detail made him a superb editor.',
    options: ['penchant', 'aversion', 'indifference', 'reluctance'],
    correctIndex: 0,
    explanation:
      "A 'penchant for' something is a strong liking. The other options all suggest dislike or avoidance.",
    topic: 'vocabulary',
  },
  {
    id: 'c2-013',
    prompt: 'The defence lawyer could not refute the ____ evidence against her client.',
    options: ['damping', 'dawning', 'dimming', 'damning'],
    correctIndex: 3,
    explanation:
      "'Damning' evidence strongly proves guilt or fault. The look-alikes are unrelated.",
    topic: 'vocabulary',
  },
  {
    id: 'c2-014',
    prompt: 'After months of struggle, we can finally see ____ at the end of the tunnel.',
    options: ['light', 'hope', 'sun', 'fire'],
    correctIndex: 0,
    explanation: "'Light at the end of the tunnel' is the sign that a hard time is nearly over.",
    topic: 'idioms',
  },
  {
    id: 'c2-015',
    prompt: 'Her ____ wit made even the dullest meeting a pleasure.',
    options: ['acerbic', 'dull', 'blunt', 'vague'],
    correctIndex: 0,
    explanation:
      "'Acerbic' wit is sharp and clever (sometimes cutting). The others are the opposite.",
    topic: 'vocabulary',
  },
  {
    id: 'c2-016',
    prompt: 'His years of patient research finally ____ dividends.',
    options: ['gave', 'made', 'paid', 'did'],
    correctIndex: 2,
    explanation:
      "'Pay dividends' is an idiom meaning to bring benefits later, thanks to earlier effort.",
    topic: 'collocations',
  },
  {
    id: 'c2-017',
    prompt: 'The two sides eventually reached an ____ agreement and shook hands.',
    options: ['amicable', 'amenable', 'ample', 'amorous'],
    correctIndex: 0,
    explanation:
      "An 'amicable' agreement is a friendly, good-natured one. The others mean different things.",
    topic: 'confusing-pairs',
  },
  {
    id: 'c2-018',
    prompt: "The lawyer's clever reply took the wind out of her opponent's ____.",
    options: ['wings', 'feathers', 'wheels', 'sails'],
    correctIndex: 3,
    explanation:
      "'Take the wind out of someone's sails' means to weaken their confidence or advantage.",
    topic: 'idioms',
  },
  {
    id: 'c2-019',
    prompt: "The ancient diary's faded handwriting was almost ____.",
    options: ['legible', 'illegible', 'eligible', 'ineligible'],
    correctIndex: 1,
    explanation: "'Illegible' means impossible to read. 'Eligible' means qualified or allowed.",
    topic: 'confusing-pairs',
  },
  {
    id: 'c2-020',
    prompt: 'Seldom ____ such a gifted group of young musicians in one place.',
    options: ['we see', 'do we see', 'we saw', 'did we saw'],
    correctIndex: 1,
    explanation: "After 'seldom' at the start, we invert with the auxiliary: do we see.",
    topic: 'grammar',
  },
  {
    id: 'c2-021',
    prompt: "The audit ____ bare the company's deep financial problems.",
    options: ['made', 'did', 'laid', 'set'],
    correctIndex: 2,
    explanation:
      "'Lay bare' means to reveal or expose something hidden. The past of 'lay' is 'laid'.",
    topic: 'collocations',
  },
  {
    id: 'c2-022',
    prompt: 'She was ____ to the committee as its youngest ever chairperson.',
    options: ['appointed', 'anointed', 'pointed', 'annotated'],
    correctIndex: 0,
    explanation:
      "'Appoint' means to officially give someone a job or role. The others are unrelated.",
    topic: 'vocabulary',
  },
  {
    id: 'c2-023',
    prompt: 'He has a finger in every ____, involved in half the businesses in town.',
    options: ['cake', 'plate', 'dish', 'pie'],
    correctIndex: 3,
    explanation: "'A finger in every pie' means being involved in many activities at once.",
    topic: 'idioms',
  },
  {
    id: 'c2-024',
    prompt: 'His ____ kindness amazed those who only knew his stern reputation.',
    options: ['uncharacteristic', 'characteristic', 'typical', 'habitual'],
    correctIndex: 0,
    explanation:
      "'Uncharacteristic' means not typical of someone. The other three mean the opposite.",
    topic: 'vocabulary',
  },
  {
    id: 'c2-025',
    prompt: "Don't count your ____ before they hatch.",
    options: ['chickens', 'eggs', 'birds', 'profits'],
    correctIndex: 0,
    explanation: 'This idiom warns against assuming success before it actually happens.',
    topic: 'idioms',
  },
  {
    id: 'c2-026',
    prompt: 'Years of careful pruning finally made the old orchard ____ fruit again.',
    options: ['bear', 'carry', 'hold', 'make'],
    correctIndex: 0,
    explanation: "'Bear fruit' means to produce good results. It works literally and figuratively.",
    topic: 'collocations',
  },
  {
    id: 'c2-027',
    prompt: 'His speech was a tired ____ of clichés and empty promises.',
    options: ['litany', 'melody', 'harmony', 'symphony'],
    correctIndex: 0,
    explanation:
      "A 'litany of' something is a long, tedious list of it (complaints, clichés, excuses).",
    topic: 'vocabulary',
  },
  {
    id: 'c2-028',
    prompt: 'The two explanations are not mutually ____; both could be true.',
    options: ['exclusive', 'inclusive', 'conclusive', 'reclusive'],
    correctIndex: 0,
    explanation: "'Mutually exclusive' means two things cannot both be true at once.",
    topic: 'confusing-pairs',
  },
  {
    id: 'c2-029',
    prompt: 'With the project finished, the whole team was at a ____ end.',
    options: ['loose', 'dead', 'far', 'tight'],
    correctIndex: 0,
    explanation: "'At a loose end' means having nothing in particular to do.",
    topic: 'idioms',
  },
  {
    id: 'c2-030',
    prompt: 'Were it not ____ your support, the project would have collapsed.',
    options: ['for', 'of', 'to', 'with'],
    correctIndex: 0,
    explanation: "'Were it not for' is a formal way to say 'if it had not been for'.",
    topic: 'grammar',
  },
  {
    id: 'c2-031',
    prompt: 'The critics praised the novel for its ____ prose.',
    options: ['scathing', 'scattering', 'scalding', 'scintillating'],
    correctIndex: 3,
    explanation: "'Scintillating' means brilliantly clever. 'Scathing' means harshly critical.",
    topic: 'vocabulary',
  },
  {
    id: 'c2-032',
    prompt: 'His support for the policy was, at best, ____.',
    options: ['lukewarm', 'red-hot', 'boiling', 'scalding'],
    correctIndex: 0,
    explanation: "'Lukewarm' means showing little enthusiasm, neither warm nor cold.",
    topic: 'vocabulary',
  },
  {
    id: 'c2-033',
    prompt: 'The minister tried to ____ the difficult question with a joke.',
    options: ['inflect', 'reflect', 'deflect', 'genuflect'],
    correctIndex: 2,
    explanation: "'Deflect' means to turn something aside, here to avoid answering.",
    topic: 'vocabulary',
  },
  {
    id: 'c2-034',
    prompt: 'Her account of events was at ____ with the official record.',
    options: ['odds', 'ends', 'sea', 'large'],
    correctIndex: 0,
    explanation: "'At odds with' means in conflict or disagreement with.",
    topic: 'idioms',
  },
  {
    id: 'c2-035',
    prompt: 'The proposal was rejected, ____ the objections of the finance team.',
    options: ['because', 'due of', 'thanks of', 'owing to'],
    correctIndex: 3,
    explanation: "'Owing to' means because of. 'Because' alone needs a full clause after it.",
    topic: 'grammar',
  },
  {
    id: 'c2-036',
    prompt: 'The committee gave the plan its ____ approval.',
    options: ['tacit', 'tactful', 'tactile', 'taciturn'],
    correctIndex: 0,
    explanation:
      "'Tacit' means understood without being stated. 'Taciturn' means reserved in speech.",
    topic: 'vocabulary',
  },
  {
    id: 'c2-037',
    prompt: 'The two accounts are difficult to ____.',
    options: ['reconsider', 'reconvene', 'reconcile', 'reconstruct'],
    correctIndex: 2,
    explanation: "To 'reconcile' two accounts is to make them consistent with each other.",
    topic: 'vocabulary',
  },
  {
    id: 'c2-038',
    prompt: 'He spoke with such ____ that the audience was spellbound.',
    options: ['eloquence', 'elegance', 'eloquent', 'elope'],
    correctIndex: 0,
    explanation:
      "'Eloquence' is the noun for fluent, persuasive speech. 'Eloquent' is the adjective.",
    topic: 'confusing-pairs',
  },
  {
    id: 'c2-039',
    prompt: "The new evidence ____ the prosecution's entire case.",
    options: ['underlined', 'undertook', 'underwent', 'undermined'],
    correctIndex: 3,
    explanation: "'Undermine' means to weaken gradually. 'Underline' means to emphasise.",
    topic: 'vocabulary',
  },
  {
    id: 'c2-040',
    prompt: 'Their differences were, in the end, more apparent than ____.',
    options: ['real', 'really', 'reality', 'realistic'],
    correctIndex: 0,
    explanation: "'More apparent than real' is a set phrase: seeming greater than they truly are.",
    topic: 'idioms',
  },
  {
    id: 'c2-041',
    prompt: 'Not for one moment ____ the truth of her story.',
    options: ['I doubted', 'did I doubt', 'I did doubt', 'doubted I'],
    correctIndex: 1,
    explanation: 'A fronted negative phrase forces inversion: did I doubt.',
    topic: 'grammar',
  },
  {
    id: 'c2-042',
    prompt: 'The report is a ____ of half-truths and speculation.',
    options: ['hotchpotch', 'hopscotch', 'hodgepodge of', 'patchwork of'],
    correctIndex: 0,
    explanation: "A 'hotchpotch' is a confused mixture. 'Hopscotch' is a children's game.",
    topic: 'vocabulary',
  },
  {
    id: 'c2-043',
    prompt: 'She has an ____ grasp of the subject, missing no detail.',
    options: ['episodic', 'encyclopaedia', 'encyclopaedic', 'epidemic'],
    correctIndex: 2,
    explanation: "'Encyclopaedic' knowledge is comprehensive and detailed.",
    topic: 'vocabulary',
  },
  {
    id: 'c2-044',
    prompt: 'The deal fell apart, and with it ____ any hope of a merger.',
    options: ['went', 'gone', 'going', 'goes'],
    correctIndex: 0,
    explanation:
      "After the fronted adverbial 'with it' the verb comes before the subject: went any hope.",
    topic: 'grammar',
  },
  {
    id: 'c2-045',
    prompt: 'The author has a tendency to ____ rather than to argue.',
    options: ['precipitate', 'punctuate', 'percolate', 'pontificate'],
    correctIndex: 3,
    explanation: "'Pontificate' means to express opinions in a pompous, dogmatic way.",
    topic: 'vocabulary',
  },
  {
    id: 'c2-046',
    prompt: 'The policy is a ____ for disaster, given the current climate.',
    options: ['recipe', 'receipt', 'reception', 'recipient'],
    correctIndex: 0,
    explanation: "'A recipe for disaster' is an idiom: something likely to go badly wrong.",
    topic: 'idioms',
  },
  {
    id: 'c2-047',
    prompt: 'The negotiations were conducted ____ closed doors.',
    options: ['beneath', 'beyond', 'behind', 'between'],
    correctIndex: 2,
    explanation: "'Behind closed doors' means in private, away from public view.",
    topic: 'idioms',
  },
  {
    id: 'c2-048',
    prompt: 'His theory, ____ elegant, fails to account for the data.',
    options: ['however', 'whatever', 'whenever', 'moreover'],
    correctIndex: 0,
    explanation: "'However elegant' concedes a point: no matter how elegant it is.",
    topic: 'grammar',
  },
  {
    id: 'c2-049',
    prompt: 'The board moved to ____ the rogue executive.',
    options: ['oaf', 'oun', 'oath', 'oust'],
    correctIndex: 3,
    explanation: "'Oust' means to force someone out of a position of power.",
    topic: 'vocabulary',
  },
  {
    id: 'c2-050',
    prompt: 'The findings ____ serious questions about the method.',
    options: ['raise', 'rise', 'arise', 'arouse'],
    correctIndex: 0,
    explanation: "You 'raise questions' (transitive). 'Rise' and 'arise' are intransitive.",
    topic: 'confusing-pairs',
  },
  {
    id: 'c2-051',
    prompt: 'The two policies are not necessarily ____.',
    options: ['incomprehensible', 'incomparable', 'incompatible', 'incontestable'],
    correctIndex: 2,
    explanation:
      "'Incompatible' means unable to coexist. The others mean unmatched, unclear, undeniable.",
    topic: 'confusing-pairs',
  },
  {
    id: 'c2-052',
    prompt: 'The general was determined to ____ the rebellion.',
    options: ['quibble', 'quench', 'quell', 'quaver'],
    correctIndex: 2,
    explanation: "'Quell' means to put an end to, especially by force.",
    topic: 'vocabulary',
  },
  {
    id: 'c2-053',
    prompt: 'Rarely ____ such a compelling performance.',
    options: ['I have seen', 'have I seen', 'I saw', 'seen I have'],
    correctIndex: 1,
    explanation: "After the fronted adverb 'Rarely' we invert: have I seen.",
    topic: 'grammar',
  },
  {
    id: 'c2-054',
    prompt: 'The plan was, by any ____, a remarkable success.',
    options: ['measure', 'measures', 'measuring', 'means of'],
    correctIndex: 0,
    explanation: "'By any measure' is a set phrase meaning by any standard of judgement.",
    topic: 'idioms',
  },
  {
    id: 'c2-055',
    prompt: 'The lecture was so ____ that half the audience fell asleep.',
    options: ['supercilious', 'sophisticated', 'superficial', 'soporific'],
    correctIndex: 3,
    explanation: "'Soporific' means tending to induce sleep.",
    topic: 'vocabulary',
  },
  {
    id: 'c2-056',
    prompt: 'She remained ____ in the face of fierce criticism.',
    options: ['unflappable', 'unflattering', 'unfathomable', 'unfailing'],
    correctIndex: 0,
    explanation: "'Unflappable' means calm and not easily upset in a crisis.",
    topic: 'vocabulary',
  },
  {
    id: 'c2-057',
    prompt: 'The argument ____ on a single, unproven assumption.',
    options: ['harnesses', 'hinders', 'hampers', 'hinges'],
    correctIndex: 3,
    explanation: "Something 'hinges on' a key point, meaning it depends entirely on it.",
    topic: 'collocations',
  },
  {
    id: 'c2-058',
    prompt: 'He delivered the bad news with great ____.',
    options: ['tact', 'tactic', 'tactics', 'contact'],
    correctIndex: 0,
    explanation: "'Tact' is the noun for sensitivity in dealing with others. 'Tactic' is a method.",
    topic: 'confusing-pairs',
  },
  {
    id: 'c2-059',
    prompt: 'The committee chose to ____ judgement until all the facts were in.',
    options: ['reserve', 'preserve', 'conserve', 'observe'],
    correctIndex: 0,
    explanation: "'Reserve judgement' means to delay forming an opinion.",
    topic: 'collocations',
  },
  {
    id: 'c2-060',
    prompt: 'The proposal, ____ its merits, was politically impossible.',
    options: ['whatever', 'however', 'whichever', 'whenever'],
    correctIndex: 0,
    explanation: "'Whatever its merits' concedes the point: no matter what merits it has.",
    topic: 'grammar',
  },
  {
    id: 'c2-061',
    prompt:
      "A few words of genuine ____ at the right moment can change the whole course of someone's life.",
    options: ['discouragement', 'indifference', 'encouragement', 'resentment'],
    correctIndex: 2,
    explanation: "'Encouragement' is support that gives someone confidence and hope.",
    topic: 'vocabulary',
  },
  {
    id: 'c2-062',
    prompt: 'A good teacher knows how to ____ her students up when their confidence is low.',
    options: ['let', 'put', 'turn', 'lift'],
    correctIndex: 3,
    explanation: "'Lift someone up' means to encourage them and raise their spirits.",
    topic: 'phrasal-verbs',
  },
  {
    id: 'c2-063',
    prompt: 'A true friend shows unwavering ____, staying close even when it is inconvenient.',
    options: ['jealousy', 'indifference', 'loyalty', 'rivalry'],
    correctIndex: 2,
    explanation: "'Loyalty' is firm, faithful support for someone over time.",
    topic: 'vocabulary',
  },
  {
    id: 'c2-064',
    prompt: 'Real friends ____ up for each other in hard times, without being asked.',
    options: ['give', 'make', 'back', 'show'],
    correctIndex: 3,
    explanation: "'Show up for someone' means to be present and support them when it matters.",
    topic: 'phrasal-verbs',
  },
];
