/**
 * B1 (intermediate) English quiz questions.
 *
 * This is where many learners plateau, so the focus shifts to the things that
 * make English sound natural: collocations (make a decision, do homework),
 * common phrasal verbs, confusing word pairs, and dependent prepositions.
 *
 * Answer indices are 0-based. Keep explanations under 200 characters so they
 * fit Telegram's quiz explanation limit.
 */
import type { QuizQuestion } from '../types';

export const b1Questions: QuizQuestion[] = [
  {
    id: 'b1-001',
    prompt: 'We need to ____ a decision by Friday.',
    options: ['do', 'make', 'take', 'have'],
    correctIndex: 1,
    explanation: "In English you 'make a decision', not 'do' one. A handy rule: create = make.",
    topic: 'collocations',
  },
  {
    id: 'b1-002',
    prompt: 'We had to ____ the meeting because the manager was ill.',
    options: ['put on', 'put off', 'put up', 'put down'],
    correctIndex: 1,
    explanation: "'Put off' means to postpone (move to a later time). 'Put on' means to wear.",
    topic: 'phrasal-verbs',
  },
  {
    id: 'b1-003',
    prompt: 'There are ____ chairs than we need for the guests.',
    options: ['less', 'fewer', 'least', 'little'],
    correctIndex: 1,
    explanation:
      "Use 'fewer' for countable nouns (chairs) and 'less' for uncountable nouns (water).",
    topic: 'confusing-pairs',
  },
  {
    id: 'b1-004',
    prompt: "She's really good ____ playing the piano.",
    options: ['in', 'on', 'at', 'with'],
    correctIndex: 2,
    explanation: "We're 'good at' an activity or skill: good at maths, good at cooking.",
    topic: 'prepositions',
  },
  {
    id: 'b1-005',
    prompt: 'The medicine had no ____ on his headache at all.',
    options: ['affect', 'effort', 'effect', 'afford'],
    correctIndex: 2,
    explanation: "'Effect' is the noun (the result). 'Affect' is the verb (to influence).",
    topic: 'vocabulary',
  },
  {
    id: 'b1-006',
    prompt: 'I need to ____ my homework before dinner.',
    options: ['make', 'do', 'take', 'have'],
    correctIndex: 1,
    explanation:
      "You 'do homework' (and do the dishes, do exercise). 'Make' is for creating things.",
    topic: 'collocations',
  },
  {
    id: 'b1-007',
    prompt: "I'm trying to ____ sugar this year.",
    options: ['give in', 'give up', 'give out', 'give away'],
    correctIndex: 1,
    explanation: "'Give up' means to stop doing something. 'Give in' means to surrender.",
    topic: 'phrasal-verbs',
  },
  {
    id: 'b1-008',
    prompt: "They're bringing ____ dog to the park.",
    options: ['there', 'their', "they're", 'thier'],
    correctIndex: 1,
    explanation: "'Their' shows possession. 'There' is a place; 'they're' means 'they are'.",
    topic: 'confusing-pairs',
  },
  {
    id: 'b1-009',
    prompt: 'Whether we go out tomorrow depends ____ the weather.',
    options: ['of', 'on', 'from', 'to'],
    correctIndex: 1,
    explanation: "Something 'depends on' another thing, never 'depends of' or 'depends from'.",
    topic: 'prepositions',
  },
  {
    id: 'b1-010',
    prompt: 'Please ____ attention to the safety instructions.',
    options: ['give', 'make', 'pay', 'do'],
    correctIndex: 2,
    explanation: "The set phrase is 'pay attention'. It's an idiom, no money is involved!",
    topic: 'collocations',
  },
  {
    id: 'b1-011',
    prompt: 'We ____ petrol on the motorway and had to walk.',
    options: ['ran into', 'ran over', 'ran out of', 'ran up'],
    correctIndex: 2,
    explanation: "'Run out of' means to have none left. 'Run into' means to meet by chance.",
    topic: 'phrasal-verbs',
  },
  {
    id: 'b1-012',
    prompt: 'Prices have ____ sharply over the last year.',
    options: ['raised', 'risen', 'arose', 'aroused'],
    correctIndex: 1,
    explanation:
      "'Rise' is intransitive (prices rise by themselves). 'Raise' needs an object (raise prices).",
    topic: 'vocabulary',
  },
  {
    id: 'b1-013',
    prompt: 'She always ____ a shower in the morning.',
    options: ['does', 'takes', 'makes', 'gives'],
    correctIndex: 1,
    explanation:
      "You 'take a shower' (or 'have a shower'). 'Make a shower' is not natural English.",
    topic: 'collocations',
  },
  {
    id: 'b1-014',
    prompt: "I'd like some ____ on how to improve my essay.",
    options: ['advise', 'advice', 'advices', 'counsels'],
    correctIndex: 1,
    explanation: "'Advice' is the noun (uncountable, no plural). 'Advise' is the verb.",
    topic: 'confusing-pairs',
  },
  {
    id: 'b1-015',
    prompt: 'I am very interested ____ history.',
    options: ['in', 'on', 'at', 'for'],
    correctIndex: 0,
    explanation: "The fixed phrase is 'interested in' something.",
    topic: 'prepositions',
  },
  {
    id: 'b1-016',
    prompt: 'Please ____ this form and sign at the bottom.',
    options: ['fill in', 'fill up', 'fill off', 'fill over'],
    correctIndex: 0,
    explanation:
      "You 'fill in' (or 'fill out') a form. 'Fill up' is usually for a tank or container.",
    topic: 'phrasal-verbs',
  },
  {
    id: 'b1-017',
    prompt: 'I have known her ____ five years.',
    options: ['since', 'for', 'during', 'ago'],
    correctIndex: 1,
    explanation: "Use 'for' with a length of time (for five years) and 'since' with a start point.",
    topic: 'grammar',
  },
  {
    id: 'b1-018',
    prompt: 'He apologised for the ____ and promised to fix it.',
    options: ['mistake', 'wrong', 'false', 'failure'],
    correctIndex: 0,
    explanation: "'Mistake' is the natural word here. You 'make a mistake' and apologise for it.",
    topic: 'vocabulary',
  },
  {
    id: 'b1-019',
    prompt: 'Can I ____ you a question?',
    options: ['ask', 'make', 'do', 'say'],
    correctIndex: 0,
    explanation: "You 'ask a question'. You do not 'make' or 'do' a question in English.",
    topic: 'collocations',
  },
  {
    id: 'b1-020',
    prompt: 'There is very ____ milk left, so buy some more.',
    options: ['few', 'less', 'little', 'fewer'],
    correctIndex: 2,
    explanation: "Use 'little' with uncountable nouns (milk) and 'few' with countable nouns.",
    topic: 'confusing-pairs',
  },
  {
    id: 'b1-021',
    prompt: 'The car broke ____ on the way to work.',
    options: ['down', 'up', 'off', 'into'],
    correctIndex: 0,
    explanation: "'Break down' means to stop working (a machine). 'Break up' ends a relationship.",
    topic: 'phrasal-verbs',
  },
  {
    id: 'b1-022',
    prompt: 'Thank you ____ your help with the project.',
    options: ['for', 'of', 'about', 'to'],
    correctIndex: 0,
    explanation: "We thank someone 'for' something they did or gave.",
    topic: 'prepositions',
  },
  {
    id: 'b1-023',
    prompt: 'She suggested ____ a taxi instead of walking.',
    options: ['to take', 'taking', 'take', 'we taking'],
    correctIndex: 1,
    explanation: "'Suggest' is followed by the -ing form: suggest taking. (Not 'suggest to take'.)",
    topic: 'grammar',
  },
  {
    id: 'b1-024',
    prompt: 'Let me ____ a quick phone call before we leave.',
    options: ['make', 'do', 'take', 'put'],
    correctIndex: 0,
    explanation: "You 'make a call'. You can also 'give someone a call', meaning the same thing.",
    topic: 'collocations',
  },
  {
    id: 'b1-025',
    prompt: 'It is much colder today ____ it was yesterday.',
    options: ['then', 'than', 'that', 'as'],
    correctIndex: 1,
    explanation: "'Than' is used for comparisons. 'Then' refers to time or what happens next.",
    topic: 'confusing-pairs',
  },
  {
    id: 'b1-026',
    prompt: 'I came ____ an old photo while cleaning the attic.',
    options: ['across', 'after', 'over', 'round'],
    correctIndex: 0,
    explanation: "'Come across' means to find something by chance.",
    topic: 'phrasal-verbs',
  },
  {
    id: 'b1-027',
    prompt: 'The weather is very ____ in spring, sunny then rainy.',
    options: ['changeable', 'changing', 'changed', 'exchangeable'],
    correctIndex: 0,
    explanation: "'Changeable' describes something that changes often and unpredictably.",
    topic: 'vocabulary',
  },
  {
    id: 'b1-028',
    prompt: 'By the time we arrived, the train ____.',
    options: ['left', 'had left', 'has left', 'leaves'],
    correctIndex: 1,
    explanation: "Past perfect ('had left') shows an action finished before another past action.",
    topic: 'grammar',
  },
  {
    id: 'b1-029',
    prompt: 'He is married ____ a doctor.',
    options: ['with', 'to', 'by', 'at'],
    correctIndex: 1,
    explanation: "In English you are 'married to' someone, not 'married with' them.",
    topic: 'prepositions',
  },
  {
    id: 'b1-030',
    prompt: 'We are making good ____ on the new project.',
    options: ['progress', 'progresses', 'advance', 'step'],
    correctIndex: 0,
    explanation: "The collocation is 'make progress'. 'Progress' here is uncountable, so no -s.",
    topic: 'collocations',
  },
  {
    id: 'b1-031',
    prompt: 'I ____ in London for five years now.',
    options: ['live', 'am living', 'lived', 'have lived'],
    correctIndex: 3,
    explanation: 'The present perfect links past to now: have lived (and still live there).',
    topic: 'grammar',
  },
  {
    id: 'b1-032',
    prompt: 'When I was a child, I ____ play in the street.',
    options: ['use to', 'am used to', 'was used to', 'used to'],
    correctIndex: 3,
    explanation: "'Used to' describes a past habit that is no longer true.",
    topic: 'grammar',
  },
  {
    id: 'b1-033',
    prompt: 'Can you ____ me some money until payday?',
    options: ['borrow', 'owe', 'rent', 'lend'],
    correctIndex: 3,
    explanation: "You 'lend' money to someone; you 'borrow' it from someone.",
    topic: 'confusing-pairs',
  },
  {
    id: 'b1-034',
    prompt: 'She told me to ____ up; the test was about to start.',
    options: ['hurry', 'speed', 'rush', 'quick'],
    correctIndex: 0,
    explanation: "'Hurry up' means to be quick. The other words are not used with 'up' here.",
    topic: 'phrasal-verbs',
  },
  {
    id: 'b1-035',
    prompt: 'I am really ____ forward to the weekend.',
    options: ['looking', 'seeing', 'watching', 'waiting'],
    correctIndex: 0,
    explanation: "'Look forward to' means to feel excited about something coming.",
    topic: 'phrasal-verbs',
  },
  {
    id: 'b1-036',
    prompt: 'He ____ a lot of mistakes in the exam.',
    options: ['did', 'made', 'took', 'had'],
    correctIndex: 1,
    explanation: "The collocation is 'make a mistake', not 'do a mistake'.",
    topic: 'collocations',
  },
  {
    id: 'b1-037',
    prompt: 'This is the man ____ car was stolen.',
    options: ['who', 'which', 'whose', 'whom'],
    correctIndex: 2,
    explanation: "'Whose' shows possession: the man whose car was stolen.",
    topic: 'grammar',
  },
  {
    id: 'b1-038',
    prompt: 'Could you ____ me the time, please?',
    options: ['say', 'tell', 'speak', 'talk'],
    correctIndex: 1,
    explanation: "We 'tell someone' something: tell me the time. We 'say' something to someone.",
    topic: 'confusing-pairs',
  },
  {
    id: 'b1-039',
    prompt: 'The meeting was ____ because the manager was ill.',
    options: ['called off', 'called on', 'called up', 'called in'],
    correctIndex: 0,
    explanation: "'Call off' means to cancel. The meeting was called off.",
    topic: 'phrasal-verbs',
  },
  {
    id: 'b1-040',
    prompt: 'If I ____ more time, I would travel the world.',
    options: ['have', 'had', 'will have', 'would have'],
    correctIndex: 1,
    explanation: 'Second conditional: if + past simple, then would + verb (an unreal present).',
    topic: 'grammar',
  },
  {
    id: 'b1-041',
    prompt: 'She is responsible ____ the whole department.',
    options: ['of', 'for', 'to', 'with'],
    correctIndex: 1,
    explanation: "We are 'responsible for' something or someone.",
    topic: 'prepositions',
  },
  {
    id: 'b1-042',
    prompt: 'Let me ____ a suggestion before we decide.',
    options: ['do', 'make', 'take', 'give'],
    correctIndex: 1,
    explanation: "The collocation is 'make a suggestion'.",
    topic: 'collocations',
  },
  {
    id: 'b1-043',
    prompt: 'I have known her ____ we were children.',
    options: ['for', 'since', 'during', 'from'],
    correctIndex: 1,
    explanation:
      "Use 'since' with the start point (since we were children); 'for' with a duration.",
    topic: 'confusing-pairs',
  },
  {
    id: 'b1-044',
    prompt: 'My car broke ____ on the motorway this morning.',
    options: ['down', 'up', 'off', 'out'],
    correctIndex: 0,
    explanation: "'Break down' means to stop working (for a machine or vehicle).",
    topic: 'phrasal-verbs',
  },
  {
    id: 'b1-045',
    prompt: 'You ____ smoke here; it is a hospital.',
    options: ["mustn't", "don't have to", "needn't", 'could not'],
    correctIndex: 0,
    explanation: "'Mustn't' means it is forbidden. 'Don't have to' means it is not necessary.",
    topic: 'grammar',
  },
  {
    id: 'b1-046',
    prompt: 'We need to ____ a solution to this problem.',
    options: ['find', 'make', 'do', 'take'],
    correctIndex: 0,
    explanation: "The natural collocation is 'find a solution' (also 'come up with' one).",
    topic: 'collocations',
  },
  {
    id: 'b1-047',
    prompt: 'I cannot ____ the difference between the two photos.',
    options: ['tell', 'say', 'speak', 'talk'],
    correctIndex: 0,
    explanation: "'Tell the difference' means to see how two things differ.",
    topic: 'confusing-pairs',
  },
  {
    id: 'b1-048',
    prompt: 'Please ____ out the form in capital letters.',
    options: ['fill', 'write', 'put', 'make'],
    correctIndex: 0,
    explanation: "'Fill out' (or 'fill in') a form means to complete it.",
    topic: 'phrasal-verbs',
  },
  {
    id: 'b1-049',
    prompt: 'She apologised ____ being late.',
    options: ['of', 'for', 'about', 'to'],
    correctIndex: 1,
    explanation: "We 'apologise for' something we did: apologise for being late.",
    topic: 'prepositions',
  },
  {
    id: 'b1-050',
    prompt: 'It was raining, ____ we stayed indoors.',
    options: ['although', 'so', 'despite', 'however'],
    correctIndex: 1,
    explanation: "'So' introduces a result. 'Although' and 'despite' introduce a contrast.",
    topic: 'grammar',
  },
  {
    id: 'b1-051',
    prompt: 'He finally ____ fast food last year.',
    options: ['gave up', 'gave in', 'gave away', 'gave off'],
    correctIndex: 0,
    explanation: "'Give up' means to stop a habit. 'Give away' means to donate.",
    topic: 'phrasal-verbs',
  },
  {
    id: 'b1-052',
    prompt: 'The teacher made us ____ the exercise again.',
    options: ['to do', 'do', 'doing', 'done'],
    correctIndex: 1,
    explanation: "After 'make someone' we use the bare infinitive: made us do it.",
    topic: 'grammar',
  },
  {
    id: 'b1-053',
    prompt: 'I am not used ____ getting up so early.',
    options: ['to', 'for', 'with', 'of'],
    correctIndex: 0,
    explanation: "'Be used to' + -ing means something is familiar: used to getting up early.",
    topic: 'prepositions',
  },
  {
    id: 'b1-054',
    prompt: 'They ____ a great deal of effort into the show.',
    options: ['put', 'made', 'did', 'gave'],
    correctIndex: 0,
    explanation: "The collocation is 'put effort into' something.",
    topic: 'collocations',
  },
  {
    id: 'b1-055',
    prompt: 'We will have to ____ the meeting until next week.',
    options: ['put off', 'put on', 'put up', 'put out'],
    correctIndex: 0,
    explanation: "'Put off' means to postpone. The other forms have different meanings.",
    topic: 'phrasal-verbs',
  },
  {
    id: 'b1-056',
    prompt: 'He behaved as if nothing ____ happened.',
    options: ['has', 'had', 'have', 'having'],
    correctIndex: 1,
    explanation:
      "After 'as if' about the past we use the past perfect: as if nothing had happened.",
    topic: 'grammar',
  },
  {
    id: 'b1-057',
    prompt: 'The price ____ tax is forty pounds.',
    options: ['including', 'included', 'include', 'includes'],
    correctIndex: 0,
    explanation: "'Including' is a preposition here: the price including tax.",
    topic: 'confusing-pairs',
  },
  {
    id: 'b1-058',
    prompt: 'I came ____ this old photo while cleaning.',
    options: ['across', 'over', 'up', 'into'],
    correctIndex: 0,
    explanation: "'Come across' means to find something by chance.",
    topic: 'phrasal-verbs',
  },
  {
    id: 'b1-059',
    prompt: 'She congratulated me ____ passing the exam.',
    options: ['for', 'on', 'about', 'of'],
    correctIndex: 1,
    explanation: "We 'congratulate someone on' an achievement.",
    topic: 'prepositions',
  },
  {
    id: 'b1-060',
    prompt: 'It is high time we ____ a decision.',
    options: ['make', 'made', 'will make', 'making'],
    correctIndex: 1,
    explanation:
      "After 'it is high time' we use the past simple to talk about now: time we made it.",
    topic: 'grammar',
  },
];
