/**
 * A2 (elementary) English quiz questions.
 *
 * One step up from A1: the past simple, comparatives, countable/uncountable
 * nouns, "going to", more everyday vocabulary, and the first common phrasal
 * verbs (turn off, get up, look after).
 *
 * Answer indices are 0-based. Keep explanations under 200 characters so they
 * fit Telegram's quiz explanation limit.
 */
import type { QuizQuestion } from '../types';

export const a2Questions: QuizQuestion[] = [
  {
    id: 'a2-001',
    prompt: 'Please ____ the lights when you leave the room.',
    options: ['turn off', 'turn up', 'turn into', 'turn over'],
    correctIndex: 0,
    explanation:
      "'Turn off' means to stop a machine or light. 'Turn up' means to increase the volume.",
    topic: 'phrasal-verbs',
  },
  {
    id: 'a2-002',
    prompt: 'Yesterday I ____ to the cinema with my friends.',
    options: ['go', 'went', 'gone', 'going'],
    correctIndex: 1,
    explanation:
      "'Yesterday' signals the past simple. The past of 'go' is the irregular form 'went'.",
    topic: 'grammar',
  },
  {
    id: 'a2-003',
    prompt: 'The film was really ____. I almost fell asleep.',
    options: ['exciting', 'boring', 'funny', 'loud'],
    correctIndex: 1,
    explanation: "If something makes you want to sleep, it's boring. 'Exciting' is the opposite.",
    topic: 'vocabulary',
  },
  {
    id: 'a2-004',
    prompt: 'What time do you usually ____ in the morning?',
    options: ['get up', 'get over', 'get off', 'get on'],
    correctIndex: 0,
    explanation:
      "'Get up' means to leave your bed. 'Get on' means to board a bus, train, or plane.",
    topic: 'phrasal-verbs',
  },
  {
    id: 'a2-005',
    prompt: 'She is taller ____ her brother.',
    options: ['then', 'that', 'than', 'as'],
    correctIndex: 2,
    explanation: "We use 'than' to compare two things: taller than. ('Then' is about time.)",
    topic: 'grammar',
  },
  {
    id: 'a2-006',
    prompt: 'She is ____ home today because she feels ill.',
    options: ['in', 'at', 'on', 'to'],
    correctIndex: 1,
    explanation: "'At home' is a fixed phrase. We don't say 'in home' or 'on home'.",
    topic: 'prepositions',
  },
  {
    id: 'a2-007',
    prompt: 'Could you ____ me the salt, please?',
    options: ['take', 'pass', 'carry', 'bring'],
    correctIndex: 1,
    explanation: "At the table we ask someone to 'pass' something to us: pass the salt.",
    topic: 'vocabulary',
  },
  {
    id: 'a2-008',
    prompt: 'There are too ____ people in this small room.',
    options: ['much', 'many', 'lot', 'more'],
    correctIndex: 1,
    explanation:
      "Use 'many' with countable nouns (people) and 'much' with uncountable nouns (water).",
    topic: 'grammar',
  },
  {
    id: 'a2-009',
    prompt: 'Can you ____ the baby while I cook dinner?',
    options: ['look for', 'look after', 'look up', 'look out'],
    correctIndex: 1,
    explanation: "'Look after' means to take care of someone. 'Look for' means to search.",
    topic: 'phrasal-verbs',
  },
  {
    id: 'a2-010',
    prompt: 'We have a meeting ____ Monday morning.',
    options: ['in', 'on', 'at', 'of'],
    correctIndex: 1,
    explanation: "We use 'on' with days and dates: on Monday, on 5 May.",
    topic: 'prepositions',
  },
  {
    id: 'a2-011',
    prompt: "It's raining hard. Don't forget your ____.",
    options: ['umbrella', 'sunglasses', 'towel', 'ticket'],
    correctIndex: 0,
    explanation: 'An umbrella keeps you dry in the rain. Sunglasses are for sunny weather.',
    topic: 'vocabulary',
  },
  {
    id: 'a2-012',
    prompt: "He's going to ____ a doctor when he grows up.",
    options: ['is', 'be', 'being', 'been'],
    correctIndex: 1,
    explanation: "After 'going to' we use the base verb: going to be a doctor.",
    topic: 'grammar',
  },
  {
    id: 'a2-013',
    prompt: 'I am not sure of the answer. Let me ____ it online.',
    options: ['make', 'check', 'do', 'say'],
    correctIndex: 1,
    explanation: "To 'check' something means to look at it to be sure it is correct.",
    topic: 'vocabulary',
  },
  {
    id: 'a2-014',
    prompt: 'We did not ____ the news until this morning.',
    options: ['heard', 'hear', 'hearing', 'hears'],
    correctIndex: 1,
    explanation: "After 'did not' we use the base verb: did not hear. The 'did' shows the past.",
    topic: 'grammar',
  },
  {
    id: 'a2-015',
    prompt: "Hurry up and ____ your coat, it's time to go!",
    options: ['put off', 'put on', 'put up', 'put out'],
    correctIndex: 1,
    explanation: "'Put on' means to start wearing clothes. 'Take off' is the opposite (remove).",
    topic: 'phrasal-verbs',
  },
  {
    id: 'a2-016',
    prompt: 'The keys are ____ my bag.',
    options: ['in', 'on', 'at', 'to'],
    correctIndex: 0,
    explanation: "We use 'in' for something inside a container: in my bag, in the box.",
    topic: 'prepositions',
  },
  {
    id: 'a2-017',
    prompt: 'She ____ a lot of money and bought a car.',
    options: ['earned', 'spent', 'lost', 'owed'],
    correctIndex: 0,
    explanation: "You 'earn' money by working. 'Owe' means you must pay money back.",
    topic: 'vocabulary',
  },
  {
    id: 'a2-018',
    prompt: 'If it rains tomorrow, we ____ at home.',
    options: ['will stay', 'stayed', 'would stay', 'staying'],
    correctIndex: 0,
    explanation:
      "First conditional: 'if' + present simple, then 'will' + base verb for the result.",
    topic: 'grammar',
  },
  {
    id: 'a2-019',
    prompt: 'I get ____ well with my new classmates.',
    options: ['on', 'off', 'up', 'in'],
    correctIndex: 0,
    explanation: "'Get on (with someone)' means to have a good relationship with them.",
    topic: 'phrasal-verbs',
  },
  {
    id: 'a2-020',
    prompt: "The shop is ____ on Sundays, so we can't go.",
    options: ['open', 'closed', 'free', 'empty'],
    correctIndex: 1,
    explanation: "If you cannot go in, the shop is 'closed'. 'Open' is the opposite.",
    topic: 'vocabulary',
  },
  {
    id: 'a2-021',
    prompt: "This is the ____ film I've ever seen.",
    options: ['good', 'better', 'best', 'more good'],
    correctIndex: 2,
    explanation: "The superlative of 'good' is the irregular 'best': the best film ever.",
    topic: 'grammar',
  },
  {
    id: 'a2-022',
    prompt: 'I have lived here ____ 2019.',
    options: ['since', 'for', 'from', 'ago'],
    correctIndex: 0,
    explanation: "Use 'since' with a point in time (since 2019) and 'for' with a length of time.",
    topic: 'prepositions',
  },
  {
    id: 'a2-023',
    prompt: 'My grandfather is 80, but he is still very ____.',
    options: ['healthy', 'sick', 'tired', 'hungry'],
    correctIndex: 0,
    explanation: "'Healthy' means not ill and in good condition, a positive thing at any age.",
    topic: 'vocabulary',
  },
  {
    id: 'a2-024',
    prompt: 'The plane will ____ in ten minutes, so fasten your seatbelt.',
    options: ['take off', 'take on', 'take up', 'take in'],
    correctIndex: 0,
    explanation: "'Take off' means to leave the ground (a plane). It also means to remove clothes.",
    topic: 'phrasal-verbs',
  },
  {
    id: 'a2-025',
    prompt: "I have ____ been to Japan, but I'd love to go one day.",
    options: ['never', 'ever', 'yet', 'since'],
    correctIndex: 0,
    explanation:
      "'Never' means 'not at any time'. We use it with the present perfect: I have never been.",
    topic: 'grammar',
  },
  {
    id: 'a2-026',
    prompt: "The opposite of 'expensive' is ____.",
    options: ['cheap', 'big', 'fast', 'new'],
    correctIndex: 0,
    explanation: "'Cheap' means it does not cost much money, the opposite of expensive.",
    topic: 'vocabulary',
  },
  {
    id: 'a2-027',
    prompt: 'She works ____ than her colleagues.',
    options: ['hard', 'harder', 'hardest', 'more hard'],
    correctIndex: 1,
    explanation:
      "The comparative of 'hard' is 'harder'. We add -er to short adjectives and adverbs.",
    topic: 'grammar',
  },
  {
    id: 'a2-028',
    prompt: 'I brush my teeth ____ the morning.',
    options: ['at', 'in', 'on', 'by'],
    correctIndex: 1,
    explanation: "We say 'in the morning', 'in the afternoon', 'in the evening' (but 'at night').",
    topic: 'prepositions',
  },
  {
    id: 'a2-029',
    prompt: 'She had to ____ early to catch her flight.',
    options: ['wake up', 'wake on', 'wake off', 'wake over'],
    correctIndex: 0,
    explanation: "'Wake up' means to stop sleeping. The other forms are not real phrasal verbs.",
    topic: 'phrasal-verbs',
  },
  {
    id: 'a2-030',
    prompt: 'He is very ____; he always helps other people.',
    options: ['kind', 'lazy', 'rude', 'shy'],
    correctIndex: 0,
    explanation: 'Someone who helps others is kind. The other options are negative.',
    topic: 'vocabulary',
  },
];
