/**
 * C2 (mastery) shadowing clips.
 *
 * Near-native lines with rhetorical polish: persuasion, elegant disagreement,
 * vivid storytelling, understatement. The skill here is subtle: controlling
 * pitch and pause to carry meaning the words only imply. Shadow closely to
 * absorb the timing that makes a speaker compelling to listen to.
 */
import type { ShadowingClip } from '../types';

export const c2Shadowing: ShadowingClip[] = [
  {
    id: 'c2-sh-001',
    text: 'If anything, this only strengthens the case for change.',
    context: 'Making a persuasive point',
    focus: 'stress',
    note: `Lean into "ANYTHING" and "STRENGTHENS". Let "for change" land with conviction.`,
    audio: 'c2-sh-001.ogg',
  },
  {
    id: 'c2-sh-002',
    text: "I'd be inclined to push back on that, respectfully.",
    context: 'Elegant disagreement',
    focus: 'pacing',
    note: `Smooth and unhurried. The pitch dips on "respectfully" to stay gracious.`,
    audio: 'c2-sh-002.ogg',
  },
  {
    id: 'c2-sh-003',
    text: 'Out of nowhere, the whole thing just came crashing down.',
    context: 'Telling a vivid story',
    focus: 'intonation',
    note: `Build pitch through "out of nowhere", then let "crashing down" drop sharply.`,
    audio: 'c2-sh-003.ogg',
  },
  {
    id: 'c2-sh-004',
    text: "I'll grant you that, but it's the exception, not the rule.",
    context: 'Conceding then countering',
    focus: 'stress',
    note: `Contrast "EXCEPTION" with "RULE". A crisp, parallel rhythm sells the point.`,
    audio: 'c2-sh-004.ogg',
  },
  {
    id: 'c2-sh-005',
    text: "It's no small thing to admit you were wrong.",
    context: 'Understated emphasis',
    focus: 'pacing',
    note: `Slow on "no small thing". Let the understatement breathe with a deliberate pause.`,
    audio: 'c2-sh-005.ogg',
  },
  {
    id: 'c2-sh-006',
    text: "We've come too far to throw in the towel now.",
    context: 'Rallying a team',
    focus: 'stress',
    note: `Drive "TOO FAR" and "NOW". Keep "throw in the towel" tight and idiomatic.`,
    audio: 'c2-sh-006.ogg',
  },
  {
    id: 'c2-sh-007',
    text: 'She has a real knack for reading a room.',
    context: 'Describing a skill',
    focus: 'linking',
    note: `"knack for" links to "knack-fer" and "reading a" to "ree-di-na". Effortless flow.`,
    audio: 'c2-sh-007.ogg',
  },
  {
    id: 'c2-sh-008',
    text: "I wouldn't go so far as to say it's a failure.",
    context: 'Hedging with finesse',
    focus: 'intonation',
    note: `Stay even until "failure", which dips, signalling careful restraint.`,
    audio: 'c2-sh-008.ogg',
  },
  {
    id: 'c2-sh-009',
    text: 'At the end of the day, results speak for themselves.',
    context: 'Closing an argument',
    focus: 'stress',
    note: `Say the set phrase fast, then weight "RESULTS" and "THEMSELVES". Land it firmly.`,
    audio: 'c2-sh-009.ogg',
  },
  {
    id: 'c2-sh-010',
    text: "Reading between the lines, I think they're stalling.",
    context: 'Reading the subtext',
    focus: 'reduction',
    note: `"they're" is one quick sound. Keep the idiom smooth, with suspicion in your tone.`,
    audio: 'c2-sh-010.ogg',
  },
  {
    id: 'c2-sh-011',
    text: "If I'm being completely candid, it fell flat.",
    context: 'Giving honest feedback',
    focus: 'pacing',
    note: `Even until "fell flat", which drops sharply for effect.`,
    audio: 'c2-sh-011.ogg',
  },
  {
    id: 'c2-sh-012',
    text: "That's a moot point at this stage.",
    context: 'Dismissing a side issue',
    focus: 'stress',
    note: `Stress "MOOT". Crisp, but stay polite.`,
    audio: 'c2-sh-012.ogg',
  },
  {
    id: 'c2-sh-013',
    text: "Let's not throw the baby out with the bathwater.",
    context: 'Warning against overcorrecting',
    focus: 'pacing',
    note: `Keep the long idiom smooth and quick, as one unit.`,
    audio: 'c2-sh-013.ogg',
  },
  {
    id: 'c2-sh-014',
    text: "I'd venture to say it's unprecedented.",
    context: 'Making a bold claim',
    focus: 'stress',
    note: `Stress "UNPRECEDENTED". Measured, deliberate weight.`,
    audio: 'c2-sh-014.ogg',
  },
  {
    id: 'c2-sh-015',
    text: "It cuts both ways, if we're honest.",
    context: 'Noting a two-sided point',
    focus: 'stress',
    note: `Stress "BOTH WAYS". Drop "if we're honest" softly.`,
    audio: 'c2-sh-015.ogg',
  },
  {
    id: 'c2-sh-016',
    text: "Let's call a spade a spade.",
    context: 'Asking for plain speaking',
    focus: 'stress',
    note: `Keep the idiom tight. Stress the second "SPADE".`,
    audio: 'c2-sh-016.ogg',
  },
  {
    id: 'c2-sh-017',
    text: "That's where I beg to differ.",
    context: 'Polite firm disagreement',
    focus: 'pacing',
    note: `Even and gracious. A slight stress on "DIFFER".`,
    audio: 'c2-sh-017.ogg',
  },
  {
    id: 'c2-sh-018',
    text: "I wouldn't read too much into it.",
    context: 'Downplaying a detail',
    focus: 'reduction',
    note: `"too much into it" flows: "too-mu-chin-tuh-it".`,
    audio: 'c2-sh-018.ogg',
  },
  {
    id: 'c2-sh-019',
    text: "We're preaching to the choir here.",
    context: 'Noting shared agreement',
    focus: 'stress',
    note: `Stress "CHOIR". A knowing, slightly amused tone.`,
    audio: 'c2-sh-019.ogg',
  },
  {
    id: 'c2-sh-020',
    text: "That's the long and the short of it.",
    context: 'Summing up',
    focus: 'linking',
    note: `Keep the idiom flowing. Conclusive, falling tone.`,
    audio: 'c2-sh-020.ogg',
  },
  {
    id: 'c2-sh-021',
    text: "Let's give it the once-over first.",
    context: 'Suggesting a quick check',
    focus: 'linking',
    note: `"once-over" links smoothly. "first" lands firm.`,
    audio: 'c2-sh-021.ogg',
  },
  {
    id: 'c2-sh-022',
    text: "I'd argue the opposite, in fact.",
    context: 'Stating a strong counterview',
    focus: 'stress',
    note: `Stress "OPPOSITE". "in fact" adds a firm little punch.`,
    audio: 'c2-sh-022.ogg',
  },
  {
    id: 'c2-sh-023',
    text: "That's neither here nor there.",
    context: 'Setting aside a point',
    focus: 'stress',
    note: `Stress "HERE" and "THERE". Dismissive but light.`,
    audio: 'c2-sh-023.ogg',
  },
  {
    id: 'c2-sh-024',
    text: "Let's not put the cart before the horse.",
    context: 'Warning against rushing',
    focus: 'pacing',
    note: `Keep the idiom smooth and unhurried.`,
    audio: 'c2-sh-024.ogg',
  },
  {
    id: 'c2-sh-025',
    text: "It's a slippery slope, make no mistake.",
    context: 'Warning of a risk',
    focus: 'pacing',
    note: `Stress "SLIPPERY SLOPE". "make no mistake" lands firm.`,
    audio: 'c2-sh-025.ogg',
  },
  {
    id: 'c2-sh-026',
    text: "I'll take it under advisement.",
    context: 'Considering a suggestion',
    focus: 'reduction',
    note: `"under advisement" flows together. Measured but warm.`,
    audio: 'c2-sh-026.ogg',
  },
  {
    id: 'c2-sh-027',
    text: 'That speaks volumes, frankly.',
    context: 'Reading meaning into something',
    focus: 'stress',
    note: `Stress "VOLUMES". Drop "frankly" with a knowing tone.`,
    audio: 'c2-sh-027.ogg',
  },
  {
    id: 'c2-sh-028',
    text: "We're in uncharted territory now.",
    context: 'Facing the unknown',
    focus: 'stress',
    note: `Stress "UNCHARTED". Add a touch of gravity.`,
    audio: 'c2-sh-028.ogg',
  },
  {
    id: 'c2-sh-029',
    text: "That's a hill I'm willing to die on.",
    context: 'Defending a strong stance',
    focus: 'stress',
    note: `Stress "HILL" and "DIE ON". Put conviction in the tone.`,
    audio: 'c2-sh-029.ogg',
  },
  {
    id: 'c2-sh-030',
    text: "Let's not lose the thread here.",
    context: 'Refocusing a discussion',
    focus: 'stress',
    note: `Stress "THREAD". Calm and refocusing.`,
    audio: 'c2-sh-030.ogg',
  },
  {
    id: 'c2-sh-031',
    text: "I'll hold my tongue for now.",
    context: 'Choosing not to speak',
    focus: 'pacing',
    note: `Even and restrained. A slight pause before "for now".`,
    audio: 'c2-sh-031.ogg',
  },
  {
    id: 'c2-sh-032',
    text: "That's a feather in your cap.",
    context: 'Congratulating someone',
    focus: 'linking',
    note: `Keep the idiom flowing. Warm and congratulatory.`,
    audio: 'c2-sh-032.ogg',
  },
  {
    id: 'c2-sh-033',
    text: "We're going around in circles.",
    context: 'Noting a stuck discussion',
    focus: 'stress',
    note: `Stress "CIRCLES". Slightly weary, ready to move on.`,
    audio: 'c2-sh-033.ogg',
  },
  {
    id: 'c2-sh-034',
    text: "Let's strike while the iron is hot.",
    context: 'Urging quick action',
    focus: 'stress',
    note: `Stress "STRIKE" and "HOT". Energetic and decisive.`,
    audio: 'c2-sh-034.ogg',
  },
  {
    id: 'c2-sh-035',
    text: "I'd stake my reputation on it.",
    context: 'Showing strong confidence',
    focus: 'stress',
    note: `Stress "REPUTATION". Strong conviction in the voice.`,
    audio: 'c2-sh-035.ogg',
  },
  {
    id: 'c2-sh-036',
    text: 'For what it is worth, I think it is brilliant.',
    context: 'Offering an opinion modestly',
    focus: 'pacing',
    note: `Throw away "for what it is worth", then warm up on "BRILLIANT".`,
    audio: 'c2-sh-036.ogg',
  },
  {
    id: 'c2-sh-037',
    text: "Let's give them the benefit of the doubt.",
    context: 'Choosing a generous view',
    focus: 'pacing',
    note: `Keep the idiom flowing. Generous, even tone.`,
    audio: 'c2-sh-037.ogg',
  },
  {
    id: 'c2-sh-038',
    text: 'That is easier said than done, admittedly.',
    context: 'Acknowledging a hard task',
    focus: 'stress',
    note: `Stress "DONE". Drop "admittedly" softly at the end.`,
    audio: 'c2-sh-038.ogg',
  },
  {
    id: 'c2-sh-039',
    text: "I'm inclined to take the long view here.",
    context: 'Thinking strategically',
    focus: 'reduction',
    note: `"inclined to" blurs to "inclined-tuh". Calm and considered.`,
    audio: 'c2-sh-039.ogg',
  },
  {
    id: 'c2-sh-040',
    text: "That's the elephant in the room, isn't it?",
    context: 'Raising the obvious issue',
    focus: 'intonation',
    note: `The tag "isn't it?" rises, inviting agreement. Knowing tone.`,
    audio: 'c2-sh-040.ogg',
  },
  {
    id: 'c2-sh-041',
    text: "I wouldn't read too much into it, if I were you.",
    context: 'Reassuring someone',
    focus: 'pacing',
    note: `Pause before "if I were you". Calm and knowing.`,
    audio: 'c2-sh-041.ogg',
  },
  {
    id: 'c2-sh-042',
    text: "That's easier said than done, I'm afraid.",
    context: 'Pushing back gently',
    focus: 'stress',
    note: `Contrast "SAID" and "DONE". A rueful fall on "afraid".`,
    audio: 'c2-sh-042.ogg',
  },
  {
    id: 'c2-sh-043',
    text: "Let's give credit where credit's due.",
    context: 'Acknowledging someone fairly',
    focus: 'stress',
    note: `Punch both instances of "CREDIT". Generous and warm.`,
    audio: 'c2-sh-043.ogg',
  },
  {
    id: 'c2-sh-044',
    text: "I'll believe it when I see it, frankly.",
    context: 'Expressing doubt',
    focus: 'intonation',
    note: `Keep it flat and dry, with a tiny lift on "frankly".`,
    audio: 'c2-sh-044.ogg',
  },
  {
    id: 'c2-sh-045',
    text: "We'll cross that bridge when we come to it.",
    context: 'Deferring a worry',
    focus: 'linking',
    note: `"come to it" runs to "come-tuit". Unhurried and settled.`,
    audio: 'c2-sh-045.ogg',
  },
  {
    id: 'c2-sh-046',
    text: "That's the long and short of it, really.",
    context: 'Wrapping up a summary',
    focus: 'pacing',
    note: `Pause before "really". Conclusive and final.`,
    audio: 'c2-sh-046.ogg',
  },
];
