/**
 * C1 (advanced) shadowing clips.
 *
 * Fluent, idiomatic lines for meetings and serious conversation: opening a
 * discussion, conceding gracefully, diplomatic disagreement, softening bad
 * news. Idioms are treated as single units of rhythm. Shadow the speaker to
 * absorb the easy, polished delivery of a confident professional.
 */
import type { ShadowingClip } from '../types';

export const c1Shadowing: ShadowingClip[] = [
  {
    id: 'c1-sh-001',
    text: "Let's get the ball rolling, shall we?",
    context: 'Opening a meeting',
    focus: 'intonation',
    note: `The tag "shall we?" lifts to invite. Say "get the ball rolling" as one fluid idiom.`,
    audio: 'c1-sh-001.ogg',
  },
  {
    id: 'c1-sh-002',
    text: "Fair enough, I hadn't looked at it that way.",
    context: 'Conceding a point',
    focus: 'linking',
    note: `"hadn't" reduces to "had-n", and "looked at it" links to "loo-ka-dit".`,
    audio: 'c1-sh-002.ogg',
  },
  {
    id: 'c1-sh-003',
    text: "I take your point, though I'd argue it's more nuanced.",
    context: 'Diplomatic disagreement',
    focus: 'pacing',
    note: `Keep an even, measured pace. A slight stress on "NUANCED" sounds thoughtful.`,
    audio: 'c1-sh-003.ogg',
  },
  {
    id: 'c1-sh-004',
    text: 'To cut a long story short, it all worked out in the end.',
    context: 'Wrapping up a story',
    focus: 'linking',
    note: `Keep the idiom fast, as one unit. "worked out" links to "wor-kout".`,
    audio: 'c1-sh-004.ogg',
  },
  {
    id: 'c1-sh-005',
    text: "It's a bit of a gray area, if I'm being honest.",
    context: 'Hedging carefully',
    focus: 'reduction',
    note: `"bit of a" blurs to "bi-duv-a". Use a casual, falling tone on "honest".`,
    audio: 'c1-sh-005.ogg',
  },
  {
    id: 'c1-sh-006',
    text: "Credit where it's due, you handled that really well.",
    context: 'Praising diplomatically',
    focus: 'stress',
    note: `Say the set phrase up front, then stress "HANDLED" and "WELL". Sound sincere.`,
    audio: 'c1-sh-006.ogg',
  },
  {
    id: 'c1-sh-007',
    text: "On the one hand it's risky, on the other it could pay off.",
    context: 'Weighing two sides',
    focus: 'intonation',
    note: `Rise slightly on "risky", then fall on "pay off" to mark the two sides.`,
    audio: 'c1-sh-007.ogg',
  },
  {
    id: 'c1-sh-008',
    text: "I'm afraid it's not quite what we were hoping for.",
    context: 'Softening bad news',
    focus: 'pacing',
    note: `Slow and gentle. A tiny pause after "afraid". Let "hoping for" trail downward.`,
    audio: 'c1-sh-008.ogg',
  },
  {
    id: 'c1-sh-009',
    text: "I'm really on board with this. It's a great call.",
    context: 'Showing support at work',
    focus: 'stress',
    note: `Stress "ON BOARD" and "GREAT CALL". Confident, energetic, and clear.`,
    audio: 'c1-sh-009.ogg',
  },
  {
    id: 'c1-sh-010',
    text: 'In hindsight, we may have jumped the gun a little.',
    context: 'Reflecting on a decision',
    focus: 'linking',
    note: `"may have" reduces to "may-uv". Keep "jumped the gun" tight, as one idiom.`,
    audio: 'c1-sh-010.ogg',
  },
  {
    id: 'c1-sh-011',
    text: "Let's not get bogged down in the details.",
    context: 'Keeping a meeting moving',
    focus: 'stress',
    note: `Stress "BOGGED DOWN". Keep the rest light and brisk.`,
    audio: 'c1-sh-011.ogg',
  },
  {
    id: 'c1-sh-012',
    text: "I'd push back on that, respectfully.",
    context: 'Disagreeing with care',
    focus: 'pacing',
    note: `Even and calm. Dip your pitch on "respectfully" to stay gracious.`,
    audio: 'c1-sh-012.ogg',
  },
  {
    id: 'c1-sh-013',
    text: "That's a fair assessment, on the whole.",
    context: 'Agreeing broadly',
    focus: 'pacing',
    note: `Stress "FAIR". Drop "on the whole" quietly at the end.`,
    audio: 'c1-sh-013.ogg',
  },
  {
    id: 'c1-sh-014',
    text: "Let's table this for now.",
    context: 'Pausing a topic',
    focus: 'stress',
    note: `Stress "TABLE". Brisk, decisive, falling tone.`,
    audio: 'c1-sh-014.ogg',
  },
  {
    id: 'c1-sh-015',
    text: "I'm cautiously optimistic about it.",
    context: 'Giving a guarded view',
    focus: 'stress',
    note: `Stress "CAUTIOUSLY OPTIMISTIC". Measured but warm.`,
    audio: 'c1-sh-015.ogg',
  },
  {
    id: 'c1-sh-016',
    text: 'We seem to be talking at cross purposes.',
    context: 'Clearing a misunderstanding',
    focus: 'pacing',
    note: `Keep "cross purposes" smooth. Even, diplomatic pace.`,
    audio: 'c1-sh-016.ogg',
  },
  {
    id: 'c1-sh-017',
    text: "That's where I'd draw the line.",
    context: 'Setting a limit',
    focus: 'stress',
    note: `Stress "DRAW THE LINE". Firm but calm.`,
    audio: 'c1-sh-017.ogg',
  },
  {
    id: 'c1-sh-018',
    text: "Let's give credit where it's due.",
    context: 'Recognizing good work',
    focus: 'linking',
    note: `Keep the idiom flowing as one unit. Sincere tone.`,
    audio: 'c1-sh-018.ogg',
  },
  {
    id: 'c1-sh-019',
    text: "I'd take that as a given.",
    context: 'Treating something as obvious',
    focus: 'reduction',
    note: `"take that as a" links smoothly. "given" lands lightly.`,
    audio: 'c1-sh-019.ogg',
  },
  {
    id: 'c1-sh-020',
    text: "It's a double-edged sword, really.",
    context: 'Noting a trade-off',
    focus: 'stress',
    note: `Stress "DOUBLE-EDGED". Drop "really" softly at the end.`,
    audio: 'c1-sh-020.ogg',
  },
  {
    id: 'c1-sh-021',
    text: "Let's not lose momentum now.",
    context: 'Keeping energy up',
    focus: 'stress',
    note: `Stress "MOMENTUM". Energetic and urging.`,
    audio: 'c1-sh-021.ogg',
  },
  {
    id: 'c1-sh-022',
    text: "I'll defer to your judgment on this.",
    context: 'Yielding gracefully',
    focus: 'pacing',
    note: `Even and respectful. Stress "JUDGMENT".`,
    audio: 'c1-sh-022.ogg',
  },
  {
    id: 'c1-sh-023',
    text: 'That rings a bell, actually.',
    context: 'Half-remembering something',
    focus: 'intonation',
    note: `Lift "RINGS A BELL". Drop "actually" at the end.`,
    audio: 'c1-sh-023.ogg',
  },
  {
    id: 'c1-sh-024',
    text: "We're splitting hairs at this point.",
    context: 'Calling out tiny distinctions',
    focus: 'stress',
    note: `Stress "SPLITTING HAIRS". A slightly weary tone.`,
    audio: 'c1-sh-024.ogg',
  },
  {
    id: 'c1-sh-025',
    text: "Let's iron out the wrinkles first.",
    context: 'Fixing small problems',
    focus: 'linking',
    note: `Keep "iron out the wrinkles" smooth. "first" lands firm.`,
    audio: 'c1-sh-025.ogg',
  },
  {
    id: 'c1-sh-026',
    text: "I'd be inclined to hold off for now.",
    context: 'Advising patience',
    focus: 'reduction',
    note: `"inclined to" blurs to "inclined-tuh". Calm and cautious.`,
    audio: 'c1-sh-026.ogg',
  },
  {
    id: 'c1-sh-027',
    text: "That's the elephant in the room.",
    context: 'Naming the obvious problem',
    focus: 'stress',
    note: `Stress "ELEPHANT". Knowing, slightly pointed tone.`,
    audio: 'c1-sh-027.ogg',
  },
  {
    id: 'c1-sh-028',
    text: "Let's touch base offline about it.",
    context: 'Moving a chat elsewhere',
    focus: 'reduction',
    note: `"touch base offline" flows together. "about it" is light.`,
    audio: 'c1-sh-028.ogg',
  },
  {
    id: 'c1-sh-029',
    text: "I think we're splitting the difference.",
    context: 'Reaching a compromise',
    focus: 'stress',
    note: `Stress "DIFFERENCE". Even, conciliatory tone.`,
    audio: 'c1-sh-029.ogg',
  },
  {
    id: 'c1-sh-030',
    text: "That's a tall order, frankly.",
    context: 'Noting a hard request',
    focus: 'stress',
    note: `Stress "TALL ORDER". Drop "frankly" softly at the end.`,
    audio: 'c1-sh-030.ogg',
  },
  {
    id: 'c1-sh-031',
    text: "Let's keep this under wraps for now.",
    context: 'Asking for discretion',
    focus: 'linking',
    note: `Keep "under wraps" smooth. Use a quiet, confidential tone.`,
    audio: 'c1-sh-031.ogg',
  },
  {
    id: 'c1-sh-032',
    text: "I'll take that on board.",
    context: 'Accepting feedback',
    focus: 'linking',
    note: `"on board" links to "on-bord". Sincere and accepting.`,
    audio: 'c1-sh-032.ogg',
  },
  {
    id: 'c1-sh-033',
    text: "We're reading from the same script.",
    context: 'Confirming alignment',
    focus: 'stress',
    note: `Stress "SAME SCRIPT". Confident, aligned tone.`,
    audio: 'c1-sh-033.ogg',
  },
  {
    id: 'c1-sh-034',
    text: "Let's not reinvent the wheel here.",
    context: 'Avoiding wasted effort',
    focus: 'stress',
    note: `Stress "REINVENT THE WHEEL". Practical and light.`,
    audio: 'c1-sh-034.ogg',
  },
  {
    id: 'c1-sh-035',
    text: "That's par for the course, sadly.",
    context: 'Accepting the usual',
    focus: 'reduction',
    note: `Keep "par for the course" smooth. Drop "sadly" softly.`,
    audio: 'c1-sh-035.ogg',
  },
  {
    id: 'c1-sh-036',
    text: "I'd rather not commit just yet.",
    context: 'Holding back a decision',
    focus: 'pacing',
    note: `Even and careful. Stress "COMMIT". "just yet" is light.`,
    audio: 'c1-sh-036.ogg',
  },
  {
    id: 'c1-sh-037',
    text: "Let's see how the land lies first.",
    context: 'Assessing before acting',
    focus: 'linking',
    note: `Keep "how the land lies" flowing. "first" lands firm.`,
    audio: 'c1-sh-037.ogg',
  },
  {
    id: 'c1-sh-038',
    text: "That's the crux of the matter.",
    context: 'Naming the key issue',
    focus: 'stress',
    note: `Stress "CRUX". Deliberate, weighty tone.`,
    audio: 'c1-sh-038.ogg',
  },
  {
    id: 'c1-sh-039',
    text: "Let me play devil's advocate here.",
    context: 'Testing an idea',
    focus: 'pacing',
    note: `Keep the idiom quick, then pause before your point.`,
    audio: 'c1-sh-039.ogg',
  },
  {
    id: 'c1-sh-040',
    text: "Let's call it a day.",
    context: 'Wrapping up',
    focus: 'stress',
    note: `Stress "CALL IT A DAY". Warm, conclusive fall.`,
    audio: 'c1-sh-040.ogg',
  },
  {
    id: 'c1-sh-041',
    text: "I'm inclined to agree with you on that.",
    context: 'Agreeing thoughtfully',
    focus: 'stress',
    note: `Stress "INCLINED" and "AGREE". A considered, measured tone.`,
    audio: 'c1-sh-041.ogg',
  },
  {
    id: 'c1-sh-042',
    text: "Let's keep our options open for now.",
    context: 'Staying flexible',
    focus: 'pacing',
    note: `Pause before "for now". Measured and unhurried.`,
    audio: 'c1-sh-042.ogg',
  },
  {
    id: 'c1-sh-043',
    text: "On balance, I think it's worth the risk.",
    context: 'Weighing up a decision',
    focus: 'pacing',
    note: `Pause after "On balance", then sound decisive on "worth the risk".`,
    audio: 'c1-sh-043.ogg',
  },
  {
    id: 'c1-sh-044',
    text: "I take your point, but there's another side to it.",
    context: 'Offering a counter-argument',
    focus: 'intonation',
    note: `Rise on "another side", inviting them to keep listening.`,
    audio: 'c1-sh-044.ogg',
  },
  {
    id: 'c1-sh-045',
    text: "It's a tricky one, I'll grant you that.",
    context: 'Conceding a difficulty',
    focus: 'reduction',
    note: `"grant you that" blurs to "gran-cha-that". A wry, easy tone.`,
    audio: 'c1-sh-045.ogg',
  },
  {
    id: 'c1-sh-046',
    text: "Let's play it by ear and see how it goes.",
    context: 'Staying flexible',
    focus: 'linking',
    note: `"play it by ear" runs together. Relaxed and open.`,
    audio: 'c1-sh-046.ogg',
  },
  {
    id: 'c1-sh-047',
    text: "I'd hesitate to call it a success just yet.",
    context: 'Cautious assessment',
    focus: 'pacing',
    note: `Pause before "just yet". Careful and measured.`,
    audio: 'c1-sh-047.ogg',
  },
  {
    id: 'c1-sh-048',
    text: "That's a compelling argument, I must admit.",
    context: 'Conceding a point',
    focus: 'stress',
    note: `Stress "COMPELLING". A gracious fall on "admit".`,
    audio: 'c1-sh-048.ogg',
  },
  {
    id: 'c1-sh-049',
    text: "Let's not lose sight of the bigger picture.",
    context: 'Refocusing a discussion',
    focus: 'pacing',
    note: `Pause before "the bigger picture". Steady and calm.`,
    audio: 'c1-sh-049.ogg',
  },
  {
    id: 'c1-sh-050',
    text: "I'm broadly in favor, with a few reservations.",
    context: 'Giving qualified support',
    focus: 'reduction',
    note: `Keep "in favor" even; a small lift on "reservations".`,
    audio: 'c1-sh-050.ogg',
  },
  {
    id: 'c1-sh-051',
    text: 'It boils down to a question of priorities.',
    context: 'Summarising an issue',
    focus: 'linking',
    note: `"boils down to" runs together. Crisp and clear.`,
    audio: 'c1-sh-051.ogg',
  },
  {
    id: 'c1-sh-052',
    text: "I'd tread carefully there, if I were you.",
    context: 'Warning gently',
    focus: 'pacing',
    note: `Pause before "if I were you". Quiet and knowing.`,
    audio: 'c1-sh-052.ogg',
  },
  {
    id: 'c1-sh-053',
    text: "There's more to it than meets the eye.",
    context: 'Hinting at complexity',
    focus: 'linking',
    note: `"meets the eye" flows together. Slightly intriguing.`,
    audio: 'c1-sh-053.ogg',
  },
  {
    id: 'c1-sh-054',
    text: "Let's give it the green light, then.",
    context: 'Approving a plan',
    focus: 'stress',
    note: `Punch "GREEN LIGHT". Decisive and upbeat.`,
    audio: 'c1-sh-054.ogg',
  },
];
