/**
 * A2 (elementary) shadowing clips.
 *
 * Slightly longer everyday lines than A1, still high-frequency. The learner
 * starts joining small words together and using simple tags ("isn't it?").
 * Listen, then repeat WITH the speaker, copying the rhythm.
 */
import type { ShadowingClip } from '../types';

export const a2Shadowing: ShadowingClip[] = [
  {
    id: 'a2-sh-001',
    text: "It's been a while! How have you been?",
    context: 'Catching up with a friend',
    focus: 'linking',
    note: `"been a" links to "bee-na". Let "How have you" blur into "how-uv-yuh".`,
    audio: 'a2-sh-001.ogg',
  },
  {
    id: 'a2-sh-002',
    text: "I'll have the chicken sandwich, please.",
    context: 'Ordering food',
    focus: 'stress',
    note: `Stress "CHICKEN SANDWICH". "I will have the" is light and quick before it.`,
    audio: 'a2-sh-002.ogg',
  },
  {
    id: 'a2-sh-003',
    text: "It's really nice out today, isn't it?",
    context: 'Small talk about the weather',
    focus: 'intonation',
    note: `The tag "isn't it?" rises a little, inviting the other person to agree.`,
    audio: 'a2-sh-003.ogg',
  },
  {
    id: 'a2-sh-004',
    text: 'Could you give me a hand with this?',
    context: 'Asking a favor',
    focus: 'reduction',
    note: `"Could you" softens to "couldja". Keep "give me a hand" smooth and friendly.`,
    audio: 'a2-sh-004.ogg',
  },
  {
    id: 'a2-sh-005',
    text: "Why don't we meet around six?",
    context: 'Making a suggestion',
    focus: 'linking',
    note: `Link "Why don't we" into "why-don-we". Keep "around six" clear.`,
    audio: 'a2-sh-005.ogg',
  },
  {
    id: 'a2-sh-006',
    text: "I'm thinking about going to the beach.",
    context: 'Talking about the weekend',
    focus: 'pacing',
    note: `Group it: "I'm thinking / about going / to the beach." Breathe at the slashes.`,
    audio: 'a2-sh-006.ogg',
  },
  {
    id: 'a2-sh-007',
    text: "Thanks, but I think I'll pass this time.",
    context: 'Declining politely',
    focus: 'stress',
    note: `Stress "PASS" and "THIS TIME". Keep "Thanks, but I think I'll" soft and quick.`,
    audio: 'a2-sh-007.ogg',
  },
  {
    id: 'a2-sh-008',
    text: 'Can we talk about this after lunch?',
    context: 'At work',
    focus: 'intonation',
    note: `Falling melody on "lunch": it is a calm request, so stay even and clear.`,
    audio: 'a2-sh-008.ogg',
  },
  {
    id: 'a2-sh-009',
    text: "Oh wow, that's great news!",
    context: 'Reacting to good news',
    focus: 'intonation',
    note: `Jump your pitch up on "WOW" and "GREAT" to sound genuinely excited.`,
    audio: 'a2-sh-009.ogg',
  },
  {
    id: 'a2-sh-010',
    text: "Sorry I'm late, the traffic was crazy.",
    context: 'Giving a quick excuse',
    focus: 'reduction',
    note: `"was" reduces to "wuz". Keep the rhythm flowing: "the-traffic-wuz-crazy".`,
    audio: 'a2-sh-010.ogg',
  },
  {
    id: 'a2-sh-011',
    text: 'Could I have the bill, please?',
    context: 'Finishing a meal',
    focus: 'linking',
    note: `Link "Could I have the" smoothly into one run. Stress "BILL".`,
    audio: 'a2-sh-011.ogg',
  },
  {
    id: 'a2-sh-012',
    text: 'What do you do for a living?',
    context: 'Getting to know someone',
    focus: 'reduction',
    note: `"do you" blurs to "d'yuh", and "for a" becomes "fer-a". Stress "LIVING".`,
    audio: 'a2-sh-012.ogg',
  },
  {
    id: 'a2-sh-013',
    text: "I'm just looking, thanks.",
    context: 'In a shop',
    focus: 'stress',
    note: `Stress "JUST LOOKING". Friendly, with a little smile in your voice.`,
    audio: 'a2-sh-013.ogg',
  },
  {
    id: 'a2-sh-014',
    text: 'Do you have this in a bigger size?',
    context: 'Shopping for clothes',
    focus: 'linking',
    note: `Link "have this in a" together. Let "size?" rise gently at the end.`,
    audio: 'a2-sh-014.ogg',
  },
  {
    id: 'a2-sh-015',
    text: 'Could you take a photo of us?',
    context: 'Sightseeing',
    focus: 'reduction',
    note: `"Could you" softens to "couldja". Stress "PHOTO".`,
    audio: 'a2-sh-015.ogg',
  },
  {
    id: 'a2-sh-016',
    text: "I'll be there in ten minutes.",
    context: 'On your way',
    focus: 'stress',
    note: `Stress "TEN MINUTES". "I'll be there in" is quick before it.`,
    audio: 'a2-sh-016.ogg',
  },
  {
    id: 'a2-sh-017',
    text: "Sorry, I didn't catch that.",
    context: 'Asking someone to repeat',
    focus: 'pacing',
    note: `"didn't catch" links to "didn-catch". Say it lightly, not heavily stressed.`,
    audio: 'a2-sh-017.ogg',
  },
  {
    id: 'a2-sh-018',
    text: 'That works for me.',
    context: 'Agreeing to a plan',
    focus: 'stress',
    note: `Stress "WORKS". Calm, falling tone to confirm.`,
    audio: 'a2-sh-018.ogg',
  },
  {
    id: 'a2-sh-019',
    text: 'Let me know if you need anything.',
    context: 'Offering help',
    focus: 'reduction',
    note: `"Let me" becomes "lemme", "if you" blurs to "if-yuh". Warm and easy.`,
    audio: 'a2-sh-019.ogg',
  },
  {
    id: 'a2-sh-020',
    text: 'How was your weekend?',
    context: 'Monday small talk',
    focus: 'intonation',
    note: `"How was your" runs together. Lift "WEEKEND?" warmly.`,
    audio: 'a2-sh-020.ogg',
  },
  {
    id: 'a2-sh-021',
    text: 'It was really fun, actually.',
    context: 'Sharing your news',
    focus: 'stress',
    note: `Stress "REALLY FUN". Drop "actually" softly at the end.`,
    audio: 'a2-sh-021.ogg',
  },
  {
    id: 'a2-sh-022',
    text: 'Can I give you a call back?',
    context: 'On the phone',
    focus: 'linking',
    note: `Link "give you a" to "gi-vyuh-a". Let "back?" rise at the end.`,
    audio: 'a2-sh-022.ogg',
  },
  {
    id: 'a2-sh-023',
    text: "I'm running a bit late, sorry.",
    context: 'Letting someone know',
    focus: 'pacing',
    note: `"running a bit" blends together. A quick apology with a warm tone.`,
    audio: 'a2-sh-023.ogg',
  },
  {
    id: 'a2-sh-024',
    text: 'Do you want to come with us?',
    context: 'Inviting a friend',
    focus: 'reduction',
    note: `"want to" becomes "wanna", "with us" links to "wi-thus".`,
    audio: 'a2-sh-024.ogg',
  },
  {
    id: 'a2-sh-025',
    text: 'That sounds like a plan.',
    context: 'Agreeing happily',
    focus: 'stress',
    note: `Stress "PLAN". Easy, confident, falling tone.`,
    audio: 'a2-sh-025.ogg',
  },
  {
    id: 'a2-sh-026',
    text: "I'll think about it.",
    context: 'Not deciding yet',
    focus: 'pacing',
    note: `Pause before "about it". "about it" links to "uh-bow-dit".`,
    audio: 'a2-sh-026.ogg',
  },
  {
    id: 'a2-sh-027',
    text: 'What time should we meet?',
    context: 'Making plans',
    focus: 'linking',
    note: `"What time should we" runs together. Stress "MEET".`,
    audio: 'a2-sh-027.ogg',
  },
  {
    id: 'a2-sh-028',
    text: 'I really enjoyed that.',
    context: 'After an event',
    focus: 'stress',
    note: `Stress "REALLY enjoyed". Sincere, warm delivery.`,
    audio: 'a2-sh-028.ogg',
  },
  {
    id: 'a2-sh-029',
    text: 'Could you say that again, please?',
    context: 'Asking for help',
    focus: 'pacing',
    note: `Slow and polite. "Could you" softens to "couldja".`,
    audio: 'a2-sh-029.ogg',
  },
  {
    id: 'a2-sh-030',
    text: 'No worries, take your time.',
    context: 'Reassuring someone',
    focus: 'reduction',
    note: `"take your" blurs to "take-yer". Relaxed and reassuring.`,
    audio: 'a2-sh-030.ogg',
  },
  {
    id: 'a2-sh-031',
    text: "I'm not feeling great today.",
    context: 'Talking about health',
    focus: 'stress',
    note: `Stress "NOT" and "GREAT". Let your voice drop a little.`,
    audio: 'a2-sh-031.ogg',
  },
  {
    id: 'a2-sh-032',
    text: "Let's catch up soon.",
    context: 'Saying goodbye to a friend',
    focus: 'linking',
    note: `"catch up" links to "ca-chup". Warm rise on "SOON".`,
    audio: 'a2-sh-032.ogg',
  },
  {
    id: 'a2-sh-033',
    text: 'Can you give me a hand?',
    context: 'Asking for help',
    focus: 'reduction',
    note: `"give me a" blurs to "gi-mee-a". Stress "HAND".`,
    audio: 'a2-sh-033.ogg',
  },
  {
    id: 'a2-sh-034',
    text: "I'd better get going.",
    context: 'Leaving',
    focus: 'stress',
    note: `Stress "BETTER" and "GOING". "I'd" almost disappears.`,
    audio: 'a2-sh-034.ogg',
  },
  {
    id: 'a2-sh-035',
    text: "That's so kind of you.",
    context: 'Thanking warmly',
    focus: 'intonation',
    note: `Warm, rising pitch on "SO KIND". Sincere and grateful.`,
    audio: 'a2-sh-035.ogg',
  },
  {
    id: 'a2-sh-036',
    text: 'Do you know what time it is?',
    context: 'Asking the time',
    focus: 'linking',
    note: `"what time it is" runs together: "wut-tie-mi-tiz".`,
    audio: 'a2-sh-036.ogg',
  },
  {
    id: 'a2-sh-037',
    text: "I'll send you the details later.",
    context: 'Wrapping up at work',
    focus: 'stress',
    note: `Stress "DETAILS". "I'll send you the" is quick before it.`,
    audio: 'a2-sh-037.ogg',
  },
  {
    id: 'a2-sh-038',
    text: 'Can we reschedule for tomorrow?',
    context: 'Changing a plan',
    focus: 'pacing',
    note: `Stress "RESCHEDULE". Let "tomorrow?" rise gently at the end.`,
    audio: 'a2-sh-038.ogg',
  },
  {
    id: 'a2-sh-039',
    text: "It's not a big deal.",
    context: 'Reassuring someone',
    focus: 'stress',
    note: `Stress "NOT" and "BIG". Calm and reassuring.`,
    audio: 'a2-sh-039.ogg',
  },
  {
    id: 'a2-sh-040',
    text: 'Thanks for letting me know.',
    context: 'Replying to news',
    focus: 'reduction',
    note: `"letting me" blurs to "le-ting-mee". Warm and quick.`,
    audio: 'a2-sh-040.ogg',
  },
  {
    id: 'a2-sh-041',
    text: 'Do you want to grab a coffee later?',
    context: 'Making plans',
    focus: 'reduction',
    note: `"want to" becomes "wanna": "Do-you-wanna-grab". Light and casual.`,
    audio: 'a2-sh-041.ogg',
  },
  {
    id: 'a2-sh-042',
    text: "I'm not sure, let me think about it.",
    context: 'Buying time to decide',
    focus: 'pacing',
    note: `Pause after "not sure". Calm, no rush to answer.`,
    audio: 'a2-sh-042.ogg',
  },
  {
    id: 'a2-sh-043',
    text: 'It was really nice to see you.',
    context: 'Saying goodbye warmly',
    focus: 'stress',
    note: `Punch "REALLY" and "NICE". Make it sound warm and genuine.`,
    audio: 'a2-sh-043.ogg',
  },
  {
    id: 'a2-sh-044',
    text: 'Can you write that down for me?',
    context: 'Asking for it in writing',
    focus: 'linking',
    note: `"write that down" flows together. Clear and friendly.`,
    audio: 'a2-sh-044.ogg',
  },
  {
    id: 'a2-sh-045',
    text: "I'll give you a call tomorrow.",
    context: 'Promising to follow up',
    focus: 'linking',
    note: `"give you a" runs to "gi-vya": "I'll-gi-vya-call".`,
    audio: 'a2-sh-045.ogg',
  },
  {
    id: 'a2-sh-046',
    text: 'Sorry to bother you, but can I ask something?',
    context: 'Interrupting politely',
    focus: 'pacing',
    note: `Pause after "bother you". Keep it gentle and brief.`,
    audio: 'a2-sh-046.ogg',
  },
  {
    id: 'a2-sh-047',
    text: "I'll meet you at the entrance.",
    context: 'Arranging where to meet',
    focus: 'linking',
    note: `"meet you" blurs to "mee-chu". Smooth and easy.`,
    audio: 'a2-sh-047.ogg',
  },
  {
    id: 'a2-sh-048',
    text: 'Can I leave a message?',
    context: 'Leaving a phone message',
    focus: 'reduction',
    note: `"Can I" softens to "c'n-I". Polite rise at the end.`,
    audio: 'a2-sh-048.ogg',
  },
  {
    id: 'a2-sh-049',
    text: "That doesn't work for me, sorry.",
    context: 'Declining a time',
    focus: 'stress',
    note: `Stress "DOESN'T". Keep "sorry" soft and apologetic.`,
    audio: 'a2-sh-049.ogg',
  },
  {
    id: 'a2-sh-050',
    text: 'Do you mind if I open the window?',
    context: 'Asking permission',
    focus: 'reduction',
    note: `"Do you mind if" runs together. Gentle, polite tone.`,
    audio: 'a2-sh-050.ogg',
  },
  {
    id: 'a2-sh-051',
    text: 'I had a great time, thanks for inviting me.',
    context: 'Leaving a party',
    focus: 'pacing',
    note: `Small pause after "great time". Warm and sincere.`,
    audio: 'a2-sh-051.ogg',
  },
  {
    id: 'a2-sh-052',
    text: 'Could you turn it down a bit?',
    context: 'Asking to lower the volume',
    focus: 'linking',
    note: `"turn it down" flows as one. Friendly, not sharp.`,
    audio: 'a2-sh-052.ogg',
  },
  {
    id: 'a2-sh-053',
    text: 'I am afraid I have to go now.',
    context: 'Leaving politely',
    focus: 'reduction',
    note: `"have to" becomes "hafta": "I hafta go now".`,
    audio: 'a2-sh-053.ogg',
  },
  {
    id: 'a2-sh-054',
    text: "Let me know when you're free.",
    context: 'Making loose plans',
    focus: 'linking',
    note: `"when you're" blurs to "when-yer". Relaxed and open.`,
    audio: 'a2-sh-054.ogg',
  },
  {
    id: 'a2-sh-055',
    text: "I'll text you the address.",
    context: 'Sharing details',
    focus: 'linking',
    note: `"text you" blends into "teks-chu". Quick and casual.`,
    audio: 'a2-sh-055.ogg',
  },
  {
    id: 'a2-sh-056',
    text: 'Do you need a hand with that?',
    context: 'Offering help',
    focus: 'reduction',
    note: `"need a hand" blurs together. Warm and ready.`,
    audio: 'a2-sh-056.ogg',
  },
  {
    id: 'a2-sh-057',
    text: "Let's grab a bite to eat.",
    context: 'Suggesting food',
    focus: 'linking',
    note: `"grab a bite" runs together. Relaxed and friendly.`,
    audio: 'a2-sh-057.ogg',
  },
  {
    id: 'a2-sh-058',
    text: 'Sorry, could you repeat the price?',
    context: 'Asking again',
    focus: 'pacing',
    note: `Small pause before "the price". Polite, not annoyed.`,
    audio: 'a2-sh-058.ogg',
  },
  {
    id: 'a2-sh-059',
    text: 'That sounds good to me.',
    context: 'Agreeing to a plan',
    focus: 'stress',
    note: `Stress "GOOD". Easy, positive, and warm.`,
    audio: 'a2-sh-059.ogg',
  },
  {
    id: 'a2-sh-060',
    text: "I'll be right with you.",
    context: 'Telling someone to wait a moment',
    focus: 'reduction',
    note: `"right with you" softens to "righ-with-ya".`,
    audio: 'a2-sh-060.ogg',
  },
];
