/**
 * A1 (beginner) shadowing clips.
 *
 * Shadowing means: listen to a short native line, then say it out loud at the
 * same time, copying the rhythm and melody. At A1 the lines are very short,
 * high-frequency, everyday survival sentences. The goal is confidence with the
 * music of English, not long sentences.
 *
 * Each `note` is a concrete tip in plain words (template literals so the
 * phonetic spellings can use both quotes freely). The `text` is also the exact
 * script the audio is generated from (scripts/generate-audio.ts), so the spoken
 * clip and the on-screen transcript always match.
 */
import type { ShadowingClip } from '../types';

export const a1Shadowing: ShadowingClip[] = [
  {
    id: 'a1-sh-001',
    text: 'Can I get a small coffee, please?',
    context: 'Ordering at a café',
    focus: 'linking',
    note: `Link "Can I get a" into one smooth run: "c'n-I-ge-da". Keep it light and quick.`,
    audio: 'a1-sh-001.ogg',
  },
  {
    id: 'a1-sh-002',
    text: "Hey, how's it going?",
    context: 'Greeting someone',
    focus: 'reduction',
    note: `"How is it" becomes "how's it". Say it fast and friendly, with the stress on "going".`,
    audio: 'a1-sh-002.ogg',
  },
  {
    id: 'a1-sh-003',
    text: 'Thanks so much, I really appreciate it.',
    context: 'Saying thank you',
    focus: 'stress',
    note: `Punch the strong words: THANKS, MUCH, REALLY. Let the small words fall away.`,
    audio: 'a1-sh-003.ogg',
  },
  {
    id: 'a1-sh-004',
    text: "Excuse me, where's the bathroom?",
    context: 'Asking for directions',
    focus: 'intonation',
    note: `Start "excuse me" with a gentle rise, then let "bathroom" fall. Stay polite.`,
    audio: 'a1-sh-004.ogg',
  },
  {
    id: 'a1-sh-005',
    text: "Nice to meet you. I'm Sam.",
    context: 'Meeting a new person',
    focus: 'linking',
    note: `Link "meet you" so it sounds like "mee-chu". Smile as you say it.`,
    audio: 'a1-sh-005.ogg',
  },
  {
    id: 'a1-sh-006',
    text: 'How much is this one?',
    context: 'Shopping',
    focus: 'stress',
    note: `Stress "MUCH" and "THIS". The melody falls at the end, like a normal question.`,
    audio: 'a1-sh-006.ogg',
  },
  {
    id: 'a1-sh-007',
    text: 'Hi, this is Sam. Can you hear me okay?',
    context: 'On the phone',
    focus: 'intonation',
    note: `Let "okay" rise at the end so it sounds like a real check, not a flat statement.`,
    audio: 'a1-sh-007.ogg',
  },
  {
    id: 'a1-sh-008',
    text: 'Do you want to grab lunch later?',
    context: 'Making plans',
    focus: 'reduction',
    note: `"want to" becomes "wanna": "Do you wanna grab lunch?" Quick and casual.`,
    audio: 'a1-sh-008.ogg',
  },
  {
    id: 'a1-sh-009',
    text: "Sorry, I'm a little late.",
    context: 'Apologizing',
    focus: 'pacing',
    note: `Tiny pause after "Sorry," then finish smoothly. Do not rush the apology.`,
    audio: 'a1-sh-009.ogg',
  },
  {
    id: 'a1-sh-010',
    text: 'Okay, see you tomorrow!',
    context: 'Ending a chat',
    focus: 'intonation',
    note: `Lift your pitch on "tomorrow" to sound warm and upbeat, not flat.`,
    audio: 'a1-sh-010.ogg',
  },
  {
    id: 'a1-sh-011',
    text: 'Good morning! Did you sleep well?',
    context: 'A morning greeting',
    focus: 'intonation',
    note: `Lift "morning" warmly, then let "sleep well?" rise like a gentle question.`,
    audio: 'a1-sh-011.ogg',
  },
  {
    id: 'a1-sh-012',
    text: 'Can I have the menu, please?',
    context: 'At a restaurant',
    focus: 'linking',
    note: `Link "Can I have the" so it flows: "c'n-I-have-the". Stress "MENU".`,
    audio: 'a1-sh-012.ogg',
  },
  {
    id: 'a1-sh-013',
    text: "I'd like a glass of water.",
    context: 'Ordering a drink',
    focus: 'stress',
    note: `Stress "GLASS" and "WATER". "I'd like a" is quick and soft before them.`,
    audio: 'a1-sh-013.ogg',
  },
  {
    id: 'a1-sh-014',
    text: 'Where are you from?',
    context: 'Getting to know someone',
    focus: 'reduction',
    note: `"are you" blurs to "er-yuh": "Where-er-yuh-from?" The pitch falls at the end.`,
    audio: 'a1-sh-014.ogg',
  },
  {
    id: 'a1-sh-015',
    text: 'What time is it?',
    context: 'Asking the time',
    focus: 'linking',
    note: `Link "time is it" into "ti-mi-zit". Stress "TIME".`,
    audio: 'a1-sh-015.ogg',
  },
  {
    id: 'a1-sh-016',
    text: "I don't understand. Can you repeat that?",
    context: 'Asking for help',
    focus: 'pacing',
    note: `Pause after "understand." Then ask slowly. "Can you" softens to "c'n-yuh".`,
    audio: 'a1-sh-016.ogg',
  },
  {
    id: 'a1-sh-017',
    text: "Let's go! I'm ready.",
    context: 'Starting out',
    focus: 'stress',
    note: `Punch "GO" and "READY". Bright and energetic, short and sharp.`,
    audio: 'a1-sh-017.ogg',
  },
  {
    id: 'a1-sh-018',
    text: 'This is really good!',
    context: 'Enjoying food',
    focus: 'intonation',
    note: `Jump your pitch up on "REALLY GOOD" to sound happy, not flat.`,
    audio: 'a1-sh-018.ogg',
  },
  {
    id: 'a1-sh-019',
    text: 'Excuse me, can you help me?',
    context: 'Asking a stranger',
    focus: 'intonation',
    note: `Gentle rise on "excuse me", then "help me?" lifts politely at the end.`,
    audio: 'a1-sh-019.ogg',
  },
  {
    id: 'a1-sh-020',
    text: "No, thank you. I'm fine.",
    context: 'Politely saying no',
    focus: 'pacing',
    note: `Small pause after "No,". Keep it warm so it sounds kind, not cold.`,
    audio: 'a1-sh-020.ogg',
  },
  {
    id: 'a1-sh-021',
    text: "What's your name?",
    context: 'Meeting someone',
    focus: 'reduction',
    note: `"What's your" runs together: "wuts-yer-name?" The pitch falls gently.`,
    audio: 'a1-sh-021.ogg',
  },
  {
    id: 'a1-sh-022',
    text: 'See you next week!',
    context: 'Saying goodbye',
    focus: 'linking',
    note: `Link "See you" to "see-yuh". Lift "next WEEK" to sound friendly.`,
    audio: 'a1-sh-022.ogg',
  },
  {
    id: 'a1-sh-023',
    text: "I'm so tired today.",
    context: 'Talking about how you feel',
    focus: 'stress',
    note: `Stretch and stress "SO TIRED". Let your voice drop to show the feeling.`,
    audio: 'a1-sh-023.ogg',
  },
  {
    id: 'a1-sh-024',
    text: 'Can you speak more slowly, please?',
    context: 'Asking for help',
    focus: 'pacing',
    note: `Say it slowly yourself! Stress "SLOWLY". "Can you" softens to "c'n-yuh".`,
    audio: 'a1-sh-024.ogg',
  },
  {
    id: 'a1-sh-025',
    text: 'Happy birthday! This is for you.',
    context: 'Giving a gift',
    focus: 'intonation',
    note: `Big, bright pitch on "HAPPY BIRTHDAY". Warm fall on "for you".`,
    audio: 'a1-sh-025.ogg',
  },
  {
    id: 'a1-sh-026',
    text: "I'll take this one, please.",
    context: 'Buying something',
    focus: 'stress',
    note: `Stress "THIS ONE". "I'll take" is light and quick before it.`,
    audio: 'a1-sh-026.ogg',
  },
  {
    id: 'a1-sh-027',
    text: 'Where is the train station?',
    context: 'Asking for directions',
    focus: 'linking',
    note: `Link "Where is the" to "where-iz-the". Stress "TRAIN STATION".`,
    audio: 'a1-sh-027.ogg',
  },
  {
    id: 'a1-sh-028',
    text: "It's over there, on the left.",
    context: 'Giving directions',
    focus: 'pacing',
    note: `Pause after "there,". Point with your voice as you say "on the LEFT".`,
    audio: 'a1-sh-028.ogg',
  },
  {
    id: 'a1-sh-029',
    text: 'Are you okay?',
    context: 'Checking on someone',
    focus: 'intonation',
    note: `Let "okay?" rise softly to show you care. "Are you" blurs to "er-yuh".`,
    audio: 'a1-sh-029.ogg',
  },
  {
    id: 'a1-sh-030',
    text: 'Let me check my phone.',
    context: 'Looking something up',
    focus: 'reduction',
    note: `"Let me" becomes "lemme": "Lemme check my phone." Casual and quick.`,
    audio: 'a1-sh-030.ogg',
  },
  {
    id: 'a1-sh-031',
    text: "I'm hungry. Let's eat.",
    context: 'Suggesting a meal',
    focus: 'stress',
    note: `Stress "HUNGRY" and "EAT". Two short beats, full of energy.`,
    audio: 'a1-sh-031.ogg',
  },
  {
    id: 'a1-sh-032',
    text: 'Wait for me, please!',
    context: 'Calling out',
    focus: 'stress',
    note: `Stress "WAIT" and "ME". "for" almost disappears: "wait-fer-me".`,
    audio: 'a1-sh-032.ogg',
  },
  {
    id: 'a1-sh-033',
    text: 'Can I sit here?',
    context: 'Finding a seat',
    focus: 'intonation',
    note: `"Can I" links to "c'nai". Let "here?" rise at the end to ask politely.`,
    audio: 'a1-sh-033.ogg',
  },
  {
    id: 'a1-sh-034',
    text: "That's a great idea!",
    context: 'Reacting to a suggestion',
    focus: 'intonation',
    note: `Jump up on "GREAT IDEA" to sound excited and encouraging.`,
    audio: 'a1-sh-034.ogg',
  },
  {
    id: 'a1-sh-035',
    text: 'I have a question.',
    context: 'In a class or meeting',
    focus: 'linking',
    note: `Link "have a" to "ha-va". Stress "QUESTION".`,
    audio: 'a1-sh-035.ogg',
  },
  {
    id: 'a1-sh-036',
    text: 'Call me later, okay?',
    context: 'Ending a call',
    focus: 'intonation',
    note: `Falling pitch on "later", then a small rise on "okay?" to check.`,
    audio: 'a1-sh-036.ogg',
  },
  {
    id: 'a1-sh-037',
    text: "It's too expensive for me.",
    context: 'Shopping',
    focus: 'stress',
    note: `Stretch "TOO expensive". "for me" trails off quietly.`,
    audio: 'a1-sh-037.ogg',
  },
  {
    id: 'a1-sh-038',
    text: 'Have a nice day!',
    context: 'A friendly goodbye',
    focus: 'linking',
    note: `Link "Have a" to "ha-va". Warm, rising melody on "nice DAY".`,
    audio: 'a1-sh-038.ogg',
  },
  {
    id: 'a1-sh-039',
    text: "I'm not sure. Maybe.",
    context: 'Being unsure',
    focus: 'pacing',
    note: `Pause after "sure." Say "Maybe" slowly, with a thinking tone.`,
    audio: 'a1-sh-039.ogg',
  },
  {
    id: 'a1-sh-040',
    text: 'Thank you for your help.',
    context: 'Thanking someone',
    focus: 'reduction',
    note: `"for your" blurs to "fer-yer": "Thank-you-fer-yer-help." Warm and even.`,
    audio: 'a1-sh-040.ogg',
  },
];
