/**
 * B1 (intermediate) shadowing clips.
 *
 * Real conversation now: opinions, gentle disagreement, telling a short story,
 * polite requests at work. This is where connected speech (linking and weak
 * forms) starts to matter for sounding natural. Listen, then say it WITH the
 * speaker, matching the stress and the flow.
 */
import type { ShadowingClip } from '../types';

export const b1Shadowing: ShadowingClip[] = [
  {
    id: 'b1-sh-001',
    text: "Honestly, I think it's worth a try.",
    context: 'Sharing an opinion',
    focus: 'stress',
    note: `Lean on "HONESTLY" and "WORTH A TRY". The "I think it's" is fast and low.`,
    audio: 'b1-sh-001.ogg',
  },
  {
    id: 'b1-sh-002',
    text: "I see your point, but I'm not so sure.",
    context: 'Disagreeing gently',
    focus: 'pacing',
    note: `Pause after "point," then drop your pitch on "not so sure" to soften it.`,
    audio: 'b1-sh-002.ogg',
  },
  {
    id: 'b1-sh-003',
    text: 'So, the other day, I ran into an old friend.',
    context: 'Telling a story',
    focus: 'linking',
    note: `"ran into an" links to "ra-nin-tu-an". Keep "the other day" quick and casual.`,
    audio: 'b1-sh-003.ogg',
  },
  {
    id: 'b1-sh-004',
    text: 'Would you mind sending me the file?',
    context: 'A polite request at work',
    focus: 'reduction',
    note: `"Would you" becomes "wouldja". Keep "sending me the file" smooth and even.`,
    audio: 'b1-sh-004.ogg',
  },
  {
    id: 'b1-sh-005',
    text: "It's not a big deal, but it's a bit annoying.",
    context: 'Talking about a small problem',
    focus: 'stress',
    note: `Contrast "not a BIG deal" with "bit ANNOYING". Let that contrast carry the line.`,
    audio: 'b1-sh-005.ogg',
  },
  {
    id: 'b1-sh-006',
    text: "Yeah, exactly, that's what I was thinking.",
    context: 'Agreeing with someone',
    focus: 'intonation',
    note: `Ride the energy: rise on "EXACTLY", then land warmly on "thinking".`,
    audio: 'b1-sh-006.ogg',
  },
  {
    id: 'b1-sh-007',
    text: "We're hoping to launch it by the end of the month.",
    context: 'Describing a plan',
    focus: 'pacing',
    note: `Group it: "We're hoping / to launch it / by the end of the month."`,
    audio: 'b1-sh-007.ogg',
  },
  {
    id: 'b1-sh-008',
    text: 'Oh no, that sounds really frustrating.',
    context: 'Showing empathy',
    focus: 'intonation',
    note: `Soften and slow down. Let your pitch fall gently on "frustrating".`,
    audio: 'b1-sh-008.ogg',
  },
  {
    id: 'b1-sh-009',
    text: 'So, just to make sure, you need it by Friday?',
    context: 'Checking you understood',
    focus: 'intonation',
    note: `End on a clear rise at "Friday" to confirm. Keep the front part light.`,
    audio: 'b1-sh-009.ogg',
  },
  {
    id: 'b1-sh-010',
    text: 'Not much, just taking it easy this week.',
    context: 'A casual catch-up',
    focus: 'reduction',
    note: `"taking it easy" blends to "tay-ki-ni-zy". Relaxed, low energy on purpose.`,
    audio: 'b1-sh-010.ogg',
  },
  {
    id: 'b1-sh-011',
    text: "I'm really looking forward to it.",
    context: 'Showing excitement',
    focus: 'stress',
    note: `Stress "REALLY" and "FORWARD". Let the excitement show in your pitch.`,
    audio: 'b1-sh-011.ogg',
  },
  {
    id: 'b1-sh-012',
    text: "To be honest, I'd rather stay in tonight.",
    context: 'Saying what you prefer',
    focus: 'pacing',
    note: `Pause after "honest,". "I'd rather" links to "I-drather".`,
    audio: 'b1-sh-012.ogg',
  },
  {
    id: 'b1-sh-013',
    text: "That's a good point, I hadn't thought of that.",
    context: 'Agreeing in a discussion',
    focus: 'stress',
    note: `Stress "GOOD POINT". "hadn't" reduces to "had-n".`,
    audio: 'b1-sh-013.ogg',
  },
  {
    id: 'b1-sh-014',
    text: 'Could you walk me through it?',
    context: 'Asking for an explanation',
    focus: 'reduction',
    note: `"Could you" softens to "couldja". "walk me through" flows together.`,
    audio: 'b1-sh-014.ogg',
  },
  {
    id: 'b1-sh-015',
    text: "I'm a bit swamped at the moment.",
    context: 'Saying you are busy',
    focus: 'stress',
    note: `Stress "SWAMPED". "at the moment" trails off quickly and quietly.`,
    audio: 'b1-sh-015.ogg',
  },
  {
    id: 'b1-sh-016',
    text: "Let's give it a shot.",
    context: 'Deciding to try',
    focus: 'linking',
    note: `"give it a" links to "gi-vi-da". Confident fall on "SHOT".`,
    audio: 'b1-sh-016.ogg',
  },
  {
    id: 'b1-sh-017',
    text: 'I see what you mean.',
    context: 'Showing you understand',
    focus: 'stress',
    note: `Stress "SEE" and "MEAN". Put a nod into your voice.`,
    audio: 'b1-sh-017.ogg',
  },
  {
    id: 'b1-sh-018',
    text: 'Can we touch base tomorrow?',
    context: 'Planning a work chat',
    focus: 'pacing',
    note: `Stress "TOUCH BASE". Let "tomorrow?" rise softly at the end.`,
    audio: 'b1-sh-018.ogg',
  },
  {
    id: 'b1-sh-019',
    text: "I'll keep that in mind.",
    context: 'Taking advice',
    focus: 'reduction',
    note: `"keep that in mind" flows: "keep-tha-tin-mind". Calm and sincere.`,
    audio: 'b1-sh-019.ogg',
  },
  {
    id: 'b1-sh-020',
    text: 'It depends on the situation, really.',
    context: 'Giving a careful answer',
    focus: 'pacing',
    note: `Stress "DEPENDS". Drop "really" softly at the end.`,
    audio: 'b1-sh-020.ogg',
  },
  {
    id: 'b1-sh-021',
    text: "I'm not too sure about that.",
    context: 'Showing doubt',
    focus: 'stress',
    note: `Stress "NOT" and "SURE". Use a hesitant, slightly falling tone.`,
    audio: 'b1-sh-021.ogg',
  },
  {
    id: 'b1-sh-022',
    text: 'Let me get back to you on that.',
    context: 'Buying time',
    focus: 'reduction',
    note: `"get back to you" links smoothly. "on that" is light and quick.`,
    audio: 'b1-sh-022.ogg',
  },
  {
    id: 'b1-sh-023',
    text: 'That makes total sense.',
    context: 'Understanding an explanation',
    focus: 'stress',
    note: `Stress "TOTAL SENSE". Warm, agreeing tone.`,
    audio: 'b1-sh-023.ogg',
  },
  {
    id: 'b1-sh-024',
    text: "I'd appreciate your help with this.",
    context: 'Asking politely',
    focus: 'stress',
    note: `Stress "APPRECIATE". Sincere and polite, not rushed.`,
    audio: 'b1-sh-024.ogg',
  },
  {
    id: 'b1-sh-025',
    text: "We're on the same page.",
    context: 'Confirming agreement',
    focus: 'linking',
    note: `"on the same" links together. Confident fall on "PAGE".`,
    audio: 'b1-sh-025.ogg',
  },
  {
    id: 'b1-sh-026',
    text: 'Sorry to interrupt, but quick question.',
    context: 'Jumping into a meeting',
    focus: 'pacing',
    note: `Pause after "interrupt,". Keep "quick question" light and fast.`,
    audio: 'b1-sh-026.ogg',
  },
  {
    id: 'b1-sh-027',
    text: "I'll do my best.",
    context: 'Promising effort',
    focus: 'stress',
    note: `Stress "BEST". Short, sincere, and a little firm.`,
    audio: 'b1-sh-027.ogg',
  },
  {
    id: 'b1-sh-028',
    text: "That's easier said than done.",
    context: 'Reacting to a big idea',
    focus: 'stress',
    note: `Stress "EASIER" and "DONE". Use a knowing, slightly wry tone.`,
    audio: 'b1-sh-028.ogg',
  },
  {
    id: 'b1-sh-029',
    text: 'Can you fill me in later?',
    context: 'Catching up on news',
    focus: 'reduction',
    note: `"fill me in" links to "fi-mee-in". Let "later?" rise at the end.`,
    audio: 'b1-sh-029.ogg',
  },
  {
    id: 'b1-sh-030',
    text: "I totally get where you're coming from.",
    context: 'Showing empathy',
    focus: 'pacing',
    note: `"where you're coming from" runs together quickly. Warm, even tone.`,
    audio: 'b1-sh-030.ogg',
  },
  {
    id: 'b1-sh-031',
    text: "Let's play it by ear.",
    context: 'Keeping plans loose',
    focus: 'linking',
    note: `"play it by ear" flows as one idiom: "play-i-by-ear".`,
    audio: 'b1-sh-031.ogg',
  },
  {
    id: 'b1-sh-032',
    text: "I'm leaning toward the first option.",
    context: 'Sharing a preference',
    focus: 'stress',
    note: `Stress "FIRST OPTION". "leaning toward" is smooth and quick.`,
    audio: 'b1-sh-032.ogg',
  },
  {
    id: 'b1-sh-033',
    text: 'That would be a huge help.',
    context: 'Accepting an offer',
    focus: 'stress',
    note: `Stress "HUGE HELP". Grateful, warm tone.`,
    audio: 'b1-sh-033.ogg',
  },
  {
    id: 'b1-sh-034',
    text: 'Let me double-check and get back to you.',
    context: 'Confirming details',
    focus: 'pacing',
    note: `Pause after "double-check". Keep an even, calm pace.`,
    audio: 'b1-sh-034.ogg',
  },
  {
    id: 'b1-sh-035',
    text: "I'm afraid I can't make it.",
    context: 'Declining an invitation',
    focus: 'stress',
    note: `Stress "CAN'T". Gentle, apologetic fall at the end.`,
    audio: 'b1-sh-035.ogg',
  },
  {
    id: 'b1-sh-036',
    text: "It's worth a try, I think.",
    context: 'Suggesting an idea',
    focus: 'stress',
    note: `Stress "WORTH A TRY". "I think" drops softly at the end.`,
    audio: 'b1-sh-036.ogg',
  },
  {
    id: 'b1-sh-037',
    text: 'Could we go over this again?',
    context: 'Asking to review',
    focus: 'reduction',
    note: `"Could we" softens to "could-we". "go over this" links smoothly.`,
    audio: 'b1-sh-037.ogg',
  },
  {
    id: 'b1-sh-038',
    text: 'Thanks for the heads up.',
    context: 'Reacting to a warning',
    focus: 'linking',
    note: `"heads up" links to "head-zup". Warm and quick.`,
    audio: 'b1-sh-038.ogg',
  },
  {
    id: 'b1-sh-039',
    text: "I'll take care of it.",
    context: 'Accepting a task',
    focus: 'stress',
    note: `Stress "TAKE CARE". Confident, reassuring fall.`,
    audio: 'b1-sh-039.ogg',
  },
  {
    id: 'b1-sh-040',
    text: "Let's stay in touch.",
    context: 'Saying goodbye',
    focus: 'linking',
    note: `"stay in touch" flows together. Warm rise on "TOUCH".`,
    audio: 'b1-sh-040.ogg',
  },
  {
    id: 'b1-sh-041',
    text: 'I was wondering if you could help me out.',
    context: 'Asking a favour',
    focus: 'reduction',
    note: `"could you" softens to "c'd-ya". Make the whole line easy and polite.`,
    audio: 'b1-sh-041.ogg',
  },
  {
    id: 'b1-sh-042',
    text: 'Honestly, I could go either way.',
    context: 'Staying neutral on a choice',
    focus: 'reduction',
    note: `"could go either way" means no strong preference. Relaxed.`,
    audio: 'b1-sh-042.ogg',
  },
  {
    id: 'b1-sh-043',
    text: 'Let me know if that works for you.',
    context: 'Confirming plans',
    focus: 'linking',
    note: `"works for you" flows together, with a friendly fall at the end.`,
    audio: 'b1-sh-043.ogg',
  },
  {
    id: 'b1-sh-044',
    text: "I'm really looking forward to the weekend.",
    context: 'Talking about plans',
    focus: 'stress',
    note: `Punch "LOOKING FORWARD". Bright and upbeat.`,
    audio: 'b1-sh-044.ogg',
  },
  {
    id: 'b1-sh-045',
    text: 'It depends on how busy I am.',
    context: 'Giving a conditional answer',
    focus: 'pacing',
    note: `A slight pause before "how busy". Sounds thoughtful, not vague.`,
    audio: 'b1-sh-045.ogg',
  },
  {
    id: 'b1-sh-046',
    text: 'That sounds like a great idea to me.',
    context: 'Agreeing with a suggestion',
    focus: 'intonation',
    note: `Warm rise on "GREAT", soft fall on "me". Sound pleased.`,
    audio: 'b1-sh-046.ogg',
  },
  {
    id: 'b1-sh-047',
    text: "I'll get back to you by the end of the day.",
    context: 'Promising a reply',
    focus: 'reduction',
    note: `"get back to you" softens to "ge-back-to-ya".`,
    audio: 'b1-sh-047.ogg',
  },
  {
    id: 'b1-sh-048',
    text: "That's totally fine by me.",
    context: 'Agreeing to a plan',
    focus: 'stress',
    note: `Punch "TOTALLY FINE". Easy and reassuring.`,
    audio: 'b1-sh-048.ogg',
  },
  {
    id: 'b1-sh-049',
    text: "I'm going to need a bit more time.",
    context: 'Asking for an extension',
    focus: 'reduction',
    note: `"going to" becomes "gonna": "I'm-gonna-need".`,
    audio: 'b1-sh-049.ogg',
  },
  {
    id: 'b1-sh-050',
    text: 'Do you happen to know where it is?',
    context: 'Asking politely',
    focus: 'linking',
    note: `"happen to" runs to "happen-tuh". Soft and polite.`,
    audio: 'b1-sh-050.ogg',
  },
  {
    id: 'b1-sh-051',
    text: 'I completely forgot about that.',
    context: 'Admitting a slip',
    focus: 'stress',
    note: `Punch "COMPLETELY". A light, honest tone.`,
    audio: 'b1-sh-051.ogg',
  },
  {
    id: 'b1-sh-052',
    text: "Let's split it down the middle.",
    context: 'Sharing a cost',
    focus: 'linking',
    note: `"split it down" flows together. Fair and breezy.`,
    audio: 'b1-sh-052.ogg',
  },
  {
    id: 'b1-sh-053',
    text: "I'll keep you posted.",
    context: 'Promising updates',
    focus: 'reduction',
    note: `"keep you" blurs to "kee-pya". Brisk and warm.`,
    audio: 'b1-sh-053.ogg',
  },
  {
    id: 'b1-sh-054',
    text: 'Thanks for bearing with me.',
    context: 'After a delay',
    focus: 'linking',
    note: `"bearing with" runs together. Genuine and grateful.`,
    audio: 'b1-sh-054.ogg',
  },
  {
    id: 'b1-sh-055',
    text: 'Let me run something by you.',
    context: 'Floating an idea',
    focus: 'linking',
    note: `"run something by you" flows together. Casual and collegial.`,
    audio: 'b1-sh-055.ogg',
  },
  {
    id: 'b1-sh-056',
    text: "I'm in two minds about it.",
    context: 'Being undecided',
    focus: 'pacing',
    note: `Pause before "about it". Sounds genuinely torn.`,
    audio: 'b1-sh-056.ogg',
  },
  {
    id: 'b1-sh-057',
    text: "That's a weight off my shoulders.",
    context: 'Feeling relieved',
    focus: 'stress',
    note: `Stress "WEIGHT" and "SHOULDERS". Sound relieved.`,
    audio: 'b1-sh-057.ogg',
  },
  {
    id: 'b1-sh-058',
    text: "Let's touch on that later.",
    context: 'Deferring a point',
    focus: 'linking',
    note: `"touch on that" runs together. Brisk and easy.`,
    audio: 'b1-sh-058.ogg',
  },
  {
    id: 'b1-sh-059',
    text: "I'll see what I can do.",
    context: 'Offering tentative help',
    focus: 'reduction',
    note: `"what I can" softens to "wod-I-kn". Warm, no promise.`,
    audio: 'b1-sh-059.ogg',
  },
  {
    id: 'b1-sh-060',
    text: "It's not the end of the world.",
    context: 'Reassuring someone',
    focus: 'pacing',
    note: `Keep an even, calm pace. Light and kind.`,
    audio: 'b1-sh-060.ogg',
  },
  {
    id: 'b1-sh-061',
    text: "I'll be honest with you.",
    context: 'Being frank',
    focus: 'reduction',
    note: `"I'll be" softens to "I'll-be". Warm and direct.`,
    audio: 'b1-sh-061.ogg',
  },
  {
    id: 'b1-sh-062',
    text: "Let's pencil it in for Friday.",
    context: 'Making a tentative plan',
    focus: 'linking',
    note: `"pencil it in" runs together. It means a not-yet-fixed plan.`,
    audio: 'b1-sh-062.ogg',
  },
  {
    id: 'b1-sh-063',
    text: "That's a relief, honestly.",
    context: 'Feeling relieved',
    focus: 'stress',
    note: `Stress "RELIEF". Let the breath out as you say it.`,
    audio: 'b1-sh-063.ogg',
  },
  {
    id: 'b1-sh-064',
    text: "I'd appreciate a second opinion.",
    context: 'Asking for advice',
    focus: 'reduction',
    note: `"I'd appreciate a" blurs together. Polite and warm.`,
    audio: 'b1-sh-064.ogg',
  },
  {
    id: 'b1-sh-065',
    text: 'Can we go over this one more time?',
    context: 'Asking to review',
    focus: 'linking',
    note: `"go over this" runs together. A patient tone.`,
    audio: 'b1-sh-065.ogg',
  },
  {
    id: 'b1-sh-066',
    text: "I'm doing my best to keep up.",
    context: 'Coping with a lot',
    focus: 'reduction',
    note: `"keep up" links; sound a little stretched but okay.`,
    audio: 'b1-sh-066.ogg',
  },
];
