/**
 * B2 (upper-intermediate) shadowing clips.
 *
 * Confident, natural lines for real discussions: balanced views, polite push
 * back, anecdotes, light negotiation. Connected speech is heavier here, so the
 * tips focus on blending words and controlling pace. Listen, then shadow it,
 * copying the speaker's calm, fluent delivery.
 */
import type { ShadowingClip } from '../types';

export const b2Shadowing: ShadowingClip[] = [
  {
    id: 'b2-sh-001',
    text: 'To be fair, there are pros and cons either way.',
    context: 'Giving a balanced view',
    focus: 'stress',
    note: `Stress "FAIR", "PROS", "CONS". "there are" reduces to "there're".`,
    audio: 'b2-sh-001.ogg',
  },
  {
    id: 'b2-sh-002',
    text: "I get where you're coming from, but I'd push back a little.",
    context: 'Pushing back politely',
    focus: 'pacing',
    note: `Pause just before "but". "where you're coming from" runs together quickly.`,
    audio: 'b2-sh-002.ogg',
  },
  {
    id: 'b2-sh-003',
    text: 'Long story short, we ended up missing the train.',
    context: 'Telling an anecdote',
    focus: 'linking',
    note: `"ended up" links to "en-de-dup". Keep "long story short" brisk, as one set phrase.`,
    audio: 'b2-sh-003.ogg',
  },
  {
    id: 'b2-sh-004',
    text: 'Could we maybe meet in the middle on this?',
    context: 'Negotiating',
    focus: 'reduction',
    note: `"Could we" softens to "could-we", "maybe" almost "mebbe". Keep it easygoing.`,
    audio: 'b2-sh-004.ogg',
  },
  {
    id: 'b2-sh-005',
    text: "I'm not entirely convinced, to be honest.",
    context: 'Expressing doubt',
    focus: 'intonation',
    note: `Let your pitch drop slowly across "convinced" to signal genuine hesitation.`,
    audio: 'b2-sh-005.ogg',
  },
  {
    id: 'b2-sh-006',
    text: 'You really nailed it. That was spot on.',
    context: 'Complimenting good work',
    focus: 'stress',
    note: `Hit "NAILED" and "SPOT ON" hard. Short, punchy, confident delivery.`,
    audio: 'b2-sh-006.ogg',
  },
  {
    id: 'b2-sh-007',
    text: "I'll do my best, but I can't promise anything.",
    context: 'Managing expectations',
    focus: 'pacing',
    note: `Even rhythm, with a small pause before "but". Calm and matter of fact.`,
    audio: 'b2-sh-007.ogg',
  },
  {
    id: 'b2-sh-008',
    text: "Anyway, moving on, what's the plan for Friday?",
    context: 'Changing the subject',
    focus: 'intonation',
    note: `Throw away "anyway, moving on" quickly, then lift into the real question.`,
    audio: 'b2-sh-008.ogg',
  },
  {
    id: 'b2-sh-009',
    text: "Don't worry about it, these things happen.",
    context: 'Reassuring someone',
    focus: 'reduction',
    note: `"about it" links to "uh-bow-dit". Use a warm, falling tone to comfort them.`,
    audio: 'b2-sh-009.ogg',
  },
  {
    id: 'b2-sh-010',
    text: 'Looking back, I probably should have said something.',
    context: 'Reflecting on the past',
    focus: 'pacing',
    note: `Pause after "Looking back," then let the regret show in a slower second half.`,
    audio: 'b2-sh-010.ogg',
  },
  {
    id: 'b2-sh-011',
    text: "I'd say it's worth considering, at least.",
    context: 'Floating an idea',
    focus: 'pacing',
    note: `Keep an even pace. Drop "at least" quietly at the very end.`,
    audio: 'b2-sh-011.ogg',
  },
  {
    id: 'b2-sh-012',
    text: "Let's not jump to conclusions just yet.",
    context: 'Slowing a discussion down',
    focus: 'stress',
    note: `Stress "JUMP" and "CONCLUSIONS". "just yet" is light at the end.`,
    audio: 'b2-sh-012.ogg',
  },
  {
    id: 'b2-sh-013',
    text: "Just to play devil's advocate for a second.",
    context: 'Testing an argument',
    focus: 'pacing',
    note: `Keep the idiom quick. Pause after it before you make your point.`,
    audio: 'b2-sh-013.ogg',
  },
  {
    id: 'b2-sh-014',
    text: "That's not quite what I had in mind.",
    context: 'Correcting gently',
    focus: 'stress',
    note: `Stress "NOT QUITE". "had in mind" links smoothly together.`,
    audio: 'b2-sh-014.ogg',
  },
  {
    id: 'b2-sh-015',
    text: "I'm inclined to agree with you.",
    context: 'Agreeing thoughtfully',
    focus: 'reduction',
    note: `"inclined to" blurs to "inclined-tuh". Measured, calm tone.`,
    audio: 'b2-sh-015.ogg',
  },
  {
    id: 'b2-sh-016',
    text: "Let's circle back to that later.",
    context: 'Postponing a topic',
    focus: 'linking',
    note: `"circle back" flows together. "to that" is light and quick.`,
    audio: 'b2-sh-016.ogg',
  },
  {
    id: 'b2-sh-017',
    text: "It's a tricky one, to be fair.",
    context: 'Acknowledging difficulty',
    focus: 'pacing',
    note: `Stress "TRICKY". Drop "to be fair" softly at the end.`,
    audio: 'b2-sh-017.ogg',
  },
  {
    id: 'b2-sh-018',
    text: 'I can see both sides of it.',
    context: 'Staying balanced',
    focus: 'stress',
    note: `Stress "BOTH SIDES". Even, balanced delivery throughout.`,
    audio: 'b2-sh-018.ogg',
  },
  {
    id: 'b2-sh-019',
    text: "We'll have to agree to disagree.",
    context: 'Ending a debate kindly',
    focus: 'stress',
    note: `Stress "AGREE" and "DISAGREE". Keep a light, friendly tone.`,
    audio: 'b2-sh-019.ogg',
  },
  {
    id: 'b2-sh-020',
    text: "That's a load off my mind.",
    context: 'Feeling relieved',
    focus: 'linking',
    note: `"load off" links to "loa-doff". Use a relieved, falling tone.`,
    audio: 'b2-sh-020.ogg',
  },
  {
    id: 'b2-sh-021',
    text: 'Let me play it back to you.',
    context: 'Confirming understanding',
    focus: 'reduction',
    note: `"play it back" flows: "play-i-back". Calm and clear.`,
    audio: 'b2-sh-021.ogg',
  },
  {
    id: 'b2-sh-022',
    text: "I'd take that with a grain of salt.",
    context: 'Reacting to a claim',
    focus: 'stress',
    note: `Keep the idiom smooth. Stress "GRAIN OF SALT".`,
    audio: 'b2-sh-022.ogg',
  },
  {
    id: 'b2-sh-023',
    text: "It's a bit of a mixed bag, honestly.",
    context: 'Giving a so-so review',
    focus: 'reduction',
    note: `"bit of a" blurs to "bi-duv-a". Drop "honestly" softly at the end.`,
    audio: 'b2-sh-023.ogg',
  },
  {
    id: 'b2-sh-024',
    text: "Let's nail down the details.",
    context: 'Getting specific',
    focus: 'stress',
    note: `Stress "NAIL DOWN". Firm and businesslike.`,
    audio: 'b2-sh-024.ogg',
  },
  {
    id: 'b2-sh-025',
    text: "I'm on the fence about it.",
    context: 'Being undecided',
    focus: 'linking',
    note: `"on the fence" flows together. "about it" is light.`,
    audio: 'b2-sh-025.ogg',
  },
  {
    id: 'b2-sh-026',
    text: 'That caught me off guard.',
    context: 'Reacting to a surprise',
    focus: 'linking',
    note: `"off guard" links to "off-gard". Use a surprised tone.`,
    audio: 'b2-sh-026.ogg',
  },
  {
    id: 'b2-sh-027',
    text: "Let's give it the benefit of the doubt.",
    context: 'Being generous',
    focus: 'pacing',
    note: `Keep the idiom flowing. Use an even, generous tone.`,
    audio: 'b2-sh-027.ogg',
  },
  {
    id: 'b2-sh-028',
    text: "I'll run it by the team first.",
    context: 'Checking with others',
    focus: 'reduction',
    note: `"run it by" flows: "ru-ni-by". "first" lands firm at the end.`,
    audio: 'b2-sh-028.ogg',
  },
  {
    id: 'b2-sh-029',
    text: "That's easier than I expected.",
    context: 'Pleasantly surprised',
    focus: 'stress',
    note: `Stress "EASIER". Use a lighter, pleasantly surprised tone.`,
    audio: 'b2-sh-029.ogg',
  },
  {
    id: 'b2-sh-030',
    text: "We're cutting it a bit fine.",
    context: 'Running low on time',
    focus: 'stress',
    note: `Stress "FINE". Use a slightly tense, urgent tone.`,
    audio: 'b2-sh-030.ogg',
  },
  {
    id: 'b2-sh-031',
    text: "Let's keep our options open.",
    context: 'Staying flexible',
    focus: 'stress',
    note: `Stress "OPTIONS OPEN". Calm and strategic.`,
    audio: 'b2-sh-031.ogg',
  },
  {
    id: 'b2-sh-032',
    text: "I'd rather err on the side of caution.",
    context: 'Being careful',
    focus: 'pacing',
    note: `Keep "err on the side of caution" smooth and measured.`,
    audio: 'b2-sh-032.ogg',
  },
  {
    id: 'b2-sh-033',
    text: "That's food for thought.",
    context: 'Reacting to an idea',
    focus: 'stress',
    note: `Stress "FOOD" and "THOUGHT". Thoughtful, falling tone.`,
    audio: 'b2-sh-033.ogg',
  },
  {
    id: 'b2-sh-034',
    text: 'Let me sleep on it.',
    context: 'Delaying a decision',
    focus: 'reduction',
    note: `"sleep on it" flows: "slee-po-nit". Easy and unhurried.`,
    audio: 'b2-sh-034.ogg',
  },
  {
    id: 'b2-sh-035',
    text: "I'll believe it when I see it.",
    context: 'Friendly skepticism',
    focus: 'stress',
    note: `Stress "SEE IT". Add a touch of playful doubt.`,
    audio: 'b2-sh-035.ogg',
  },
  {
    id: 'b2-sh-036',
    text: "We're more or less on track.",
    context: 'Giving a status update',
    focus: 'reduction',
    note: `"more or less" blurs to "mor-er-less". Reassuring tone.`,
    audio: 'b2-sh-036.ogg',
  },
  {
    id: 'b2-sh-037',
    text: "That's a step in the right direction.",
    context: 'Encouraging progress',
    focus: 'stress',
    note: `Stress "RIGHT DIRECTION". Warm and encouraging.`,
    audio: 'b2-sh-037.ogg',
  },
  {
    id: 'b2-sh-038',
    text: "Let's not overthink it.",
    context: 'Keeping things simple',
    focus: 'stress',
    note: `Stress "OVERTHINK". Light and relaxed.`,
    audio: 'b2-sh-038.ogg',
  },
  {
    id: 'b2-sh-039',
    text: "I'm drawing a blank, sorry.",
    context: 'Forgetting something',
    focus: 'pacing',
    note: `Pause after "blank,". A little apologetic.`,
    audio: 'b2-sh-039.ogg',
  },
  {
    id: 'b2-sh-040',
    text: "That's worth bearing in mind.",
    context: 'Noting something useful',
    focus: 'linking',
    note: `"bearing in mind" flows together. Even and thoughtful.`,
    audio: 'b2-sh-040.ogg',
  },
  {
    id: 'b2-sh-041',
    text: "I see your point, but I'm not entirely convinced.",
    context: 'Disagreeing politely',
    focus: 'pacing',
    note: `Pause after "point". Measured and calm, not hostile.`,
    audio: 'b2-sh-041.ogg',
  },
  {
    id: 'b2-sh-042',
    text: "Let's touch base early next week.",
    context: 'Scheduling a follow-up',
    focus: 'linking',
    note: `"touch base" flows as one. Keep an even, businesslike tone.`,
    audio: 'b2-sh-042.ogg',
  },
  {
    id: 'b2-sh-043',
    text: "I'd appreciate it if you could let me know soon.",
    context: 'Making a polite request',
    focus: 'reduction',
    note: `"appreciate it" blurs to "appreciate-it". Warm and unhurried.`,
    audio: 'b2-sh-043.ogg',
  },
  {
    id: 'b2-sh-044',
    text: 'To cut a long story short, we missed the train.',
    context: 'Summarising quickly',
    focus: 'stress',
    note: `Punch "SHORT", then drop into the result. Brisk and clear.`,
    audio: 'b2-sh-044.ogg',
  },
  {
    id: 'b2-sh-045',
    text: "It's not really my area, to be honest.",
    context: 'Saying it is not your expertise',
    focus: 'reduction',
    note: `"to be honest" softens to "t'be-honest". Modest and easy.`,
    audio: 'b2-sh-045.ogg',
  },
  {
    id: 'b2-sh-046',
    text: "That's a fair point, I hadn't thought of that.",
    context: 'Conceding in a discussion',
    focus: 'intonation',
    note: `Fall on "fair point", small rise of surprise on "that".`,
    audio: 'b2-sh-046.ogg',
  },
  {
    id: 'b2-sh-047',
    text: "I'll loop you in once I hear back.",
    context: 'Promising a work follow-up',
    focus: 'linking',
    note: `"loop you in" runs to "loo-pyu-in". Easy, collegial.`,
    audio: 'b2-sh-047.ogg',
  },
  {
    id: 'b2-sh-048',
    text: "Let's park that for now and move on.",
    context: 'Setting a topic aside',
    focus: 'pacing',
    note: `Pause after "park that". Calm and decisive.`,
    audio: 'b2-sh-048.ogg',
  },
  {
    id: 'b2-sh-049',
    text: "I'm happy to take the lead on this.",
    context: 'Volunteering',
    focus: 'stress',
    note: `Punch "HAPPY" and "LEAD". Warm and willing.`,
    audio: 'b2-sh-049.ogg',
  },
  {
    id: 'b2-sh-050',
    text: 'Can we ballpark the budget first?',
    context: 'Planning costs',
    focus: 'linking',
    note: `"ballpark the" flows together. A practical tone.`,
    audio: 'b2-sh-050.ogg',
  },
  {
    id: 'b2-sh-051',
    text: "That's a fair compromise, I'd say.",
    context: 'Settling a debate',
    focus: 'pacing',
    note: `Small pause before "I'd say". Measured and fair.`,
    audio: 'b2-sh-051.ogg',
  },
  {
    id: 'b2-sh-052',
    text: "I don't want to step on anyone's toes.",
    context: 'Being careful with others',
    focus: 'reduction',
    note: `"want to" becomes "wanna". Considerate and light.`,
    audio: 'b2-sh-052.ogg',
  },
  {
    id: 'b2-sh-053',
    text: "Let's make sure we're on the same wavelength.",
    context: 'Checking alignment',
    focus: 'linking',
    note: `"on the same" runs together. A collaborative tone.`,
    audio: 'b2-sh-053.ogg',
  },
  {
    id: 'b2-sh-054',
    text: "I'll flag it if anything changes.",
    context: 'Promising to alert someone',
    focus: 'reduction',
    note: `"flag it" blurs to "fla-git". Brisk and helpful.`,
    audio: 'b2-sh-054.ogg',
  },
  {
    id: 'b2-sh-055',
    text: "Let's not get ahead of ourselves.",
    context: 'Slowing things down',
    focus: 'pacing',
    note: `Pause before "of ourselves". Measured and steady.`,
    audio: 'b2-sh-055.ogg',
  },
  {
    id: 'b2-sh-056',
    text: "I'll circle back once I know more.",
    context: 'Promising a follow-up',
    focus: 'linking',
    note: `"circle back" flows together. Businesslike and calm.`,
    audio: 'b2-sh-056.ogg',
  },
  {
    id: 'b2-sh-057',
    text: "That's a bit of a stretch, honestly.",
    context: 'Doubting a claim',
    focus: 'stress',
    note: `Stress "STRETCH". A wry, frank tone.`,
    audio: 'b2-sh-057.ogg',
  },
  {
    id: 'b2-sh-058',
    text: "Let's get everyone on the same page.",
    context: 'Aligning a team',
    focus: 'linking',
    note: `"on the same page" runs together. Collaborative.`,
    audio: 'b2-sh-058.ogg',
  },
  {
    id: 'b2-sh-059',
    text: "I'd rather we didn't rush this.",
    context: 'Urging care',
    focus: 'reduction',
    note: `"didn't" softens and shortens. Calm but firm.`,
    audio: 'b2-sh-059.ogg',
  },
  {
    id: 'b2-sh-060',
    text: "Let's give it a fair shot.",
    context: 'Committing to try',
    focus: 'stress',
    note: `Stress "FAIR SHOT". Encouraging and fair.`,
    audio: 'b2-sh-060.ogg',
  },
];
