/**
 * B1 (intermediate) stories: fuller narratives with a clear arc and a takeaway,
 * using past tenses, time linkers, and a little description.
 */
import type { Story } from '../types';

export const b1Stories: Story[] = [
  {
    id: 'b1-st-001',
    title: 'The two travellers',
    text: 'Two friends were walking through a forest when they met a bear. One of them quickly climbed a tree and hid. The other fell to the ground and pretended to be dead. The bear sniffed him and walked away. Later, the first friend asked, "What did the bear whisper to you?" His friend smiled and said, "Never travel with a friend who leaves you in danger."',
    note: `A classic fable. The lesson lands in the final line of dialogue.`,
    audio: 'b1-st-001.ogg',
  },
  {
    id: 'b1-st-002',
    title: 'The job interview',
    text: 'Priya was very nervous before her first job interview. She had practised her answers for days. When she arrived, she realised she had forgotten her notes. At first she panicked, but then she decided to just be honest and natural. The interview went well, and she got the job. Sometimes being yourself works better than a perfect plan.',
    note: `Notice the past perfect: "she had practised", "she had forgotten".`,
    audio: 'b1-st-002.ogg',
  },
  {
    id: 'b1-st-003',
    title: 'The old guitar',
    text: 'In the corner of a shop sat an old, dusty guitar. Nobody wanted it. One day, a young woman picked it up and played a beautiful song. Suddenly, everyone in the shop stopped to listen. She bought the guitar for almost nothing. The value of a thing often depends on who is holding it.',
    note: `The takeaway is a small idea about value and potential.`,
    audio: 'b1-st-003.ogg',
  },
  {
    id: 'b1-st-004',
    title: 'A long walk home',
    text: 'When Karim missed the last bus, he had to walk an hour home. He was annoyed at first. But the night was quiet and the stars were bright. He passed shops he had never noticed and heard music from an open window. By the time he got home, he felt strangely calm. The slow way showed him things the bus never did.',
    note: `"By the time he got home..." marks the end of the journey and the change.`,
    audio: 'b1-st-004.ogg',
  },
  {
    id: 'b1-st-005',
    title: 'The honest mistake',
    text: 'A waiter gave Lena too much change by mistake. She noticed it outside the café. It was a small amount, and no one would ever know. Still, she went back and returned it. The waiter was surprised and grateful. Lena felt lighter as she walked away. Doing the right thing is often its own reward.',
    note: `"Still" signals she acted against the easy choice.`,
    audio: 'b1-st-005.ogg',
  },
  {
    id: 'b1-st-006',
    title: 'The garden next door',
    text: 'For years, an old man grew vegetables in his garden. He always gave some to his neighbours. When he became ill and could not work, the neighbours quietly took over the garden. When he recovered, it was still full of life. The kindness he had planted came back to him.',
    note: `The garden is a small metaphor: kindness, like seeds, comes back.`,
    audio: 'b1-st-006.ogg',
  },
  {
    id: 'b1-st-007',
    title: 'Maybe',
    text: `A farmer's horse ran away. His neighbours said, "How unlucky!" The farmer just said, "Maybe." The next day, the horse returned with two wild horses. "How lucky!" they cried. "Maybe," he replied. Life kept turning, and the farmer knew better than to judge too soon.`,
    note: `A classic tale: we rarely know if an event is good or bad yet.`,
    audio: 'b1-st-007.ogg',
  },
  {
    id: 'b1-st-008',
    title: 'The closed door',
    text: `Nadia did not get the job she wanted, and she was crushed. A month later, a much better opportunity appeared, one she could only take because she was still free. She realised that a closed door had quietly pointed her somewhere better.`,
    note: `"a closed door" is a gentle metaphor for a lucky rejection.`,
    audio: 'b1-st-008.ogg',
  },
  {
    id: 'b1-st-009',
    title: 'The street musician',
    text: `A man played the violin in a busy station, and almost no one stopped. Later, people learned he was a world-famous musician. They had walked past beauty without noticing it. We often miss the wonderful things right in front of us.`,
    note: `Based on a true experiment about attention and beauty.`,
    audio: 'b1-st-009.ogg',
  },
  {
    id: 'b1-st-010',
    title: 'Two builders',
    text: `Two builders were asked what they were doing. One said, "I am laying bricks." The other said, "I am building a cathedral." They did the same work, but only one of them saw the meaning in it. The story we tell ourselves changes everything.`,
    note: `Same task, two mindsets: meaning is something we choose to see.`,
    audio: 'b1-st-010.ogg',
  },
  {
    id: 'b1-st-011',
    title: 'The patient gardener',
    text: `A woman planted a rare tree that would not flower for ten years. People asked why she bothered. She just smiled and kept watering it. In her old age, the tree finally bloomed, more beautiful than anyone had imagined. The best things are often worth a long wait.`,
    note: `Notice "would not flower" and "had imagined" for time and patience.`,
    audio: 'b1-st-011.ogg',
  },
  {
    id: 'b1-st-012',
    title: 'The empty pot',
    text: `A king wanted an honest heir. He gave every child a seed and asked them to grow a plant. Months later, one boy came with an empty pot, ashamed that nothing had grown. The king smiled, for he had given everyone boiled seeds. The honest boy became king.`,
    note: `A fable about honesty: the only true pot was the empty one.`,
    audio: 'b1-st-012.ogg',
  },
  {
    id: 'b1-st-013',
    title: 'The wrong bag',
    text: `At the airport, a man grabbed the wrong bag by mistake. Inside, he found a child's drawings and a note that read, "For Grandma." Instead of leaving it, he tracked down the owner and posted it back. Weeks later, a thank-you card arrived, signed by a little girl. He kept it for years.`,
    note: `A small effort for a stranger becomes a lasting memory.`,
    audio: 'b1-st-013.ogg',
  },
  {
    id: 'b1-st-014',
    title: 'The quiet volunteer',
    text: `Every Saturday, a woman cleaned the small park, alone and unpaid. People barely noticed. When she fell ill and stopped, the park slowly filled with litter. Only then did the neighbours see how much one quiet person had done. They formed a group to continue her work.`,
    note: `We often notice quiet good work only once it stops.`,
    audio: 'b1-st-014.ogg',
  },
  {
    id: 'b1-st-015',
    title: 'The second chance',
    text: `A young man failed his driving test three times. Embarrassed, he almost gave up. His sister reminded him that the only real failure was quitting. He practised for one more month and passed. Years later, he taught his own daughter to drive, with the same patience.`,
    note: `"the only real failure was quitting" is the lesson.`,
    audio: 'b1-st-015.ogg',
  },
  {
    id: 'b1-st-016',
    title: 'The missed train',
    text: 'Maria always took the same train to work. One morning, she missed it by a minute and felt terrible. While she waited for the next one, she helped a lost traveller find his way. It turned out he worked at a company she hoped to join one day. They stayed in touch, and months later, he told her about a job there. A bad start sometimes hides a good turn.',
    note: `Notice "While she waited" and "It turned out" moving the story along.`,
    audio: 'b1-st-016.ogg',
  },
  {
    id: 'b1-st-017',
    title: 'The quiet student',
    text: 'There was a student who never spoke in class. Everyone thought he was not interested. In fact, he was simply shy. One day, the teacher asked the class to write their ideas down instead. His notes were full of thought and care. After that, she found new ways to hear from him. Quiet does not mean empty.',
    note: `"In fact" corrects what everyone wrongly assumed.`,
    audio: 'b1-st-017.ogg',
  },
  {
    id: 'b1-st-018',
    title: 'The old chair',
    text: "Daniel's grandfather gave him an old, broken chair. His friends told him to throw it away. Instead, he spent a weekend learning how to repair it. The work was slow and difficult, but the chair became beautiful again. Years later, it was his favourite thing in the house. Some things are worth saving.",
    note: `"Instead" marks his choice to repair, not replace.`,
    audio: 'b1-st-018.ogg',
  },
];
