/**
 * B1 (intermediate) useful talks: practical, motivating advice on focus and
 * wellbeing, with reasons and examples. General guidance, not medical advice.
 */
import type { Talk } from '../types';

export const b1Talks: Talk[] = [
  {
    id: 'b1-tk-001',
    topic: 'The power of deep work',
    text: 'Deep work means focusing on one important task without distraction. It is becoming rare, because our phones and apps constantly interrupt us. Yet the most valuable work usually needs long, quiet attention. Try blocking out a set time, turning off notifications, and working on a single task. At first it feels strange, but your concentration grows like a muscle. An hour of deep work often beats a whole day of scattered effort.',
    note: `Try this: schedule one 60-minute, distraction-free block tomorrow.`,
    audio: 'b1-tk-001.ogg',
  },
  {
    id: 'b1-tk-002',
    topic: 'Take control of social media',
    text: 'Social media apps are built to hold your attention for as long as possible. That is their business. The danger is not the apps themselves, but using them without thinking. Notice how you feel after scrolling: often tired, not happy. Try deciding in advance when and how long you will use them. Remove the apps from your home screen, or set a timer. The goal is to use them on purpose, not by habit.',
    note: `Try this: move social apps off your home screen for a week.`,
    audio: 'b1-tk-002.ogg',
  },
  {
    id: 'b1-tk-003',
    topic: 'Eating well without a strict diet',
    text: 'Healthy eating does not require a perfect, strict plan. A simple and common rule is to eat mostly whole foods: vegetables, fruit, beans, whole grains, and lean protein. Try to limit very processed snacks and sugary drinks, but do not aim for perfection. Cooking at home gives you control over what you eat. Most importantly, build habits you can keep for years, not just for a month.',
    note: `Try this: cook one extra meal at home this week.`,
    audio: 'b1-tk-003.ogg',
  },
  {
    id: 'b1-tk-004',
    topic: 'Staying fit and active',
    text: 'Regular movement is one of the most powerful things you can do for your body and mind. Health experts often suggest about 150 minutes of moderate activity each week, plus some strength work. That sounds like a lot, but it is only around twenty minutes a day. Walking counts. The best exercise is the one you actually enjoy and will repeat, so find an activity that does not feel like a punishment.',
    note: `Try this: pick one activity you enjoy and do it three times this week.`,
    audio: 'b1-tk-004.ogg',
  },
  {
    id: 'b1-tk-005',
    topic: 'Why sleep matters',
    text: 'Many people treat sleep as the first thing to cut when they are busy. In fact, sleep is when the body repairs and the brain stores what you learned. Adults generally need seven to nine hours. Poor sleep harms your focus, your mood, and even your health. To sleep better, keep a regular schedule, avoid screens and caffeine late, and keep your bedroom cool and dark. Protect your sleep like an important appointment.',
    note: `Try this: set a "wind down" alarm 30 minutes before bed.`,
    audio: 'b1-tk-005.ogg',
  },
  {
    id: 'b1-tk-006',
    topic: 'How habits really change',
    text: 'We often fail at new habits because we try to change too much at once. A more reliable way is to start tiny and be consistent. Link the new habit to something you already do, like stretching right after you brush your teeth. Make it so small that it feels easy. Repeat it daily, and let it grow slowly. Identity follows action: do the small thing often, and you become the kind of person who does it.',
    note: `Try this: make your new habit two minutes long to start.`,
    audio: 'b1-tk-006.ogg',
  },
  {
    id: 'b1-tk-007',
    topic: 'Manage your time well',
    text: 'Time management is really about choices. Each day brings more tasks than hours, so the skill is deciding what matters. Try planning your day the night before, and start with your hardest, most important task while your energy is high. Group small jobs together, and protect time for focused work. A clear plan removes the stress of deciding all day long.',
    note: `Try this: plan tomorrow before you go to sleep tonight.`,
    audio: 'b1-tk-007.ogg',
  },
  {
    id: 'b1-tk-008',
    topic: 'How to handle stress',
    text: 'Some stress is useful; it helps us act. The problem is constant, unmanaged stress, which harms both body and mind. Build simple habits that lower it: regular sleep, movement, time outdoors, and real conversations. Learn to notice your early signs of stress and respond before it grows. You cannot remove all stress, but you can build the habits that handle it.',
    note: `Try this: name one early stress signal and a small response to it.`,
    audio: 'b1-tk-008.ogg',
  },
  {
    id: 'b1-tk-009',
    topic: 'Learn how to learn',
    text: 'Most of us were never taught how to learn. Two methods stand out. First, test yourself: trying to recall something is far more powerful than rereading it. Second, space your practice over several days instead of cramming it all at once. Add short breaks and mix topics. These methods feel harder, but they make learning stick far better.',
    note: `Try this: quiz yourself today on something you learned yesterday.`,
    audio: 'b1-tk-009.ogg',
  },
  {
    id: 'b1-tk-010',
    topic: 'Why gratitude matters',
    text: 'Our minds naturally focus on problems and worries. That instinct once kept us safe, but today it often just makes us anxious. Gratitude is a simple counterweight. Regularly noticing what is good, in a journal or just in your head, trains your attention toward the positive. It will not solve every problem, but it reliably lifts your mood over time.',
    note: `Try this: keep a short gratitude note for one week.`,
    audio: 'b1-tk-010.ogg',
  },
  {
    id: 'b1-tk-011',
    topic: 'Why reading matters',
    text: 'Reading is a quiet superpower. It builds vocabulary faster than almost anything else, sharpens focus in a world full of distractions, and lets you live a thousand lives. You do not need difficult books. Choose what genuinely interests you, read a little each day, and keep a list of new words. Over a year, that small daily habit adds up to a real change.',
    note: `Try this: read something you enjoy for 15 minutes a day.`,
    audio: 'b1-tk-011.ogg',
  },
  {
    id: 'b1-tk-012',
    topic: 'Simple money habits',
    text: 'Managing money is less about how much you earn and more about your habits. Three simple ones go a long way: spend less than you earn, save a fixed amount automatically, and avoid debt for things that lose value. Track your spending for a month to see the truth. You do not need to be an expert; you need to be consistent.',
    note: `Try this: set up an automatic transfer to savings each payday.`,
    audio: 'b1-tk-012.ogg',
  },
  {
    id: 'b1-tk-013',
    topic: 'How to set goals that stick',
    text: 'Most goals fail because they are too big and too vague. The fix is to make them small, specific, and tied to a habit. Instead of "learn English", say "study 20 minutes after breakfast". Track it where you can see it, and focus on the system, not just the result. Tiny, consistent steps beat bursts of motivation every time.',
    note: `Try this: turn your goal into a daily habit with a fixed time.`,
    audio: 'b1-tk-013.ogg',
  },
  {
    id: 'b1-tk-014',
    topic: 'The skill of listening',
    text: 'Most people listen only to reply. They wait for their turn to speak, already planning their answer in their head. Real listening is different and rare. It means giving someone your full attention, without judging or interrupting, until they feel truly heard. This builds trust faster than any clever words. Next time someone speaks to you, try to understand them completely before you say a single thing. You will be surprised how much people open up to a good listener.',
    note: `Try this: in your next conversation, listen fully before you reply.`,
    audio: 'b1-tk-014.ogg',
  },
  {
    id: 'b1-tk-015',
    topic: 'The power of patience',
    text: 'We live in a world built for speed, where waiting can feel like failing. Yet most things worth having grow slowly: a skill, a friendship, good health, a good name. Patience is not doing nothing; it is staying steady while the slow work happens. When you feel the urge to quit because results are not instant, remember that the people you admire simply kept going longer than others. Give your goals the time they honestly need.',
    note: `Try this: pick one slow goal and stay with it for a full month.`,
    audio: 'b1-tk-015.ogg',
  },
  {
    id: 'b1-tk-016',
    topic: 'Start your morning well',
    text: "How you start your morning often shapes the whole day. If you grab your phone the moment you wake up, your mind fills with other people's news and worries before you have had a single calm thought. Try a gentler start instead: a glass of water, a few minutes of quiet, and one clear plan for the day. You do not need a long routine. A simple, calm beginning gives you a sense of control that lasts for hours.",
    note: `Try this: wait one hour before checking your phone in the morning.`,
    audio: 'b1-tk-016.ogg',
  },
  {
    id: 'b1-tk-017',
    topic: 'Manage your energy, not just your time',
    text: 'We spend a lot of effort managing our time, but we often ignore something just as important: our energy. You can have a free hour and still get nothing done if you are tired and drained. Notice when in the day you feel sharp and alert, and save your hardest work for those hours. Rest, food, movement, and sleep all refill your energy. A short break at the right moment can be worth more than another hour of tired effort.',
    note: `Try this: do your most important task during your highest-energy hour.`,
    audio: 'b1-tk-017.ogg',
  },
  {
    id: 'b1-tk-018',
    topic: 'How to take feedback well',
    text: 'Feedback can be hard to hear, but it is one of the fastest ways to improve. The trick is to separate the message from your feelings. When someone points out a weakness, try not to defend yourself at once. Instead, listen, thank them, and ask a question to understand better. You do not have to agree with everything, but look for the useful part. People who can take honest feedback grow far faster than those who only want praise.',
    note: `Try this: next time you get feedback, just say "thank you" and think it over.`,
    audio: 'b1-tk-018.ogg',
  },
  {
    id: 'b1-tk-019',
    topic: 'How to apologize well',
    text: 'Everyone makes mistakes, but few people know how to apologize well. A good apology is simple and honest. First, say sorry clearly, without excuses. Do not say "I am sorry if you felt upset"; that blames the other person. Instead, name what you did wrong and show that you understand why it hurt. Then, if you can, offer to fix it. A real apology rebuilds trust, while a weak one often makes things worse. The courage to say a clear sorry is a sign of strength, not weakness.',
    note: `Try this: if you owe someone an apology, give a clear one with no excuses.`,
    audio: 'b1-tk-019.ogg',
  },
  {
    id: 'b1-tk-020',
    topic: 'Do not compare yourself to others',
    text: "It is easy to look at other people and feel that you are behind. Social media makes this worse, because people share only their best moments. But comparing your everyday life to someone else's highlights is unfair to yourself. Everyone has a different path, a different start, and struggles you cannot see. A healthier habit is to compare yourself only to who you were yesterday. Are you a little better, a little kinder, a little wiser? That is the only race worth running.",
    note: `Try this: each day, measure your progress against your own past, not others.`,
    audio: 'b1-tk-020.ogg',
  },
];
