/**
 * C2 (mastery) vocabulary: sophisticated words that mark a truly fluent speaker,
 * each with a plain meaning, examples, and a usage tip.
 */
import type { VocabularyEntry } from '../types';

export const c2Vocabulary: VocabularyEntry[] = [
  {
    id: 'c2-vc-001',
    word: 'ubiquitous',
    meaning: 'seeming to be everywhere at once.',
    examples: ['Smartphones are now ubiquitous.', 'Coffee shops are ubiquitous here.'],
    note: `A formal way to say "everywhere". Close to "omnipresent".`,
    audio: 'c2-vc-001.ogg',
  },
  {
    id: 'c2-vc-002',
    word: 'pragmatic',
    meaning: 'dealing with things in a practical, realistic way.',
    examples: ['She took a pragmatic approach.', 'We need a pragmatic solution.'],
    note: `Opposite of "idealistic". The noun is "pragmatism".`,
    audio: 'c2-vc-002.ogg',
  },
  {
    id: 'c2-vc-003',
    word: 'candid',
    meaning: 'honest and direct, even about difficult things.',
    examples: ['Can I be candid with you?', 'She gave a candid interview.'],
    note: `The noun is "candor". Close to "frank" or "straightforward".`,
    audio: 'c2-vc-003.ogg',
  },
  {
    id: 'c2-vc-004',
    word: 'scrutiny',
    meaning: 'careful and critical examination.',
    examples: ['The plan came under scrutiny.', 'It cannot survive close scrutiny.'],
    note: `Common phrases: "under scrutiny", "close scrutiny". The verb is "scrutinise".`,
    audio: 'c2-vc-004.ogg',
  },
  {
    id: 'c2-vc-005',
    word: 'paradox',
    meaning: 'a statement that seems to contradict itself but may be true.',
    examples: ['It is a paradox that less can be more.', 'Her life was full of paradoxes.'],
    note: `The adjective "paradoxical" describes something self-contradictory.`,
    audio: 'c2-vc-005.ogg',
  },
  {
    id: 'c2-vc-006',
    word: 'mitigate',
    meaning: 'to make something bad less severe.',
    examples: ['We took steps to mitigate the risk.', 'Nothing could mitigate the damage.'],
    note: `Formal. Often "mitigate the risk, impact, or effects".`,
    audio: 'c2-vc-006.ogg',
  },
  {
    id: 'c2-vc-007',
    word: 'profound',
    meaning: 'very great, deep, or far-reaching.',
    examples: ['It had a profound effect on me.', 'She asked a profound question.'],
    note: `Stronger than "big" or "deep". Often "a profound effect or impact".`,
    audio: 'c2-vc-007.ogg',
  },
  {
    id: 'c2-vc-008',
    word: 'juxtapose',
    meaning: 'to place two things side by side to compare or contrast them.',
    examples: ['The film juxtaposes wealth and poverty.', 'She juxtaposed the two photos.'],
    note: `The noun is "juxtaposition", common in art and writing.`,
    audio: 'c2-vc-008.ogg',
  },
  {
    id: 'c2-vc-009',
    word: 'ephemeral',
    meaning: 'lasting a very short time.',
    examples: ['Fame can be ephemeral.', 'It was an ephemeral trend.'],
    note: `Close to "fleeting" or "short-lived".`,
    audio: 'c2-vc-009.ogg',
  },
  {
    id: 'c2-vc-010',
    word: 'quintessential',
    meaning: 'the most perfect example of a type.',
    examples: ['The quintessential summer day.', 'He is the quintessential gentleman.'],
    note: `It means the purest, most typical example of something.`,
    audio: 'c2-vc-010.ogg',
  },
  {
    id: 'c2-vc-011',
    word: 'salient',
    meaning: 'most noticeable or important.',
    examples: ['Let us focus on the salient points.', 'That is the salient detail.'],
    note: `Often "the salient point", the one that stands out.`,
    audio: 'c2-vc-011.ogg',
  },
  {
    id: 'c2-vc-012',
    word: 'tenuous',
    meaning: 'weak, thin, or very slight.',
    examples: ['There is a tenuous connection.', 'His grip on power is tenuous.'],
    note: `Often "a tenuous link" between two things.`,
    audio: 'c2-vc-012.ogg',
  },
  {
    id: 'c2-vc-013',
    word: 'cogent',
    meaning: 'clear, logical, and convincing.',
    examples: ['She made a cogent argument.', 'He gave a cogent reason.'],
    note: `Used of reasoning that is hard to argue against.`,
    audio: 'c2-vc-013.ogg',
  },
  {
    id: 'c2-vc-014',
    word: 'ostensible',
    meaning: 'appearing true on the surface, but perhaps not the real reason.',
    examples: ['The ostensible reason was cost.', 'That was his ostensible aim.'],
    note: `The adverb "ostensibly" hints the real reason is different.`,
    audio: 'c2-vc-014.ogg',
  },
  {
    id: 'c2-vc-015',
    word: 'innocuous',
    meaning: 'harmless; unlikely to offend or cause harm.',
    examples: ['It was an innocuous remark.', 'The plant looks innocuous.'],
    note: `Opposite of "harmful" or "offensive".`,
    audio: 'c2-vc-015.ogg',
  },
  {
    id: 'c2-vc-016',
    word: 'prudent',
    meaning: 'careful and sensible; wise in practice.',
    examples: ['It was a prudent decision.', 'It is prudent to save.'],
    note: `The noun is "prudence". Close to "sensible" or "cautious".`,
    audio: 'c2-vc-016.ogg',
  },
  {
    id: 'c2-vc-017',
    word: 'eloquent',
    meaning: 'fluent and persuasive in speech or writing.',
    examples: ['She is an eloquent speaker.', 'He gave an eloquent reply.'],
    note: `The noun is "eloquence".`,
    audio: 'c2-vc-017.ogg',
  },
  {
    id: 'c2-vc-018',
    word: 'austere',
    meaning: 'very plain and strict, without comfort or luxury.',
    examples: ['It was an austere room.', 'They led an austere life.'],
    note: `It can describe people (severe) or things (bare).`,
    audio: 'c2-vc-018.ogg',
  },
  {
    id: 'c2-vc-019',
    word: 'lucid',
    meaning: 'clear and easy to understand; clear-thinking.',
    examples: ['She gave a lucid explanation.', 'He stayed calm and lucid.'],
    note: `The noun is "lucidity". Opposite: "confusing".`,
    audio: 'c2-vc-019.ogg',
  },
  {
    id: 'c2-vc-020',
    word: 'disparate',
    meaning: 'very different in kind; hard to compare.',
    examples: ['She drew on disparate ideas.', 'It was a disparate group.'],
    note: `It means fundamentally different, not just varied.`,
    audio: 'c2-vc-020.ogg',
  },
  {
    id: 'c2-vc-021',
    word: 'arduous',
    meaning: 'needing a lot of hard, tiring effort.',
    examples: ['It was an arduous journey.', 'The training is arduous.'],
    note: `Close to "gruelling". Stronger than "difficult".`,
    audio: 'c2-vc-021.ogg',
  },
  {
    id: 'c2-vc-022',
    word: 'perpetual',
    meaning: 'never ending or seeming to never stop.',
    examples: ['A perpetual state of worry.', 'Their perpetual arguing.'],
    note: `Close to "constant" or "endless".`,
    audio: 'c2-vc-022.ogg',
  },
  {
    id: 'c2-vc-023',
    word: 'intrinsic',
    meaning: 'belonging naturally to something; essential to it.',
    examples: ['It has intrinsic value.', 'Curiosity is intrinsic to learning.'],
    note: `"intrinsic to" something. Opposite: "extrinsic".`,
    audio: 'c2-vc-023.ogg',
  },
  {
    id: 'c2-vc-024',
    word: 'ostentatious',
    meaning: 'showy in a way meant to impress others.',
    examples: ['An ostentatious display of wealth.', 'The decor was ostentatious.'],
    note: `Negative. The opposite is "understated" or "modest".`,
    audio: 'c2-vc-024.ogg',
  },
  {
    id: 'c2-vc-025',
    word: 'gregarious',
    meaning: 'enjoying the company of others; sociable.',
    examples: ['He is warm and gregarious.', 'A gregarious host.'],
    note: `Opposite of "solitary" or "reserved".`,
    audio: 'c2-vc-025.ogg',
  },
  {
    id: 'c2-vc-026',
    word: 'succinct',
    meaning: 'expressed clearly in very few words.',
    examples: ['She gave a succinct summary.', 'Keep the reply succinct.'],
    note: `Close to "concise". The opposite is "long-winded".`,
    audio: 'c2-vc-026.ogg',
  },
  {
    id: 'c2-vc-027',
    word: 'tenacious',
    meaning: 'holding on firmly; not giving up.',
    examples: ['A tenacious negotiator.', 'She is tenacious about her goals.'],
    note: `The noun is "tenacity". Close to "determined".`,
    audio: 'c2-vc-027.ogg',
  },
  {
    id: 'c2-vc-028',
    word: 'magnanimous',
    meaning: 'generous and forgiving, especially toward a rival.',
    examples: ['He was magnanimous in victory.', 'A magnanimous gesture.'],
    note: `Suggests rising above pettiness. Noun: "magnanimity".`,
    audio: 'c2-vc-028.ogg',
  },
  {
    id: 'c2-vc-029',
    word: 'erudite',
    meaning: 'having or showing deep, wide knowledge.',
    examples: ['She gave an erudite lecture.', 'He is remarkably erudite.'],
    note: `Formal. Close to "learned" or "scholarly".`,
    audio: 'c2-vc-029.ogg',
  },
  {
    id: 'c2-vc-030',
    word: 'sagacious',
    meaning: 'wise and showing good judgment.',
    examples: ['A sagacious leader plans ahead.', 'She offered sagacious advice.'],
    note: `Literary and formal. The noun is "sagacity".`,
    audio: 'c2-vc-030.ogg',
  },
  {
    id: 'c2-vc-031',
    word: 'indefatigable',
    meaning: 'never seeming to get tired; tireless.',
    examples: ['She is an indefatigable worker.', 'His energy was indefatigable.'],
    note: `Praises someone who simply does not give up.`,
    audio: 'c2-vc-031.ogg',
  },
  {
    id: 'c2-vc-032',
    word: 'fastidious',
    meaning: 'very attentive to detail and hard to please.',
    examples: ['He is fastidious about cleanliness.', 'She is a fastidious editor.'],
    note: `Can be praise or a mild criticism, depending on tone.`,
    audio: 'c2-vc-032.ogg',
  },
  {
    id: 'c2-vc-033',
    word: 'circumspect',
    meaning: 'careful to consider everything before acting.',
    examples: ['Be circumspect about what you share online.', 'She gave a circumspect reply.'],
    note: `Close to "cautious" or "wary".`,
    audio: 'c2-vc-033.ogg',
  },
  {
    id: 'c2-vc-034',
    word: 'unflappable',
    meaning: 'calm and not easily upset, even under pressure.',
    examples: ['She stayed unflappable during the crisis.', 'He is an unflappable manager.'],
    note: `Praises someone who never seems to panic.`,
    audio: 'c2-vc-034.ogg',
  },
];
