/**
 * B1 (intermediate) vocabulary: useful describing and discussing words, each with
 * a plain meaning, examples, and a collocation or synonym tip.
 */
import type { VocabularyEntry } from '../types';

export const b1Vocabulary: VocabularyEntry[] = [
  {
    id: 'b1-vc-001',
    word: 'reliable',
    meaning: 'able to be trusted to do what is expected.',
    examples: ['She is a reliable worker.', 'We need a reliable car.'],
    note: `Opposite of "unreliable". A close synonym is "dependable".`,
    audio: 'b1-vc-001.ogg',
  },
  {
    id: 'b1-vc-002',
    word: 'generous',
    meaning: 'happy to give time, money, or help.',
    examples: ['He is very generous with his time.', 'That was a generous gift.'],
    note: `"generous with" something. The noun is "generosity".`,
    audio: 'b1-vc-002.ogg',
  },
  {
    id: 'b1-vc-003',
    word: 'confident',
    meaning: 'sure of yourself and your abilities.',
    examples: ['She feels confident before exams.', 'Try to sound confident.'],
    note: `"confident about" or "confident in". The noun is "confidence".`,
    audio: 'b1-vc-003.ogg',
  },
  {
    id: 'b1-vc-004',
    word: 'suggest',
    meaning: 'to offer an idea for someone to think about.',
    examples: ['I suggest we leave early.', 'She suggested a new plan.'],
    note: `Use "suggest doing" or "suggest that...". Not "suggest to do".`,
    audio: 'b1-vc-004.ogg',
  },
  {
    id: 'b1-vc-005',
    word: 'manage',
    meaning: 'to succeed in doing something difficult, or to be in charge.',
    examples: ['I managed to finish on time.', 'She manages a small team.'],
    note: `"manage to do" means you succeeded despite difficulty.`,
    audio: 'b1-vc-005.ogg',
  },
  {
    id: 'b1-vc-006',
    word: 'achieve',
    meaning: 'to reach a goal through effort.',
    examples: ['He achieved his dream.', 'We achieved great results.'],
    note: `The noun is "achievement". Often "achieve a goal".`,
    audio: 'b1-vc-006.ogg',
  },
  {
    id: 'b1-vc-007',
    word: 'prefer',
    meaning: 'to like one thing more than another.',
    examples: ['I prefer tea to coffee.', 'She prefers to walk.'],
    note: `"prefer X to Y", or "prefer doing", or "prefer to do".`,
    audio: 'b1-vc-007.ogg',
  },
  {
    id: 'b1-vc-008',
    word: 'ordinary',
    meaning: 'normal and not special.',
    examples: ['It was just an ordinary day.', 'He lives an ordinary life.'],
    note: `Opposite of "extraordinary" or "special". Close to "everyday".`,
    audio: 'b1-vc-008.ogg',
  },
  {
    id: 'b1-vc-009',
    word: 'encourage',
    meaning: 'to give someone confidence or support to do something.',
    examples: ['She encouraged me to apply.', 'Good teachers encourage students.'],
    note: `"encourage someone to do". Opposite: "discourage".`,
    audio: 'b1-vc-009.ogg',
  },
  {
    id: 'b1-vc-010',
    word: 'admire',
    meaning: 'to respect and like someone or something.',
    examples: ['I admire her courage.', 'They admire his work.'],
    note: `The noun is "admiration".`,
    audio: 'b1-vc-010.ogg',
  },
  {
    id: 'b1-vc-011',
    word: 'deserve',
    meaning: 'to be worthy of something, good or bad.',
    examples: ['You deserve a break.', 'She deserves the prize.'],
    note: `Use "deserve to" do something, or "deserve" a noun.`,
    audio: 'b1-vc-011.ogg',
  },
  {
    id: 'b1-vc-012',
    word: 'appreciate',
    meaning: 'to be grateful for, or to value something.',
    examples: ['I appreciate your help.', 'I appreciate good food.'],
    note: `"I would appreciate it if..." is a polite request.`,
    audio: 'b1-vc-012.ogg',
  },
  {
    id: 'b1-vc-013',
    word: 'recommend',
    meaning: 'to suggest that something is good.',
    examples: ['I recommend this book.', 'She recommended a doctor.'],
    note: `Use "recommend doing" or "recommend that...", not "recommend to do".`,
    audio: 'b1-vc-013.ogg',
  },
  {
    id: 'b1-vc-014',
    word: 'consider',
    meaning: 'to think about something carefully.',
    examples: ['I am considering a new job.', 'Consider all the options.'],
    note: `Use "consider doing" something. The noun is "consideration".`,
    audio: 'b1-vc-014.ogg',
  },
  {
    id: 'b1-vc-015',
    word: 'realise',
    meaning: 'to suddenly understand or become aware of something.',
    examples: ['I realised my mistake.', 'She realised he was right.'],
    note: `Spelled "realize" in American English.`,
    audio: 'b1-vc-015.ogg',
  },
  {
    id: 'b1-vc-016',
    word: 'afford',
    meaning: 'to have enough money or time for something.',
    examples: ['I cannot afford it.', 'Can we afford the trip?'],
    note: `Almost always with "can" or "cannot".`,
    audio: 'b1-vc-016.ogg',
  },
  {
    id: 'b1-vc-017',
    word: 'depend',
    meaning: 'to be decided by something else, or to rely on someone.',
    examples: ['It depends on the weather.', 'I depend on my team.'],
    note: `Always "depend on". "It depends" is very common.`,
    audio: 'b1-vc-017.ogg',
  },
  {
    id: 'b1-vc-018',
    word: 'available',
    meaning: 'able to be used or obtained, or free to meet.',
    examples: ['The room is available.', 'Are you available on Monday?'],
    note: `Opposite: "unavailable". The noun is "availability".`,
    audio: 'b1-vc-018.ogg',
  },
  {
    id: 'b1-vc-019',
    word: 'aware',
    meaning: 'knowing that something exists or is true.',
    examples: ['I am aware of the risk.', 'Are you aware of the rules?'],
    note: `"aware of" something. The noun is "awareness".`,
    audio: 'b1-vc-019.ogg',
  },
  {
    id: 'b1-vc-020',
    word: 'willing',
    meaning: 'ready and happy to do something.',
    examples: ['I am willing to help.', 'She is willing to learn.'],
    note: `"willing to do". Opposite: "unwilling" or "reluctant".`,
    audio: 'b1-vc-020.ogg',
  },
];
