/**
 * B1 (intermediate) vocabulary: useful describing and discussing words, each with
 * a plain meaning, examples, and a collocation or synonym tip.
 */
import type { VocabularyEntry } from '../types';

export const b1Vocabulary: VocabularyEntry[] = [
  {
    id: 'b1-vc-001',
    word: 'reliable',
    meaning: 'able to be trusted to do what is expected.',
    examples: ['She is a reliable worker.', 'We need a reliable car.'],
    note: `Opposite of "unreliable". A close synonym is "dependable".`,
    audio: 'b1-vc-001.ogg',
  },
  {
    id: 'b1-vc-002',
    word: 'generous',
    meaning: 'happy to give time, money, or help.',
    examples: ['He is very generous with his time.', 'That was a generous gift.'],
    note: `"generous with" something. The noun is "generosity".`,
    audio: 'b1-vc-002.ogg',
  },
  {
    id: 'b1-vc-003',
    word: 'confident',
    meaning: 'sure of yourself and your abilities.',
    examples: ['She feels confident before exams.', 'Try to sound confident.'],
    note: `"confident about" or "confident in". The noun is "confidence".`,
    audio: 'b1-vc-003.ogg',
  },
  {
    id: 'b1-vc-004',
    word: 'suggest',
    meaning: 'to offer an idea for someone to think about.',
    examples: ['I suggest we leave early.', 'She suggested a new plan.'],
    note: `Use "suggest doing" or "suggest that...". Not "suggest to do".`,
    audio: 'b1-vc-004.ogg',
  },
  {
    id: 'b1-vc-005',
    word: 'manage',
    meaning: 'to succeed in doing something difficult, or to be in charge.',
    examples: ['I managed to finish on time.', 'She manages a small team.'],
    note: `"manage to do" means you succeeded despite difficulty.`,
    audio: 'b1-vc-005.ogg',
  },
  {
    id: 'b1-vc-006',
    word: 'achieve',
    meaning: 'to reach a goal through effort.',
    examples: ['He achieved his dream.', 'We achieved great results.'],
    note: `The noun is "achievement". Often "achieve a goal".`,
    audio: 'b1-vc-006.ogg',
  },
  {
    id: 'b1-vc-007',
    word: 'prefer',
    meaning: 'to like one thing more than another.',
    examples: ['I prefer tea to coffee.', 'She prefers to walk.'],
    note: `"prefer X to Y", or "prefer doing", or "prefer to do".`,
    audio: 'b1-vc-007.ogg',
  },
  {
    id: 'b1-vc-008',
    word: 'ordinary',
    meaning: 'normal and not special.',
    examples: ['It was just an ordinary day.', 'He lives an ordinary life.'],
    note: `Opposite of "extraordinary" or "special". Close to "everyday".`,
    audio: 'b1-vc-008.ogg',
  },
  {
    id: 'b1-vc-009',
    word: 'encourage',
    meaning: 'to give someone confidence or support to do something.',
    examples: ['She encouraged me to apply.', 'Good teachers encourage students.'],
    note: `"encourage someone to do". Opposite: "discourage".`,
    audio: 'b1-vc-009.ogg',
  },
  {
    id: 'b1-vc-010',
    word: 'admire',
    meaning: 'to respect and like someone or something.',
    examples: ['I admire her courage.', 'They admire his work.'],
    note: `The noun is "admiration".`,
    audio: 'b1-vc-010.ogg',
  },
  {
    id: 'b1-vc-011',
    word: 'deserve',
    meaning: 'to be worthy of something, good or bad.',
    examples: ['You deserve a break.', 'She deserves the prize.'],
    note: `Use "deserve to" do something, or "deserve" a noun.`,
    audio: 'b1-vc-011.ogg',
  },
  {
    id: 'b1-vc-012',
    word: 'appreciate',
    meaning: 'to be grateful for, or to value something.',
    examples: ['I appreciate your help.', 'I appreciate good food.'],
    note: `"I would appreciate it if..." is a polite request.`,
    audio: 'b1-vc-012.ogg',
  },
  {
    id: 'b1-vc-013',
    word: 'recommend',
    meaning: 'to suggest that something is good.',
    examples: ['I recommend this book.', 'She recommended a doctor.'],
    note: `Use "recommend doing" or "recommend that...", not "recommend to do".`,
    audio: 'b1-vc-013.ogg',
  },
  {
    id: 'b1-vc-014',
    word: 'consider',
    meaning: 'to think about something carefully.',
    examples: ['I am considering a new job.', 'Consider all the options.'],
    note: `Use "consider doing" something. The noun is "consideration".`,
    audio: 'b1-vc-014.ogg',
  },
  {
    id: 'b1-vc-015',
    word: 'realise',
    meaning: 'to suddenly understand or become aware of something.',
    examples: ['I realised my mistake.', 'She realised he was right.'],
    note: `Spelled "realize" in American English.`,
    audio: 'b1-vc-015.ogg',
  },
  {
    id: 'b1-vc-016',
    word: 'afford',
    meaning: 'to have enough money or time for something.',
    examples: ['I cannot afford it.', 'Can we afford the trip?'],
    note: `Almost always with "can" or "cannot".`,
    audio: 'b1-vc-016.ogg',
  },
  {
    id: 'b1-vc-017',
    word: 'depend',
    meaning: 'to be decided by something else, or to rely on someone.',
    examples: ['It depends on the weather.', 'I depend on my team.'],
    note: `Always "depend on". "It depends" is very common.`,
    audio: 'b1-vc-017.ogg',
  },
  {
    id: 'b1-vc-018',
    word: 'available',
    meaning: 'able to be used or obtained, or free to meet.',
    examples: ['The room is available.', 'Are you available on Monday?'],
    note: `Opposite: "unavailable". The noun is "availability".`,
    audio: 'b1-vc-018.ogg',
  },
  {
    id: 'b1-vc-019',
    word: 'aware',
    meaning: 'knowing that something exists or is true.',
    examples: ['I am aware of the risk.', 'Are you aware of the rules?'],
    note: `"aware of" something. The noun is "awareness".`,
    audio: 'b1-vc-019.ogg',
  },
  {
    id: 'b1-vc-020',
    word: 'willing',
    meaning: 'ready and happy to do something.',
    examples: ['I am willing to help.', 'She is willing to learn.'],
    note: `"willing to do". Opposite: "unwilling" or "reluctant".`,
    audio: 'b1-vc-020.ogg',
  },
  {
    id: 'b1-vc-021',
    word: 'honest',
    meaning: 'truthful; not lying or cheating.',
    examples: ['She gave an honest answer.', 'To be honest, I disagree.'],
    note: `The "h" is silent: "onest". The noun is "honesty".`,
    audio: 'b1-vc-021.ogg',
  },
  {
    id: 'b1-vc-022',
    word: 'patient',
    meaning: 'able to wait calmly without getting annoyed.',
    examples: ['Be patient, it takes time.', 'She is patient with children.'],
    note: `Opposite: "impatient". The noun is "patience".`,
    audio: 'b1-vc-022.ogg',
  },
  {
    id: 'b1-vc-023',
    word: 'curious',
    meaning: 'wanting to know or learn about things.',
    examples: ['I am curious about other cultures.', 'A curious child asks questions.'],
    note: `"curious about" something. The noun is "curiosity".`,
    audio: 'b1-vc-023.ogg',
  },
  {
    id: 'b1-vc-024',
    word: 'ambitious',
    meaning: 'having a strong wish to succeed.',
    examples: ['She is very ambitious.', 'It is an ambitious plan.'],
    note: `The noun is "ambition". Can describe people or plans.`,
    audio: 'b1-vc-024.ogg',
  },
  {
    id: 'b1-vc-025',
    word: 'organised',
    meaning: 'arranged in a neat, planned way.',
    examples: ['She is very organised.', 'Keep your notes organised.'],
    note: `Spelled "organized" in American English. Opposite: "disorganised".`,
    audio: 'b1-vc-025.ogg',
  },
  {
    id: 'b1-vc-026',
    word: 'responsible',
    meaning: 'in charge of something, or reliable and sensible.',
    examples: ['She is responsible for the team.', 'He is a responsible adult.'],
    note: `"responsible for" something. The noun is "responsibility".`,
    audio: 'b1-vc-026.ogg',
  },
  {
    id: 'b1-vc-027',
    word: 'sensible',
    meaning: 'showing good judgment; practical.',
    examples: ['That is a sensible choice.', 'Be sensible about money.'],
    note: `Do not confuse it with "sensitive" (easily affected by feelings).`,
    audio: 'b1-vc-027.ogg',
  },
  {
    id: 'b1-vc-028',
    word: 'frustrated',
    meaning: 'annoyed because you cannot do what you want.',
    examples: ['I felt frustrated by the delay.', 'She gets frustrated easily.'],
    note: `You feel "frustrated"; a thing is "frustrating".`,
    audio: 'b1-vc-028.ogg',
  },
  {
    id: 'b1-vc-029',
    word: 'brave',
    meaning: 'ready to face danger, pain, or difficulty.',
    examples: ['It was a brave decision.', 'Be brave and give it a try.'],
    note: `The noun is "bravery". Close to "courageous".`,
    audio: 'b1-vc-029.ogg',
  },
  {
    id: 'b1-vc-030',
    word: 'calm',
    meaning: 'relaxed and not worried or excited.',
    examples: ['Stay calm and breathe slowly.', 'The sea was calm.'],
    note: `Opposite of "anxious"; for weather, opposite of "stormy".`,
    audio: 'b1-vc-030.ogg',
  },
  {
    id: 'b1-vc-031',
    word: 'loyal',
    meaning: 'faithful and reliable to a person or group.',
    examples: ['He is a loyal friend.', 'Loyal customers keep coming back.'],
    note: `The noun is "loyalty". Opposite: "disloyal".`,
    audio: 'b1-vc-031.ogg',
  },
  {
    id: 'b1-vc-032',
    word: 'modest',
    meaning: 'not boasting about yourself or your success.',
    examples: ['She is modest about her talent.', 'He gave a modest reply.'],
    note: `It can also mean small: "a modest salary".`,
    audio: 'b1-vc-032.ogg',
  },
  {
    id: 'b1-vc-033',
    word: 'eager',
    meaning: 'very keen and excited to do something.',
    examples: ['He is eager to learn.', 'The children were eager to start.'],
    note: `Use "eager to" plus a verb.`,
    audio: 'b1-vc-033.ogg',
  },
  {
    id: 'b1-vc-034',
    word: 'sincere',
    meaning: 'honest and truly meant.',
    examples: ['Please accept my sincere thanks.', 'She gave a sincere apology.'],
    note: `The adverb "sincerely" often closes a formal letter.`,
    audio: 'b1-vc-034.ogg',
  },
];
