/**
 * C2 (mastery) vocabulary: sophisticated words that mark a truly fluent speaker,
 * each with a plain meaning, examples, and a usage tip.
 */
import type { VocabularyEntry } from '../types';

export const c2Vocabulary: VocabularyEntry[] = [
  {
    id: 'c2-vc-001',
    word: 'ubiquitous',
    meaning: 'seeming to be everywhere at once.',
    examples: ['Smartphones are now ubiquitous.', 'Coffee shops are ubiquitous here.'],
    note: `A formal way to say "everywhere". Close to "omnipresent".`,
    audio: 'c2-vc-001.ogg',
  },
  {
    id: 'c2-vc-002',
    word: 'pragmatic',
    meaning: 'dealing with things in a practical, realistic way.',
    examples: ['She took a pragmatic approach.', 'We need a pragmatic solution.'],
    note: `Opposite of "idealistic". The noun is "pragmatism".`,
    audio: 'c2-vc-002.ogg',
  },
  {
    id: 'c2-vc-003',
    word: 'candid',
    meaning: 'honest and direct, even about difficult things.',
    examples: ['Can I be candid with you?', 'She gave a candid interview.'],
    note: `The noun is "candor". Close to "frank" or "straightforward".`,
    audio: 'c2-vc-003.ogg',
  },
  {
    id: 'c2-vc-004',
    word: 'scrutiny',
    meaning: 'careful and critical examination.',
    examples: ['The plan came under scrutiny.', 'It cannot survive close scrutiny.'],
    note: `Common phrases: "under scrutiny", "close scrutiny". The verb is "scrutinise".`,
    audio: 'c2-vc-004.ogg',
  },
  {
    id: 'c2-vc-005',
    word: 'paradox',
    meaning: 'a statement that seems to contradict itself but may be true.',
    examples: ['It is a paradox that less can be more.', 'Her life was full of paradoxes.'],
    note: `The adjective "paradoxical" describes something self-contradictory.`,
    audio: 'c2-vc-005.ogg',
  },
  {
    id: 'c2-vc-006',
    word: 'mitigate',
    meaning: 'to make something bad less severe.',
    examples: ['We took steps to mitigate the risk.', 'Nothing could mitigate the damage.'],
    note: `Formal. Often "mitigate the risk, impact, or effects".`,
    audio: 'c2-vc-006.ogg',
  },
  {
    id: 'c2-vc-007',
    word: 'profound',
    meaning: 'very great, deep, or far-reaching.',
    examples: ['It had a profound effect on me.', 'She asked a profound question.'],
    note: `Stronger than "big" or "deep". Often "a profound effect or impact".`,
    audio: 'c2-vc-007.ogg',
  },
  {
    id: 'c2-vc-008',
    word: 'juxtapose',
    meaning: 'to place two things side by side to compare or contrast them.',
    examples: ['The film juxtaposes wealth and poverty.', 'She juxtaposed the two photos.'],
    note: `The noun is "juxtaposition", common in art and writing.`,
    audio: 'c2-vc-008.ogg',
  },
  {
    id: 'c2-vc-009',
    word: 'ephemeral',
    meaning: 'lasting a very short time.',
    examples: ['Fame can be ephemeral.', 'It was an ephemeral trend.'],
    note: `Close to "fleeting" or "short-lived".`,
    audio: 'c2-vc-009.ogg',
  },
  {
    id: 'c2-vc-010',
    word: 'quintessential',
    meaning: 'the most perfect example of a type.',
    examples: ['The quintessential summer day.', 'He is the quintessential gentleman.'],
    note: `It means the purest, most typical example of something.`,
    audio: 'c2-vc-010.ogg',
  },
  {
    id: 'c2-vc-011',
    word: 'salient',
    meaning: 'most noticeable or important.',
    examples: ['Let us focus on the salient points.', 'That is the salient detail.'],
    note: `Often "the salient point", the one that stands out.`,
    audio: 'c2-vc-011.ogg',
  },
  {
    id: 'c2-vc-012',
    word: 'tenuous',
    meaning: 'weak, thin, or very slight.',
    examples: ['There is a tenuous connection.', 'His grip on power is tenuous.'],
    note: `Often "a tenuous link" between two things.`,
    audio: 'c2-vc-012.ogg',
  },
  {
    id: 'c2-vc-013',
    word: 'cogent',
    meaning: 'clear, logical, and convincing.',
    examples: ['She made a cogent argument.', 'He gave a cogent reason.'],
    note: `Used of reasoning that is hard to argue against.`,
    audio: 'c2-vc-013.ogg',
  },
  {
    id: 'c2-vc-014',
    word: 'ostensible',
    meaning: 'appearing true on the surface, but perhaps not the real reason.',
    examples: ['The ostensible reason was cost.', 'That was his ostensible aim.'],
    note: `The adverb "ostensibly" hints the real reason is different.`,
    audio: 'c2-vc-014.ogg',
  },
  {
    id: 'c2-vc-015',
    word: 'innocuous',
    meaning: 'harmless; unlikely to offend or cause harm.',
    examples: ['It was an innocuous remark.', 'The plant looks innocuous.'],
    note: `Opposite of "harmful" or "offensive".`,
    audio: 'c2-vc-015.ogg',
  },
  {
    id: 'c2-vc-016',
    word: 'prudent',
    meaning: 'careful and sensible; wise in practice.',
    examples: ['It was a prudent decision.', 'It is prudent to save.'],
    note: `The noun is "prudence". Close to "sensible" or "cautious".`,
    audio: 'c2-vc-016.ogg',
  },
  {
    id: 'c2-vc-017',
    word: 'eloquent',
    meaning: 'fluent and persuasive in speech or writing.',
    examples: ['She is an eloquent speaker.', 'He gave an eloquent reply.'],
    note: `The noun is "eloquence".`,
    audio: 'c2-vc-017.ogg',
  },
  {
    id: 'c2-vc-018',
    word: 'austere',
    meaning: 'very plain and strict, without comfort or luxury.',
    examples: ['It was an austere room.', 'They led an austere life.'],
    note: `It can describe people (severe) or things (bare).`,
    audio: 'c2-vc-018.ogg',
  },
  {
    id: 'c2-vc-019',
    word: 'lucid',
    meaning: 'clear and easy to understand; clear-thinking.',
    examples: ['She gave a lucid explanation.', 'He stayed calm and lucid.'],
    note: `The noun is "lucidity". Opposite: "confusing".`,
    audio: 'c2-vc-019.ogg',
  },
  {
    id: 'c2-vc-020',
    word: 'disparate',
    meaning: 'very different in kind; hard to compare.',
    examples: ['She drew on disparate ideas.', 'It was a disparate group.'],
    note: `It means fundamentally different, not just varied.`,
    audio: 'c2-vc-020.ogg',
  },
];
