/**
 * A1 (beginner) vocabulary: high-frequency everyday words a learner needs first,
 * each with a plain meaning, simple examples, and a usage tip.
 */
import type { VocabularyEntry } from '../types';

export const a1Vocabulary: VocabularyEntry[] = [
  {
    id: 'a1-vc-001',
    word: 'busy',
    meaning: 'having a lot to do.',
    examples: ['I am very busy today.', 'She is busy at work.'],
    note: `Opposite of "free". We say "busy with work" or "busy doing something".`,
    audio: 'a1-vc-001.ogg',
  },
  {
    id: 'a1-vc-002',
    word: 'cheap',
    meaning: 'not expensive; low in price.',
    examples: ['This bag is very cheap.', 'I found a cheap hotel.'],
    note: `Opposite of "expensive". For people, "cheap" can sound rude; use "careful with money".`,
    audio: 'a1-vc-002.ogg',
  },
  {
    id: 'a1-vc-003',
    word: 'tired',
    meaning: 'needing to rest or sleep.',
    examples: ['I am tired after work.', 'You look tired today.'],
    note: `"Tired of something" means bored with it: "I am tired of waiting."`,
    audio: 'a1-vc-003.ogg',
  },
  {
    id: 'a1-vc-004',
    word: 'hungry',
    meaning: 'wanting to eat.',
    examples: ['I am so hungry.', 'Are you hungry yet?'],
    note: `"Thirsty" is the same idea for drinks: wanting to drink.`,
    audio: 'a1-vc-004.ogg',
  },
  {
    id: 'a1-vc-005',
    word: 'early',
    meaning: 'before the usual or expected time.',
    examples: ['I wake up early.', 'We arrived early.'],
    note: `Opposite of "late". "Early in the morning" is a common phrase.`,
    audio: 'a1-vc-005.ogg',
  },
  {
    id: 'a1-vc-006',
    word: 'careful',
    meaning: 'giving attention so you do not make a mistake or get hurt.',
    examples: ['Be careful with the hot water.', 'She is a careful driver.'],
    note: `"Be careful!" is a common warning. The adverb is "carefully".`,
    audio: 'a1-vc-006.ogg',
  },
  {
    id: 'a1-vc-007',
    word: 'friendly',
    meaning: 'kind and easy to talk to.',
    examples: ['The staff are very friendly.', 'He has a friendly smile.'],
    note: `It ends in "-ly" but it is an adjective, not an adverb.`,
    audio: 'a1-vc-007.ogg',
  },
  {
    id: 'a1-vc-008',
    word: 'favorite',
    meaning: 'the one you like best.',
    examples: ['Blue is my favorite color.', 'What is your favorite food?'],
    note: `In British English it is spelled "favourite".`,
    audio: 'a1-vc-008.ogg',
  },
  {
    id: 'a1-vc-009',
    word: 'clean',
    meaning: 'not dirty.',
    examples: ['The room is very clean.', 'Please keep the table clean.'],
    note: `Opposite of "dirty". As a verb: "clean the house".`,
    audio: 'a1-vc-009.ogg',
  },
  {
    id: 'a1-vc-010',
    word: 'quiet',
    meaning: 'with little or no noise.',
    examples: ['The library is quiet.', 'Please be quiet.'],
    note: `Opposite of "loud" or "noisy".`,
    audio: 'a1-vc-010.ogg',
  },
  {
    id: 'a1-vc-011',
    word: 'loud',
    meaning: 'making a lot of noise.',
    examples: ['The music is too loud.', 'He has a loud voice.'],
    note: `Opposite of "quiet". The adverb is "loudly".`,
    audio: 'a1-vc-011.ogg',
  },
  {
    id: 'a1-vc-012',
    word: 'easy',
    meaning: 'not difficult to do.',
    examples: ['The test was easy.', 'It is easy to use.'],
    note: `Opposite of "difficult" or "hard".`,
    audio: 'a1-vc-012.ogg',
  },
  {
    id: 'a1-vc-013',
    word: 'difficult',
    meaning: 'not easy; hard to do.',
    examples: ['This question is difficult.', 'It is difficult to choose.'],
    note: `A common synonym is "hard".`,
    audio: 'a1-vc-013.ogg',
  },
  {
    id: 'a1-vc-014',
    word: 'expensive',
    meaning: 'costing a lot of money.',
    examples: ['That car is expensive.', 'Hotels here are expensive.'],
    note: `Opposite of "cheap".`,
    audio: 'a1-vc-014.ogg',
  },
  {
    id: 'a1-vc-015',
    word: 'heavy',
    meaning: 'weighing a lot.',
    examples: ['This bag is heavy.', 'The box is too heavy to lift.'],
    note: `Opposite of "light". Also used in "heavy rain".`,
    audio: 'a1-vc-015.ogg',
  },
  {
    id: 'a1-vc-016',
    word: 'empty',
    meaning: 'with nothing inside.',
    examples: ['The bottle is empty.', 'The streets were empty.'],
    note: `Opposite of "full".`,
    audio: 'a1-vc-016.ogg',
  },
  {
    id: 'a1-vc-017',
    word: 'safe',
    meaning: 'not in danger, or not dangerous.',
    examples: ['It is safe here.', 'Keep your money safe.'],
    note: `The noun is "safety". Opposite: "dangerous".`,
    audio: 'a1-vc-017.ogg',
  },
  {
    id: 'a1-vc-018',
    word: 'ready',
    meaning: 'prepared for something.',
    examples: ['Are you ready?', 'Dinner is ready.'],
    note: `Use "ready for" something or "ready to" do it.`,
    audio: 'a1-vc-018.ogg',
  },
  {
    id: 'a1-vc-019',
    word: 'sure',
    meaning: 'having no doubt; certain.',
    examples: ['I am sure he will come.', 'Are you sure?'],
    note: `"sure about" something. A synonym is "certain".`,
    audio: 'a1-vc-019.ogg',
  },
  {
    id: 'a1-vc-020',
    word: 'free',
    meaning: 'not busy, or costing no money.',
    examples: ['Are you free tomorrow?', 'The app is free.'],
    note: `It has two meanings: not busy, and no cost.`,
    audio: 'a1-vc-020.ogg',
  },
];
