/**
 * C1 (advanced) vocabulary: precise, higher-register words that sharpen
 * expression, each with a plain meaning, examples, and a usage tip.
 */
import type { VocabularyEntry } from '../types';

export const c1Vocabulary: VocabularyEntry[] = [
  {
    id: 'c1-vc-001',
    word: 'meticulous',
    meaning: 'very careful about small details.',
    examples: ['She is meticulous about her work.', 'He kept meticulous records.'],
    note: `Stronger than "careful". Often "meticulous about" something.`,
    audio: 'c1-vc-001.ogg',
  },
  {
    id: 'c1-vc-002',
    word: 'resilient',
    meaning: 'able to recover quickly from difficulty.',
    examples: ['Children are remarkably resilient.', 'A resilient economy bounces back.'],
    note: `The noun is "resilience", a popular word in work and wellbeing.`,
    audio: 'c1-vc-002.ogg',
  },
  {
    id: 'c1-vc-003',
    word: 'nuance',
    meaning: 'a small, subtle difference in meaning or feeling.',
    examples: ['He missed the nuance of the joke.', 'The argument has many nuances.'],
    note: `The adjective "nuanced" means subtle and carefully balanced.`,
    audio: 'c1-vc-003.ogg',
  },
  {
    id: 'c1-vc-004',
    word: 'inevitable',
    meaning: 'certain to happen; impossible to avoid.',
    examples: ['Change is inevitable.', 'A delay now seems inevitable.'],
    note: `The adverb "inevitably" introduces a result you expected.`,
    audio: 'c1-vc-004.ogg',
  },
  {
    id: 'c1-vc-005',
    word: 'advocate',
    meaning: 'to support an idea publicly; or a person who does so.',
    examples: ['She advocates for cleaner energy.', 'He is a strong advocate of reform.'],
    note: `The verb stresses the end (advoCATE); the noun the start (ADvocate).`,
    audio: 'c1-vc-005.ogg',
  },
  {
    id: 'c1-vc-006',
    word: 'deliberate',
    meaning: 'done on purpose; or slow and careful.',
    examples: ['It was a deliberate choice.', 'She spoke in a slow, deliberate way.'],
    note: `As a verb (deLIBerate) it means to think carefully before deciding.`,
    audio: 'c1-vc-006.ogg',
  },
  {
    id: 'c1-vc-007',
    word: 'ambiguous',
    meaning: 'having more than one possible meaning; unclear.',
    examples: ['The wording is ambiguous.', 'He gave an ambiguous reply.'],
    note: `The noun is "ambiguity". Opposite: "clear" or "unambiguous".`,
    audio: 'c1-vc-007.ogg',
  },
  {
    id: 'c1-vc-008',
    word: 'undermine',
    meaning: 'to weaken something gradually, often without it being obvious.',
    examples: ['Constant doubt undermined her confidence.', 'The leak undermined trust.'],
    note: `Often used with "confidence", "trust", or "authority".`,
    audio: 'c1-vc-008.ogg',
  },
  {
    id: 'c1-vc-009',
    word: 'comprehensive',
    meaning: 'complete; covering everything that is relevant.',
    examples: ['A comprehensive guide.', 'They did a comprehensive review.'],
    note: `Do not confuse it with "comprehensible" (able to be understood).`,
    audio: 'c1-vc-009.ogg',
  },
  {
    id: 'c1-vc-010',
    word: 'inherent',
    meaning: 'existing as a natural, permanent part of something.',
    examples: ['Risk is inherent in business.', 'It has an inherent flaw.'],
    note: `Use "inherent in" something. The adverb is "inherently".`,
    audio: 'c1-vc-010.ogg',
  },
  {
    id: 'c1-vc-011',
    word: 'prevalent',
    meaning: 'common or widespread in a place or time.',
    examples: ['That view is prevalent here.', 'It is a prevalent myth.'],
    note: `Close to "widespread". The noun is "prevalence".`,
    audio: 'c1-vc-011.ogg',
  },
  {
    id: 'c1-vc-012',
    word: 'compelling',
    meaning: 'so convincing or interesting you cannot ignore it.',
    examples: ['She made a compelling argument.', 'The story is compelling.'],
    note: `Close to "convincing" or "gripping".`,
    audio: 'c1-vc-012.ogg',
  },
  {
    id: 'c1-vc-013',
    word: 'arbitrary',
    meaning: 'based on chance or personal whim, not on reason.',
    examples: ['It was an arbitrary decision.', 'The rules seem arbitrary.'],
    note: `It suggests there is no clear logic behind the choice.`,
    audio: 'c1-vc-013.ogg',
  },
  {
    id: 'c1-vc-014',
    word: 'robust',
    meaning: 'strong and able to withstand pressure or difficulty.',
    examples: ['We need a robust system.', 'The economy is robust.'],
    note: `For health it means strong; for things, durable and reliable.`,
    audio: 'c1-vc-014.ogg',
  },
  {
    id: 'c1-vc-015',
    word: 'plausible',
    meaning: 'seeming reasonable or probably true.',
    examples: ['That is a plausible explanation.', 'It sounds plausible.'],
    note: `It seems true but is not proven. Opposite: "implausible".`,
    audio: 'c1-vc-015.ogg',
  },
  {
    id: 'c1-vc-016',
    word: 'redundant',
    meaning: 'not needed, often because it repeats something.',
    examples: ['That word is redundant.', 'This step is redundant.'],
    note: `In British English it can also mean "laid off" from a job.`,
    audio: 'c1-vc-016.ogg',
  },
  {
    id: 'c1-vc-017',
    word: 'coherent',
    meaning: 'clear, logical, and well-connected.',
    examples: ['She gave a coherent argument.', 'Try to stay coherent.'],
    note: `Opposite: "incoherent". The noun is "coherence".`,
    audio: 'c1-vc-017.ogg',
  },
  {
    id: 'c1-vc-018',
    word: 'tentative',
    meaning: 'not certain or fixed; provisional.',
    examples: ['We have a tentative plan.', 'They set a tentative date.'],
    note: `The adverb "tentatively" means not yet finally decided.`,
    audio: 'c1-vc-018.ogg',
  },
  {
    id: 'c1-vc-019',
    word: 'viable',
    meaning: 'able to work or succeed in practice.',
    examples: ['It is a viable option.', 'The plan is not viable.'],
    note: `Close to "feasible" or "workable".`,
    audio: 'c1-vc-019.ogg',
  },
  {
    id: 'c1-vc-020',
    word: 'underlying',
    meaning: 'hidden beneath the surface, but real and important.',
    examples: ['We must find the underlying cause.', 'There is an underlying problem.'],
    note: `It points to the real reason beneath the obvious one.`,
    audio: 'c1-vc-020.ogg',
  },
];
