/**
 * A2 (elementary) vocabulary: useful everyday words and a few that learners often
 * confuse, each with a plain meaning, examples, and a usage tip.
 */
import type { VocabularyEntry } from '../types';

export const a2Vocabulary: VocabularyEntry[] = [
  {
    id: 'a2-vc-001',
    word: 'borrow',
    meaning: 'to take something for a short time and give it back.',
    examples: ['Can I borrow your pen?', 'I borrowed a book from the library.'],
    note: `You borrow FROM someone; they lend TO you. Do not mix them up.`,
    audio: 'a2-vc-001.ogg',
  },
  {
    id: 'a2-vc-002',
    word: 'lend',
    meaning: 'to give something for a short time, expecting it back.',
    examples: ['Can you lend me ten dollars?', 'She lent me her car.'],
    note: `The opposite of "borrow". Past form is "lent".`,
    audio: 'a2-vc-002.ogg',
  },
  {
    id: 'a2-vc-003',
    word: 'decide',
    meaning: 'to choose after thinking about it.',
    examples: ['I decided to stay home.', 'We need to decide soon.'],
    note: `Use "decide to do" something. The noun is "decision".`,
    audio: 'a2-vc-003.ogg',
  },
  {
    id: 'a2-vc-004',
    word: 'improve',
    meaning: 'to get better, or make something better.',
    examples: ['My English is improving.', 'I want to improve my cooking.'],
    note: `The noun is "improvement". Often "improve at" a skill.`,
    audio: 'a2-vc-004.ogg',
  },
  {
    id: 'a2-vc-005',
    word: 'enough',
    meaning: 'as much as you need; not more, not less.',
    examples: ['We have enough time.', 'This is not big enough.'],
    note: `It goes BEFORE a noun but AFTER an adjective: "enough money", "big enough".`,
    audio: 'a2-vc-005.ogg',
  },
  {
    id: 'a2-vc-006',
    word: 'polite',
    meaning: 'showing good manners and respect.',
    examples: ['She is always polite.', 'It is polite to say thank you.'],
    note: `Opposite of "rude". The adverb is "politely".`,
    audio: 'a2-vc-006.ogg',
  },
  {
    id: 'a2-vc-007',
    word: 'nervous',
    meaning: 'worried or a little afraid about something.',
    examples: ['I am nervous about the test.', 'He felt nervous before the talk.'],
    note: `"Nervous about" something. Different from "angry" or "excited".`,
    audio: 'a2-vc-007.ogg',
  },
  {
    id: 'a2-vc-008',
    word: 'bored',
    meaning: 'tired and unhappy because nothing interesting is happening.',
    examples: ['I am bored at home.', 'The film was so boring.'],
    note: `You feel "bored"; a thing is "boring". Do not say "I am boring".`,
    audio: 'a2-vc-008.ogg',
  },
  {
    id: 'a2-vc-009',
    word: 'arrive',
    meaning: 'to reach a place.',
    examples: ['We arrived at noon.', 'The train arrives soon.'],
    note: `Use "arrive at" a place, but "arrive in" a city or country.`,
    audio: 'a2-vc-009.ogg',
  },
  {
    id: 'a2-vc-010',
    word: 'prepare',
    meaning: 'to get ready, or make something ready.',
    examples: ['I prepared dinner.', 'She prepared for the exam.'],
    note: `Use "prepare for" something. The noun is "preparation".`,
    audio: 'a2-vc-010.ogg',
  },
  {
    id: 'a2-vc-011',
    word: 'explain',
    meaning: 'to make something clear.',
    examples: ['Can you explain the rule?', 'He explained the problem.'],
    note: `"explain something to someone". The noun is "explanation".`,
    audio: 'a2-vc-011.ogg',
  },
  {
    id: 'a2-vc-012',
    word: 'allow',
    meaning: 'to let someone do something.',
    examples: ['They allow dogs here.', 'We are not allowed to smoke.'],
    note: `"allow someone to do". Close to "let".`,
    audio: 'a2-vc-012.ogg',
  },
  {
    id: 'a2-vc-013',
    word: 'avoid',
    meaning: 'to keep away from something.',
    examples: ['I avoid sugar.', 'She avoided the question.'],
    note: `Use "avoid doing" something, not "avoid to do".`,
    audio: 'a2-vc-013.ogg',
  },
  {
    id: 'a2-vc-014',
    word: 'complain',
    meaning: 'to say you are unhappy about something.',
    examples: ['He complained about the noise.', 'Please do not complain.'],
    note: `"complain about" something. The noun is "complaint".`,
    audio: 'a2-vc-014.ogg',
  },
  {
    id: 'a2-vc-015',
    word: 'relax',
    meaning: 'to rest and become calm.',
    examples: ['I relax on weekends.', 'Just relax and breathe.'],
    note: `The adjective "relaxed" describes how you feel.`,
    audio: 'a2-vc-015.ogg',
  },
  {
    id: 'a2-vc-016',
    word: 'worried',
    meaning: 'feeling anxious about something.',
    examples: ['I am worried about you.', 'She looked worried.'],
    note: `"worried about" something. The verb is "worry".`,
    audio: 'a2-vc-016.ogg',
  },
  {
    id: 'a2-vc-017',
    word: 'excited',
    meaning: 'very happy and eager about something.',
    examples: ['I am excited about the trip.', 'The kids were excited.'],
    note: `You feel "excited"; a thing is "exciting".`,
    audio: 'a2-vc-017.ogg',
  },
  {
    id: 'a2-vc-018',
    word: 'surprised',
    meaning: 'feeling that something was unexpected.',
    examples: ['I was surprised by the news.', 'She seemed surprised.'],
    note: `You feel "surprised"; a thing is "surprising".`,
    audio: 'a2-vc-018.ogg',
  },
  {
    id: 'a2-vc-019',
    word: 'comfortable',
    meaning: 'giving a pleasant, relaxed feeling.',
    examples: ['This chair is comfortable.', 'I feel comfortable here.'],
    note: `Opposite of "uncomfortable". Often shortened to "comfy".`,
    audio: 'a2-vc-019.ogg',
  },
  {
    id: 'a2-vc-020',
    word: 'convenient',
    meaning: 'easy and useful for your needs.',
    examples: ['The shop is convenient.', 'Is Friday convenient?'],
    note: `The noun is "convenience". Opposite: "inconvenient".`,
    audio: 'a2-vc-020.ogg',
  },
];
